### ISSUE TITLE
Models: default low quality avatar

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1004]
Like the VRChat robot, or some sort of 256fes fallback avatar.

**Comment by plankatron** [comment]
i vote for egg dogoo .. no i joke ,, if you have any starting points for a concept that would be helpful ,

**Comment by madjin** [comment]
For starters:

Cryptoavatars (Have 100+, on average they're <5k triangles 1.4MB)

![image](https://user-images.githubusercontent.com/32600939/112567448-3d2fb380-8db7-11eb-83b1-83310e69cebf.png)

https://blueasis.booth.pm/ (many default VRChat ones here)

![image](https://user-images.githubusercontent.com/32600939/112567630-8f70d480-8db7-11eb-8b2f-3bd82c6063fa.png)

Another idea is to make a roster of 256fes avatars, they're quick to make (takes 1 day each) and pretty retro. We could use vroid for inspiration to attract artists who are familiar with VRoid (they're the most interoperable avatars afterall) and come up with original characters as well.

![image](https://user-images.githubusercontent.com/32600939/112553260-89b8c600-8d9a-11eb-9429-dc0a9e97d440.png)

Reminder that 256 can actually look good, most have a neat retro vibe to them.

![image](https://user-images.githubusercontent.com/32600939/112564067-f50d9280-8db0-11eb-9820-136ac4ae41a1.png)

I have many of these tiny box avatars as VRMs

![brave_wlb9kfbulk](https://user-images.githubusercontent.com/32600939/112566178-ddd0a400-8db4-11eb-9c03-ebb06042dd9c.png)

Few other ideas:

- Via could make body parts for users to construct their own avatars
- Doom sprite avatars: https://hackmd.io/@XR/avatars#Spritesheets
- Import Cryptovoxels / Decentraland avatars: https://github.com/webaverse/app/issues/1010

**Comment by plankatron** [comment]
@madjin cool ! thanks for all the ideas , i will stare at these and try to come up with some concepts tomorrow

**Comment by avaer** [comment]
I think we need something that is very "default" and "broken placeholder". These avatar references are decent quality and people will actually use them. They do not signify a problem/downgrade, which is the intent of having a placeholder avatar.

Going off of Jin's idea, I think Via should handle this, and we should probably do a nice mellow abstract low poly avatar with visemes.

**Comment by avaer** [comment]
https://cdn.discordapp.com/attachments/696210985035235358/824846951534166046/744468.png

**Comment by avaer** [comment]
Jin has those Unity packages.

**Comment by madjin** [comment]
Bigtin is going to help us make optimized default avatars with visemes and no IK.

![image](https://user-images.githubusercontent.com/32600939/112868616-1e5c4600-9071-11eb-8d85-2b521c0293c6.png)

Feedback:

- Shape the body into more like Ethereum.
- Textures can be simple gradiant

Had another idea for default avatar...

- What if the avatar is a simple geometric shape like a sphere with a cool shader and could be animated with the Hubs `scale-audio-feedback` blender exporter property?

**Comment by Vianvolaeus** [comment]
I made a low poly bot to teach basic rigging to someone not too long ago that can probably be retrofitted for the needs here. (rescale to fit humanoid proportions better)

Also a bit 'Ethereum-shaped' as suggested by Jin.

Has plenty of body real-estate if you want to display different error messages / placeholder reasons
![unknown 1](https://user-images.githubusercontent.com/80061436/112977087-8ed89500-914d-11eb-9aee-0477f5de03c8.png)

**Comment by Vianvolaeus** [comment]
Couple more concept variations based on feedback in Discord.

One is _very_ Ether shaped, other is a bit rounded out and gives us some real estate for error messages etc. - the current VRchat fallback robots have tiny error messages


I can move to the finger rigging and texturing once we've decided on a concept. Going to continue working on some variations.
![unknown 1](https://user-images.githubusercontent.com/80061436/113130885-72536000-9214-11eb-916b-287c08c4034c.png)

**Comment by Vianvolaeus** [comment]
Thinner / more humanoid ones, smoother sub.d one too

![image](https://user-images.githubusercontent.com/80061436/113178882-eeff3200-9246-11eb-9aaa-7a730cf4e07e.png)

Gradient & wireframe is just a viewport preview in Blender.

I can put pieces of these together if there's certain parts or features that are desireable - kept everything seperated

**Comment by plankatron** [comment]
top left corner +1
