### ISSUE TITLE
App: Export GLB of a CV or DCL parcel

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1006]
Suggestion for bringing content from other virtual worlds such as Cryptovoxels or Decentraland into Webaverse:

* User logs into the website
* Owned parcels automatically rendered
* User goes to parcel on the map they want to port
* Highlights it by hovering over the parcel
* Hits export
* Sign transaction, pay fee
* Receive GLB of just the parcel

![image](https://user-images.githubusercontent.com/32600939/112435194-ccd35480-8d1a-11eb-9ddc-2a60e6fd55f9.png)

**Comment by avaer** [comment]
These worlds should sponsor and promote it. Unless they do I don't see this happening.
