### ISSUE TITLE
Fe: (Performance) Item previews and Map

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1014]
It'd be faster if we could simply reload the NFT rather than reload the entire page for Webaverse TV: https://webaverse.com/tv/1

![brave_LhZ9KsLGdR](https://user-images.githubusercontent.com/32600939/112707706-95cc8280-8e83-11eb-9f54-22bc3651b62a.png)

Also it would be useful if there was progress loading animation for the NFT so we can tell what's happening, especially if the NFT media is large.

**Comment by madjin** [comment]
Map takes a long time to load, would be useful to have a loading bar in meantime.

![](https://i.imgur.com/fCDsGW8.png)

**Comment by avaer** [comment]
The TV and map cases are separate.

For the TV case we should do a postMessage.

For the map case, we need to render the map serverside, without anyone relying on the hack I did to generate the map in realtime.

**Comment by avaer** [comment]
Broken out into:
- https://github.com/webaverse/app/issues/1024
- https://github.com/webaverse/app/issues/583
