### ISSUE TITLE
Fe: UI / UX improvement suggestions

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1015]
1. After clicking a NFT on the front page, you have to go back to see any others.  It would be nice to see related NFTs and continue browsing, like Youtube. Right now the asset page is quite plain.

![image](https://user-images.githubusercontent.com/32600939/112707464-17bbac00-8e82-11eb-8a87-38025d164faa.png)

2. No way to full screen when clicking the preview image of the NFT in the trading card window. Atleast on Opensea when you click the preview image it will open a full screen preview.

![image](https://user-images.githubusercontent.com/32600939/112707498-56e9fd00-8e82-11eb-8539-912eed554a98.png)

3. In [Webaverse TV](https://webaverse.com/tv/1) it's not obvious how to take a closer look at pictures which are sitting on the ground. Grab is with `e` which may not be as intuitive as simply click and hold, without onscreen instructions.

![](https://i.imgur.com/gof23lr.png)

4. Transaction types still show as FLUX

![](https://i.imgur.com/j4AJiXB.png)

5. I want to be able to drag left or right to scroll through cards on the front page, not just grab the scroll bar.

![](https://i.imgur.com/RkmnE0c.png)

6. Would be useful to have some information about file types or link to documentation on the page to mint files.

![](https://i.imgur.com/O90EzMe.png)

**Comment by avaer** [comment]
These are good but should be separate issues/requests.

**Comment by madjin** [comment]
Closing this issue since there's a new frontend and many of these things should be separate issues.
