### ISSUE TITLE
Fe: Can't rename animation name when minting

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1018]
Trying to mint a pet, the drag n' drop interface assumes the name for an animation and if it's wrong won't let me change it to the right one. Would be better to manually type in the name for now until there's a drop down selection.

![image](https://user-images.githubusercontent.com/32600939/112748294-cf3ae600-8f88-11eb-9711-8986d8df95f2.png)

**Comment by avaer** [comment]
We should add the dropdown.
