### ISSUE TITLE
Login: Currently FE only shows Discord login

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1023]
![image](https://user-images.githubusercontent.com/32600939/112789800-e41c8580-902b-11eb-9a0b-54a7409b0583.png)

Need to re-add other login options like email / private key else it may give people a first impression this is tied to Discord only.

**Comment by madjin** [comment]
We should have login via metamask:

As per NoodleSploder: "The first connection is a transaction, where you "sign" from the wallet, after that, there is a cookie cache essentially which makes it"

**Comment by NoodleSploder** [comment]
hi guys.  Yah, so authentication from wallets such as MetaMask (Ethereum) and PolkaDot.js (PolkaDOT / Kusama / Sora) will be important I think, because this is essentially Web 3.0 authenitcation, where identity management is managed on-chain.

**Comment by NoodleSploder** [comment]
applications in web 3.0 are identity and asset agnostic.

**Comment by avaer** [comment]
> applications in web 3.0 are identity and asset agnostic.
I wish but this is not really true rn.

The problem is each contract offers different features.

But I like the idea of basing this login off of Metamask as well, for the people who want to pay hundred dollar fees to get started :P.

**Comment by avaer** [comment]
Ok, I think we can just support this. Assuming the user has the same key across Discord and MetaMask, it should even be compatible.

**Comment by madjin** [comment]
How it looks on new FE, still Discord only.
 
![image](https://user-images.githubusercontent.com/32600939/116153160-e3235600-a6b4-11eb-9017-6b8f82c24272.png)
