### ISSUE TITLE
Fe: Webaverse TV dynamic injection of NFTs

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1024]
It'd be faster if we could simply reload the NFT rather than reload the entire page for Webaverse TV: https://webaverse.com/tv/1

![brave_LhZ9KsLGdR](https://user-images.githubusercontent.com/32600939/112707706-95cc8280-8e83-11eb-9f54-22bc3651b62a.png)

Also it would be useful if there was progress loading animation for the NFT so we can tell what's happening, especially if the NFT media is large.

**Comment by madjin** [comment]
Update:
![image](https://user-images.githubusercontent.com/32600939/117614105-d29fc080-b135-11eb-8fbc-3e5c88aeb26e.png)

**Comment by madjin** [comment]
related issues: https://github.com/webaverse/app/issues/1209 https://github.com/webaverse/app/issues/1192

**Comment by avaer** [comment]
This can be closed.
