### ISSUE TITLE
App: primer for artists

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1031]
Share the shoryboard/scripts/scenes with artists.

**Comment by madjin** [comment]
Film treatment: "A film treatment (or simply treatment) is a piece of prose, typically the step between scene cards (index cards) and the first draft of a screenplay for a motion picture, television program, or radio play."

- https://www.masterclass.com/articles/how-to-write-a-film-treatment-in-6-steps#the-4-elements-of-a-film-treatment
- https://nofilmschool.com/film-treatment

![image](https://user-images.githubusercontent.com/32600939/131219353-013d99e8-5ad4-490e-bbe9-962aafccb136.png)
