### ISSUE TITLE
Docs: Matic setup instructions

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1035]
https://docs.matic.network/docs/develop/metamask/config-matic/

This might involve instructions on how to get matic tokens available.

**Comment by avaer** [comment]
How to move MATIC from ETH mainnet to POLYGON network:

https://wallet.matic.network/

**Comment by madjin** [comment]
Made great progress on this, got blocked by https://github.com/webaverse/app/issues/1064
https://github.com/madjin/docs/blob/master/docs/market/matic-guide.md

**Comment by madjin** [comment]
fixed https://docs.webaverse.com/docs/market/matic-guide
