### ISSUE TITLE
Docs: add NFT roles (.redeem)

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1037]

**Comment by madjin** [comment]
AFAIK no one has used .redeem in Discord before, how it works is here:
https://github.com/webaverse/ethereum-bot/blob/300fe0e3d8519984573a0652ef0f3fb6d4dfba79/discordbot.js#L547

**Comment by avaer** [comment]
It currently has hard coded start/end ids: https://github.com/webaverse/ethereum-bot/blob/300fe0e3d8519984573a0652ef0f3fb6d4dfba79/discordbot.js#L576

We'll need to change that for real usage.
