### ISSUE TITLE
App: VRM eye rigging 

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1041]
Some prebuilt models have some incorrect / incompatible eye rigging:
![unknown 1](https://user-images.githubusercontent.com/80061436/113003483-affbae80-916a-11eb-81b0-be034ca9f3f1.png)

Should be able to (manually) compensate for poorly / incorrectly rigged eyes like this if weba accounts for  VRMLookAtBlendShapeApplyer - can assign blendshapes for eye look rather than use bone transforms. 

It's not commonly used, but I have seen look blendshapes included on a couple of VRM models - some vtuber software recognize them and can use them, so makes sense to be on VRM models

Other option is to replace them with normal eyeballs with a flat face and re-uv like so, since these can be easily rigged correctly and rely on bone origin rotation only.:

![unknown 1](https://user-images.githubusercontent.com/80061436/113003593-c9045f80-916a-11eb-9cc7-be1fac56798b.png)
This is a more destructive and time consuming method, but will be likely be more reliable

Looking into a potential solution that's non-destructive (Unity based, sadly) that would allow blendshapes to be added, without having to redo metadata (spring bones, etc) since the VRM plugin for Blender doesn't seem to retain it.

**Comment by avaer** [comment]
I see, should we look for one and if not found use the other?

**Comment by Vianvolaeus** [comment]
That's most likely best, yes. 
Allows artists to reconfigure models that'd otherwise be incompatible, and should help interoperability a bit too.

If the original for the model on the right is available I can take a look at that and test compatibility with it. Can't find it in the avatar list

**Comment by avaer** [comment]
Just uploaded, I think the model on the right is here: https://github.com/webaverse/avatar-models/blob/master/model54.vrm
