### ISSUE TITLE
App: Can't log in anon, white screen

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1042]
Tried loading the app in a private tab so I can try anon login and ran into this bug with login.js

![brave_eggJD7yRMl](https://user-images.githubusercontent.com/32600939/113071771-72f7e200-9193-11eb-933e-5044f0716070.png)

![image](https://user-images.githubusercontent.com/32600939/113071729-5c518b00-9193-11eb-9755-c291deaddb7d.png)

**Comment by avaer** [comment]
This is because of the cross origin request.

**Comment by avaer** [comment]
Cosmo hacked a patch here: https://github.com/webaverse/api-backend/commit/5c109c300c70f44f617c5fda072643e3ee7d5c0c

This should probably just immediately return empty, or null, or we should have the frontend handle that case.
