### ISSUE TITLE
Fe: 500 error on account page

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1043]
![image](https://user-images.githubusercontent.com/32600939/113072118-409ab480-9194-11eb-8f90-a19f94d9faf3.png)

![image](https://user-images.githubusercontent.com/32600939/113072107-37a9e300-9194-11eb-9cef-c3b406725863.png)

Also having 403 errors when doing `.login`

**Comment by avaer** [comment]
@madjin Can this be closed?

**Comment by madjin** [comment]
fixed
