### ISSUE TITLE
Fe: mints after 214 not appearing in FE inventory

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1050]
Did a console diff to see what's not loading between a working preview and non working asset:
- https://webaverse.com/assets/214
- https://webaverse.com/assets/215

This is missing from the non-working preview
`/_next/static/chunks/pages/preview/%5Bid%5D-e590b1670a9300ef3b6e.js`

The mints still show up in Discord, https://webaverse.com/activity, and we can preview them with `.preview 215`, just the website isn't showing it.

**Comment by soulofmischief** [comment]
https://github.com/webaverse/webaverse.com/blob/master/pages/accounts/%5Bid%5D.js

`data` seems bare, only provides balance and a partial profile containing the balance and address/id

**Comment by soulofmischief** [comment]
What is populating this data field?

**Comment by avaer** [comment]
So it is the account page that doesn't show it up? What about the assets page.

**Comment by avaer** [comment]
https://github.com/webaverse/api-backend/commit/f7dd8bafb1fc5c66a2c28f9e31631a8c70c13343
