### ISSUE TITLE
Fe: ability to mint VRM avatars

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1060]
We still don't have this. Also, it would be a good way to test avatars without having to go into the virtual world.

This could also include a mirror.

**Comment by madjin** [comment]
Does this mean we can close the issue?
![image](https://user-images.githubusercontent.com/32600939/118404895-e28e3780-b642-11eb-9c71-7357da2a5ccd.png)

**Comment by avaer** [comment]
There are optimizations we can do like VR + mirror + better pose.

But yes we can close this.
