### ISSUE TITLE
Bot: New mints not found on FE

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1063]
All the tokens up until 254 work but I just tried minting a glb and jpg and met with an error `Token not found`. I can still inspect the token and see it in my Discord inventory.

https://webaverse.com/assets/256

![image](https://user-images.githubusercontent.com/32600939/113521196-d902b180-9565-11eb-9bb7-aca2a0e7caaf.png)

**Comment by avaer** [comment]
I did another pass and these ones should be showing up at least.

This could be due to the polygon sockets crashing during our cache procedure, which could hold up tokens from appearing in the cache/api. (https://github.com/webaverse/app/issues/1066)
