### ISSUE TITLE
Fe: Clicking trade unexpected error

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1064]
Clicking Trade tab on the asset page will lead to unexpected error: https://webaverse.com/assets/244

![image](https://user-images.githubusercontent.com/32600939/113527294-1b8ab500-958b-11eb-87d4-29d7891ace79.png)

**Comment by avaer** [comment]
Thanks, I'm working on this flow tonight.

**Comment by avaer** [comment]
This should be fixed on webaverse.com now.
