### ISSUE TITLE
App: Add other portals / parcels

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1065]
Wireframe cages did a good job of explaining parcels better than the floor portals (floortals).

![2021-04-04-22:02:28](https://user-images.githubusercontent.com/32600939/113539004-8d65fd00-9591-11eb-868b-6cdf2344263f.jpg)

These portals red pill people on how Webaverse glues virtual worlds together too, not sure how to spawn them?

![2021-04-04-22:01:46](https://user-images.githubusercontent.com/32600939/113539044-a8d10800-9591-11eb-9ccf-5fb9f1fd5ea9.jpg)

**Comment by avaer** [comment]
We still have that code, would need to pull it out.
