### ISSUE TITLE
Token: add to matic.opensea.io

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1068]
https://docs.google.com/forms/d/e/1FAIpQLScL-zLEyCjizXsRj7PLSJ-aYvWH9Xo-K1rTB5xCdFnf2m4cNg/viewform

**Comment by madjin** [comment]
We've been added 
![image](https://user-images.githubusercontent.com/32600939/117613432-eb5ba680-b134-11eb-90a2-7b10bfb2b5dc.png)
