### ISSUE TITLE
App: OK bot avatar design

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1073]

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/113601325-1421e500-9639-11eb-8640-374bfc337e5d.png)

All parts are separate - if there's parts of one that are good etc, they can be merged and kitbashed together

Wireframe is just a preview, but can be added as part of the texturing.

Currently unrigged, but scaled to the default VRoid armature ready for rigging

**Comment by Vianvolaeus** [comment]
![GradientBots](https://user-images.githubusercontent.com/80061436/113606006-55b58e80-963f-11eb-9105-501884c0c264.png)

Updated with gradients and faces.

Forgot to mention that this comment [https://github.com/webaverse/app/issues/1004#issuecomment-809589435](url) has a good idea - we can do Hubs style head size style visemes by populating the visemes with a simple blend shape that scales the head if desired. Simple but very visible to users

**Comment by avaer** [comment]
Let's try with 2 + 6.

**Comment by madjin** [comment]
VRMs made 👍
