### ISSUE TITLE
App: Visual loading indicator

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1078]
Currently no way to tell if something that's been drag and dropped into window is actually loading. I'd imagine it's good to have some kind of feedback to the user that the app is loading what they've put in

**Comment by 0xmetabad** [comment]
I think this has been added, the DDR arrow. It is really awesome. https://github.com/webaverse/app/issues/1342

**Comment by 0xmetabad** [comment]
Related issues:
- https://github.com/webaverse/app/issues/1478
- https://github.com/webaverse/app/issues/373
