### ISSUE TITLE
Be: api-backend incorrectly logs polygon events

### ISSUE THREAD

**Issue by soulofmischief** [webaverse/app#1088]
The calls made at 

* https://github.com/webaverse/api-backend/blob/32392927ac486c8fe5d589ae14cded159b280faa/tokens.js#L623
* https://github.com/webaverse/api-backend/blob/32392927ac486c8fe5d589ae14cded159b280faa/tokens.js#L630

produce the chain names `polygonpolygon` and `polygonsidechain`.

This causes the TypeError `Cannot read property 'NFTProxy' of undefined`.

The `polygonpolygon` is a simple string replacement at [line 566](https://github.com/webaverse/api-backend/blob/32392927ac486c8fe5d589ae14cded159b280faa/tokens.js#L566), but what about `polygonsidechain`? This shouldn't exist, right? Want to make sure before I undo any preliminary work.

**Comment by avaer** [comment]
I suspect this is handled in The new polygon branch.

**Comment by avaer** [comment]
Let me check

**Comment by avaer** [comment]
https://github.com/webaverse/api-backend/pull/61/files#diff-5db56f50aabacf6cac7190b53c7ff6ddff6fee9ccd29b31c391d63e49d9c869aR684

**Comment by avaer** [comment]
I hope to ship that this morning.

**Comment by soulofmischief** [comment]
Awesome, just wanted to be sure.

**Comment by avaer** [comment]
This should be shipped.
