### ISSUE TITLE
Fe: land page crash

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1093]
https://webaverse.com/land

**Comment by soulofmischief** [comment]
https://github.com/webaverse/api-backend/pull/62

**Comment by soulofmischief** [comment]
Fixed this before I saw the issue.. ok to merge?

**Comment by soulofmischief** [comment]
land is loading very slowly, investigating...

**Comment by avaer** [comment]
I don't think land is cached.

**Comment by soulofmischief** [comment]
@avaer land was indeed caching, could probably be made more semantically clear, but fixing the bucket fixed loading times.

However, https://webaverse.com/land/1 is still busted.

**Comment by soulofmischief** [comment]
https://github.com/webaverse/webaverse.com/blob/1bc65863b65b57fa5b92708b4aecd07554032fd7/components/LandCardDetails.js#L304

`currentLocation` is undefined.

It seems `assets/[id].js` passes `currentLocation` to `CardDetails` as a property of `token`, however the corresponding `land` variable in `land/[id].js` does not have this property.

Additionally, at https://github.com/webaverse/webaverse.com/blob/1bc65863b65b57fa5b92708b4aecd07554032fd7/pages/land/%5Bid%5D.js#L14, 

`const [loading, setLoading] = useState(data);`

should instead be:

`const [loading, setLoading] = useState(false);`

Gonna patch that into master now.

**Comment by soulofmischief** [comment]
Ok, I see your recent commits in `tokens.js` provide this value for tokens. Will wait for comment before proceeding with this issue. 

Caching, iterating under `/land` and stuck loading in `/land/[id]` are fixed.

**Comment by avaer** [comment]
The `currentLocation` is the stick detection of the backend.

We are not doing that for LAND tokens right now, since the land tokens are not cached.

However that variable could be faked.

**Comment by avaer** [comment]
I added hacks to the land page so it no longer crashes.

However, that land page needs to be rewritten with backend caching and stuck detection support. Mostly just a lot of variable names need to be parameterized by `LAND` vs `NFT`.

I'll open a separate issue for `LAND` support in these.

**Comment by avaer** [comment]
Related: https://github.com/webaverse/app/issues/1093
