### ISSUE TITLE
App: White screen when logged in for jin and others

### ISSUE THREAD

**Issue by soulofmischief** [webaverse/app#1097]
Can't reproduce.

Jin gets an error indicating `contracts.back` is undefined here:

https://github.com/webaverse/app/blob/f8c83283f4b7ba2b90a666fcc5b606bfa6bc0b6f/login.js#L22

**Comment by madjin** [comment]
When I clear my cache, I get logged out but I can atleast enter the app. When I log back in with the Discord bot, I can't open the app (get white screen + this error).

![brave_Kiuev3ggni](https://user-images.githubusercontent.com/32600939/114140637-8a934100-98de-11eb-9d1d-6e7e6b2e4b67.png)

**Comment by avaer** [comment]
Look like this issue was filed with the wrong repo. It's `app`, not the `fe`.

**Comment by avaer** [comment]
Who are the "others"?

**Comment by avaer** [comment]
Looking at the code it seems anyone with a `number`-ish token loaded (e.g. a tokenized avatar) would experience this.

**Comment by avaer** [comment]
@madjin Is it fixed now?

**Comment by avaer** [comment]
I'm assuming it's fixed, please report again if it is not.
