### ISSUE TITLE
Opensea: Mainnet and Matic store confusion

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1109]
ASSET collection on Matic (https://matic.opensea.io/) isn't showing the polygon assets we mint, they're getting minted to https://opensea.io/collection/asset-v3 instead.

This is the correct address:
`0x1E9dC2903cF07A047eBDdb28B14174eA3A86A775`

https://github.com/webaverse/contracts/blob/b09d68a29892c602314f7b808525b1ad5f40db2f/config/addresses.js#L45

Need to poke opensea again

Solving this may depend on Cosmos work with migrations

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/114350349-18696900-9b37-11eb-94e3-443b3e87280a.png)

https://opensea.io/assets/0x42fae5a6dbd93cf63ed9eea0449825ddc8234a17/86

The tokens one is allowed to offer are WETH, DAI, USDC on the things we already minted on mainnet ASSETs. These tokens are what people would use to bid on Matic NFTS.

**Comment by madjin** [comment]
Naming suggestion: mASSET (matic ASSET)

Moving sidechain -> ETH mainnet = https://opensea.io/collection/asset
Moving sidechain -> Polygon = https://opensea.io/collection/masset

**Comment by avaer** [comment]
Yeah I think we need to update the contract address. Once migrations are done we can add the Ownable interface to the contract and do it one more time.
