### ISSUE TITLE
Fe: Add filters for nsfw content

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1111]
Seems like we need two levels of filter: Nsfw and banned

Nsfw needs to be treated special, banned means we won’t show it at all (illegal or something)

**Comment by avaer** [comment]
It could be a bot command, we would just need to whitelist the users who can filter.

The filter can be stored in dynamodb.

**Comment by avaer** [comment]
I added a `token` table for this in DynamoDb. It should be accessible the usual way.

Here is the PK (`id` number):

![image](https://user-images.githubusercontent.com/6926057/114593297-f1578800-9c59-11eb-931e-b57e4f634cd6.png)

We can also use this for e.g. likes.
