### ISSUE TITLE
FE: Stripe "buy SILK" button (+)

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1113]
![image](https://user-images.githubusercontent.com/6926057/114767431-9d21d600-9d35-11eb-83c5-cfc303c6bf66.png)

**Comment by madjin** [comment]
I'm very hesitant about this feature, this will negate the invite only aspect of Webaverse and the web of trust we aim to build with it. It will be an open invitation for anyone to join, with no chain of whom invited them. We could think of other ways of distributing SILK first.

**Comment by avaer** [comment]
I don't have a strong opinion.

It would be nice to have an answer for people how we are sustaining the mints.
