### ISSUE TITLE
Fe: activity page -> open source viewer

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1114]
We should move the custom https://webaverse.com/activity page to a real block explorer.

Since we are running regular geth nodes, I expect https://github.com/blockscout/blockscout would be compatible and looks good. Polygon uses it.

**Comment by softwarebycl** [comment]
This could be setup with the [api](https://polygon-explorer-mainnet.chainstacklabs.com/api-docs) (link to Polygon's) provided by block scout (#1130).

**Comment by avaer** [comment]
Closing in favor of https://github.com/webaverse/app/issues/1130, they are basically the same issue.
