### ISSUE TITLE
App: High metallic values result in very dark models

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1116]
### glTF viewer, hdri skybox
![image](https://user-images.githubusercontent.com/80061436/114923783-23691580-9e25-11eb-9847-9b314ca37b14.png)

### in-app, webaverse
![image](https://user-images.githubusercontent.com/80061436/114921971-0895a180-9e23-11eb-9156-be2b1912d40a.png)

Metallics on models at high ranges will appear dark.

Current workaround that appears to work is to dial back metallic values to sub 0.500, and to fake the effect of reflections a bit, up the roughness. (could possibly add a seperate texture to do this, but that then goes against the ORM/RGB workflow for glTF) 

With lighting and skybox support this will be less of an issue / non-issue

**Comment by avaer** [comment]
I wonder if adding more lights to the scene would help.

**Comment by Vianvolaeus** [comment]
That, or intensity of existing lighting increased. The current light(s) are probably quite low, and since there's a lot of baked lighting / toon models being used at the moment, we wouldn't really notice it.

**Comment by avaer** [comment]
Via's engine research: https://github.com/webaverse/app/issues/1393#issuecomment-886689890
