### ISSUE TITLE
Fe: Jumpy card

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1119]
Seems specific to screen sizes?

![](https://gyazo.com/29aee9d6eb5e1bfabd97751d71b56a42.gif)

**Comment by avaer** [comment]
This is probably because the timing of the images loading and the exact size of the screen causes the dimensions to be captured during the wrong time before the cards re-sort.

**Comment by avaer** [comment]
Probably fixed with https://github.com/webaverse/webaverse.com/commit/49b5d1994fb9e2089d0bcb9b73fea8790012e450, can you re-test once it deploys?

**Comment by avaer** [comment]
This should be fixed now.
