### ISSUE TITLE
Fe: Possible caching bug with assets

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1129]
Checked my inventory, saw that asset 1 2 3 weren't there. I looked at asset 1 and it says its owned by me (`0x31e4ca4c07aeb731183334532e80e273d34c47af`) but apparently it belongs to `0x7fb5ffc37c34729ca982e1c01bb2d8a4e0ff6350`?

![image](https://user-images.githubusercontent.com/32600939/115095270-a7d39b00-9eee-11eb-892b-6e9769ea0ef2.png)

Note: this happened sometime after I associated my mainnet address to the sidechain on the account settings page.

**Comment by avaer** [comment]
I think this needs to be checked for accounts as well as the inlined account info in the tokens endpoint.
