### ISSUE TITLE
Be: Sidechain blockchain explorer

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1130]
Software to use: https://github.com/blockscout/blockscout

Links: 

* https://docs.blockscout.com/for-developers/information-and-settings/client-settings-parity-geth-ganache#geth-client
* https://docs.blockscout.com/for-developers/aws-marketplace/install-from-aws-marketplace

**Comment by avaer** [comment]
This still needs to be done, bumping. Related: https://github.com/webaverse/app/issues/1445

**Comment by madjin** [comment]
This guide has been useful: https://docs.komodoplatform.com/qa/blockscout-deployment-guide.html#blockscout-installation
I have ansible scripts backed up from setting it up last time incase it's useful.

**Comment by softwarebycl** [comment]
@madjin got blockscout running on AWS -- we could point `explorer.webaverse.com`  and link to it from the website / use its API to get activity histories.

![image](https://user-images.githubusercontent.com/29695350/130645074-599d2329-83a9-4f13-ba5a-7af079e7da8e.png)

**Comment by avaer** [comment]
I’ll point to the AWS address. I’m guessing it should be fronted with HTTPS certs?
