### ISSUE TITLE
Fe: Card colors for filetypes

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1131]
It's more confusing than its worth for random generating a color for every card. Can instead have a color for each filetype:

* Images
  * png
  * gif
  * jpg
* Video
  * webm
  * mp4
* Audio
  * mp3
* Models
  * glb
* Avatars
  * VRM

**Comment by madjin** [comment]
Question: Should there be a slight variation of color between two similar filetypes like webm and mp4? Personally I think it'd be cool if they're slightly different.

**Comment by madjin** [comment]
I think this color scheme will work good with a slight color variation for the different extensions.

Images: blue
Video: purple
Audio: green
Models: red
Avatars: orange

**Comment by Vianvolaeus** [comment]
note: we touched briefly on rarity as well as type influencing card design - eg: rarity for border color, type for main color, or vice versa.

I think from a design standpoint I think it depends which aspect is wanted to be portrayed as more important - the type of item, or the rarity of it. (eg: rarity focus - golden / shiny etc. main color with ex. red border to show it's a glb)
