### ISSUE TITLE
App: Spawning .vox is angled and mirrored

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1134]
When spawning a .vox model with drag n drop into the window it loads in tilted at an angle and the text is backwards.

![image](https://user-images.githubusercontent.com/32600939/115186458-ba490280-a0af-11eb-9d45-4b9a74bf7d24.png)

**Comment by avaer** [comment]
It's probably a bug in the vox loader we're using, probably need to invert the loop.

Can we get a sample file/NFT?

**Comment by madjin** [comment]
https://cdn.discordapp.com/attachments/684167488963215364/833500712562458704/cl.vox

**Comment by avaer** [comment]
Should be fixed now.
