### ISSUE TITLE
default avatar leaning issue

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1146]
just noticed this , will do my best to debug 
![Screenshot at 2021-04-23 08-40-56](https://user-images.githubusercontent.com/5592454/115872456-d3371800-a40f-11eb-8ac9-6f29468e192a.png)

**Comment by avaer** [comment]
What is this about?

**Comment by plankatron** [comment]
fixed, for now..
![Screenshot at 2021-04-23 13-21-31](https://user-images.githubusercontent.com/5592454/115907503-f88b4c80-a436-11eb-999f-01c1e522f9fa.png)
