### ISSUE TITLE
Fe: copies owned for editions

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1147]

**Comment by madjin** [comment]
context: when you own a lot of editions of a NFT it doesn't say so on the frontend

I own 30 editions of these shirts: https://webaverse.com/assets/627

versus on opensea it says x2 when you own 2 of that edition
![image](https://user-images.githubusercontent.com/32600939/128266421-248e73c0-471d-4234-bf15-16db16c0d5b1.png)
