### ISSUE TITLE
Fe: Changing title / description doesn't update card

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1163]
When I mint a NFT, then change the title or description, the change isn't reflected on the card.

Also, going to check if I can buy a NFT from Opensea then transfer back to the sidechain and edit it. Not sure if bug or feature. Technically if you bought it you could do anything with it right? Could open up the gates to remix culture, sorta like how people alter thrift store art and make awesome paintings with it.

![image](https://user-images.githubusercontent.com/32600939/116426709-33ef9780-a7f8-11eb-81a1-7dc8e189a06a.png)

**Comment by avaer** [comment]
> When I mint a NFT, then change the title or description, the change isn't reflected on the card.

This is because we never re-cache the card render.

**Comment by avaer** [comment]
We might have to do some sort of DELETE-based preview purge...

**Comment by madjin** [comment]
![2021-05-18-19:59:56](https://user-images.githubusercontent.com/32600939/118737937-bddcc000-b7fa-11eb-9255-2c59596f6b0a.jpg)

What if this refresh button updated the card?

**Comment by msub2** [comment]
Having seen the card UI for the first time, my first instinct was to click the refresh button to try and update the card.
