### ISSUE TITLE
Fe: Disable 3D and live for now

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1171]
![image](https://user-images.githubusercontent.com/32600939/116500571-d0f41400-a87c-11eb-9e44-d98cc7b599b5.png)

I think we can disable these buttons for now, meanwhile make 2D and card mode work great

**Comment by Vianvolaeus** [comment]
Specifically the 3D mode loads all content at once in the live preview mode w/ physics enabled, which isn't a smooth user experience - runs quite slowly for me at least.

**Comment by madjin** [comment]
Fixed with new carousel mode 
![image](https://user-images.githubusercontent.com/32600939/118403526-cf786900-b63c-11eb-8548-3048a5c4a741.png)
