### ISSUE TITLE
Fe: preview controls not functional

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1175]
Heart (favourite?) control for objects not persistent - loses when you revisit the same asset

Question mark control doesn't appear to do anything

There is also the [zoom issue detailed here](https://github.com/webaverse/app/issues/1138) regarding cards. 
Given the size of some of the card details are, and that fullscreen offers a lot of space real estate, and they're showing off card art / previews, seems appropriate that the user should be able to zoom in and pan/translate the card etc - like the 3d preview system works

**Comment by avaer** [comment]
> Heart (favourite?) control for objects not persistent - loses when you revisit the same asset
> Question mark control doesn't appear to do anything

Yup, it's not implmented yet. Good catch.
