### ISSUE TITLE
Fe: asset information incorrect

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1176]
Appears to be that the information panel is providing the info for the card itself rather than the asset (500x700 is the image resolution) - is this intentional? 

Below is a VRM asset card 
https://webaverse.com/assets/170
![image](https://user-images.githubusercontent.com/80061436/116595506-4d3d3480-a91b-11eb-989b-423b015c56ec.png)

**Comment by avaer** [comment]
Thanks, not implemented yet!
