### ISSUE TITLE
Fe: broken / incorrect asset preview

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1178]
https://webaverse.com/assets/321

This asset in particular is supposed to be a png according to madjin

* for some reason the preview hasn't worked correctly (and appears to be zoomed far in)

**Comment by avaer** [comment]
http://tokens.webaverse.com/321

**Comment by avaer** [comment]
This asset is seriously busted, its hash is `0.6r160a6hnqh` which makes me think some update got the radix wrong during a bignum parse or something.

@madjin was this ever hit with the experimental file browser?

**Comment by madjin** [comment]
It's this image, not sure about experimental file browser. I exported this image out of gimp for what its worth.
![couch](https://user-images.githubusercontent.com/32600939/118404460-f042bd80-b640-11eb-9fca-eb70564d09fe.png)
