### ISSUE TITLE
App: drag/drop and direct upload for VRMs not working

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1189]
drag/drop upload for VRMs appears to be broken - tested with the Default Bot 6 VRM.

No error message and/or upload message

Direct upload does not work - same as above.

**Comment by avaer** [comment]
We might be killing all free uploads like this, it was never supported and often abused.

FYI uploading avatars to the FE does work.

https://cdn.discordapp.com/attachments/737801646364557394/838407410510332014/2021-05-02_09-25-20.mp4

**Comment by Vianvolaeus** [comment]
Makes sense. I was mainly using it for testing - if this pre-mint preview is accurate to the game environment, then it should absolutely suffice
