### ISSUE TITLE
App: forward walk crouch control is a Chrome hotkey

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1191]
Ctrl + W is the shortcut to close current open tab, which is also the control to crouch and move forwards.

We probably should remap that control, but a toggle for crouch would work to a degree

**Comment by avaer** [comment]
We _do_ toggle crouch with CTRL.

However, the key conflict is indeed an issue and we might need to switch keys. Note that we cannot remap this hotkey, as the browser does not allow it.

**Comment by Vianvolaeus** [comment]
TIL my left CTRL is broken. Wonderful.

Apologies - I mean remapping the crouch control. Currently Z + C both individually open the editing menu and we could switch to one of those instead.

**Comment by soulofmischief** [comment]
> TIL my left CTRL is broken. Wonderful.
> 
> Apologies - I mean remapping the crouch control. Currently Z + C both individually open the editing menu and we could switch to one of those instead.

this was my suggestion as well, I think it's the best way forward and while V is more comfortable, C is probably the idiomatic choice.
