### ISSUE TITLE
FE: IN-GAME section of minting frontend showing incorrect object

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1195]
Preview environment showing the incorrect model during minting preview: 

Here we have the audio NFT minting section displaying an image, for example

![image](https://user-images.githubusercontent.com/80061436/116911892-60b00e80-ac3f-11eb-9dac-2a7d319e17a7.png)

Appears to be working with items that are already minted (?) :

![image](https://user-images.githubusercontent.com/80061436/116912147-be445b00-ac3f-11eb-8dc9-7fde0893a304.png)

**Comment by avaer** [comment]
Thanks, this should be fixed now 🙏.
