### ISSUE TITLE
Animation : Citrine poses for website

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1197]
Need about 50 poses for website , all poses should have transparent background for easier web development.

**Comment by avaer** [comment]
Maybe like 30 tops.

I think we have enough material in the assets/poses directory: https://github.com/webaverse/assets/tree/master/poses

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/121790468-b7e5bf00-cbad-11eb-8317-f8779fde1332.png)

About 17 poses made, currently in gdrive - is that the best place?

**Comment by plankatron** [comment]
https://drive.google.com/drive/folders/1AlBtFqtQdEl8QjZgzQDrv76Mw0CVUKJm also the face / pose matrix directories

**Comment by madjin** [comment]
Are the poses saved in the blend?

**Comment by plankatron** [comment]
just uploaded the blend file in the poses directory , above link
