### ISSUE TITLE
Fe: transferable/non-transferable tokens

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1200]
For minting personal/test copies of NFTs, we should support setting a token as transferrable or not during the minting process.

Non-transferable tokens cannot be moved (ERC721 transfer will fail), except to `0x000000000000000000000000000000000000dead` which is a burn.

By default non-transferable tokens can be created from an in-world drop (it could for example add it to your inventory, but you couldn't send it to anyone).

This will need contracts support, so depends on migrations.

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/121789990-d1d0d300-cba8-11eb-8f94-4df5bae08541.png)

**Comment by hamzatrq** [comment]
Non transferable NFTs is not supported in the contracts as of now. But contracts are upgradeable and it's a small feature so can be implemented within few hours.
