### ISSUE TITLE
Chest: silk does not explode out

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1213]
![image](https://user-images.githubusercontent.com/6926057/117077799-c1eee500-ad06-11eb-9475-b947bcf2f90d.png)

Very rarely it does (see on the left).

**Comment by madjin** [comment]
Strange, this just started happening for me also. 
![image](https://user-images.githubusercontent.com/32600939/118404144-955c9680-b63f-11eb-9e9e-24ad37df9fb8.png)
