### ISSUE TITLE
Docs: item PNGs

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1216]
Transparent PNGs of the following:

## Items
* SILK
  * Blob of silk
* Swords
  * Cryptosaber
  * Giant blade
* Rifle
  * New rifle by Sunny
* Pistol
  * New pistols
* Scythe
* Hoverboard
* Mounts
* Pets
* Parcels
* Models
* Music
* Videos
* Images
* HTML
* Animations
need transparent pngs for all of these

**Comment by plankatron** [comment]
directory for item images : https://drive.google.com/drive/folders/1dgLbfbbak1NTolG2yg8YFAd7dp_4FEXe?usp=sharing

**Comment by madjin** [comment]
Thinking of how to add these into https://docs.webaverse.com/docs/webaverse/items, first upgrading to v2 (https://github.com/webaverse/app/issues/1308)

**Comment by madjin** [comment]
going to quickly finish this issue 
![image](https://user-images.githubusercontent.com/32600939/122316883-8db43a00-ceea-11eb-9763-8d24f1f9b475.png)

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/122334341-92d3b200-cf07-11eb-94ab-6e4e0969e03f.png)
uploaded to same drive

**Comment by madjin** [comment]
How should these get displayed on the docs? https://docs.webaverse.com/docs/webaverse/items

**Comment by madjin** [comment]
Still need: 

- Animations
- Parcels

**Comment by madjin** [comment]
What I found for animation icons

![image](https://user-images.githubusercontent.com/32600939/122677568-def54f80-d1b0-11eb-8305-bdb5b8353a53.png)
https://thenounproject.com/term/animation/

Parcel icon ideas:

![image](https://user-images.githubusercontent.com/32600939/122677734-91c5ad80-d1b1-11eb-8afd-c657f5bc8acd.png)

I like the design somnium space has: 
![image](https://user-images.githubusercontent.com/32600939/122677749-a2762380-d1b1-11eb-8530-09b3bfcd20a4.png)

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/122677762-b9b51100-d1b1-11eb-8696-db328fd8915e.png)

**Comment by plankatron** [comment]
![parcel](https://user-images.githubusercontent.com/5592454/123319454-6d920580-d4fe-11eb-950d-16405a074558.png)
??

**Comment by madjin** [comment]
that works, thanks

**Comment by plankatron** [comment]
here is a 'dark' version
![parcel1](https://user-images.githubusercontent.com/5592454/123338802-6fb48e00-d517-11eb-879c-3cf9f5c57ed3.png)

**Comment by madjin** [comment]
Potions
![round_jar_transp](https://user-images.githubusercontent.com/32600939/125527038-8fc9ab36-def8-4525-86e3-86deb8b2e5e7.png)
![square_jar_transp](https://user-images.githubusercontent.com/32600939/125527042-1ebea467-fe26-4367-801f-306f6863dacd.png)
