### ISSUE TITLE
Fe: Improve screenshot angles and fidelity

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1218]
Some angles don't look good for the screenshots the preview server generates, here's a couple examples:

* https://webaverse.com/assets/104
* https://webaverse.com/assets/340

These could use better angles and shader which often the creator has the best eye for.

**Comment by Vianvolaeus** [comment]
During minting process, this avatar's preview appears to be different than the others on the site, which all have face-on headshots. Unsure why.

![image](https://user-images.githubusercontent.com/80061436/117331116-53d52a00-ae8e-11eb-93a2-5c20835a10d8.png)

for VRMs, there is usually a similar shot taken during the export process. VRoid Studio does it automatically. Custom VRMs can be exported with a thumbnail of choice.

If the minting process can read the VRM meta, this is another way of generating a preview for a minted avatar in particular.

**Comment by Vianvolaeus** [comment]
Suggestion to generate more than one preview at mint and allow user to pick the best one: 

https://discord.com/channels/433492168825634816/696210985035235358/839931257361137684

**Comment by plankatron** [comment]
Would it be possible during minting process for a 3d view of the item being minted to show up and allow the author to rotate around model origin , pick the angle they prefer and then take that as the preview shot?

**Comment by avaer** [comment]
> Would it be possible during minting process for a 3d view of the item being minted to show up and allow the author to rotate around model origin , pick the angle they prefer and then take that as the preview shot?

Yes, that is a good idea. Angles could be recommended.
