### ISSUE TITLE
Fe: VRM Mtoon values not previewing / compatible 

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1224]
In VRoid Studio relies on these shader effects for coloring hair, skin, and other effects - also opens up options for creators down the line too if things like this are supported.

![image](https://user-images.githubusercontent.com/80061436/117326039-305bb080-ae89-11eb-9a64-fcb5a5c11d6c.png)

UV scrolling is (very rarely) used and has been noted in #915

I am unsure if #896 is relevant to any current toon shader (planned?) implementation

**Comment by Vianvolaeus** [comment]
I will also add that https://github.com/vrm-c/vrm-specification/projects/1#card-43990752
appears to be the hub for working on the VRM spec itself - while almost entirely in Japanese, it translates well enough to understand what's going on. Might be useful, appears they are actively changing things in the shader spec itself at present.

**Comment by avaer** [comment]
We should support the spec as fully as possible. [`three-vrm`](https://github.com/pixiv/three-vrm) has most of the shaders, I just don't think they are currently hooked up.
