### ISSUE TITLE
Art: clean up directories

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1225]
- [x] Move the `Environment` (https://drive.google.com/drive/u/0/folders/1nc8BXqSXGw7UqhMaMT0TceV2HwdcwJse) directory to `Webaverse_Content` (https://drive.google.com/drive/u/1/folders/127YVFJOhfWLDQrP7nV_rz8AEvKGqnSlQ)
- [x] General clean up sorting the art assets

**Comment by madjin** [comment]
It's an ongoing chore, but I'd say that I've sufficiently re-organized the art assets in the drive to this point and have been downloading as much images/media to a local directory also.

![image](https://user-images.githubusercontent.com/32600939/122630357-f806df00-d090-11eb-97fc-b0b408a3a548.png)
