### ISSUE TITLE
App: able to build in minting In-Game scene, no control panel

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1226]
Not sure if either the ability to build or the control list being missing is intentional, but you can build in the In-Game mint preview - there's not visible control list. Could confuse users during minting process, but also does allow for possibilities down the line for custom previews? 

![image](https://user-images.githubusercontent.com/80061436/117475142-9e6caa00-af53-11eb-830e-14cbb0165327.png)

**Comment by avaer** [comment]
Previews work entirely different now.
