### ISSUE TITLE
Galad Avatar 

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1244]
make an avatar based off of galad's concept art , 

Current progress
![galad-avatar](https://user-images.githubusercontent.com/5592454/117722981-cd7f5780-b1af-11eb-99f4-e6a7b9ec89e4.jpg)

**Comment by plankatron** [comment]
some updates 
![untitled](https://user-images.githubusercontent.com/5592454/117909689-b2444300-b2a8-11eb-9924-45dcae66b8ba.jpg)

**Comment by plankatron** [comment]
![test_texture (1)](https://user-images.githubusercontent.com/5592454/118024693-fe38cb80-b32c-11eb-83ae-9bca16747aa1.png)
![test_texture](https://user-images.githubusercontent.com/5592454/118024700-fed16200-b32c-11eb-8a48-96ff0fa5bfb9.jpg)

**Comment by plankatron** [comment]
![Uploading test_texture1.png…]()

**Comment by plankatron** [comment]
little animation of current progress

https://user-images.githubusercontent.com/5592454/118166326-589c5f80-b3f3-11eb-9a18-a452e0e27f36.mp4

**Comment by plankatron** [comment]
adding in some bump / spec / roughness in prepping for this to export to glb
![pbr](https://user-images.githubusercontent.com/5592454/118320350-201b8500-b4ca-11eb-884c-dd2ac139718c.jpg)

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/118325421-717b4280-b4d1-11eb-92fe-dbbd5f5e8f85.mp4

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/118326044-64128800-b4d2-11eb-99ad-7305a7a63ddd.mp4

**Comment by plankatron** [comment]
currently adding some animations to this they will be as follows 

8-way directional animations , whole body
hatch open / close animation 
jump animation 

currently i plan for this to be a glb since its not meant to be be wearable but i can swap out the armature in the future, one issue with this being a vrm though is it needs special bones for its hatch open / close animations and i am not all the way sure how vrm/webaverse would handle that

**Comment by avaer** [comment]
In the future any named animation will be able to be selected for avatar/pet actions and states but I wouldn't worry about it yet.

**Comment by Vianvolaeus** [comment]
Is this effectively finished? We've been using the current iteration in docs images and in the loredoc. They play a part in the lore and story, so this should be confirmed as finished or revisited if required.

**Comment by plankatron** [comment]
its essentially done , for now
