### ISSUE TITLE
Fe: Stuck at Polygon

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1248]
Item is https://webaverse.com/assets/264

The NFT has a collaborator (myself) that was set with the Discord bot.

The unlockable for the NFT was set via a DM with the NFT Discord bot via `.sets 264 <ipfs url>`

Transaction was rejected for transfer to Polygon, has been in stuck state ever since.

![image](https://user-images.githubusercontent.com/32600939/118378707-9344fa00-b5a3-11eb-9892-969edd8fbb52.png)

Hit retry, complained about network

![brave!UNITO-UNDERSCORE!6dF0qfBtBJ](https://user-images.githubusercontent.com/32600939/118378794-08183400-b5a4-11eb-888c-f5a1c90ce468.png)

Changed network for matic (chain id 137), then hit retry. Will get error message in the console of the metamask before confirming transaction saying: "ALERT: Transaction Error: Exception thrown in contract code"

![brave!UNITO-UNDERSCORE!iD4Ha6CAuW](https://user-images.githubusercontent.com/32600939/118378812-1cf4c780-b5a4-11eb-836f-fae80c0f9466.png)

Hitting confirm anyways will result in a failed transaction.

**Comment by madjin** [comment]
Token is appearing on Opensea: https://opensea.io/assets/matic/0x1e9dc2903cf07a047ebddb28b14174ea3a86a775/264

**Comment by soulofmischief** [comment]
I solved this the other day for myself

**Comment by soulofmischief** [comment]
The solution was to add Matic network to metamask:

- Add custom RPC:
Name: Matic Mainnet
RPC URL: https://rpc-mainnet.maticvigil.com/
Chain ID: 137
Symbol: MATIC

**Comment by soulofmischief** [comment]
oh wait I see that was tried... it worked for me. I didn't encounter the same error. Investigataing.

**Comment by avaer** [comment]
What worked for you? This token?

That should be impossible, since the transfer address has been committed.

**Comment by avaer** [comment]
Do NOT use this in endpoint production or you will be fired: https://stuck-debug.webaverse.com/NFT/mainnetsidechain

This will however let an engineer compute the delta as perceived by the redis server.

**Comment by soulofmischief** [comment]
my own token, but i didn't actually confirm the tx because i wanted it to remain stuck for testing, I am transferring MATIC to my address now to try confirming it.

Thanks for the endpoint, that's super helpful.

**Comment by avaer** [comment]
```
a = [paste the endpoint result]
a = Object.keys(x).map(k => {return {name: k, values: x[k].filter(e => e.returnValues.tokenId === '264')} })
```

**Comment by avaer** [comment]
```
[
  {
    "name": "mainnetDepositedEntries",
    "values": []
  },
  {
    "name": "mainnetWithdrewEntries",
    "values": []
  },
  {
    "name": "sidechainDepositedEntries",
    "values": [
      {
        "address": "0x368F1F035E8ED29614b0a3E29947bCD2957f3782",
        "blockNumber": 4709883,
        "transactionHash": "0x1b010bb35bf0a16b332c7b9e5704e7d91754c1d80125f5faf542a5c43853b79c",
        "transactionIndex": 0,
        "blockHash": "0x859fd78999494114fc50dd897c45b8e439ad97b3aca7d70ad6aa4e1e35f17b24",
        "logIndex": 0,
        "removed": false,
        "id": "log_c07f551d",
        "returnValues": {
          "0": "0x0e3a41217d8C291081598c46d738AaAf5Be3907e",
          "1": "264",
          "to": "0x0e3a41217d8C291081598c46d738AaAf5Be3907e",
          "tokenId": "264"
        },
        "event": "Deposited",
        "signature": "0x2da466a7b24304f47e87fa2e1e5a81b9831ce54fec19055ce277ca2f39ba42c4",
        "raw": {
          "data": "0x",
          "topics": [
            "0x2da466a7b24304f47e87fa2e1e5a81b9831ce54fec19055ce277ca2f39ba42c4",
            "0x0000000000000000000000000e3a41217d8c291081598c46d738aaaf5be3907e",
            "0x0000000000000000000000000000000000000000000000000000000000000108"
          ]
        }
      }
    ]
  },
  {
    "name": "sidechainWithdrewEntries",
    "values": []
  },
  {
    "name": "polygonDepositedEntries",
    "values": []
  },
  {
    "name": "polygonWithdrewEntries",
    "values": [
      {
        "address": "0x368F1F035E8ED29614b0a3E29947bCD2957f3782",
        "blockNumber": 14538440,
        "transactionHash": "0x11bc2f03366c244ae27094639f0da10f3baa29cedcea484dcff864098b02462b",
        "transactionIndex": 49,
        "blockHash": "0xb53332e1153ee9576447a86a27d573591644b66804918383340f1063efcd0474",
        "logIndex": 123,
        "removed": false,
        "id": "log_101c9fad",
        "returnValues": {
          "0": "0x0e3a41217d8C291081598c46d738AaAf5Be3907e",
          "1": "264",
          "2": "12214294513535647191783285361456577053590499754375295158351499708756602894236",
          "from": "0x0e3a41217d8C291081598c46d738AaAf5Be3907e",
          "tokenId": "264",
          "timestamp": "12214294513535647191783285361456577053590499754375295158351499708756602894236"
        },
        "event": "Withdrew",
        "signature": "0xadec52fcd1408589179b85e44b434374db078b4eaf793e7d1a1bb0ae4ecfeee5",
        "raw": {
          "data": "0x",
          "topics": [
            "0xadec52fcd1408589179b85e44b434374db078b4eaf793e7d1a1bb0ae4ecfeee5",
            "0x0000000000000000000000000e3a41217d8c291081598c46d738aaaf5be3907e",
            "0x0000000000000000000000000000000000000000000000000000000000000108",
            "0x1b010bb35bf0a16b332c7b9e5704e7d91754c1d80125f5faf542a5c43853b79c"
          ]
        }
      }
    ]
  }
]
```

**Comment by avaer** [comment]
Do not trust what I say without independent verification. But as far as I can tell this token is not stuck, it is on polygon.

Which would indicate this endpoint is wrong:
https://tokens.webaverse.com/264

Which would mean the redis-server is incorrectly computing and caching the stuckness state.
Possibly around this area: https://github.com/webaverse/redis-server/blob/342aff1573e56475d94372dafe28add98224638b/tokens.js#L152

**Comment by soulofmischief** [comment]
That would explain why I am getting invalid txs as well using the same code. This is what I was looking into today anyway so I'll dig into it.

**Comment by soulofmischief** [comment]
Untested on this codebase until I get a rediskey, but tested on the contracts codebase:

**Comment by madjin** [comment]
Another user repro'd the issue, rejected the transaction to add a description which then got the token in a stuck state. Network was set to Matic in Metamask. Link to asset: https://webaverse.com/assets/436

**Comment by soulofmischief** [comment]
@madjin https://webaverse.com/assets/264 should correctly show Polygon now, but asset 436 appears to genuinely be stuck.

**Comment by soulofmischief** [comment]
Docs should solve the metamask rpc config issue, try to unstick 436 using the correct rpc and see if it works.

**Comment by avaer** [comment]
We should trigger the matic network reconfig rather than spitting out this error.

**Comment by avaer** [comment]
https://github.com/webaverse/webaverse.com/blob/151ece9a6c1091e8296c7408cca614063a9b0fc1/webaverse/blockchain.js#L348

**Comment by soulofmischief** [comment]
https://github.com/webaverse/webaverse.com/pull/49
