### ISSUE TITLE
Fe: NFTs missing from inventory

### ISSUE THREAD

**Issue by soulofmischief** [webaverse/app#1249]
[#322](https://webaverse.com/assets/322) does not appear in CL's inventory and must be accessed from [opensea](https://opensea.io/assets/0x42fae5a6dbd93cf63ed9eea0449825ddc8234a17/322).

https://tokens.webaverse.com/322 correctly shows the location as mainnet, however the asset page says "webaverse sidechain"

CL also reports that some assets sent to polygon also do not appear in their inventory.

**Comment by soulofmischief** [comment]
With redis patches in place, https://tokens.webaverse.com/264 now correctly shows the right chain but still shows owner as Anonymous and is not present in the user's inventory.

**Comment by avaer** [comment]
If the token is on another chain then it will not be considered owned by the user anymore, it is owned by the contract.

With a more thorough signature validation (https://github.com/webaverse/app/issues/1173) a user with a metamask sig bound could be shown as the owner.

But the general policy is if you have moved the token elsewhere then you are on your own for managing it, and there is no reason we have to show it on our end.

**Comment by soulofmischief** [comment]
We could also just clarify that the token is owned by the contract instead of Anonymous.

**Comment by avaer** [comment]
> We could also just clarify that the token is owned by the contract instead of Anonymous.

That is already the case. The contract has no name so it is `Anonymous`.

It's a good idea to make it a special case though.

**Comment by soulofmischief** [comment]
I wrote this:

```
async function getTokenOwner(token) {
  if (await isContractAddress(token.ownerAddress)) {
    return 'Webaverse';
  } else {
    return token.owner.username;
  }
}

async function isContractAddress(address) {
  const {addresses} = await getBlockchain();

  // Reduce address object to a list of addresses.
  const contractAddresses = Object
    .values(addresses)
    .flatMap( network => Object.values(network))
    .map( a => a.toLowerCase())

  // Test against the provided address.
  return contractAddresses.includes(address.toLowerCase());
}
```

but it looks like passing async props is a total mess for that component and I'm not sure what the idiomatic approach is bc I see two conflicting strategies, and as it stands, state is not being updated asynchronously. If you want to hook in `getTokenOwner` be my guest, it looks like I would need to sit down and rewrite part of the component and it's probably fresh in your memory.

**Comment by avaer** [comment]
The list of contract addresses can be fetched once on load and then at runtime, it's a `.includes` check.
