### ISSUE TITLE
Be: redis-server doesn't always cleanly stop

### ISSUE THREAD

**Issue by soulofmischief** [webaverse/app#1254]
Sometimes the process exits immediately after executing instead of waiting for child processes to finish and a system reboot is required. Child processes probably are not being cleanly stopped.

**Comment by avaer** [comment]
I noticed this too but why a system reboot? Can't it just be killed?

**Comment by soulofmischief** [comment]
Killing the parent process wasn't enough. I needed to kill the children and a reboot was just a way to do that without knowing what the children processes were.

**Comment by avaer** [comment]
Why not `ps faux`?

**Comment by soulofmischief** [comment]
`ps faux`, `ps -aux | grep node`, either are fine. I misspoke saying a reboot was *required*, it's just what I did the first time.
