### ISSUE TITLE
Avatar: boneperson

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1256]
Can we get a VRM model made that is literally just a bone representation?

![image](https://user-images.githubusercontent.com/6926057/118552769-615f9f00-b72d-11eb-94b8-504924a930a1.png)

I am going to be doing wearable UI and wearables attach to bones. So I need a visualization of the bones which I can raycast against. The easiest way is a model that is all bones, very low poly.

**Comment by plankatron** [comment]
I'm on it

**Comment by plankatron** [comment]
a super duper quick one 
this is 1.7k triangles
http://7rnx.net/fleeky-pub/webaverse/bone-avatar/ybot-dec.vrm

this is 50k triangles
http://7rnx.net/fleeky-pub/webaverse/bone-avatar/ybot.vrm

**Comment by avaer** [comment]
Is that 1:1 with VRM bones and perfectly aligned? I actually hadn't even considered ybot here because I didn't realize the avatar's meat to bone ratio was 1:1.

But I don't think it works anyway; I want to underlay this model on an avatar, so you have both the bone structure and your own avatar displayed, and then you click the bones inside the avatar. And this guy's fat to fit inside of a vroid.

**Comment by avaer** [comment]
I honestly think just remaking blender bones in blender (lol), or pilfering their source for this makes the most sense.

**Comment by Vianvolaeus** [comment]
Like a physical representation of a Blender Armature (octahedral)? 

I have something similar already - won't be *named like VRM*, but it should be VRM compatible (humanoid)

**Comment by avaer** [comment]
That looks great. I guess we'd just need to make it an actual VRM.

**Comment by plankatron** [comment]
![Screenshot at 2021-05-17 22-17-46](https://user-images.githubusercontent.com/5592454/118580462-eb276080-b75d-11eb-879f-7b47dace2bc0.png)
here is the vrm : http://7rnx.net/fleeky-pub/webaverse/bone-avatar/ybot_vrm1.vrm

**Comment by plankatron** [comment]
and here is an octahedron version 
![Screenshot at 2021-05-17 23-54-07](https://user-images.githubusercontent.com/5592454/118587859-4e6bbf80-b76b-11eb-98df-64edbe1e38b4.png)
http://7rnx.net/fleeky-pub/webaverse/bone-avatar/ybot_vrm_octa.vrm

**Comment by avaer** [comment]
Thanks, I'll see if I can make it work!

**Comment by madjin** [comment]
I'd say it's working ![](https://i.gyazo.com/e2e24370fdda5e8df4062e1282de9ab4.gif)
https://webaverse.com/assets/669

**Comment by madjin** [comment]
![e2e24370fdda5e8df4062e1282de9ab4](https://user-images.githubusercontent.com/32600939/121963892-b98fbe00-cd38-11eb-8628-89a05d6745b8.gif)

**Comment by Vianvolaeus** [comment]
Is this still an open issue? I believe this is completed.

**Comment by madjin** [comment]
yeah it needs to be tested in a certain context of the app first

**Comment by plankatron** [comment]
i would call this one done

**Comment by avaer** [comment]
I b think it is done hit it hasn’t been tested in the wearables editor do it is not known if it will need changes.

Keeping it open until that is the case.
