### ISSUE TITLE
Fe: Map isn't loading

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1259]
The map is broken, shows as black screen for everyone: https://webaverse.com/map

I say we replace it with blog for now.

**Comment by madjin** [comment]
Is this related? https://github.com/webaverse/app/issues/119

**Comment by avaer** [comment]
No, an engineer needs to fix it.

**Comment by avaer** [comment]
This is my fault, the error is pretty obvious from https://app.webaverse.com/map.html.

That HTML file import tree hasn't been ported to the webaverse runtime lib: https://github.com/webaverse/lib

I'll fix it.

**Comment by avaer** [comment]
Fix should be deployed. Please re-open if it's still an issue.
