### ISSUE TITLE
Model: card ripping animation

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1260]
I need a model of a card being ripped down the middle with a morph. The intent is to be able to rip cards in VR. If I have an animated card morph with certain specifications, I can handle the avatar kinematics while twiddling the morph.

## Pseudo-Spec
Card horizonatal, facing towards the camera (pov perspective), rips down the middle as if ripped from the top, with left hand shoved forward and right hand shoved back.

At the end position of the morph, you would have the two sections of the card separated by 90 degrees (pitched +90deg up around X axis) and no longer connected. The rip should be exactly in the middle of the card. The origin should be the starting point of the rip, the center-top point. This is for easy math.

No need to model the hands, only the card performing the rip. It should look natural; there is some amount of flexing in a rip.

The card should have four (4) image placeholder panels, each exactly half of the card in size, two halves per side, front and back sides, UV'd so that only two textures are needed (front and back). I can set these panels with a texture in the engine if they have descriptive names. The rip textures in the middle (on each side) covers up the seam. The cards should have the typical bevel, and should be z-distant enough that there is no fighting at personal distance.

The measures can be the physical Pokemon card dimensions, 2.5 inches by 3.5 inches.

There is a rip texture available here which might work if stuck on both sides: https://www.behance.net/gallery/89362471/Free-Download-Ripped-Paper-Texture-Set

**Comment by plankatron** [comment]
I am wondering if you have any specific concepts or expectations of fidelity on this one. 

- Z-fighting will be the biggest problem here
- doing some kind of physics sim and baking that is out of the question since we do not support alembic or anything like that
- manually modelling the rip is possible but may end up looking cartoony / lowpoly? 
- can try the rip overlap concept, but again z-fighting 
- have a rip state in code so you can immediately switch to the 'ripped' version of the card model and perform the ripping animation 

once i understand what you want a little more precisely i can probably get this done pretty fast, just want to be on the same page first.

any concept images / animations / examples would be helpful!

**Comment by avaer** [comment]
I think we can separate the card by even 1mm and then Z fighting shouldn't be a problem.

A baked rip sounds fine.

> have a rip state in code so you can immediately switch to the 'ripped' version of the card model and perform the ripping animation

Yes, that is why we can get away with slight Z difference. I think it won't be noticeable.

**Comment by avaer** [comment]
<img width="1247" alt="hands" src="https://user-images.githubusercontent.com/6926057/118867307-ef17c780-b8b0-11eb-901e-7aa294cb3b79.png">

**Comment by plankatron** [comment]
current progress , i need to find a way to fix this one specific issue , have a few ideas
![card](https://user-images.githubusercontent.com/5592454/119027509-69f5e680-b974-11eb-9614-39b6dbfc92aa.jpg)

**Comment by avaer** [comment]
This looks like a good start. Btw, the ripping direction is preferably horizonal, but I imagine that to be just a scale + uv change.

Is the issue that the front/back layers don't play nice and need to be simultaneously ripped?

**Comment by plankatron** [comment]
does webaverse support multiple uv channels ? 
would be ideal for this situation one set of uvcoords handles this base texturing and then for the actual card design we could have another ,

**Comment by plankatron** [comment]
one more update, having issues with transparency , went from alpha blend to alpha clipped, still need to mess with it a bit more .. anyway here is the result so far. 

https://user-images.githubusercontent.com/5592454/119048487-48edbf80-b98d-11eb-8b13-a8bc210cdb51.mp4

**Comment by avaer** [comment]
I can write any shader so we can have as many uvs as needed.

But my thinking on this is that the rip can just be a separate geometry/mesh.

**Comment by plankatron** [comment]
removed the taper that i had so that everything would fit together nicely , it sort of looks better but i also tweaked the animation so maybe i can just fix this in the animation hmm 

https://user-images.githubusercontent.com/5592454/119051650-6f155e80-b991-11eb-9d23-3e4d8b429cb9.mp4

**Comment by plankatron** [comment]
a bit better

https://user-images.githubusercontent.com/5592454/119052911-4bebae80-b993-11eb-8703-b237c18c9f0d.mp4

**Comment by avaer** [comment]
Looks like progress!

> the tradeoff is now you can see a clear difference between the tear geo and the card geo

Can we just make sure the top and the bottom of the rip mesh aligns correctly with the card image mesh? This should be possible to do pixel perfect.

One thing with the animation is that it isn't a progressive rip. There should be a line you can draw from v=0 to v=1 that progressively unzips the card.

Also the final angle in that video doesn't match the requirements.

**Comment by plankatron** [comment]
a bit of an update, having camera angle issues atm , but probably if you go orthagraphic or if its further away might be closer to your concept. 

https://user-images.githubusercontent.com/5592454/119170707-a3405c00-ba31-11eb-811a-fc53fb56bb81.mp4

**Comment by madjin** [comment]
![snowcrash](https://user-images.githubusercontent.com/32600939/119177984-17cbc880-ba3b-11eb-9f33-b515a8ce4114.gif)

**Comment by plankatron** [comment]
oops , i misunderstood part of this assignment,  fixed the card ratio!

https://user-images.githubusercontent.com/5592454/119193881-4bfdb400-ba50-11eb-97d2-0b7ab2de8e57.mp4

**Comment by avaer** [comment]
Looks like it's worth testing! I want to check out how the rip feels on a real card.

Can we put the asset in the assets repo?

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/119197376-a0eff900-ba55-11eb-9627-46a0005a2213.mp4

**Comment by plankatron** [comment]
http://7rnx.net/fleeky-pub/webaverse/card/card4.glb
i tested this in babylon.js and it did not come out looking correctly, but i did re-import into blender and the extra uv channel is at least exporting.

**Comment by plankatron** [comment]
ok comitted card-rip.glb to repo
