### ISSUE TITLE
Fe: Search bar isn't completely obvious

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1264]
To make it dummy proof, can add "search" faded in the text field of the search bar. Perhaps we need a better magnifying glass icon?

**Comment by madjin** [comment]
Also I'd consider replacing the music filter icon with music notes and add tooltips.

The alternative is we remove the filters on the top navbar, and just leave it as search only, then try to make the navbar thinner. When people search for something, there can be a filter UI in between the results and the different views buttons. The placement somewhat similar to Sketchfab search: https://sketchfab.com/search

**Comment by softwarebycl** [comment]
New website has search bar at top / magnifying glass  / search placeholder text.
