### ISSUE TITLE
Fe: Media + In-game preview broken for Firefox

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1265]
Based on user feedback with fresh install of Firefox, was able to repro as well.

Webaverse.com -> media / in-game previews don't display any previews

![image](https://user-images.githubusercontent.com/32600939/118846841-1e233e80-b89b-11eb-9205-847ac356ef7a.png)

**Comment by madjin** [comment]
This issue also extends to the app as well for Firefox users
![image](https://user-images.githubusercontent.com/32600939/118847076-5dea2600-b89b-11eb-9cbb-f1dc79d3123c.png)

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/122683333-8469ec80-d1cc-11eb-93a0-4af500adfade.png)

here's the issue https://github.com/webaverse/app/blob/master/preview.js

**Comment by madjin** [comment]
https://github.com/webaverse/app/compare/147f031abf8e...98151fa71e8e#diff-ffb35c4e1cca724e6787fb3774da04e864cc7fc240540ce69a799004fde036f9

**Comment by avaer** [comment]
This isn't going to be supported until Firefox implements import maps.

https://github.com/webaverse/app/issues/1319#issue-926523290

**Comment by avaer** [comment]
https://caniuse.com/import-maps

**Comment by Gomez** [comment]
I had success with this polyfill: https://github.com/guybedford/es-module-shims

The error is still in the console but the app renders and i can walk around :+1:

**Comment by avaer** [comment]
Good to know! I think we'll probably just get rid of the import maps on our end either way.

**Comment by Gomez** [comment]
That would mean a bundler, like webpack, right? Looks like a bigger refactoring?

In the meantime, i could prepare a PR with the polyfill. Just not sure how the libs get into https://lib.webaverse.com/?

**Comment by avaer** [comment]
> That would mean a bundler, like webpack, right? Looks like a bigger refactoring?

No bundler, but rather relatively mechanical refactoring that would touch a lot of file heads, moving references to `https://lib.webaverse.com/`.

There are other reasons we might want to bundle however.

> In the meantime, i could prepare a PR with the polyfill.

It might be good for posterity but I'd rather just get rid of the import maps entirely, in favor of the lib.

The lib is at https://github.com/webaverse/lib
