### ISSUE TITLE
Galad Tactical Guitar concept to creation thread

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1266]
just putting this here to post my updates on the tactical guitar 
![GuitarConcept_V2](https://user-images.githubusercontent.com/5592454/118849204-7f4c1180-b89d-11eb-988b-bec4c33fe2de.jpg)

**Comment by plankatron** [comment]
basic blockout done : 
![tactical_guitar](https://user-images.githubusercontent.com/5592454/120244200-9abd0200-c237-11eb-963c-b5d370ae87e5.jpg)

**Comment by plankatron** [comment]
update : 
![tactical_guitar1](https://user-images.githubusercontent.com/5592454/121252425-f90c6500-c875-11eb-9008-730e5ca1e6a4.jpg)

**Comment by GaladWarder** [comment]
Following up from our chat in #. dev, this is the only tweaks I would make - I wasn't sure how granular of feedback you wanted, so I just marked up anything that caught my eye - hopefully it helps!
![guitarCrit](https://user-images.githubusercontent.com/29031531/121530290-dfaf1880-ca2f-11eb-98b7-12941cc686bb.jpg)

**Comment by GaladWarder** [comment]
I'll have that materials sheet to you in a bit over an hour - need to get a bit of dinner, then I'll finish it up!

**Comment by GaladWarder** [comment]
Here's the materials sheet - the colors can all be tweaked, I'm not totally sold on this scheme. I do think the materials should be correct though - playing the steel, plastic, and rubber-y materials off of each other should give a pretty cool look. Feel free to mess around with it though - this is just what I had in mind off the bat.
![GuitarConcept_Textures_V4](https://user-images.githubusercontent.com/29031531/121548541-ac748580-ca3f-11eb-9252-6dd63d5f19f6.jpg)

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/121962290-9106c480-cd36-11eb-92f1-a898677f1e95.png)

**Comment by plankatron** [comment]
Current Todo for this asset : 
* make backpack 
* fold up animation for guitar , folds into a watchmen happy face 
* happy face goes onto backpack?

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/123432092-e908bb00-d5c1-11eb-810d-ec476b600b8f.png)

Made up a bunch of color variants. Haven't exported yet, but going to export a few that appeal visually.

One of the lighter / pink variants (or a more concentrated variant of it) might work as a prop for the Shilo character

**Comment by avaer** [comment]
These look good, but it turned out the concept of a guitar doesn’t fit
anymore (I know the art is working ahead of the script, sorry about that).

This looks like it could be turned into a scythe or other harvesting tool,
while keeping the same vibe, which does fit the current script.

**Comment by avaer** [comment]
Either way I think the guitar can be used later, but it doesn’t seem to
work with the initial 4 weapon set.

(One other thing that does fit is the mega sword, and I’m not sure about
the bow yet).

**Comment by Vianvolaeus** [comment]
It can probably be retrofitted as an axe / harvesting type tool/ weapon, like you say, by removing the headstock, strings, and perhaps having the 'blade' spin.

@plankatron started working on the backpack, so might be an idea to decide whether that needs to go in a different direction or stop entirely. 

Either way, posed Shilo with 'her' version of it earlier: 
![image](https://user-images.githubusercontent.com/80061436/123460443-8a523a00-d5df-11eb-800d-b0b6d0e2fc75.png)

**Comment by avaer** [comment]
Yeah it looks cool, I just don’t think it makes sense anymore.

It’s not so much that it can’t be retrofitted to a harvesting tool. It’s
more that I know people are gonna make these kinds of screenshots/poses
(because it is a cool idea), which is the problem of having any sort of
implication that it is a guitar.

**Comment by avaer** [comment]
I chatted a bit with the AI whether guitars specifically make sense and it seems to think no.

```
Comment:
Are there musical instruments like guitars in this world?
Rico:
There are musical instruments but not guitars.

Answer:
No.

Object Recognition lets you identify items, but it is not a good skill for a musician.

Answer:
There are no musical instruments in this world because music is hard to put into #blockchain as an NFT.

What would Sacks say?

Sacks:
In the old days, you could carry any object in the game and it would play music.

Rank:
That's so stupid.

Sacks:
The old guys got bored and wanted to see if they could make a guitar that worked.

Rank:
So they made it?

Sacks:
They did it in about 4th iteration.

Rank:
And you can play the guitar in the game?

Sacks:
But they never ended up putting it in the game.
```

**Comment by avaer** [comment]
I don't actually agree with all of that by the way so don't take it as gospel, I'm just showing the process in action.

**Comment by Vianvolaeus** [comment]
Backburner-ing while we work on the key character weapons and assets.
