### ISSUE TITLE
Fe: Show images as default, not cards

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1269]
Based on user feedback

We should have images as default, not cards. The details on the cards are basically unreadable unless you are really zoomed in.

Could swap the button order for cards and images.

**Comment by avaer** [comment]
This is probably not happening, but we should definitely increase the size of details.

**Comment by madjin** [comment]
![brave_5YgXNVdVn0](https://user-images.githubusercontent.com/32600939/118874714-34d88e00-b8b9-11eb-8673-88e2dfb9c9b4.jpg)

---


![brave_I0jLWVnpBw](https://user-images.githubusercontent.com/32600939/118874721-36a25180-b8b9-11eb-9f28-06454cde511b.png)

---

The previews are squished with the cards. The main details people look for at first is labeled in image preview mode: minter, filename + extension.
