### ISSUE TITLE
FE: Editions rendering

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1276]
User minted 10 editions, shows up in Discord inventory but not web UI

![image](https://user-images.githubusercontent.com/32600939/119058764-fc11e500-b99c-11eb-8dec-cb6bd607676e.png)

![image](https://user-images.githubusercontent.com/32600939/119058752-f74d3100-b99c-11eb-931a-14ce92e323da.png)

![image](https://user-images.githubusercontent.com/32600939/119058806-0fbd4b80-b99d-11eb-923d-e86e30673261.png)

**Comment by avaer** [comment]
FE needs editions rendering support.
