### ISSUE TITLE
Fe: Improvements to minting

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1281]
Some ideas on how to improve the frontend minting process based on strong use-cases (like NFTs to power virtual events).

1. Checkbox for transferrable or non transferrable

Right now its set to non-transferrable by default. I think there's a chance this can get glanced over and get minted as non-transferrable by accident. Would be better for this option to be more deliberate upon minting.

1. Add unlockable content during mint

While minting many editions, the ability to add unlockable content in bulk would save a ton of time. This is especially useful for event organizers and community admins. This can go right below `File`.

1. Add tags

Option right below description have ability to add comma separated tags, will improve search.

1. Add royalties

Option to set between 10-25% royalties after first sale. This can be the final option before preview.

**Comment by avaer** [comment]
Nice to haves.
