### ISSUE TITLE
modification to home.glb 

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1282]
just a thread about modifying home.glb 
atm i cannot commit directly to avaer's personal repo so i will post a link here for avaer to test with. 
http://7rnx.net/fleeky-pub/webaverse/avaer-home/test-home.glb

**Comment by avaer** [comment]
Repo has been moved here: https://github.com/webaverse/home

**Comment by plankatron** [comment]
comitted test-home to webaverse home repo

**Comment by madjin** [comment]
think this issue is no longer needed
