### ISSUE TITLE
Art: S1 logo

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1283]
This issue is for exploring logo designs for season 1.

The cold W really doesn't work with light designs I've been working on -- I feel like the the hard aesthetic of the grid clashes with things that stray from the grid.

Also, I want to kind of get away from the "W on a grid" in general. It hints at "metaverse" but that is a vague notion with a lot of baggage, it is impersonal, and the grid makes people think of land, which is the wrong place to start. It also doesn't seem very welcoming.

I threw this together with google images using stolen art:

![logo-01](https://user-images.githubusercontent.com/6926057/119428816-9c3c7680-bcdb-11eb-8c28-f7a79b0a0a39.PNG)
https://www.pikpng.com/pngvi/iximwow_cherry-blossom-drawing-png-clipart/
https://www.vectorstock.com/royalty-free-vector/elegant-black-roses-design-vector-20046056
https://www.google.com/search?q=nature+svg+divider
https://www.google.com/search?q=sakura+branch+svg

I tried to imply a lot of ideas with this:
- creativity
- openness
- markup `<>`
- cartoon logo
- convergence
- merging
- roads
- growth
- organic
- hand made
- high quality
- high tech
- caring
- good future
- park bench

By segmenting parts like this it would also allow for a lot of animation possibility in UIs.

Could use some variations playing around with this.

**Comment by avaer** [comment]
There could be a road/map motif in here somewhere too.

**Comment by avaer** [comment]
https://github.com/webaverse/assets/blob/master/logo-draft.ai

**Comment by avaer** [comment]
It could also be yin yang themed. The bottom right could be the hard "dark side" with the top representing the "light".

**Comment by avaer** [comment]
![apocalyptic-science-fiction-overgrown-wallpaper-preview](https://user-images.githubusercontent.com/6926057/120880400-51064b80-c598-11eb-9ae2-253af4ede0bf.jpg)

**Comment by avaer** [comment]
![unknown](https://user-images.githubusercontent.com/6926057/120880417-6aa79300-c598-11eb-8723-92f1d697978c.png)

**Comment by avaer** [comment]
![danganronpa](https://user-images.githubusercontent.com/6926057/120881851-0be71700-c5a2-11eb-81cc-d4e7ed0b36de.png)

**Comment by avaer** [comment]
![botw](https://user-images.githubusercontent.com/6926057/120881978-d5f66280-c5a2-11eb-8952-56464050fc32.jpg)

**Comment by avaer** [comment]
![botw2](https://user-images.githubusercontent.com/6926057/120881994-f3c3c780-c5a2-11eb-9c6d-9bbc461a31b7.jpg)

**Comment by avaer** [comment]
http://images.google.com/search?q=storybook+letters

**Comment by avaer** [comment]
https://www.pinterest.ca/pin/472103973414756728/

**Comment by GaladWarder** [comment]
Going to dump some stuff here - still a lot of work to go, hope you don't mind the looser sketching. If anything jumps out as especially good or bad, feel free to let me know
![Sketches_01](https://user-images.githubusercontent.com/29031531/121055842-33cbba00-c7f0-11eb-9b92-9f636845622a.jpg)
![Mockups_2](https://user-images.githubusercontent.com/29031531/121055863-37f7d780-c7f0-11eb-884b-6457efc07e5d.jpg)

**Comment by GaladWarder** [comment]
Is there any 'icon' that really relates to Webaverse in the same way that Link's sword relates to the Zelda games?

I'm playing around with the Street, the W, and  the pyramid, but they all feel a bit generic - let me know if anything comes to mind

**Comment by GaladWarder** [comment]
**This is old, just putting it here for records reasons. Already got feedback on these, they aren't in the right direction**

![Styleguide_AssetSheet_V1](https://user-images.githubusercontent.com/29031531/121059590-37f9d680-c7f4-11eb-9f1f-28ed53a0f320.jpg)

**Comment by GaladWarder** [comment]
Tried a totally different approach, seems like the previous ones weren't quite right. How is this direction? Playing more on the Street  idea, as well as on the stylized nature of Webaverse, the Fortnite influences, and the magical/RPG elements
![CartoonyMockup_V1](https://user-images.githubusercontent.com/29031531/121358566-4ca9ac00-c965-11eb-8882-df64738e4405.jpg)

**Comment by avaer** [comment]
Great work!

Very interesting approach with the street concept.

The one thing that seems missing is from the street is the implication of creativity or exploration;

Perhaps if the letters were made from some other materials growing out of the street, like ancient vines, advanced tech or weird goops it would add more personality.

Another comment is that whereas the 3D street looks great it might be hard to draw (people suck at perspective). I would also try some flatter versions (maybe sideways or top down view, depending on how the letters are represented).

Would also be interesting to see how that concept can collapse into a square or circle shape for iconography.

The other word marks have interesting color+line ideas too. But the street plus fortnite combination is the best basis.

**Comment by avaer** [comment]
Also, the logo should have a hint of Japanese, or something hinting at non-western origins.

That was always implied with 山 and people generally picked up on that. Although this font looks great and even adventurous, it loses a bit of that aspect. But there's probably also ways to add that back in with some sort of shape language like torrii, sakura, or whatever.

**Comment by GaladWarder** [comment]
Thanks for the feedback - I can definitely work with that!

I'll see what I can do to pull in more of the creativity/exploration vibes, as well as making the Street simpler and pulling some Japanese vibes/influences in, as well.

I'll do another round of revisions iterating on the more fortnite-y style and see what I can come up with!

**Comment by Vianvolaeus** [comment]
I'm not particularly great with logos but wanted to try and pitch in to help! I imagine there's some kind of terminology for it, but one thing I see that's quite prevalent and usually effective is this kind of standout single letter in the typography of some text based logos / headers: 

![image](https://user-images.githubusercontent.com/80061436/121735671-590d4080-caee-11eb-96f9-3de903632c20.png)

Some of them incorporate an existing logo into them or viceversa - take that element and run with it like a favicon etc. 

I think the 山 can work great with the proposed ideas, it looks like spires, or something vines / ivy could grow from.

If I can think of any other logos etc that might be inspiring, I'll communicate them to you or drop them here / update

**Comment by GaladWarder** [comment]
This is super useful, thanks vian!

It's funny that you were thinking of that too - I was messing around with having the A be a torii gate, hadn't considered using the 山 in a similar way but I think it's definitely worth messing with!

**Comment by avaer** [comment]
Are there source files for that cool font and design?

**Comment by avaer** [comment]
This is coming up on a month now so maybe it's time for me to take over the job.

**Comment by GaladWarder** [comment]
I have a PSD file for it, if that will work - https://drive.google.com/file/d/1-P0enrlDa-lN3cpni3hkpth3P526LkpY/view?usp=sharing

The font is called River Adventurer.

I can have it done pretty quickly though, the only reason it isn't yet is that last I heard I was supposed to pivot to wearables. If it's high priority, I can have it done and in SVG by the end of the week, possibly sooner.

Just let me know what you prefer!

**Comment by avaer** [comment]
Thanks!

I think wearables is ironically blocked on this in part, because the wearables should make sense in terms of the branding, rather than vice versa.

**Comment by GaladWarder** [comment]
Sure, no problem! I'll have updates here soon and I'll just shoot to have this shipped by end-of-week, then.

**Comment by avaer** [comment]
Ecco 2 Tides of Time (Genesis)
This is actually quite dark in tone, but in a curious way. Might provide some interesting textures or ideas to draw from.

![bot2](https://user-images.githubusercontent.com/6926057/122424980-271c3400-cf5d-11eb-959c-9a354b213be6.jpg)
![bot2](https://user-images.githubusercontent.com/6926057/122425354-6d719300-cf5d-11eb-8429-801ace8eed14.jpg)

**Comment by avaer** [comment]
Dragon from Sekiro
![img](https://i.pinimg.com/originals/2b/c4/02/2bc402527e99f8b18f434bbf2b1567df.jpg)

**Comment by GaladWarder** [comment]
These are silhouettes only - I want to get a final silhouette nailed down then I will add color/textures.
I think these should be getting closer to what you're looking for, is there one that jumps out to you that I can make tweaks to?

Also thanks for those screenshots/images - I think I'll pull color and texture ideas from Ecco, among other things.

![LogoRevisions_V4](https://user-images.githubusercontent.com/29031531/122509858-17711e00-d037-11eb-98f6-718edaeafee3.jpg)

**Comment by GaladWarder** [comment]
![LogoRevisions_V4](https://user-images.githubusercontent.com/29031531/122630545-11db0d00-d0f7-11eb-9c40-75e73600679e.jpg)

Looks like this may not have attached? Trying a re-upload

**Comment by GaladWarder** [comment]
Any feedback on these one way or another? I'll need to do a final pass on texture and color today, so if I haven't heard anything, I'll just run with the one I feel is strongest. 

Can always go back through if needed, but I'm shooting to have something final by the end of the week, so I'll have to run with something today.

**Comment by madjin** [comment]
personally think the W should be more emphasized rather than A, for sake of icons (see Z above: https://github.com/webaverse/app/issues/1283#issuecomment-855190700)

**Comment by avaer** [comment]
I don't think any letters need to be emphasized, but as a final step once everything is done perhaps the first letter could be storybooked.

https://www.google.com/search?q=story+book+font

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/122633373-4ecae380-d0a6-11eb-8cb7-6e823e337e9b.png)

This one is best but it's hurt by the enlarged torii and flat street (maybe I was wrong, or the lack of color and outlines makes this hard to picture in its final form).

I imagine the details being entangled with the letters themselves, growing into the letters somehow from the street. That would be really hard to show untextured.

And I also imagine there's more than one style of growth; perhaps vines plus something more digital or weird (that's why I added the Ecco references).

**Comment by avaer** [comment]
Also, that plant _does_ seem on brand, but I adding extra distinct objects in the letter area seems like it's muddying the design.

**Comment by GaladWarder** [comment]
Alright, I'll take the torii out and see about having the letters growing out of the Street, then!

**Comment by GaladWarder** [comment]
Alright lads, here's what I came up with. Tried to pull in the letters 'growing' from the street and mixing the organic with the tech/magic vibes, removed any accented letters, kept letter silhouettes clear of obstruction, and pulled in some of the Ecco textures while keeping to a loosely Fortnite style.

I think we're going to run into the issue of it needing to be simpler, but I'm honestly not sure how else to compress all that information to a simpler read; there may end up having to be a sacrifice of either some of the information or some of the clarity of the read.

I'll be able to do another round of revision before the Monday meeting (Monday my time is Sunday in the states), and am hoping we can find another time to voice chat either during the meeting or otherwise; there's a lot of info that's difficult to transmit over text.

Let me know what you think!

![LogoRevisions_V6](https://user-images.githubusercontent.com/29031531/122641563-bd588180-d138-11eb-8c95-87e85aba9ac6.jpg)

**Comment by GaladWarder** [comment]
Went through another round of revisions with Jin today, here's the sketches that resulted:

![LogoRevisions_Rendered_V8 copy](https://user-images.githubusercontent.com/29031531/122918597-e031a280-d391-11eb-9dbb-239bed72782c.jpg)
![LogoRevisions_V7 copy](https://user-images.githubusercontent.com/29031531/122918609-e32c9300-d391-11eb-8321-2342cce6c74a.jpg)

**Comment by GaladWarder** [comment]
I've also blocked in the vector shapes and base colors for a final, locking it to a grid and following design practices for spacing, etc...

![LogoRender_V9 copy](https://user-images.githubusercontent.com/29031531/122918738-048d7f00-d392-11eb-8b46-deeb7dac7148.jpg)

I am going to finish up a render tomorrow - this part took longer than expected due to being extremely unfamiliar with Adobe Illustrator. I think the only good way to get a clean end result is to re-create it all in Illustrator, so I am going to try rendering directly in that program.

**Comment by madjin** [comment]
That looks awesome! I wonder what it'd look like if the W was more wood / handmade texture and if the bottom right bracket is metallic / dark? This logo is a different flavor than the heavily stylized Fortnite Street, but does strike many of the ideas implied at beginning of the thread.

**Comment by GaladWarder** [comment]
Of course! I should have clarified: this is a WIP - I am just blocking out shapes. I'll add textures and form tomorrow.

**Comment by avaer** [comment]
This getting close, into the realm of usable already. 👏

Both the W and street styles of logos are good, but I actually think two distinct but related logos might be needed.

# Rectangle logo

![img](https://user-images.githubusercontent.com/29031531/122641563-bd588180-d138-11eb-8c95-87e85aba9ac6.jpg)

I think we see the same thing about simplifying.

I like like how the street bleeds into the letters, but that might be part of the problem. What might be a better idea is to swap that layer for some other color/texture that is a counterpoint to the green. Perhaps some of the ideas from the Square logo (below) could be incorporated.

Also, it seems that it's the rock texture that adds the most complexity. Would any other textures, gradients, or outlines make the letters stand out more? The outlines in the previous glowing version seemed to do a good job focusing attention on the logotype.

# Square logo

![image](https://user-images.githubusercontent.com/6926057/123003903-e1f36a00-d381-11eb-893f-576bd7239a61.png)

I really love the handrawn style of these, it's almost better than trying to flatten it if it can still be clear in favicon size (that's a good thing to check).

I highlighted what I think are the right ingredients, though I don't know how many of them will work together:

![image](https://user-images.githubusercontent.com/6926057/123004120-326ac780-d382-11eb-8dd2-42ec5151b9ff.png)
![image](https://user-images.githubusercontent.com/6926057/123005111-92ae3900-d383-11eb-944b-e45c5e5d0b77.png)

I like the idea of the socket plugging in, and how it combines the nature and digital theme, but I think it's too realistic/mundane. It might be more thematically if instead of being a traditional socket the cables implied:
- charging your phone or VR headset (different cable type)
- jacking into the Matrix (spinal hook)
- the Steward from infinity train (tentacles)

But adding some sort of counterpoint to the nature theme is what I think works best. The flowers on the plant could also be Ecco balls instead, if instead of the digital component like cables we wanted something more abstract.

![image](https://user-images.githubusercontent.com/6926057/123005184-afe30780-d383-11eb-9b52-8afbfbb1dd83.png)

**Comment by avaer** [comment]
The closest one word descriptor I found is "solarpunk", which should generate a lot of other ingredients if needed.

https://www.reddit.com/r/solarpunk
https://www.pcgamer.com/au/enough-cyberpunkits-solarpunks-time-to-shine/

**Comment by GaladWarder** [comment]
Alright - got some more iterations! Also, just for the record - thanks for the links to solarpunk; I think it's my favorite aesthetic I've seen.

First off, the rendered out square logo:
- Added wood/handmade texture
- made the bottom bracket dark/metallic
- pulled in some of the circled elements
- changed the plug type
- added counterpart to the natural textures with some hard metallic elements

![LogoRender_V10 copy](https://user-images.githubusercontent.com/29031531/123087049-b1c9cb00-d456-11eb-92a8-06a0f98ec924.jpg)

Tried to keep the individual textures low-contrast so that it will still read when small. I think for favicon size, though, it would be best to just use the 'w'.

**Comment by GaladWarder** [comment]
Next, I tried a more 'hand-drawn' look to it as mentioned, following along with some of the aesthetics I've seen in crypto art. Just an experiment, let me know what you think:

![LogoRender_HandDrawn copy](https://user-images.githubusercontent.com/29031531/123087248-e9387780-d456-11eb-8999-a7eabfbaaf8b.jpg)

This one will read extremely well small, and will be easy to convert to SVG. Loses some of the detail, though.

**Comment by GaladWarder** [comment]
Finally, I tried to hyper-simplify the rectangular logo as discussed. I think I kept most of the essence, but it reads much better now. Not sure if it's too simple or not, though:

![LogoRevisions_Stylized_V11 copy](https://user-images.githubusercontent.com/29031531/123087407-15ec8f00-d457-11eb-921c-c15462459730.jpg)

**Comment by GaladWarder** [comment]
Also, I had an idea when re-rendering the square logo - if we were to keep the overall format, the 'W' with the brackets, it could just be re-rendered in different art styles to match the different seasons.

So for example, if there was a voxel season, it could be rendered out pixellated and voxel-y. If there was an artist collab season, it could be rendered in their style, and so-on.

By keeping the same silhouette, it would tie all the seasons together while still being a season-specific logo. It also would be fast to remake since it's just iterations off a base.

**Comment by madjin** [comment]
Can we see versions without the electric wire / socket?

**Comment by GaladWarder** [comment]
Totally - I'll render out one  without the wire and one replacing it instead with Ecco balls on the tree

**Comment by GaladWarder** [comment]
With the Ecco balls instead of flowers:

![LogoRender_Ecco_V11 copy](https://user-images.githubusercontent.com/29031531/123228785-50623480-d508-11eb-940f-500f3fcacb4c.jpg)

**Comment by GaladWarder** [comment]
Without the wire:

![LogoRender_NoWires_V10 copy](https://user-images.githubusercontent.com/29031531/123228921-6cfe6c80-d508-11eb-91e7-d29c6520c5c8.jpg)

**Comment by avaer** [comment]
For the square.

1) it's not hand drawn/digital enough now; I think that effect worked, especially the imperfections of coloring in some parts
2) the digital UI aspect is lost
The way I see it, the W is black and white, as if you typed it on a phone screen, and the glowing bars are a phone UI. This is implication I was going for:
![image](https://user-images.githubusercontent.com/6926057/123293918-60ffb400-d4e2-11eb-96ca-4a55b54c16b5.png)
That analogy is kind of lost with new materials.
3) overall too colorful and hard to replicate. There doesn't need to be much color; the low fi drawings were trending in the right direction.
4) the top left cable seems better as a vine to me -- a vine hanging from a phone UI.

**Comment by avaer** [comment]
For the rectangle.

![img](https://user-images.githubusercontent.com/29031531/122641563-bd588180-d138-11eb-8c95-87e85aba9ac6.jpg)

This is the best version and already nearly usable, but wanted to try those other things, like making the street _not_ bleed into the letters but more the letters containing some other material inside (red digital lava?), or maybe some branch structures like this:

![image](https://user-images.githubusercontent.com/6926057/123295448-b8525400-d4e3-11eb-9ef6-257722d6872b.png)

**Comment by avaer** [comment]
Actually, for the rectangle we might want two or three lines of text. (see how Danganronpa did it: https://github.com/webaverse/app/issues/1283#issuecomment-855190102)

I think that still works with the street and same logotype.

I don't have exact words yet but imagine "Webaverse: The Ultimate Adventure".

**Comment by GaladWarder** [comment]
Alright, I'll take another few passes at these!

**Comment by GaladWarder** [comment]
Went back through these, tried to bring in feedback from all the previous ones as well. I think there is some solid stuff in this group, let me know what you think!

First up, the square:
- Messed with intentional imperfection
- Pulled the color down, played off of a phone UI
- Made the cables vines
- Made some versions in various levels of hand-drawn-ness
![LogoRevisions_Square_V13 copy](https://user-images.githubusercontent.com/29031531/123617802-355e3000-d83a-11eb-83c7-ba0945b2f62e.jpg)

And the rectangular:
- Simplified all textures quite a bit
- Messed with flat colors and gradients
- Played with some lowkey swirl textures
- Took out the street bleed and subbed in a lava texture, in various amounts of 'digital'
- Brought in some vines/beanches
- Tried a longer-form version with more text
![LogoRevisions_Rectangular_V13 copy](https://user-images.githubusercontent.com/29031531/123618084-722a2700-d83a-11eb-9b06-5cde3f5d4fb4.jpg)

**Comment by avaer** [comment]
![img](https://cdn.discordapp.com/attachments/842248635948597279/859316972067749908/unknown.png)

**Comment by GaladWarder** [comment]
Github doesn't support SVG upload, so I stuck them in this folder:

https://drive.google.com/drive/folders/1Op_xN-zQF6TvHnF0jr7sFJXsY9IH9t4L?usp=sharing

There are two versions of each; one is slanted and the other is square-on. Sorry this took so long, it was a bit of a struggle to get nice clean paths to work with for future animations/etc.

Fonts used are Electroharmonix: https://www.dafont.com/electroharmonix.font
and Consolas: https://docs.microsoft.com/en-us/typography/font-list/consolas

**Comment by avaer** [comment]
I think you got the style, can we flatten this to reduce the complexity?

I don't think the text should overlap anything (we can move it). The outline is thin and traces the objects, which makes it hard and tedious to draw. I see it more like a license plate with a geometric silhouette.

The flower is a good recreation but there are two issues I see. The first is that it is too good of a copy and I don't think we should steal it. There are many variations we could try for color, changing slew, and maybe adding sharper petals. Second, it should feel attached to the bottom, like an actual flower tied or growing there. What we have now is more of a sticker that was glued on, rather than an organic flat part of the logo.

**Comment by avaer** [comment]
The skewed rectangle is fine.

The W feels crunched and fat compared its typical appearance in CJK script. I don't know if it would look weird to an actual Eastern native. Is there is a way to thinnen the text stroke in genera?

**Comment by avaer** [comment]
Were these intended to be vectors or rasters?

![image](https://user-images.githubusercontent.com/6926057/124345482-1d264200-dba7-11eb-9db4-6627ffe196d0.png)

**Comment by GaladWarder** [comment]
I can make those adjustments easily enough - the flower will take some fiddling to get it integrated, but shouldn't be a huge problem - same with the W font, I can just thin it down.

The brambles should be a vector - they are made with a vector path. If Illustrator isn't treating them as such, it could have something to do with the export? I used a smart object to make it export cleanly

**Comment by GaladWarder** [comment]
I know I was having issues with the stroke on them so I used a workaround for it, that could be causing some sort of compatability thing

**Comment by avaer** [comment]
![lolgo-01](https://user-images.githubusercontent.com/6926057/124373731-eb72b100-dc62-11eb-8227-74f77c3cb09b.png)

**Comment by avaer** [comment]
![lolgo-01](https://user-images.githubusercontent.com/6926057/124373767-3260a680-dc63-11eb-80c3-e008be43408e.png)

**Comment by avaer** [comment]
![lolgo-01](https://user-images.githubusercontent.com/6926057/124373976-45747600-dc65-11eb-9a73-976b1591ed88.png)

**Comment by avaer** [comment]
I figured out how to vectorize in Illustrator; everything there is vector.

**Comment by avaer** [comment]
![logo3-02](https://user-images.githubusercontent.com/6926057/124374405-f597ae00-dc68-11eb-9863-fa10401c4cd1.png)

**Comment by avaer** [comment]
I was trying to vectorize the mega sword for the top, but we couldn't find the blend files which have the blades morph, the substance painter source, or a clean way to retexture the carbon fiber on the sides.

So I went with a vectorization of some test art. The bottom is also a vectorization of raster Sakura found on pinterest.

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/124409298-0e11d200-dd16-11eb-9497-101ce91c39f7.png)

**Comment by GaladWarder** [comment]
Which of these do you need finals of? 

I can make them today, just not sure which versions you want. Right now, I have the initial one, but flatter, with a more integrated flower on my list, I can also track down the megasword blend files and probably Image Trace it into vector

**Comment by avaer** [comment]
I have all of these as SVG already so they do not need to be made.

The main thing I think we should change is to get an outline of the megasword instead of this -- but I could not find the files for teh sword so I could raster -> svg it and gave up.

**Comment by avaer** [comment]
Is there an AI of this one? https://github.com/webaverse/app/issues/1283#issuecomment-869548188

**Comment by GaladWarder** [comment]
No, I did all the designing in raster. There's a Photoshop file, though:

https://drive.google.com/file/d/1O6K6L2UXgvmJVEcYCl7Zex7mSxs7Cp7S/view?usp=sharing

**Comment by avaer** [comment]
I meant the bottom one: https://user-images.githubusercontent.com/29031531/123618084-722a2700-d83a-11eb-9b06-5cde3f5d4fb4.jpg

**Comment by avaer** [comment]
I think we now have all the ingredients we needed for logos.
