### ISSUE TITLE
Assets: AI voices for charas

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1284]
We need character voices for the trailer and beyond. The initial plan was fiverr, but I'm getting impressed by some of the quality of these AI renderings -- it is good enough that we can probably paper over it/explain it away with a lampshade.

I also got a lot of mileage out of fine tuning this stuff in FL Studio.

Platforms I reached out to/am testing, open to other options:

https://synthesys.io/
https://resemble.ai/

One of the voices I wanted to use, but it's stuck behind a bug on their end (from Synthesys): https://github.com/webaverse/app/blob/master/assets/DeboraD.mp3

**Comment by avaer** [comment]
It might also be an option to get a voice actor to do a large amount of lines and crunch that through a custom model.

But I don't have time to explore that space at the moment.

**Comment by avaer** [comment]
https://stackoverflow.com/questions/66726331/how-can-i-run-mozilla-tts-coqui-tts-training-with-cuda-on-a-windows-system
https://stackoverflow.com/questions/66307611/how-do-i-get-started-training-a-custom-voice-model-with-mozilla-tts-on-ubuntu-20

**Comment by Vianvolaeus** [comment]
Interesting option on the VA > AI model option. I have a contact who's done the same with their own voice to make their own YouTube content, let me reach out and report back on that. I think that could be a really good and unique option, if it's viable.
Let me know if there's any specifics you'd like me to ask them.

**Comment by Vianvolaeus** [comment]
> resemble.ai 

It appears on of their ML engineers was working on this (now unmaintained) repo for voice cloning: 

https://github.com/CorentinJ/Real-Time-Voice-Cloning
