### ISSUE TITLE
Fe: preview timeout

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1289]
https://webaverse.com/assets/650

```
preview get request {
  hash: 'https://avatar-models.exokit.org/model49',
  ext: 'vrm',
  type: 'png',
  cache: true,
  height: undefined,
  width: undefined,
  key: 'https://avatar-models.exokit.org/model49/vrm/png'
}
preview get from cache https://avatar-models.exokit.org/model49/vrm/png image/png 241788
Error: timed out: {
  "tokenId": 650,
  "ext": "jpg",
  "w": "500",
  "cardWidth": 500,
  "cardHeight": 700
}
    at Timeout._onTimeout (/home/ubuntu/preview-backend/routes/card-preview.js:106:22)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
preview error Error: timed out: {
  "url": "https://ipfs.exokit.org/ipfs/QmcHMtuumCiCsdzZHCHa7vunrgLsUe9BhofzCPrJa97C6m",
  "hash": "QmcHMtuumCiCsdzZHCHa7vunrgLsUe9BhofzCPrJa97C6m",
  "ext": "png",
  "type": "png"
}
    at Timeout._onTimeout (/home/ubuntu/preview-backend/routes/preview.js:198:22)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
```

https://webaverse.com/assets/658
Another user tried minting a .vrm file but it doesn't seem to be loading.
Created it from a vox file following the steps mentioned in a tutorial

**Comment by avaer** [comment]
Can you please print a trace using the screenshot page loaded in the browser, without going through the preview server?

This should be in the docs.

Go to `https://app.wevaverse.com/screenshot.html?` and fill in the required query string parameters. https://github.com/webaverse/app/blob/2e94ea58751369ec8e43479d7459a2b74716b404/screenshot.js#L221

Or you can find the pointer in the preview server code.

An engineer should be able to debug this in 10 minutes.

**Comment by madjin** [comment]
https://app.webaverse.com/screenshot.html?url=https://ipfs.exokit.org/ipfs/QmcHMtuumCiCsdzZHCHa7vunrgLsUe9BhofzCPrJa97C6m&hash=QmcHMtuumCiCsdzZHCHa7vunrgLsUe9BhofzCPrJa97C6m&ext=png&type=png&width=undefined&height=undefined&dst=http://127.0.0.1:8999/6920

All I see in console is `Uncaught SyntaxError: Unexpected string` which is line 8 of screenshot js `import GIF './gif.js';`

**Comment by avaer** [comment]
Might be fixed with
https://github.com/webaverse/app/commit/7c847221b96ea6aac5d1a303a4e15a88bec282b6

**Comment by madjin** [comment]
Looks like it is, thank you!
![2021-06-20-13:31:26](https://user-images.githubusercontent.com/32600939/122683249-d4d45080-d1b2-11eb-97de-5dcba80c2d90.jpg)
![2021-06-20-13:31:54](https://user-images.githubusercontent.com/32600939/122683251-d7cf4100-d1b2-11eb-9f4b-da7acaf7b7be.jpg)

**Comment by avaer** [comment]
Gotta say that card looks sick.
