### ISSUE TITLE
[Inventory] Back button on trade

### ISSUE THREAD

**Issue by avaer** [webaverse/app#129]
<img width="1541" alt="capture2" src="https://user-images.githubusercontent.com/6926057/95715730-5513e080-0c38-11eb-83d8-d7fba6bc4580.PNG">

We have confirmations at the bottom but it might be hard to see it in its current form.

**Comment by ChrisEddy** [comment]
https://github.com/webaverse/app/pull/134

**Comment by ChrisEddy** [comment]
pr merged
