### ISSUE TITLE
Fe: navbar footer links

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1290]
## Header

- Hiring: https://www.notion.so/webaverse/Webaverse-is-Hiring-8fb49c069c2f450f93ebb911149f21bd

## Footer

social links: https://github.com/webaverse/app/issues/1219
- Twitter: https://twitter.com/webaverse
- Discord: https://discord.gg/R5wqYhvv53

Other links
- Github: https://github.com/webaverse
- Blog: https://blog.webaverse.com

**Comment by softwarebycl** [comment]
The current footer now has these links:
![footl](https://user-images.githubusercontent.com/29695350/130120333-4ee3c28a-dfe7-4b35-95c5-b3857d18405b.PNG)
