### ISSUE TITLE
decu wood style hoverboard 

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1292]
thread for wood style hoverboard design , 
initial thoughts : BOTW sort of magical floating decayed log with mushrooms that pulsate when it hovers .. 
got a scan of an old log : 
![wood-scan](https://user-images.githubusercontent.com/5592454/120244437-2cc50a80-c238-11eb-8f4e-825f7c4fe32a.jpg)
super duper basic concept drawing in blender : 
![screen](https://user-images.githubusercontent.com/5592454/120244460-3babbd00-c238-11eb-9cc3-11a905729785.jpg)
doing blockout but maybe this is not the right direction , feedback and examples appreciated. 
![wood-blockout](https://user-images.githubusercontent.com/5592454/120244576-8fb6a180-c238-11eb-8940-bd875da8d22a.png)

**Comment by plankatron** [comment]
new direction as per jin's help : 
![wip-board](https://user-images.githubusercontent.com/5592454/120341756-2630a480-c2c5-11eb-9a24-724ade6ad0f7.png)

**Comment by plankatron** [comment]
![wip-board](https://user-images.githubusercontent.com/5592454/120352498-d2c35400-c2ce-11eb-87eb-9c078c2db92d.jpg)

**Comment by plankatron** [comment]
![wip-board2](https://user-images.githubusercontent.com/5592454/120365274-3bfd9400-c2dc-11eb-8fd4-eabc648e38c2.jpg)

**Comment by plankatron** [comment]
![wip-board3](https://user-images.githubusercontent.com/5592454/120365696-c6de8e80-c2dc-11eb-8521-a0712c75e85a.jpg)

**Comment by plankatron** [comment]
annddd here is the glb file 
http://7rnx.net/fleeky-pub/webaverse/hoverboards/decu-wood-hoverboard.glb

**Comment by madjin** [comment]
some kinda stencil / decal / design on top would be good

**Comment by plankatron** [comment]
@madjin any specific logo types? here is a test
![W](https://user-images.githubusercontent.com/5592454/122270240-1bbd0000-ceac-11eb-8a7b-10a66ff61c4b.jpg)

**Comment by plankatron** [comment]
moar test
![nor1](https://user-images.githubusercontent.com/5592454/122275935-41e59e80-ceb2-11eb-80b9-75129141ec15.jpg)

**Comment by plankatron** [comment]
![nor1](https://user-images.githubusercontent.com/5592454/122290409-b2e08280-cec1-11eb-9ce1-9b87b0540a99.jpg)
![nor2](https://user-images.githubusercontent.com/5592454/122290413-b2e08280-cec1-11eb-8952-2f5658b99408.png)

**Comment by madjin** [comment]
8.6k tri with 3 textures about 1.55MB, not bad. Optimizing these down a bit more but overall the glbs are great so going to close this issue.

**Comment by madjin** [comment]
Reopening because we haven't really settled on which one we're going with
