### ISSUE TITLE
App/assets: physics bones for non-avatar assets

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1293]
Discussing physics possibilities for asset flair in the Discord came across the following conundrum - what would be the best solution for an asset that is _not_ VRM that requires or makes use of physically-reactive (gravity, flexible material) assets? 

Right now avatars can have these making use of the VRM springbone components. As things currently stand, I'm not sure how / if we are capable of giving rigged meshes physics capability in a similar sense.

I think there is some kind of functionality in XRPackages, but we don't have this documented. I could be mistaken - I don't know my way around that format particularly well.

**Comment by avaer** [comment]
This is a cool idea.

I don't think there is much that is special about VRM bone flair; it could be applied based on naming or a custom blender component with the plugin.

But it would require engine support, especially in the editor.
