### ISSUE TITLE
hover-key-board

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1295]
initial blockout 
![keyboard-cat](https://user-images.githubusercontent.com/5592454/120372596-643dc080-c2e5-11eb-80d6-2c39c668cb2d.jpg)

uses a keyboard model from : https://www.blendswap.com/blend/17151  with cc-by so attribution needs to pass on but use should be acceptable

**Comment by madjin** [comment]
Looks good, going to close this issue
