### ISSUE TITLE
Sleek Silver Hoverboard 

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1296]
Thread for Sleek Silver Hoverboard 
![silver-speed-board1](https://user-images.githubusercontent.com/5592454/120535908-88ff6a00-c3b1-11eb-8bb4-59689772c5d0.jpg)
![silver-speed-board](https://user-images.githubusercontent.com/5592454/120535910-89980080-c3b1-11eb-8229-35d072877e84.jpg)

**Comment by madjin** [comment]
Great work, will test this out in-game
