### ISSUE TITLE
Docs: Trading card illustration

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1298]
Suggested fixes for the image to explain the trading card metaphor

![image](https://user-images.githubusercontent.com/32600939/120687988-94659a80-c470-11eb-91b4-bf017b83f0de.png)

Question: should royalties % be on there as well? It's not part of the formula right now.

**Comment by madjin** [comment]
note to self: when its ready will need to replace current placeholder image in the items section of docs

**Comment by avaer** [comment]
Imo the folders don't make sense in this concept.

The real folder here is the hovercraft data (which is not drawn), and the rest isn't folders (but implied to be).

I also think it makes sense for a person/avatar to be in this diagram. This isn't an automated minting process, but a personal one.

Pperhaps the folder contains the hovercraft and that is rammed into a machine along with the other ingredients and the card comes out the other end.

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/122313268-e7653600-cee3-11eb-93eb-f71b60824932.png)

- add folder around hovercraft
- remove folders around other text
- add a posed avatar model on the left side, perhaps standing next to the bot

![look](https://user-images.githubusercontent.com/32600939/122313352-0f549980-cee4-11eb-9465-82f7a89d5ea6.png)

**Comment by GaladWarder** [comment]
Here's the updated version with the requested changes!
![Card Image_V4](https://user-images.githubusercontent.com/29031531/122331024-c0037d00-cf66-11eb-92df-037fc3df5a5e.jpg)

**Comment by GaladWarder** [comment]
![Card Image_V5](https://user-images.githubusercontent.com/29031531/122333708-1f638c00-cf6b-11eb-9187-b27d2017bfc4.jpg)
![Card Image_V5_Checkmark](https://user-images.githubusercontent.com/29031531/122333716-212d4f80-cf6b-11eb-89fc-a0d3d9d944b1.jpg)

**Comment by GaladWarder** [comment]
![Card Image_V5_Checkmark](https://user-images.githubusercontent.com/29031531/122334053-af093a80-cf6b-11eb-9812-ed75b6a6fdf0.jpg)

**Comment by madjin** [comment]
much better, thanks! closing now..
