### ISSUE TITLE
Fe: Minting is down

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1303]
The templates do not load and uploading a file to mint will not get to the prview stage.
![brave_D4hWsXDIG0](https://user-images.githubusercontent.com/32600939/121278835-6d103280-c8a1-11eb-810f-ca90082e164f.png)

**Comment by avaer** [comment]
IPFS server volumes were not resized properly.

I did the correct resize, so this might be fixed now.

**Comment by madjin** [comment]
confirmed that minting fixed on fe and discord bot
