### ISSUE TITLE
Art: Wearable Accessories Concepts

### ISSUE THREAD

**Issue by GaladWarder** [webaverse/app#1305]
Going to make a single thread for these so everything's easily accessible in one place and to track progress

**Comment by GaladWarder** [comment]
Dumping a bunch of the experiments I've done to find the idea I have in mind

**Comment by GaladWarder** [comment]
![GaladWarder_2021-06-11_20-58-27](https://user-images.githubusercontent.com/29031531/121771525-684dc600-cba2-11eb-913e-88e8dd525c0f.png)

**Comment by GaladWarder** [comment]
![GaladWarder_2021-06-10_17-57-54](https://user-images.githubusercontent.com/29031531/121771537-74d21e80-cba2-11eb-834b-0a9a6eb56efd.png)

**Comment by GaladWarder** [comment]
![Uploading Headeset Initial Sketches copy.jpg…]()

**Comment by GaladWarder** [comment]
![Headeset Initial Sketches copy](https://user-images.githubusercontent.com/29031531/121771565-a6e38080-cba2-11eb-86c1-f7148dfd9fc1.jpg)

**Comment by GaladWarder** [comment]
Haven't really found a design that's right, but I think I've got the shapes/shape language in the right area. Gonna come back fresh after the weekend and choose a design to refine into a model sheet - feedback of course is welcome

**Comment by madjin** [comment]
Cool concept, though I think citrine might not be the right model to test with. She meshes well with the goggles on her head already. Would like to see many different types of hats and eyewear with other types of models. Perhaps we could scrape together images first.

**Comment by GaladWarder** [comment]
No worries,  I hadn't designed these specifically for Citrine, she was just the model I happened to grab to overpaint.

I'll scrape together images today and shoot to have a few pages of different ideas on head blanks by end of day - that way they could be used on any model, and we can go over them in the meeting.

**Comment by GaladWarder** [comment]
Speaking of scraping references together, I've started a refboard for the wearables. Not all of these pertain specifically to the headgear, but there's some good shape language in here. 

It does all fall into a similar theme - the sort of cyber-futurism theme. Are we considering branching into medieval/fantasy as well?

https://www.pinterest.co.uk/galaddota/webaverse_accessories/

**Comment by GaladWarder** [comment]
I also just cranked out a page of hat/eyewear designs - any of these could be turned into a model sheet pretty quickly, doing it this way will allow me to make a bigger volume in a day, then we can just cherrypick the good ones to flesh out the concepts/designs more for modelling.
![WEBAVERSE_Wearables_Thumbnails_V2](https://user-images.githubusercontent.com/29031531/121873904-6ff3a300-cd39-11eb-9550-8554b92cc917.jpg)

**Comment by Vianvolaeus** [comment]
Nice stuff! I was looking into some tangential styles to the cyberpunk / future themes in some existing IPs and some artists that explore the different spaces. 
I think a hard cyber style can be a bit imposing, as much as I love it, so I tried to eliminate some of that bias by looking into different interpretations of future / alternative universes that have some of those themes contained, at least from an artistic direction:

Those headsets look great 😄
![Referencing](https://user-images.githubusercontent.com/80061436/121921077-9234f300-cd30-11eb-8713-1fe7dad73649.jpg)

**Comment by GaladWarder** [comment]
Thanks Vian - these refs/IPs will be super useful for the next round! Much appreciated!

**Comment by GaladWarder** [comment]
Also Pascal Blanche is a beast - one of my favorite artists haha

**Comment by avaer** [comment]
Until the characters and branding package is done I think this is working ahead without appropriate foundations in place. We can re-open later.
