### ISSUE TITLE
Fe: Click to copy address

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1314]
small feature request to be able to click to copy the address on profile pages

![image](https://user-images.githubusercontent.com/32600939/122336301-9caae480-cf0a-11eb-900a-d22b310250d1.png)

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/128266873-7a910213-9099-4030-a872-b6d4f606f0a1.png)

similar idea to opensea profile page

**Comment by softwarebycl** [comment]
Closing outdated issue. The new website has the copy address feature.

![profl](https://user-images.githubusercontent.com/29695350/130282819-529039f1-766c-4176-8222-8d6b5ade0b6e.PNG)
