### ISSUE TITLE
Fe: previews not loading

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1315]
Currently investigating the issue, logs seem to show that the previews are timing out. 2D previews work fine, card previews don't load and same with most webm previews.

referencing some older issues that are somewhat related while debugging:

- https://github.com/webaverse/app/issues/1243
- https://github.com/webaverse/app/issues/925

**Comment by madjin** [comment]
https://preview.exokit.org/Qme8jDJXom2wXmb9j1m2xKjoKz7Xh4xGYcYhkomUJxrwyb.vrm/preview.webm
```
Error: timed out: {
  "url": "https://ipfs.exokit.org/ipfs/Qme8jDJXom2wXmb9j1m2xKjoKz7Xh4xGYcYhkomUJxrwyb",
  "hash": "Qme8jDJXom2wXmb9j1m2xKjoKz7Xh4xGYcYhkomUJxrwyb",
  "ext": "vrm",
  "type": "webm"
}
    at Timeout._onTimeout (/home/ubuntu/preview-backend/routes/preview.js:198:22)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
```

**Comment by madjin** [comment]
Many webm previews eventually came back, issue is mainly cards related
![image](https://user-images.githubusercontent.com/32600939/122503225-105df780-cfc6-11eb-8776-f4c17946856c.png)

**Comment by madjin** [comment]
tried restarting the services, haven't tried restarting the boxes

**Comment by madjin** [comment]
test url https://card-preview.exokit.org/?w=500&t=14&ext=jpg

**Comment by avaer** [comment]
Restarting the boxes should never be needed

**Comment by avaer** [comment]
Is the ipfs server down?

**Comment by madjin** [comment]
they seem to be loading again: https://webaverse.com/
