### ISSUE TITLE
Art: New Scythe / Rifle

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1318]

**Comment by madjin** [comment]
## Scythe

![image](https://user-images.githubusercontent.com/32600939/123299531-9f4ba200-d4e7-11eb-8bc6-72fc09c2eb00.png)
https://www.pinterest.com/pin/452119250097901239/

![image](https://user-images.githubusercontent.com/32600939/123299765-dcb02f80-d4e7-11eb-86ac-1356f5cffb5c.png)
https://www.deviantart.com/epic-soldier/art/Halloween-special-2-CLOSED-641584132

![image](https://user-images.githubusercontent.com/32600939/123299961-0a957400-d4e8-11eb-802c-5e1091f0bd04.png)
https://www.pinterest.com/pin/621004236095971009/

![image](https://user-images.githubusercontent.com/32600939/123300122-3ca6d600-d4e8-11eb-88ef-2c27db7f2e02.png)
https://www.pinterest.com/pin/498492252502189129/

**Comment by plankatron** [comment]
![scythe1](https://user-images.githubusercontent.com/5592454/123706676-8ff58d00-d836-11eb-9147-5197802f40db.png)
![scythe](https://user-images.githubusercontent.com/5592454/123706680-908e2380-d836-11eb-90e8-7d6a14022ba9.jpg)
two versions

**Comment by madjin** [comment]
That looks good for an easy to remix template

## More scythes:

![image](https://user-images.githubusercontent.com/32600939/123707234-3da87200-d81e-11eb-8b8b-9b3fecc42e24.png)

![image](https://user-images.githubusercontent.com/32600939/123707239-413bf900-d81e-11eb-90cb-e63f89423fa5.png)

![image](https://user-images.githubusercontent.com/32600939/123707262-47ca7080-d81e-11eb-9a20-ef1e28d20f12.png)
https://www.artstation.com/artwork/4DEYY

- https://www.pinterest.com/pin/759982505845214794/
- https://www.pinterest.com/pin/786511522405567266/

What about Axe instead of Scythe?

![image](https://user-images.githubusercontent.com/32600939/123707529-b3144280-d81e-11eb-9bae-27de2d49cc56.png)



## Rifle with decals on it

![image](https://user-images.githubusercontent.com/32600939/123706629-5d8b6600-d81d-11eb-9838-059d6d145ed5.png)

![image](https://user-images.githubusercontent.com/32600939/123706243-e0f88780-d81c-11eb-89cc-3808e4add7d6.png)

https://www.pinterest.com/pin/669417932105472210/

**Comment by plankatron** [comment]
![glock](https://user-images.githubusercontent.com/5592454/123710875-79066900-d83d-11eb-88d4-904338f83a8a.jpg)

**Comment by madjin** [comment]
Perhaps we can optimize these assets for use

CC0 Rifles: https://sketchfab.com/search?features=downloadable&licenses=7c23a1ba438d4306920229c12afcb5f9&q=rifle&sort_by=-relevance&type=models
![brave_xc2NcUexfV](https://user-images.githubusercontent.com/32600939/123711041-c84c9980-d83d-11eb-9927-c93297242849.png)

CC0 Pistols: https://sketchfab.com/search?features=downloadable&licenses=7c23a1ba438d4306920229c12afcb5f9&q=pistol&sort_by=-relevance&type=models
![brave_2b31MNoJ4b](https://user-images.githubusercontent.com/32600939/123711077-d8647900-d83d-11eb-9be3-89294318dd6f.png)

**Comment by plankatron** [comment]
![glock](https://user-images.githubusercontent.com/5592454/123711326-4f9a0d00-d83e-11eb-962b-3b12d9201791.png)

**Comment by plankatron** [comment]
![scythe1](https://user-images.githubusercontent.com/5592454/123712409-4316b400-d840-11eb-8cc0-98ea280482db.png)

**Comment by madjin** [comment]
scythe is no longer needed

**Comment by avaer** [comment]
Most likely replaced by via's multitool.
