### ISSUE TITLE
Vocaloid producer

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1320]
Issue for finding a vocaloid producer to do a theme song like thing. It's not a requirement but we should jump in the opportunity if we see it.

It would be a one off thing.

**Comment by madjin** [comment]
Found someone on twitter that I added on Discord: https://twitter.com/theexpus

**Comment by madjin** [comment]
Examples:
https://www.youtube.com/watch?v=OEWujj5y9Cc
https://www.youtube.com/watch?v=wlhgKHHqpL0

Duet style may work.

**Comment by madjin** [comment]
Will have demos ready by end of week

**Comment by avaer** [comment]
😮

**Comment by avaer** [comment]
Dropping more seeds that I think have the right structure.

The styles are all different but any of these would work if the result was high quality (good synthesis between the lyrics and the melodic rhythms, but I think I could pull that off from most angles).

https://www.youtube.com/watch?v=caqw375JVTI
https://www.youtube.com/watch?v=zkbKpR-G9nc
https://www.youtube.com/watch?v=1iONucZRbq8

**Comment by madjin** [comment]
Sample: https://cdn.discordapp.com/attachments/856501095522369568/859175951916859392/6_28_jinidea_export.mp3

**Comment by avaer** [comment]
I made this a few weeks back, it was about a day of work: https://cdn.discordapp.com/attachments/498315766509338636/862868702362206238/street.mp3

Lyrics start at `2:40`; made with AI, rephrased and arranged by me in Vocaloid.

It is very muddy, but I think it expresses some of the flavor I wanted to inject.

This track was definitely not designed for lyrics (it is the aggressive `Nhato - Run`: https://www.youtube.com/watch?v=caqw375JVTI).

**Comment by avaer** [comment]
```
Hey, you wanna tear up the street?
[Cut the blocks]
[Get the drops]
The serpent's my curse now
But I've got NFTs

They're lessons we keep
[I got you]
[You got me]
I've got the mark, yeah
I've gotta run
I'm having fun

But I won't stand for defeat
[Stacking SILK]
[And I will]
Beat all the odds
And make my own cards
[Let it rip]

The horizon is neat to me
[It's not the end of the road]
```

**Comment by Vianvolaeus** [comment]
The flavour and feel of it is great. I think the lyrics still work here, but this might be personal bias speaking. I'm very sure this is the kind of direction that'd sell the style we're going for though!
