### ISSUE TITLE
Art: Field

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1327]
Open field with grass

## Inspiration
![image](https://user-images.githubusercontent.com/32600939/123523911-fcd12180-d694-11eb-81d7-c9c474817588.png)
Source: https://www.porterrobinson.com/

![image](https://user-images.githubusercontent.com/32600939/123525350-f4c9af80-d69d-11eb-8b3d-7a0fd7722d8b.png)
Secret Sky

![](https://i.imgur.com/jqobgMJ.jpg)
Source: https://www.vgmaps.com/Atlas/N64/
Top view: https://www.vgmaps.com/Atlas/N64/LegendOfZelda-OcarinaOfTime-Present-HyruleField(Top).jpg

Other links:

* https://github.com/spacejack/terra
* https://discourse.threejs.org/t/field-of-grass-swaying-in-the-wind/13965

Field of grass could be done with alpha cutout texture instanced planes in three.js + vertex shader for wind: https://www.youtube.com/watch?v=nhefxigg5Xo

Amazing grass by [Jesper the End](https://twitter.com/Jespertheend/status/1347244757093912576) https://www.youtube.com/watch?v=sBtHIOVa52g

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/125172225-7af9f180-e186-11eb-8c85-a86e7827e9fe.png)
![image](https://user-images.githubusercontent.com/32600939/125172282-d0ce9980-e186-11eb-98f7-2d99cf3a5e54.png)

**Comment by madjin** [comment]
Github: https://github.com/spacejack/terra
Demo: https://spacejack.github.io/terra/
![Screenshot at 2021-07-10 14-00-44](https://user-images.githubusercontent.com/32600939/125172346-433f7980-e187-11eb-8bc1-fd50d7baf29f.png)

**Comment by avaer** [comment]
Thanks, that repo might be a good place to start.

**Comment by GaladWarder** [comment]
Does this need a design pass in 2D? 

If it's literally just an open field with grass, there's not much to concept other than grass type or maybe colors; both of which are easy enough in 3D.

Let me know if you want like a key art illustration or something and I'll crank one out, (it's be pretty quick to do), but I'm not sure what would be needed on the concept side for this.

**Comment by avaer** [comment]
I don't think it's needed, it's pretty obvious. What we will need is a top down map of things but it's not related to the field.

**Comment by madjin** [comment]
Notes from our world hopping exploration

Lots of examples of grass is achieved with a vertex shader on instanced transparent pngs
![VRChat_1VP1o6jeMg](https://user-images.githubusercontent.com/32600939/126073438-dc71231a-805d-4da6-805e-c75fa5473358.jpg)


https://user-images.githubusercontent.com/32600939/126073516-4fdfbbe0-378b-4da8-96e8-a284eae1d96b.mp4



Occasionally, it can also be billboarded. Effect looks great even with less instances. This works best when the ground texture is very close to the grass / plant texture.


https://user-images.githubusercontent.com/32600939/126073530-7b12ebab-679d-499e-a5f5-45d3f8568ab4.mp4


### Flowers and grass

Easy to make own, but here's some references just in case

- https://www.textures.com/category/nature/237
- https://opengameart.org/content/60-cc0-vegetation-textures
- https://opengameart.org/content/cc0-3d-plants
- https://www.cgbookcase.com/textures?search=&resolution=1&category=Plants&color=any&page=1


https://user-images.githubusercontent.com/32600939/126073540-ee452e69-baaf-475a-bf1b-20da4afbce52.mp4
