### ISSUE TITLE
Art: Serial avatar experiments

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1328]
We have tons of avatar assets and base models from which to rapidly experiment different characters. This thread is to document the variations and ideas we come up with and build, including possible story lines for each charater.

Here's some I made in the past:

![image](https://user-images.githubusercontent.com/32600939/123624466-6c452f00-d7c3-11eb-9642-ac0d5f69b530.png)
![image](https://user-images.githubusercontent.com/32600939/123624476-6f401f80-d7c3-11eb-9e7e-913880b0862f.png)

These characters represent a cult within the metaverse called "The EYE". They are all CC0 licensed.
- https://cryptoavatars.io/item/50
- https://cryptoavatars.io/item/51
- https://cryptoavatars.io/item/70
- https://cryptoavatars.io/item/14

![image](https://user-images.githubusercontent.com/32600939/123624815-e7a6e080-d7c3-11eb-9487-38e09057a0e3.png)

The EYE represents the 'all seeing eye' of mass surveillance and virtual reality (like Oculus). It began with a mysterious shrine in cryptovoxels and started to spread into other universes.

Later I'll post an overview of the assets we currently have in terms of clothing and wearables for VRoid. I've seen VRoids look really high quality, especially with modified skin textures. CC0 is encouraged when sourcing from other places.

**Comment by madjin** [comment]
New VRoid sample models just dropped (CC0)

![image](https://user-images.githubusercontent.com/32600939/123796800-5ce4e500-d89a-11eb-9f45-2477e2f57dc7.png)
https://hub.vroid.com/en/characters/2843975675147313744/models/5644550979324015604

![image](https://user-images.githubusercontent.com/32600939/123796819-640bf300-d89a-11eb-99f5-78941ced397d.png)
https://hub.vroid.com/en/characters/7939147878897061040/models/2292219474373673889

![image](https://user-images.githubusercontent.com/32600939/123796846-6a9a6a80-d89a-11eb-9438-cf20d2c51a03.png)
https://hub.vroid.com/en/characters/1248981995540129234/models/8640547963669442173

**Comment by avaer** [comment]
This is done. We already have the profiles, hundreds of pages of content, and designs chosen (2/4 models have been started).

**Comment by avaer** [comment]
In general I don’t think we should be playing with the CC0 models, since one of the goals is to be separate from any other recognizable release.

But they could be used as a basis to morph from.

**Comment by madjin** [comment]
Good catch, I thought since previous samples were CC0 these would be too.

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/124396748-7a221500-dcd9-11eb-83b3-31b002f02a2f.png)

WillieRo in the Discord made a whole cast of awesome characters.

> "It’s an Afro-Cyberpunk concept. Not drab, rainy, and dystopic. Colorful not bubbly, hopeful but dangerous in some areas. Ancient but. Open air structures that are built with natural materials and that also don’t take gravity into a count."
