### ISSUE TITLE
Face decals/bite mark

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1331]
![image](https://user-images.githubusercontent.com/6926057/124339990-ff91b200-db7f-11eb-8942-d9a76564aa09.png)

Forgive the lack of artistry.

This issue is to track an SVG for "bite marks" to stamp characters with.

The best idea I heard for this is make it a W like the logo, or at least nod towards it.

Different variations could also exist.

**Comment by avaer** [comment]
This could also use a Pinterest pass to find ideas.

**Comment by Vianvolaeus** [comment]
I think the circled one makes a lot of sense. It's more of a glancing scar than an imprint / stamp, which makes much more sense as a bite / scar from the lisk monster.

It is easy to recall as the 山 shape and also easy to draw, while still departing from the original.

I can visualize it as the teeth / bite of the basilisk, and it looks like fangs.

It works well in 3D also. 
![image](https://user-images.githubusercontent.com/80061436/124641570-c65e8800-de86-11eb-8dfc-3895ac918e07.png)

**Comment by GaladWarder** [comment]
Made a few options based on the sketches and converted them to SVG. They are black right now to show the silhouette, but can easily be changed to any color/fill/gradient/etc.

https://drive.google.com/drive/folders/1bEgrXozE_8oi2X4WCZg1TRQiTD0Pu0LI?usp=sharing

**Comment by avaer** [comment]
Gj, my favorite is the jagged:

![4D9213CD-84FC-44D2-9E52-085C989C4A22](https://user-images.githubusercontent.com/6926057/125262265-092dbf00-e2d0-11eb-9e97-fdea9f3673b4.jpeg)

Would be good to also try a connected version. The nice thing about this W is it can also easily be a U.

**Comment by GaladWarder** [comment]
Made a thinner version, updated the AI file. There are now the two jagged versions there on the artboard, and the other paths available above, in case they are needed. Should be all ingredients needed for anyone to use:

**Direct Link to AI file:** https://drive.google.com/file/d/1czHt-X35eWNfWE6gN5AB_lcY7yjiwR_e/view?usp=sharing
** Link to Folder with All Iterations**: https://drive.google.com/drive/folders/1bEgrXozE_8oi2X4WCZg1TRQiTD0Pu0LI?usp=sharing

**Screenshot for ease of use:**
![image](https://user-images.githubusercontent.com/29031531/125392997-bd673c80-e3d9-11eb-8eb1-43fe320b1cfb.png)

**Comment by avaer** [comment]
Thanks, I think we're good on this now. What I actually meant was this but it was easy enough:

![image](https://user-images.githubusercontent.com/6926057/125406677-15c11e80-e387-11eb-9a98-96a2f2f1499a.png)

**Comment by avaer** [comment]
https://github.com/webaverse/app/blob/master/assets/bitemarks.psd

**Comment by avaer** [comment]
https://github.com/webaverse/app/issues/1331
