### ISSUE TITLE
Design media border

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1332]
![image](https://cdn.discordapp.com/attachments/498315766509338636/860709195091542055/z_CONCEPT_TEMPLATE_WEBAVERSE.jpg)

For wrapping around screenshots. It doesn't need to have any text or logos, but it should be distinguishable.

**Comment by madjin** [comment]
Note: needs to be transparent PNG

**Comment by avaer** [comment]
Ideally transparent SVG, not PNG.

**Comment by GaladWarder** [comment]
Done; there is a square and a rectangular version in this folder, as well as the AI file.

Kept it a bit simpler than the concept sheet template, but it matches the same theme. Should work for essentially any screenshot.

https://drive.google.com/drive/folders/1_vO-tTxeqByNxOU5Teyqu3jabnrukRM_?usp=sharing

**Comment by madjin** [comment]
Think this design might be a bit *too* simple. I really like what's originally posted at the top of this thread, its a jpg tough. Another idea is trying out a border, for example:

![image](https://user-images.githubusercontent.com/32600939/125021567-ef2e7b00-e048-11eb-8254-efd5575acf4b.png)

Perhaps it can use the same arrow texure as the lanes on the street
![image](https://user-images.githubusercontent.com/32600939/125021593-fbb2d380-e048-11eb-8b95-8a1b62bbf715.png)

**Comment by avaer** [comment]
Arrows texture `.ai` here: https://github.com/webaverse/app/blob/master/assets/street.ai

**Comment by madjin** [comment]
Perhaps some inspiration can come from the logo https://github.com/webaverse/app/issues/1283

**Comment by avaer** [comment]
Definitely should reflect the logo. There are several textures and themes to use:

rainbow line gradient
fake generated kanji texture 
chevron booster

**Comment by GaladWarder** [comment]
Sweet, I'll take another swing at this today then! I'll just make a few versions.

I would caution against any super bright colors or busy textures though; they will look good when it is just the border but as soon as an image is added behind the, they will take interest away from the more important content.

I'll also make one that's just a copy of the initial image Jin posted - I made that template, so I have all the assets needed to make it SVG easily.

I'll see what I can do to pull in the logo elements on a few of them too!

**Comment by GaladWarder** [comment]
Made a few more versions, they are all SVG's. I think the rainbow one toward the top is most likely to be what you're looking for.
Any of these can be easily changed for color/gradients/etc.

Also, here's a screenshot so you don't have to download the AI file to look at them.

![image](https://user-images.githubusercontent.com/29031531/125265733-b7208400-e337-11eb-8027-0ceb1e1fe455.png)

https://drive.google.com/drive/folders/1_vO-tTxeqByNxOU5Teyqu3jabnrukRM_?usp=sharing

**Comment by avaer** [comment]
There are some interesting ideas here, but I don't think it needs to be this complicated, it just needs to be more symbolic.

For example there are multiple Webaverse rhombuses here, along a path -- is that supposed to imply there being many versions of Webaverse, in clusters? Are these UI elements? UI of what software? There are things that look like scrollbars but not quite. It could be circuitry but it's not any kind of circuitry we have anywhere else.

We could incorporate the arrows, and also this texture, since the plan is to use it for avatars in the background:

![img](https://user-images.githubusercontent.com/6926057/125181125-ae14a300-e1cf-11eb-9300-2858bdad0332.png)

**Comment by avaer** [comment]
IMO the border from Jin's presentation, including the inversions, was the best so far.

**Comment by madjin** [comment]
1.
![image](https://user-images.githubusercontent.com/32600939/125486592-0cbae04e-a0f0-4c9a-9ba7-0b0cd1e48c39.png)
2.
![image](https://user-images.githubusercontent.com/32600939/125486478-794b4581-e19c-4a25-8bc0-affebf6184dc.png)

**Comment by avaer** [comment]
This looks pretty good for something like presentations, but perhaps screenshots should have something smaller, like a logo watermark.

Figuring out those policies would be a separate issue though, so I think we can close this.
