### ISSUE TITLE
Art: Megasword

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1335]
The 'megasword' was previously elected as the MC's sword, but following developments in lore / character direction changes now need to be made.

Below is the previous design for reference: 
![image](https://user-images.githubusercontent.com/80061436/124493328-66e07980-ddad-11eb-937d-4e4f0e8313be.png)

Proposed changes:
Remove cable / tassel
Sphere material change to match style, feels out of place
Add trigger system for blade activation

Potential changes:

* Removal of carbon fibre material, makes SVG/drawing problematic
* Sphere shape could be made more uniform for SVG/drawing

**Comment by avaer** [comment]
I would keep the trigger separate from the blade — if by system you mean some scheme of tying them.

**Comment by Vianvolaeus** [comment]
Can work either way, depends what's needed in terms of design / technical. Currently it is a separate object with it's own activation shapekey, separate from the blade activation shapekey.

**Comment by avaer** [comment]
Thanks, the two are best separate for coding it. 👍

**Comment by avaer** [comment]
I also noticed that the sword does not have a blade morph -- only an animation.

It seems there needs to be three dynamic elements here: trigger, blade, folding animation.

**Comment by Vianvolaeus** [comment]
I don't think that's correct in the case of the Megasword_Anims blend file in the drive, which already has those three elements separate:

https://user-images.githubusercontent.com/80061436/124643062-800a2880-de88-11eb-980a-45436ebfe2be.mp4

I'll update the file with the drivers removed and the shapekeys' names updated, as per req. on #1341.

**Comment by avaer** [comment]
Thanks for the video, I was able to locate all of the morphs. 👍

**Comment by avaer** [comment]
The main thing which IMO doesn't fit in the sword is the "core".

This wasn't clear until recently (no design phase), but the main idea behind these assets is they are intentionally made by _someone_ (both in world and out) to tell a story or express something. Therefore having a unique new material for such an important object requires explaining the material and ensuring it makes sense in the rest of the world -- and I can't figure out anything for that without adding a new dimension to the "lore"/"design" that explains weird materials or meteorites.

So what if we changed that core to something like an alien heart, or something organic that _could_ have been ripped out of a creature and requires less new explanation?

**Comment by avaer** [comment]
Some random ideas:

![10 Cloverfield Lane - Studies, Kurt Papstein](https://user-images.githubusercontent.com/6926057/124654688-db2e2200-de6c-11eb-8390-29b2b076140d.png)
![Beroe abyssicola throwing up Bolinopsis](https://user-images.githubusercontent.com/6926057/124654546-afab3780-de6c-11eb-9814-ab099983c8ad.png)
![American Museum of Natural History](https://user-images.githubusercontent.com/6926057/124654257-57743580-de6c-11eb-8ab7-5ea19e7800c5.png)
![Claire Lindner_ L’Air est une Racine – Galerie de lAncienne Poste](https://user-images.githubusercontent.com/6926057/124654082-19771180-de6c-11eb-8165-245826cd7521.png)
![Exploring the Darker Sides of Ceramics (Published 2015)](https://user-images.githubusercontent.com/6926057/124654010-ffd5ca00-de6b-11eb-85f8-163b6e5f8e67.png)
![William-Kidd_-Ceramic-‘Organic-Possibilities’](https://user-images.githubusercontent.com/6926057/124653868-d321b280-de6b-11eb-9a12-4a45d8f1418a.png)
![Limacina-helicina-feeding-mucus-ball-small](https://user-images.githubusercontent.com/6926057/124653606-7faf6480-de6b-11eb-9572-da6d923350a3.png)
![About-BuzzFeed](https://user-images.githubusercontent.com/6926057/124653341-2f380700-de6b-11eb-97b2-7e236964b391.png)
![These-Endangered-Wildlife-Photos-Are-Artistic-Masterpieces](https://user-images.githubusercontent.com/6926057/124653210-06177680-de6b-11eb-947b-81d6b4938f09.png)
![Mary’s-Monday-Metazoan_-Salpflower](https://user-images.githubusercontent.com/6926057/124653478-58f12e00-de6b-11eb-9ece-35a358f13678.png)

**Comment by avaer** [comment]
Also the core doesn't need to have any sort of cage, but it could certainly have some cool heart beat type animation.

**Comment by avaer** [comment]
In removing the carbon fiber and potentially collapsing the geometry a bit, here is some more texture/design inspiration:

![Skyforge - Weapons   Items, Anton Lavrushkin (1)](https://user-images.githubusercontent.com/6926057/124655589-0a915e80-de6e-11eb-8e18-147e21b58e04.png)
.

**Comment by avaer** [comment]
Another idea is to trap some kind of organic object in a bubble.

![Tea Weird _ The Griffon's Saddlebag on Patreon](https://user-images.githubusercontent.com/6926057/124659598-24817000-de73-11eb-9ac8-5f47f9e1401c.png)

**Comment by avaer** [comment]
The Ecco orbs could possibly also work here.

![lol](https://user-images.githubusercontent.com/6926057/124659880-71654680-de73-11eb-95b8-41e51bcf70c3.png)

**Comment by Vianvolaeus** [comment]
I think this is going to need a redo with the new design ideas in mind in order to fit the criteria for it, as well as the comment here in #1343  : https://github.com/webaverse/app/issues/1343#issuecomment-875764328

regarding basing the weapons around the basilisk parts. 

I think the having an encapsuled **eye** rather than a **heart** makes sense more on lore, (filter guidance) and will fit the sphere shape better, so I will explore that.

**Comment by Vianvolaeus** [comment]
We could have a sphere with inverted normals, with another inside it *also* with flipped normals to create an interesting effect based on viewing angle. It would remain flat / 'normal' looking when viewed headon, and is still easy to draw / outline / svg in that context.

The video also shows just a regular eye sphere encapsulated in a flipped-normal sphere at the end. 
https://user-images.githubusercontent.com/80061436/124941596-d26f5480-e002-11eb-9186-60c09836d33b.mp4

**Comment by Vianvolaeus** [comment]
Context within an actual sword model. 
https://user-images.githubusercontent.com/80061436/124959533-34d05100-e013-11eb-9149-0419beab3742.mp4

**Comment by avaer** [comment]
> I think the having an encapsuled eye rather than a heart makes sense more on lore, (filter guidance) and will fit the sphere shape better, so I will explore that.

That idea did show up in the generation, but the creepiness factor and the realization that it is a common trope put me off on the eye concept. The second suggestion was a heart, which could animate and seem meaningful but without as much creepiness.

**Comment by avaer** [comment]
> https://github.com/webaverse/app/issues/1335#issuecomment-876585983

That doesn't look bad, but IMO fitting in something organic and pulsating somewhere would be more impactful.

The inverted normals thing also is kind of a weird experience in VR since it violates the usual laws of physics.

**Comment by Vianvolaeus** [comment]
I've spent some time putting different shapes and variants together for shapes so we can narrow down a bit. 
Generally speaking the design focus here was to have some kind of spine that can expand from a handheld size, and have an animation that will protude the blade, but importantly, add a point to the end of the weapon so it can have it's compass function.

Left and right are the same designs, just rotated so they can easily be viewed from both angles.

![image](https://user-images.githubusercontent.com/80061436/125103137-f6e73180-e0d3-11eb-9cd2-dfc8f569d326.png)

**Comment by avaer** [comment]
![EF0C7E42-D0EB-4008-ABB0-27FDCC90BE60](https://user-images.githubusercontent.com/6926057/125437171-868b3e15-6d57-4dc2-9325-b68e811af7e7.jpeg)

IMO all of them meet the bar, but I expect the red one to be the most arrowable in folded form when animating. The blue is my personal favorite, but mainly because it has the cool // symbology going on.

**Comment by Vianvolaeus** [comment]
The sword shapes would look something akin to this, then: 

https://user-images.githubusercontent.com/80061436/125542744-61e4145e-c6b4-4e68-b0fe-f8b307c65fd2.mp4

(w metal matcap & screen shadows, static:) 
![image](https://user-images.githubusercontent.com/80061436/125543132-2a702d1b-2594-4ea9-933a-04b96dae4ff5.png)

**Comment by avaer** [comment]
Looks great.

**Comment by avaer** [comment]
I would still add a trigger for some sort of blade action, but that shouldn't get in the way of progress with e.g. texturing.

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/125675183-e7d20e54-baab-4faa-9af4-255a987b247e.png)
Added a simple trigger, it's better to have it in now for texture work.

@avaer, previously you hinted at wanting the actual blade itself to be a seperate material so you can work with some realtime shader effects in the engine. Is this a requirement for this one also?

**Comment by avaer** [comment]
That would be nice, yes. However it would be good if the blade had a default texture too.

The idea is pulling the trigger turns on the blade and has a cool effect.

**Comment by avaer** [comment]
The trigger is good already, nice and simple.

**Comment by Vianvolaeus** [comment]
>However it would be good if the blade had a default texture too.
> The idea is pulling the trigger turns on the blade and has a cool effect.

It'll be textured as normal, but I can separate the blade mesh specifically as it's own material following the same texture set 👍

Effectively it can be one or two materials as required, with the same texture set for visual parity.

**Comment by Vianvolaeus** [comment]
Timing can probably be edited to be a bit more impactful and visceral, but here's an activation animation for it. 

![ezgif com-gif-maker - 2021-07-15T155749 818](https://user-images.githubusercontent.com/80061436/125812160-e7cc82fd-1707-484c-a705-f24614e6d584.gif)

**Comment by Vianvolaeus** [comment]
Video for pausing playback. 
https://user-images.githubusercontent.com/80061436/125812569-963f2319-58de-44fd-9d1a-f7ce505dc19f.mp4

**Comment by avaer** [comment]
That looks mostly good, but the scaling of the bottom seems out of place.

The reason for the sides was to be able to fold them into an arrow shape without scaling, only sliding into place.

![image](https://user-images.githubusercontent.com/6926057/125876864-5480765e-4c5d-4e5c-ba95-b0e66f495dbf.png)

**Comment by Vianvolaeus** [comment]
Color blockouts and variants. 

It's not explicitly stated in loredocs, but I was under the impression Scilly was blue themed based on initial concepts. 



![image](https://user-images.githubusercontent.com/80061436/125942823-b6a338f0-bbae-4fce-a74b-c741e7bdac77.png)

I was also experimenting with some extra detail based on a curvature bake. Can add color (and height, emission, etc) to edges to varying degrees. 

![image](https://user-images.githubusercontent.com/80061436/125942901-9787864e-fa30-4c32-8f63-909fa1fd5803.png)

**Comment by avaer** [comment]
Yup you got it, and Scillia is indeed blue. I did throw in the color coding to the lore doc.

I know it's probably just the lighting + metalness but it feels like there is a very nice gradient on this one, which in addition to feeling high quality, could be animated. If that's just a trick of the lighting I would try to recreate it in emissive.

![image](https://user-images.githubusercontent.com/6926057/125948580-6ba06fbd-41ab-46fc-b89c-803182f96d45.png)

I was also going to say the handle should not be blue, but I think that material looks fine in that shot. You wouldn't want it to appear to be lighting up like the blade, like some of the other shots.

**Comment by Vianvolaeus** [comment]
There is a base color gradient running along the blade, yes. 
The entire blade can still be it's own seperated material and everything as required, if you wish to animate anything in real-time, which would likely be best for a scrolling emission like you're suggesting. 


The only thing emissive is the blade itself, that is just the metal/roughness reflecting light for the other parts. I'll tone it down a bit to avoid that confusion.

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/125961399-bd6d78e6-24ff-44da-8a02-5923cc2c7608.png)
This is the color only, for reference.

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/125961540-418e17a2-c1c0-47ea-ae77-b559acdac2cc.png)
There is an alternative blade, but I don't know how well this'll translate over since it's relying on transparency a bit.
Top full material, bottom base color only.

**Comment by avaer** [comment]
Alternate blade looks good as well, it's probably the best one, but I would want that as a separate object/material that can be swapped in code.

It looks fine in full mat.

**Comment by Vianvolaeus** [comment]
I'll upload the Blender file shortly. Still reworking the animation and rig, but there will be a single blend / object.

The two materials for the blade can be swapped by selecting the blade, selecting all in edit mode, and applying the other material.

If you need a seperate completely blank material, it can be added. 

![image](https://user-images.githubusercontent.com/80061436/125968324-51ecd859-25f5-45f1-99f1-fd8d786f11f9.png)

**Comment by avaer** [comment]
> If you need a seperate completely blank material, it can be added.

Nope, as long as it's a separate object it's all good. 👍

**Comment by avaer** [comment]
IMO that middle object should be a heart which can beat. If it's a heart I see two ways I see of doing it.

One is gruesome (an actual heart of some sort):
![image](https://user-images.githubusercontent.com/6926057/126003785-d30ea5b9-41b9-4604-a6b3-4d7bbd95de49.png)

The other way is more cute and symbolic.
![image](https://user-images.githubusercontent.com/6926057/126006200-650e7091-069c-49b3-bafc-01b9a9748a5f.png)
![image](https://user-images.githubusercontent.com/6926057/126005877-d55648bc-78fa-4e86-b0ce-03b20125f895.png)

I can fit either of these in. It could also be a flower or a cool eye, but I'm less a fan of the sword looking at you.

**Comment by avaer** [comment]
Sources:
https://www.reddit.com/r/blender/comments/drn1qe/creative_take_on_an_alien_heart_what_do_you_guys/
https://www.youtube.com/watch?v=6AXoU_SSdj4

**Comment by Vianvolaeus** [comment]
I did toy with the idea of the realistic gruesome heart, but it's not great shape-wise, it's probably going to be in the character's view a lot... it seems very out of place in my opinion. 
It also implies that the very heart of the basilisk has been removed, which suggests it's not alive! 

I thought also about a toony, cutesy heart. The resulting would probably look a bit like a Piece of Heart / Heart container from Zelda, etc. (I see that the heart is exactly that from the source) 

It'd look best from multiple angles, though, and would be pretty recognizable from however you look at it. 

The rose / flower immediately references the logo, suggesting the importance of the sword and the character, but it's also a lot more detailed than the other two options.

Here are some previews for all of them:

![image](https://user-images.githubusercontent.com/80061436/126185808-a804a576-0cf2-4cb0-a86c-e75c6e2d29dd.png)

**Comment by Vianvolaeus** [comment]
Turnaround / zoom for all of them: 

https://user-images.githubusercontent.com/80061436/126186575-77b01b90-5e52-4b08-ad37-64c2bc578fe7.mp4

Personally think the rose works really well, reads at most angles, doesn't disrupt shapes too much either. 


https://user-images.githubusercontent.com/80061436/126186455-0e52a822-1bb0-4844-9a67-42bce6702a11.mp4

**Comment by avaer** [comment]
I agree about the rose being best. IUf it's not too much trouble let's keep the Zelda heart hidden. I can see it being useful later.

**Comment by avaer** [comment]
Here is what the OpenAI loop had to say about this weapon, it thought that it is a "finger" of the Basilisk, but it is all very metaphorical.

“It started a year ago with my first Liskmare. I had a dream where I saw the Lisk. It told me I would receive three gifts. The first is the bite mark, then it bit me! The second is the sword, the Liskfinger, and it broke off its finger and put it in my inventory. Liskfinger will always point me to where I need to go next. The third and final gift is the most important and it awaits me at the end of the Street. When I woke up, both gifts were recorded on the blockchain. You can check it yourself.”

**Comment by avaer** [comment]
The sword currently is a "collection of parts", not a model in the asset. That makes it hard to copy paste and work in with other scenes.

IMO there should be a top-level object. We need to write a standards guide for this.

**Comment by avaer** [comment]
The materials in GDrive are highly busted and do not look like anything in this shot: https://github.com/webaverse/app/issues/1335#issuecomment-882642691

**Comment by avaer** [comment]
Because the model's materials are broken, I think we should change the blade to a gradient that doesn't look as bad.

**Comment by avaer** [comment]
In addition to the broken materials, it would be cool if this looked fine in darker environments, since that is one of the main uses.

That means having an emissive, glowing blade, and glowing the rose. This can be done using emissive arrows from the logo, or simply making the rose entirely emissive.

**Comment by avaer** [comment]
The rose seems to be baked into the "middle" model rather than a separate object that can be enabled/disabled, making it less than useful for swapping out the center for another model.

**Comment by Vianvolaeus** [comment]
This is currently waiting on a transparency fix before it can be finalised and exported as a gltf/glb, in which case it *would* be portable and a single object. 

Why this was marked for review I don't know, because it's been acknowledged it's not ready, and we've been actively trying to solve the transparency issue between Blender and gltf export so it can be cleared. If we can't use transparency in this manner, the asset needs to be changed, and if the asset needs to be changed, it shouldn't be posed with for preview, so it's not ready. 

> The sword currently is a "collection of parts", not a model in the asset.

The reason for the separation is due to the history of post-completion tweaks, animation changes, etc. It is much better to keep things separate like this in the .blend file to avoid headaches later, and compile it as a model once it is actually complete.

Worth nothing that a GLTF / GLB can be grabbed at any point if (even a WIP) model is wanting to be posed with, etc. 

> The materials in the version of the model in GDrive are highly busted

The materials are no different at all.
It is a different preview HDRI / preview map (background) in use. Given that the engine currently has issues with lighting, I am testing it in both light and dark environments. 

In this case it looks as if the file wasn't reset to the standard studio light HDRI that's been used for the rest of the shots, and the character itself. 
This is why I'm including color-only screenshots where relevant (eg: https://github.com/webaverse/app/issues/1335#issuecomment-881481594)

The default Blender HDRI is a highly lit forest, which gives everything a green tint and is overbright.  It should be this studio light, since it is sufficiently dark, and has main / key lights:

![image](https://user-images.githubusercontent.com/80061436/126932759-950d0bc3-4b8e-4047-b91c-b07a17146093.png)


You can change them in this window (not all of these will be here in a default Blender install)
![image](https://user-images.githubusercontent.com/80061436/126932463-a9d74b87-d921-4191-9211-660cce63790a.png)

The reason for using this is that they are much more lightweight than full tonemapped render environment background textures - 8k, 16k, etc, but still give an accurate example of different lighting scenarios in realtime (EEVEE)


> The rose seems to be baked into the "middle" model rather than a separate object that can be enabled/disabled

This doesn't match up to the request for everything to be joined.
Either you include geometry the 'baked' (*joined*) model and toggle it via shapekeys, or you keep it separate and toggle the entire object itself. 

> glowing the rose somehow.

This can be added. I advise a gradient or full emissive rather than the chevrons, they'll be barely visible at any kind medium to far distance.

**Comment by plankatron** [comment]
updated megasword glb 
* new sword_activate animation
* extra material sword to override with a shader 
https://drive.google.com/file/d/1J15xHJ-WLdpZvTI_SO-Jz8_65i1LmRSM/view?usp=sharing

**Comment by GaladWarder** [comment]
the "Sword" material can be overridden with GLSL shaders as mentioned in #1408 , I'll crosspost this there too
