### ISSUE TITLE
Org: Art asset system (Git LFS)

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1337]
Right now the primary distribution for art assets has been gdrive -- but there are actually multiple gdrives, and they are not all organized.

- [ ] Set up `git-lfs` for everyone (we can pay for the hosting on GitHub)
- [ ] Create new assets repo purely for git-lfs
- [ ] Migrate all assets to new assets repo, under LFS version control
- [ ] Organize the files using git

**Comment by avaer** [comment]
Does Git LFS work with Github Pages? I.e. with that would be be able to just push and get an instant hosting update?

(I don't know the answer to this)

**Comment by GaladWarder** [comment]
Figured I would leave a +1 on this, it would be super useful to have a central version control for all art assets. I know it's been tossed around a bunch, don't think anything is implemented yet.

I also saw some mention of a system with GRT or Filecoin?
