### ISSUE TITLE
Asset: Silk GLB

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1338]

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/124642023-55ef4100-de5d-11eb-9b95-23ecff634216.png)

**Comment by avaer** [comment]
Right now it is using a noise field to warp the mesh, but I think we can create something with a similar blobby flow as GLB. The material is a normal material.

**Comment by Vianvolaeus** [comment]
I imagine we'd be able to bake a wave +/ displace modifier to achieve something similar in Blender.

Will the material need textures, or are there other things it'll need in realtime?

**Comment by Vianvolaeus** [comment]
Couple of examples of the Wave modifier animating a mesh. Note that this isn't a material per se, but a Matcap uin the Blender viewport. This won't bake out to a GLB, hence the previous comment on materials.

https://user-images.githubusercontent.com/80061436/124646275-594df100-de8c-11eb-9161-61fe6d093a3d.mp4


https://user-images.githubusercontent.com/80061436/124646351-6ec31b00-de8c-11eb-95fd-2b5a1fdda175.mp4

**Comment by avaer** [comment]
The idea is these are lightweight SILK pickups so there would be a lot of these at a time (instanced, animation offset), and tiling/aliasing _might_ be a problem if the animation is too consistent/pulsating.

The main thing to check would be how a bunch of these look if they were just an explosion of drops on the floor.

This is already looking good, but perhaps not random enough/long enough of a loop? There might be other Blender mods to try as well.

**Comment by Vianvolaeus** [comment]
Sure, these are single modifiers on 20 frame loops.
I've uploaded a .blend to the drive under a new subdir: Branding / Misc.

There are a few different variations.

My concern was with having a *lot* of these with long animations perhaps being quite taxing on performance? For smooth shaded, actual models like this to have a similar effect as the original, the polycount has to be fairly dense (for what it is) 

We can definitely combine a few and have a set of 'waves', and offset the starting keyframe to push them out of sync. I'm not sure if you want to do this in engine, or have a few animated models each with their own offset.

**Comment by Vianvolaeus** [comment]
https://user-images.githubusercontent.com/80061436/124656081-a20ba700-de98-11eb-9400-faaf77ab745e.mp4

Preview of a few of the variations. They have a Decimate modifier in the stack (un-subdivide), a lower poly version can be previewed by toggling it. In some cases, the rend result drastically changes.

Flat shading also looks quite interesting with some of them, since they go from smooth, static looking orb / sphere to pixelized / digital feeling waves.

**Comment by avaer** [comment]
This question came up, but GLBs seemingly _can_ be baked with vertex animations -- jin noted that this works with monster mash models and indeed that seems to be the case. The GLB loads the animation with no armature, in Blender and in Webaverse.

**Comment by avaer** [comment]
My favorite of those is actually the bounce. We do want these to be floor-locked, and bounce might be better than hovering at some arbitrary height.

Any way to make the bounce more random, perhaps with a longer animation and more noise? How would that look when we have ~10 of these with random animation offsets? Would it be obvious they are tiling or would they all seem to be independently "alive"?

I agree with jin that the best part of the random procedural blob we have right now is the randomness/organicness that is very appealing to look at.

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/124669462-6a910080-de80-11eb-99fa-56f13a011c27.mp4

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/124670742-71207780-de82-11eb-98bd-52295649fae4.mp4

**Comment by avaer** [comment]
Nice, that looks headed in the right direction. Any way to smoothen the transitions so we can't tell where the loop point is?

**Comment by avaer** [comment]
> My concern was with having a *lot* of these with long animations perhaps being quite taxing on performance?

Length probably isn't much of an issue unless the model becomes large to (down￼)load. It shouldn't affect runtime. In fact I think the animation plus instancig would be faster than the in- code geometry update currently being used.

> For smooth shaded, actual models like this to have a similar effect as the original, the polycount has to be fairly dense (for what it is) 

I think the polycount on the original isn't so bad, and this also sounds like something very amenable to LoDs decimation. But yeah I think smooth shading works best (does that mean normals are baked in to the anim?)


> We can definitely combine a few and have a set of 'waves', and offset the starting keyframe to push them out of sync. I'm not sure if you want to do this in engine, or have a few animated models each with their own offset.

In-engine instancing. We only need one model, it would just need to look perceptually smooth in a group.

**Comment by plankatron** [comment]
two issues : 
this normal map matcap look does not bake down afaik , its an effect that is camera dependant 
the exported glb at about 500 frames with a 960 tri sphere is 10mb thats the low poly version  , high poly at about 3,900 tri is 30mb

**Comment by avaer** [comment]
Can draco be used for the animation? On my end I think it can.

If the normals are in the animation then that’s all I need. It sounds like
it would be doable.

**Comment by plankatron** [comment]
@Vianvolaeus here is the script i found to bake the animation to shapekeys so you can try it out as well 
http://7rnx.net/fleeky-pub/webaverse/blob/bake.py   <-- just load in the scripting tab and press alt+p

http://7rnx.net/fleeky-pub/webaverse/blob/blob.glb  <-- test glb

**Comment by avaer** [comment]
Also I think the best version would combine the bounce on y=0 with the noise in one bake.

**Comment by plankatron** [comment]
draco compression gets it down to 7.4mb but it is lossy and looks way worse , i think a tad of the noise stuff i did could add to @Vianvolaeus but honestly i think i prefer what @Vianvolaeus did

**Comment by avaer** [comment]
Thanks for checking!

I think the combination of Via's back two (hop and light noise) might be good enough then. I checked them out in blender and I think both combined wouldn't be an overbearing tiling effect.

**Comment by plankatron** [comment]
my best combo of @Vianvolaeus 's waves , still probably not what you want *and* it cannot be baked far as i can tell and achieve this result

https://user-images.githubusercontent.com/5592454/124684078-6541af00-de9c-11eb-9c6b-445b45673ae5.mp4

**Comment by avaer** [comment]
I think this would be good if the loop were less obvious and it was bakeable.

**Comment by Vianvolaeus** [comment]
https://user-images.githubusercontent.com/80061436/124798965-e4da8700-df4b-11eb-8dc0-ca742cf9f323.mp4

Revisited this and had a go with 2 different wave mods.

I've uploaded to to drive. 
@plankatron appears to have a good way of baking out shapekeys to vertex anim frames via script? so I think this would be animatable just fine, not 100% on that though.

**Comment by avaer** [comment]
The above looks like a decent morph, but it’s not hopping on y=0, just floating and flopping.

We should do one or the other — either hug the floor for most frames (plus a hop) or don’t imply that at all and just float with noise.

**Comment by Vianvolaeus** [comment]
I believe we can set the wave mod by vertex group, so we should be able to keep the top of the morph animated, while keeping the bottom flat, meaning we could have the bouncy effect, while moving the object itself on the up-axis. 

A bit like a Dragon Quest slime: 
https://i.imgur.com/Qjucg7p.gif

**Comment by plankatron** [comment]
another idea
https://user-images.githubusercontent.com/5592454/124992540-16695600-e011-11eb-9746-931bb3902ac8.mp4

**Comment by plankatron** [comment]
one more variation

https://user-images.githubusercontent.com/5592454/124992951-ac04e580-e011-11eb-809e-0959a01b004a.mp4

**Comment by avaer** [comment]
The above isn’t what I had in mind.

There shouldn’t be any lettering implied. It’s not very animated (not organic), and doesn’t hug the floor like the other proposals.

**Comment by avaer** [comment]
The shape however could be used for something like a bag of silk. If it’s on dog format it could be a frontend icon.

**Comment by avaer** [comment]
If this cannot be successfully made using blender then the next best option is for a technical artist to export the GLB from noise source. That’s like 1 hour of work.

**Comment by avaer** [comment]
Is there a way to just get an array of jiggly bones in a relatively flat tapered sheet?

![image](https://user-images.githubusercontent.com/6926057/125410148-9cc3c600-e38a-11eb-8154-d2a4aab91ae8.png)

I think that could animate well as SILK.

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/125529760-933ae7a7-a177-4590-816e-4b5180292403.mp4

**Comment by avaer** [comment]
That looks quite good, just maybe too thin.

As long as there is the bone structure evenly woven I think it would work well a quick in engine physics simulation.

**Comment by madjin** [comment]
What if SILK was a billboarded gif?

**Comment by plankatron** [comment]
> That looks quite good, just maybe too thin.
> 
> As long as there is the bone structure evenly woven I think it would work well a quick in engine physics simulation.

this will be a vertex anim not a bone anim

**Comment by avaer** [comment]
> What if SILK was a billboarded gif?

That is probably a fine optimization but we need something more uniquely solid for XR interactions and merch.

**Comment by avaer** [comment]
> this will be a vertex anim not a bone anim

No animation is required, only the bones working.

**Comment by avaer** [comment]
The bones would be animated with engine kinematics.

**Comment by plankatron** [comment]
got it , ill rig up some tests

**Comment by plankatron** [comment]
@avaer how bout this thickness

https://user-images.githubusercontent.com/5592454/125531282-950af790-2eaa-47fb-811b-27ec60f61ef2.mp4

**Comment by plankatron** [comment]
@avaer how bout this for thickness
![silk](https://user-images.githubusercontent.com/5592454/125531437-1b6f962a-48ff-447a-8d95-a8e435c04722.jpg)

**Comment by avaer** [comment]
Hm actually now that I look at it closer, the original thickness might be OK -- it's just so heavily effected that it's hard to see what's going on at the bottom.

It's hard to tell how floppy/chunky/visible it would be when holding it since we haven't yet decided on a scale.

If it's easy enough could you upload both versions? (provided we can get bones as control points working)

**Comment by plankatron** [comment]
does this look like it would work ? 
![silk_bone](https://user-images.githubusercontent.com/5592454/125548019-cc943bf2-3e14-440a-9301-32572e04008d.png)
72 bones

**Comment by avaer** [comment]
Yeah that looks fine, provided that pulling just a single bone does the right thing (there would be no bone chain, just bones pulled by kinematics with custom constraints).

My gut says it would be good.

**Comment by plankatron** [comment]
thought about what you said, you probably do not want the bones to be connected, which they currently are, so i made an alternate version where they are all parented to a root bone but thats it , otherwise disconnected and can all be controlled by the physics instead of by another bone. 
![silk_bone1](https://user-images.githubusercontent.com/5592454/125560217-5e0c8602-87bc-4bb5-b89d-5ded903261b0.png)

**Comment by avaer** [comment]
Yup. That looks good.

**Comment by avaer** [comment]
Where are these uploaded?

**Comment by plankatron** [comment]
texta-work/silk in the webaverse gdrive
