### ISSUE TITLE
SVG: DDR arrows

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1342]
Gotten here: https://zenius-i-vanisher.com/v5.2/thread?threadid=9445

I wanted to try using these arrows for UI selection in editor. The animation sheet is actually quite good and it only took a few minutes to animate in engine, but since it is raster the quality is quite low.

Note: animations are row-major.

![_Down Tap Note 16x16](https://user-images.githubusercontent.com/6926057/124579900-9333de80-de1d-11eb-82c1-9662e088ee7d.png)
![_UpLeft Tap Note 16x16](https://user-images.githubusercontent.com/6926057/124579781-74354c80-de1d-11eb-8308-7623514c4ddb.png)

AI upscaling still doesn't get us quite to good quality.

![_Down Tap Note 16x16](https://user-images.githubusercontent.com/6926057/124579965-a3e45480-de1d-11eb-89fa-59d063671b2e.png)
![_UpLeft Tap Note 16x16](https://user-images.githubusercontent.com/6926057/124579968-a47ceb00-de1d-11eb-86e1-2233216afbc0.png)

The best solution might be to remake in SVG, reduce the number of frames, while keeping the same incrementing and gradient effect.

**Comment by avaer** [comment]
Naive conversion to SVG (this is using illustrator) is also not great due to the banding, even at the max of 16 colors: 
![image](https://user-images.githubusercontent.com/6926057/124580419-18b78e80-de1e-11eb-96f7-caa42d28cd0d.png)

I think the gradients would just need to be recreated in the path fill.

**Comment by GaladWarder** [comment]
It would take quite a long time to recreate/vectorize all of these manually, but if you were able to hue shift in the code, we could essentially make a clean 'master' SVG and just control the color of the elements there. It looks like there are essentially two parts to it; the inner parts which are just flashing from grey to white, and the outer gradient shape which is just being hue shifted. 

The inner parts flashing from grey to white is just 4 states, and would be easy to make. If the hue shift could be done on the code end, the animation could be completely recreated without any loss of frames or anything like that.

**Comment by avaer** [comment]
Nice start!

Actually doing it in the shader might be the best approach now that there is this clean image. The main thing we would need then is the list of color gradients for this sheet, in some JSON-style format, so that it  can be injected into the shader.

```
[
  [
    0xD47C12,
    0xEBFFBC
  ],
  [
    0xC4531C,
    0xFFFE98
  ]
  ...
]
```

**Comment by avaer** [comment]
In removing the carbon fiber and potentially collapsing the geometry a bit, here is some more texture inspiration:

![Skyforge - Weapons   Items, Anton Lavrushkin (1)](https://user-images.githubusercontent.com/6926057/124655589-0a915e80-de6e-11eb-8e18-147e21b58e04.png)
.

**Comment by GaladWarder** [comment]
Sure, easy enough:

```
[
  [
    0xcd782e,
    0xe5fec0
  ],
  [
    0xc44d31,
    0xfffe83
  ],
  [
    0xab2b44,
    0xfffe60
  ],
  [
    0x912552,
    0xffed4c
  ],
  [
    0x66217a,
    0xffa146
  ],
  [
    0x532b8b,
    0xff7559
  ],
  [
    0x2a3dab,
    0xff4a7d
  ],
  [
    0x1755bb,
    0xf830a5
  ],
  [
    0x0076c4,
    0xa93dec
  ],
  [
    0x009fb4,
    0x5d67fa
  ],
  [
    0x0dafad,
    0x457ffc
  ],
  [
    0x49bf85,
    0x00c0fc 
  ],
  [
    0x69c776,
    0x00e8fc
  ],
  [
    0x9bbe58,
    0x22fffe
  ],
  [
    0xafad42,
    0x55fffc 
  ],
  [
    0xc38b34,
    0xb5ffef
  ],
  
]
```

The gradients are directly related to each other though as far as I can tell - so each color is a set distance from the last, if that makes sense. In each frame of the animation, it's just shifting the hue like 8-ish percent around the color wheel. Not sure if that's useful info or not, but figured it was worth mentioning

**Comment by avaer** [comment]
> The gradients are directly related to each other though as far as I can tell - so each color is a set distance from the last, if that makes sense. In each frame of the animation, it's just shifting the hue like 8-ish percent around the color wheel. Not sure if that's useful info or not, but figured it was worth mentioning

Yup super useful, thanks!

**Comment by avaer** [comment]
I think this is done, it just needs to be coded up.

**Comment by avaer** [comment]
Testing now.

**Comment by avaer** [comment]
This has been working for a while. Thanks @GaladWarder!
