### ISSUE TITLE
Art: Umbrella-leash Weapon

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1344]
A combination of a whip and a long leash for animals.

![img](https://i.imgur.com/wu6G26j.png)
![img](https://i.imgur.com/9cr9v3H.jpg)
![img](https://i.imgur.com/vz4pgHY.jpg)

It can be one long bone apendage. There is no need to animate. It should have at least one color that is tweakable as a material. It could be made cute in some way (e.g. animal paw prints). It's supposed to be "the length of a room", so 3.5m or so.

One detail that matters in design is some way to latch on with the tip, which is why the scorpion tail is in the references. It could be some other kind of spike, but a suction cup would be too far on the side of silly.

**Comment by madjin** [comment]
What if it was a chain, to represent blockchain? 😄 

![image](https://user-images.githubusercontent.com/32600939/124981412-8b359380-e003-11eb-86f3-e8ad62501caf.png)

Also I found this amazing blend on opengameart: https://opengameart.org/content/chain-whip
558 tri, blocks on a chain!!
![image](https://user-images.githubusercontent.com/32600939/124981645-ce900200-e003-11eb-99e8-390dcb3541cf.png)

**Comment by avaer** [comment]
That does not make sense unless this character is a fanboy of blockchains, which seems to not be the case. It is also confusing when there is already a blockchain analogy in the street.

**Comment by avaer** [comment]
The character that is most likely to be a fanboy of blockchains is MC. And although they did not create their sword, the concept of blocks streets and chains is best invoked there (though I think the existing designs already reflect that).

**Comment by madjin** [comment]
Considering that everything in the world is powered by the blockchain, not just the street, tying such into a weapon design seemed like a good idea to me. It made sense to me because leash = ownership of pet is a good analogy for blockchain ownership +chain whips are an actual weapon so if anything this is the item to pull such a thing off. Its a design that could teach people about the concepts powering the item.

Also thought he way it's in the sword state is pretty interesting, could be tied into the story in some interesting way like King Arthur's sword / Master Sword?

**Comment by avaer** [comment]
> Considering that everything in the world is powered by the blockchain, not just the street, tying such into a weapon design seemed like a good idea to me. It also made sense because leash = ownership of pet is a good analogy for blockchain ownership + chain whips are an actual weapon so if anything this is the item to pull such a thing off. Its a design that could teach people about the concepts powering the item.

But why would the character make such a thing if the entire premise is that blockchains are normalized and everyone knows this from the start? That would be like someone IRL making a weapon based on a skeleton, for the explicit purpose of teaching people that animals have bones inside -- which seems a silly premise.

Having it be a chain could make sense for other reasons, but it has a lot of downsides: a chain is generally a heavy duty industrial tool, and a pretty violent weapon IRL. I can't think of a soft pleasing interpretation of it, unlike the obvious wacky interpretations of "a big freaking sword".

**Comment by madjin** [comment]
What if its not made by the character and instead found by the character? What if the chain part is somewhat holographic?

**Comment by avaer** [comment]
Rather than this weapon being found, the best idea I saw is that this was made by someone else and gifted based on a comment the character made. I can see a hologram version working if it was sufficiently cartoony.

**Comment by madjin** [comment]
remove hilt, turn into some kinda umbrella 
![image](https://user-images.githubusercontent.com/32600939/126203260-a9ebdbea-528a-4ba0-864b-04c28e51e058.png)

**Comment by avaer** [comment]
An umbrella transformer would the best version of this and appropriate for the character.

**Comment by madjin** [comment]
- Some kind of leash latch at the top 
- Handle is more like an umbrella (OPTIONAL, CAN BE KATANA LIKE TOO)
- Button for opening the umbrella

![image](https://user-images.githubusercontent.com/32600939/126687447-139c630d-85a6-4f9c-948b-ff8344d35c4d.png)

![image](https://user-images.githubusercontent.com/32600939/126687607-b97c0444-4f6b-4a44-9ab2-55864f530acf.png)

**Comment by madjin** [comment]
Couple ideas here: 
- Having a more decorative handle would be good
- Could the umbrella part be some kind of energy shield?
- 
![image](https://user-images.githubusercontent.com/32600939/126690222-4d97d3e5-ec16-4904-8032-66a45665f312.png)

**Comment by Vianvolaeus** [comment]
You could also spring out the joints the opposite way and have them be telescopic. It makes less real world sense, but it does mean it works better as a grapple, and it'll also be a *lot* easier to rig and actually make.

![image](https://user-images.githubusercontent.com/80061436/126696038-cc7e6bdb-ed88-4167-a926-b748e1144aef.png)

**Comment by plankatron** [comment]
really quick edits just to address jin's requested changes .. 
![whip](https://user-images.githubusercontent.com/5592454/126700485-a5be0e96-1a31-4085-93e0-bb601cb4b215.jpg)

**Comment by avaer** [comment]
There would not be any leash latch, it would be some sort of point or weapon edge that can attach to a point and grapple.

The leash loops more like a lasso around multiple targets, rather than attaching to a collar.

**Comment by avaer** [comment]
I also think the handle should not be curved, since that makes it less pleasing to play with in VR, and harder to animate, since the handle will constantly be clipping with phantom limbs.

**Comment by plankatron** [comment]
playing around with the handle , and almost figured out the rigging but ran into an issue that i still need to solve : 
![whip2](https://user-images.githubusercontent.com/5592454/126855461-80ccdcbb-7f6f-4350-96de-498a588e5e9b.jpg)
![riggin](https://user-images.githubusercontent.com/5592454/126855460-7c6d3dba-c3a7-4d11-bebc-80e0c4377bc8.jpg)

**Comment by madjin** [comment]
Another way to do the umbrella that's prob easier is an unrolling of fan blades, see each piece of the umbrella gliders in FN:
![image](https://user-images.githubusercontent.com/32600939/126874574-2f08b6f5-ded9-4274-be05-4420c3a6ec32.png)

https://user-images.githubusercontent.com/32600939/126874616-aa8f1a8b-1422-4363-a6fd-0e79d0aee64d.mp4

**Comment by avaer** [comment]
I'm down for either style of fold-out, they both look cool. We should think more about the top design of the umbrella.

**Comment by plankatron** [comment]
so i was planning on combining the current , boring , umbrella skeleton with something that is combined more with this idea : 
https://ratools.com/wp-content/uploads/Grappling-Hook_243cfbfa5eacfb8be1150fb26ce94510.jpg

let me know if you have strong preferences for something else and we can switch gears to whatever people are feeling most strongly about

**Comment by avaer** [comment]
Where is this skeleton supposed to ho? Are we rfeplacing the leash with this geometry? Are we putting this at the tip as the bone structure of the umbrella but not the grappling hook? Are we putting this as the grappling hook up top, but _not_ the bone structure of the umbrella?

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/127087321-e46df7cf-d580-4e94-a1b4-12a1b0e1a817.png)
1. shows off a good way to hide the leash part within the tip of the weapon
2. Feels like more of Hya's personality / character (search: rwby neo)
3. Very stylized and cool looking parasol which transforms in many ways, might not be best for this
4. Solarpunk themed
5. Asian silk parasols, simplest design but might be best?

FN style umbrellas for inspiration
![image](https://user-images.githubusercontent.com/32600939/127087694-9a17fc61-088f-47da-8346-46095c794554.png)

Might need to synthesize a design from these ingredients better into some sketches

**Comment by GaladWarder** [comment]
Going to put a bunch of stuff here:

First off, played with some basic silhouettes/sketches of umbrellas - 
![image](https://user-images.githubusercontent.com/29031531/131203509-e122293e-9454-41b9-a3f0-8c3865ade8f7.png)
Last we left off, this was going to be a combo-umbrella-leash thing.

Took one of the thumbnails, refined it, and blocked in in Blender:
![UmbrellaWeapon_Blocksheet](https://user-images.githubusercontent.com/29031531/131203590-63786039-f145-42f2-acaa-5bf5775ef156.jpg)

Then went over top and started to lay in linework and design details.
![UmbrellaWeapon_Sheet1_V1](https://user-images.githubusercontent.com/29031531/131203603-52e51a46-cf28-4f0e-8c48-267b9ac059cd.jpg)

I'm thinking it could be really cool to have a hardsurface 'shell' with a holographic canopy. Shown in the blockins are various modes as well - it could theoretically be attached open or closed, and when totally shrunk down would be a cute accessory that's very much Hya's style.

There is still only primary and secondary detail on these, I need to go through a tertiary pass as well as a texturing pass but ran out of time today - figured I'd upload what I have to see if it's on the right track.

I went with the compact umbrella design because it seemed like it made the most sense if it were to be attached to a pet's collar. The clasp is also a lobster-style clasp so could be easily opened/closed with a motor or something for long-range captures.

**Comment by GaladWarder** [comment]
This is still rough, but I think there's enough here to judge if we should continue on this idea or try a different one.

**Comment by GaladWarder** [comment]
@plankatron I'll have you do some rigging and animation for this this week. We'll need:
-[] Open animation
-[] Close animation
-[] Leash extend
-[] Leash retract

Let's try to keep the anims snappy, we can look at Fortnite for a few examples on how the umbrellas are opening - especially the custom skins, or Genshin for some of the weapon state animations.

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/140436771-a2dda577-0d3b-42df-afe8-a84f0bab64c6.mp4


https://user-images.githubusercontent.com/5592454/140436776-813849e6-567d-4206-b31d-97ade1918343.mp4

**Comment by plankatron** [comment]
open 
https://user-images.githubusercontent.com/5592454/140439032-409ad1b9-4df2-4894-b380-39f783bdeb0e.mp4
close
https://user-images.githubusercontent.com/5592454/140439388-7c366d99-c7e3-4cea-a98b-aa631cf5bb7c.mp4

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/140439661-c216128b-cd30-452a-9a43-e73e687f5a26.mp4


https://user-images.githubusercontent.com/5592454/140439664-50cfb571-179a-4dd2-81fc-b89c5fabd658.mp4

**Comment by GaladWarder** [comment]
Chain for this model - can we array it realtime in the engine?

What would be the easiest way to implement the 'leash' part?

We'll need to meet w/ a dev to figure out what output is needed to implement in engine, but the base of this model is done
