### ISSUE TITLE
Weapon: scissors

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1345]
The idea here is scissors that can split apart. That can be accomplished by keeping the two parts as separate objects.

A chop animation should be included. The size should be relatively visible (not kids scissors) but not so crazy that it requires two hands.

The theme for these is kind of dark and old timey. Asymmetry in the handle or blades would help. These might be called "shears ".

**Comment by avaer** [comment]
![Bloodborne Weapons_ Asian Inspired Skill Oriented by Lucky-Trident on DeviantArt (1)](https://user-images.githubusercontent.com/6926057/124689168-07b26000-dea6-11eb-8015-db13639e5612.png)

![Bisecting Shears - Bloodborne Fan Art Trick Weapon, Dane Brennand (1)](https://user-images.githubusercontent.com/6926057/124689122-f8331700-dea5-11eb-9ef1-d8e8b155a446.png)

**Comment by plankatron** [comment]
initial thoughts , 
* how do the gameplay mechanics work ? 
* what era do we want the webaverse version from
* does it fold up? 
* is it purely mechanical , anything digital

**Comment by avaer** [comment]
I think the gameplay mechanics are mentioned in the lore doc. OHKO plus throwable in two pieces.

The era is not specified, but my impression is something old style per the owning character.

It does not fold up.

If there is a digital aspect to it, which is not necessary, then it should echo the sword for obvious reasons in the lore doc.

**Comment by avaer** [comment]
It could be wings. This would require changing the script a little but it would be a powerful silhouette/motif and pretty accurate for the chara.

![img](https://cdn.discordapp.com/attachments/823299491091841065/863209189550587944/image0.png)

**Comment by avaer** [comment]
It's even in one of the reference shots.

![img](https://i.imgur.com/8oceGXO.jpg)

**Comment by plankatron** [comment]
heres some thumbs so we can nail down the sillouhette
![thumbs](https://user-images.githubusercontent.com/5592454/125687860-0bccfc7b-61f1-4d57-8754-c07b79f8ab9e.jpg)

**Comment by avaer** [comment]
Beautifully disgusting, great work!

Torn between 6 and 8.

6 because it is unidirectional and evokes the sword. 8 because it is more impactful.

I can see either one working.

**Comment by plankatron** [comment]
I'll make variants based on those, now onto actual concept art

**Comment by plankatron** [comment]
just a first test , i will try to do some more variations tomorrow
![6-test](https://user-images.githubusercontent.com/5592454/125738286-08408dfe-79e4-44a3-a2bf-14e7fd811548.png)

**Comment by avaer** [comment]
Looks like a great variation 👏.

**Comment by plankatron** [comment]
this test did not come out the best i am going to re-asses but here is my current WIP
![death-scissor](https://user-images.githubusercontent.com/5592454/125864766-ba88725f-6bc4-438b-bf7e-f395f465b390.png)

**Comment by plankatron** [comment]
i would say this is an improvement but still not quite it , gonna keep chipping away .. 

![death-scissor1](https://user-images.githubusercontent.com/5592454/125995739-0930b216-5035-4109-852c-e48b15623ef7.jpg)

**Comment by avaer** [comment]
Other than materials and texturing that honestly looks pretty good.

I also like the sharp handle look:

![image](https://user-images.githubusercontent.com/6926057/125998265-2ea81e68-87e4-4976-845f-67be09a0a91b.png)

But I imagine this thing being a single black (possibly slightly metallic) material, with hand drawn texturing on it.

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/126018228-c04f9982-8fcc-4555-8f29-b5cb921b0207.png)
its just texture / material work now, handles can be black just like that
also some organic details to be colored in for the blades
color variation on teeth, maybe some green grunge / blood to make it more threatening and unbalanced

**Comment by Vianvolaeus** [comment]
Taken over from @plankatron who's working on the wave function city building. #1365 
High poly edit and material work from today. I've flatten the back edges of the blades where they would meet when closed. 

I've added a lot of height variation and some warping to imply some decay or infection to the 'bone' side i designated. 

Being named the Death Scissors, and the character's association with potions / ingredient crafting, and old-timey (Gothic-era?) styles, I've tried to implement some elements as such here - everything's decaying or being taken over by nature in some aspect - bone rot / cancerous growth, rusted metal, mossy / rotting wood.

I mocked up a potential glow emission for them to drive the green color a bit more. 

![image](https://user-images.githubusercontent.com/80061436/126372020-835dff9a-9fb5-440a-8a72-e4788ded4ec0.png)

**Comment by plankatron** [comment]
love the creativity !

**Comment by avaer** [comment]
I love the style, textures look good too.

The only comment I had is I feel we lost a bit in the geo. In the original geo I feel like there was implications of razors and teeth embedded in a manmade thing, like you got stabbed and the person didn't even bother to remove your remains from the weapon and then the cursed weapon grew around it. Wheras this is version is more like two very gruesome constructions put together and it is slightly less impactful as a result.

![image](https://user-images.githubusercontent.com/6926057/126377113-41a375f9-d29e-4e95-b4a4-12b5e61e70eb.png)

**Comment by avaer** [comment]
Should also note though that I really like the bone shape here, like some sort of mutated animal that doesn't exist.

![image](https://user-images.githubusercontent.com/6926057/126377647-0950f1e6-abb8-4b4a-aa2b-93677a8179ba.png)

**Comment by Vianvolaeus** [comment]
I've gone back and made changes based on the above. 

Here are four different texturing styles we could go with, as well as some updated geometry to match the concept better and seperate the organic from the manmade.

If there elements from different ones that work, I can combine them:

![image](https://user-images.githubusercontent.com/80061436/126491316-0d5e9425-01ef-40fe-a5a8-ef1dedfc21e5.png)

**Comment by Vianvolaeus** [comment]
Extra one, just had a quick idea
![image](https://user-images.githubusercontent.com/80061436/126491502-412faebe-89b4-4540-906a-58175db3667c.png)

**Comment by Vianvolaeus** [comment]
I've made some poses and animations for the scissors. These will probably want to be looked at by @plankatron for a sanity check and make sure there's nothing wrong with them / make them better

They are all NLA tracks and export out to glb fine from my testing, but there could be something I'm missing with the export settings etc.

https://user-images.githubusercontent.com/80061436/126511989-391d8586-7642-4444-ab5e-304d583b1ac0.mp4


.blend with all variations is on the drive!

**Comment by Vianvolaeus** [comment]
![spin](https://user-images.githubusercontent.com/80061436/126514121-43f6c1da-dc0d-435e-8115-6561a8e8380a.gif)
They look really good closed as well, IMO, both blades still show up well and they look pretty brutal and gruesome.

**Comment by avaer** [comment]
Great work! 👏

**Comment by plankatron** [comment]
the metal teeth look cool!
