### ISSUE TITLE
Art: Engineer character concept ('Jun')

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1346]
We need to finish these. That means two outputs for each of the characters:

* [ ] Concept sketches (one sheet probably enough)
* [ ] Avatars modeled as Vroid -> VRM

The second might depend on the first (but that is up to whoever is working on it). They should of course end up matching in the end.

Concept sketches are useful for more than just the avatar creation and building; they could themselves be published.

![babies](https://user-images.githubusercontent.com/6926057/124727109-672b6280-dedc-11eb-8365-bebff11f148c.png)

All of these already have their own profiles in the ai lore doc, including Pinterest shots. Below I list which _existing third party_ avatars they can be (or are already) based on -- these can be downloaded and posed for reference to sketch or remake.

I am also specifying whether the face, hair and clothes have been made, and/or where they can be sourced.

# Gear
Based on `gear.vrm`, https://booth.pm/en/items/1024547. The original should be in our gdrive, as well as Via's version which is quite good.

I think this one is pretty close to made, but:

1. There are a few known things like the fingernails being too dark
1. Might be some silhouette work to do (such as increasing the spikiness or edging it more androgynous) depending on how it looks in black and white when posed. Some spiky hair with the right attitude: https://hub.vroid.com/en/characters/4948904433335433581/models/6870911478905495196
1. Clothes have the right flavor imo but I am the least sure about them, if anyone has ideas that better match the lore doc.

Face: done?
Hair: done?
Clothes+body: done?

# Brown
This one has not been started.

https://hub.vroid.com/en/characters/2830638355411138718/models/190889763016197518

Face: needs to be made, but the cold look can be taken from the vroid and pinterest examples.
Hair: messy, per both this avatar and pinterest examples
Clothes+body: clothes needs to be made, but there are strong clothing references in the lore doc. per the lore doc it's supposed to be the same age/height as gear above so some adjustments might be needed

# Citrine
There were a few passes made in different directions but I still think the best one is the original Citrine, especially the hair. We might want to start with some sketches.

https://hub.vroid.com/en/characters/8171135067054409405/models/1189318216410191025

Face: needs to be made, but can be roughly inspired from the vroid. It is supposed to be the most normal/average face.
Hair: needs to be made, we probably can't copy Citrine too much.
Clothes+body: body/metrics can be copied from Citrine, the clothes should come from the lore doc. there is mention of some sort of uniform in the doc, which could be something like this:

https://hub.vroid.com/en/characters/8051482746118403420/models/6525939892996755769

# Shilo
I think this one has been started by Via, but I'm not sure whether to go with that or change to better match the generated lore doc.

However, there are plenty of example avatars to work with: trendy and/or cute designs (per archetype in the character sheet) are the bread and butter of vroid and as long as it fits in with the other avatars and can emote, it should be ok.

This is the original shilo basis:

* https://hub.vroid.com/en/characters/4755472098203122209/models/8732392610956747100

Some more vroids that dance around the design, from which things can be taken:

* Unique hair and eyes: https://hub.vroid.com/en/characters/1426176662752882970/models/1054990230631284690
* Unique hair: https://hub.vroid.com/en/characters/426253657290320164/models/157320037785394032
* Possible full clothing: https://hub.vroid.com/en/characters/8499023842866460493/models/2925117288345846359
* Possible hoodie: https://hub.vroid.com/en/characters/3373905032678618304/models/2105843759857931137

Face: many choices available, but I think the eyes should be unique in some way (shilo is). also it is important that the morphs can make exaggerated expressions. could be from https://hub.vroid.com/en/characters/1426176662752882970/models/1054990230631284690
Hair: should be one of the unique ones, could be from https://hub.vroid.com/en/characters/1426176662752882970/models/1054990230631284690
Clothes+body: clothes should get some animal theming, though Shilo and Via's take are good bases. there is a hoodie clothing idea in the avatar above (https://hub.vroid.com/en/characters/8499023842866460493/models/2925117288345846359). shilo body seems ok.

**Comment by GaladWarder** [comment]
Currently working on these, touched  base with Vian before the meeting on Monday and am working on a silhouette pass right now

**Comment by GaladWarder** [comment]
For the Citrine model, are two sets of clothing needed? There's a uniform mentioned in the doc, but it also mentions that she prefers not to wear it since it makes her stand out. Will she be wearing it on the adventure, or will she swap it out for something more casual and travel-friendly?

**Comment by Vianvolaeus** [comment]
> are two sets of clothing needed?
Just to add to that, will they need to be present / worn at the same time - very important for the modelling & skinning process

**Comment by GaladWarder** [comment]
Since the doc specifically mentions the military uniform, I just went ahead and started with that. I have sketches for more casual clothing and can refine them into a sheet if needed, but since Jun is accompanying the group on assignment, I assume she'd be in uniform.

Tried to keep the 'feel' of the original model, while working in a stronger design and some of her character attributes. Only focused on character and costume design here, I can do another pass for accessories and weapon if needed.

Directly tracing the geo wasn't working since it's so bulky, so I redrew her from scratch but kept the main proportions very similar, so it should be an easy implementation.

![JunSheet_Military_V3](https://user-images.githubusercontent.com/29031531/124910829-9ea22800-e01e-11eb-91d6-79326198fe80.jpg)

**Comment by Vianvolaeus** [comment]
Very rough kitbash of parts just to show how this might look in 3D 
![image](https://user-images.githubusercontent.com/80061436/124934936-18c1b500-dffd-11eb-9dc3-fce2170042dd.png)

**Comment by avaer** [comment]
I like the kitbash technique (it is literally what would be doing to see if something looks good).

Also the names are prone to changing so I deliberately don’t use them to avoid confusion, but it looks good on the concept art.

**Comment by Vianvolaeus** [comment]
Sure, I'll keep it in mind for the future then, will hopefully help iterate better (and save some sanity!)
From my understanding there's another char. sheet on the way, so i'll do it again for that one +/ in the future.

**Comment by GaladWarder** [comment]
Casual uniform before I jump over to another character.

I know you mentioned the names weren't set in stone, I just wasn't sure what else to call the model so I used "Jun" again for consistency.

Also, I have started on some accessory designs, but sidelined it - it probably makes sense to lock in the main design first. These designs are still slightly toward the generic side, but once some character-specific accessories are added, I think they'll fall into place. 

I was also thinking it could be cool to have some of the emphasis on accessories regardless - since the whole point is the focus on NFT's, we could take a similar design approach as games like World of Warcraft, where there is a lot of emphasis placed on 'cosmetics' to tell the story. Just some thoughts. 

![JunSheet_Casual_V2](https://user-images.githubusercontent.com/29031531/125253367-ea5d1600-e32b-11eb-8282-a09c3d71c57a.jpg)

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/125315198-c6e79a80-e32e-11eb-9eb4-be919a177342.png)
k/b for the above.

Some assets were pulled from the old kanji model and edited to fit.

**Comment by avaer** [comment]
Engineer

## Clothes

The clothes in the concepts are great, both versions.

I especially want to point out good distinct shapes, rather than wrinkles and floofiness:

![image](https://user-images.githubusercontent.com/6926057/125533563-847ada9a-35f0-4c88-9750-c801fcc7e84c.png)

I think the clothes on the kitbashes need simplification to match the theme.

I think it is mostly the materials, especially how hi fi they are, in what is otherwise a low fi and stylized design. The mats so far are all very real, whereas the concepts (and also most VROIDs, and the reference art) goes for a flatter matte look where the actual materials are almost not discernible (and not the focus). Hand drawing might be a better approach than synthesizing textures.

## Hair

The hair from the concept seems like it would work, though goggles are required for that specific shape to make sense (in the uniform it kind of doesn't, but the uniform version could just as well have goggles).

The kitbashed hair would need to be made to fit better with the goggles, and to better match e.g. the tie back, since that adds a lot to the silhouette.

## Face

The face concepts are based on Citrine but that isn't currently translating through to the models.

I think the main problem is that there is no facial emotion in either the concepts or the renders, so it is mostly not even giving the impression of embodiment.

In general I think the concepts should also flesh out faces and facial expression variations more (I tried to allude to that in the original post).

For reference, here is Citrine with basic vroid animations -- IMO it makes a world of difference in evaluating.

![image](https://user-images.githubusercontent.com/6926057/125535135-0efba42d-bdca-4696-ab7e-e945c2eb9c13.png)
![image](https://user-images.githubusercontent.com/6926057/125534765-f571079e-f8d8-4cc2-bbf3-dc8e96001d84.png)

**Comment by avaer** [comment]
> Not spending too much time on posing, it's not hugely necessary.

Imo it's worth it to do so for at least the face morphs. Sometimes you can't really tell from the neutral morph.

**Comment by Vianvolaeus** [comment]
>I think the clothes on the kitbashes need simplification to match the theme.
>I think it is mostly the KB materials, especially how hi fi they are, in what is otherwise a low fi and stylized design.

It was simply a color swap of some existing materials, yes. If we want more time spent on this that's fine.

> The face concepts are based on Citrine but that isn't currently translating through to the models.

I think the main problem is that there is no facial emotion in either the concepts or the renders

I think you're right, considering it is the *actual face* pulled from the original Citrine model to concept with. If it is somehow mistranslating from the original, then there's a different problem here. 

I'll add in turntable views and flat/outline/clay renders as well going forward, so we can check the above mentioned shapes etc.

If it's easier to evaluate via video rather than several images, I can record something as well.

**Comment by avaer** [comment]
> It was simply a color swap of some existing materials, yes. If we want more time spent on this that's fine.

Yeah I think it's worth it, since the same techniques can be used for all avatars.

It is mostly things like adjusting shininess knobs and resolution, so I'm down for learning the pipeline so I can make the tweaks along with the engine.

> I think you're right, considering it is the actual face pulled from the original Citrine model to concept with.

Yup and that's probably the way to go. But I'm so used to working with posed avatars that I can't even picture how it would look animated unless it is animated. I can do this myself if the files are available.

I think the problem is more in the sketches, where could use more face detail, color, and expression. For example, if you were to ask me if these two shots are of the same character, I would say they are not. But it should be fixable with some more work on eye placement.

![image](https://user-images.githubusercontent.com/6926057/125570663-30706142-7c47-409a-863e-390c5d2b1364.png)
![image](https://user-images.githubusercontent.com/6926057/125570716-2a3dff4e-6cf3-4eff-9fbc-ed213296a4f0.png)

**Comment by GaladWarder** [comment]
I can pay more close attn to the face if you are wanting more expression in the concepts - honestly the only reason it's like this is because I knew the model would be used which already has expressions/shapekeys, so I didn't put *any* time or design into the face area; it seemed redundant.

On the next pass, I'll render out the face with a more art-centric approach - takes a bit more time but isn't too hard. For these I literally just traced a few major landmarks from the model so that it wouldn't be blank and called it good.

Oh, also, these files are set up to be easy to work on, so if you are wanting me to go back in and spend some time really rendering stuff out to look pretty I can totally do that; the sheets as-is are almost entirely focused on the shapes, silhouettes, and design. It's not hard to render out though if you want something that looks better for presentation/socials/etc.

**Comment by avaer** [comment]
> I knew the model would be used which already has expressions/shapekeys, so I didn't put any time or design into the face area; it seemed redundant.

Yeah, it's a good workflow.

> It's not hard to render out though if you want something that looks better for presentation/socials/etc.

Something more along the lines of publishable concept art would be the goal, but while we're designing it's fine to not waste time on details. If it's easily editable then then there is no issue, but we _should_ clean up this concept with expressions at some point.

**Comment by GaladWarder** [comment]
Yeah, I know you had mentioned them potentially being used for social media posts or whatnot, so I intentionally set up the files with cleanup in mind. Just tell me when you need me to do a pass on them and I will - they could theoretically be taken all the way to an illustration level of polish.

**Comment by avaer** [comment]
Well in this avatar's case I think it's blocking Via, because once the concept art for visemes and emotions is done, changes may be made, if the emotes do not match the clothes.

**Comment by GaladWarder** [comment]
Got it - so we need a sheet of emotes for the character, then?

**Comment by avaer** [comment]
Yeah I think that would be sufficient.

**Comment by GaladWarder** [comment]
Sweet, shouldn't be too hard to do - I'll try to squeeze it in today.

Just to confirm, I'm envisioning something like this: 
![image](https://user-images.githubusercontent.com/29031531/125599411-ba41dfb2-a4f1-452a-a4f2-dda8e2bf80e6.png)

These are the types of sheets generally used for emotion in animation - if he's making visemes for them, I assume that would work

**Comment by avaer** [comment]
There is actually a standard VRM morph set, it's not arbitrary and vroid comes with it. Just sketching that set in from the actual model (e.g. Citrine) is probably good enough.

But yes, something like that with the standard set.

Here is the rough list, which should be available in Blender for VROID VRMs renamed as GLB: 
![image](https://user-images.githubusercontent.com/6926057/125599968-4f5a9d9c-3318-431e-96a2-b673f117a0e0.png)

**Comment by GaladWarder** [comment]
Perfect, that's even better.

**Comment by avaer** [comment]
☝️ Btw we don't need the vowels or the blink or anything, that would probably be silly, I'm just trying to dig the data up.

**Comment by GaladWarder** [comment]
So I took a crack at these; I honestly think they may be best done in 3D, though. Since there are already visemes on the model, it'll most likely be easiest to just tweak those directly, rather than alter them in 2D and then have to try to translate them onto the mesh.

![JunExpressions_Test](https://user-images.githubusercontent.com/29031531/125646902-a64d8fd0-af61-464f-a625-f102a7df67a3.jpg)

If the expressions are for the purpose of making the sheet look better/more interesting, then I would need to break the silhouette/geo pretty hard to make it appealing from a 2D standpoint. An example is those expressions I posted above - the shapes squash and stretch a *lot* to add the dynamism.

That's no problem to draw from an illustrative standpoint, but when trying to lock that vibe to set shapes/geo, it kind of just doesn't work - it's too flat and lifeless to really get the expression across. In 3d, it's less of an issue, but when viewed on a 2D sheet it gets kind of weird. The more I push the shapes for dynamism, the less useful it is as usable concept art - it crosses too far into illustration territory.

**Essentially the TL:DR is:** If the purpose is to make the concept sheet look better for socials or whatever, I'll just repaint the face entirely. It won't really be applicable to the actual geo we'll be using, but it will look good. If the purpose is to create expressions for visemes, it's best done directly in 3D, because the limitations of the geo will be built-in with immediate feedback.

**Comment by Vianvolaeus** [comment]
quick preview just on materials and reshapes, just fleshing out poses and expressions now as required.

I've added in a toon outline to the color render to match the concept sheet, adds a lot to make the character seem less flat with simple materials as well:

![image](https://user-images.githubusercontent.com/80061436/125653916-ad0dc3b2-61da-432e-a908-4ccc4c00d187.png)

**Comment by Vianvolaeus** [comment]
I've buzzed @plankatron on the status of #1198, if there was any progress made then I can add it into the concepting here for each character, since they share an armature.

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/125659454-5d511fb8-45c6-43b9-a808-a7ee2b9b6be5.png)
Okay - poses and expressions!

I'm surprised at the amount of character coming out from these, I think you're entirely correct on the posing and expressions making a lot of difference on visualising the character.

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/125661046-a6e164a4-74d6-40a4-8b3e-a5addaaacde9.png)
Couple of poses with the goggles on as well. I think it's got a fun vibe for the character, which doesn't necessarily line up with the character lore, but they're probably excited about building and tinkering with things.

**Comment by avaer** [comment]
@Vianvolaeus  Looking sick, this is exactly what I meant. The posing really helps to show off how good of a job you did. Also GJ on the mats, it is looking a lot closer to the sketches. It doesn’t need a too outline 

This is starting to fool me that it is done, the main things that stick out are the bandages + suspenders, which seem tubular at this stage but should be fabric planes.

Btw if the suspenders are hair we would have a nice extra flair with that in the wind.

**Comment by avaer** [comment]
@GaladWarder I think part of it is coloring the eyes but yup, that looks on the right track. And yes, I think it’s fine to redraw the face in more detail, from the avatar itself if needed.

It’s just that the concepts should intuitively match the 3d presentation in any media we release.

**Comment by GaladWarder** [comment]
Alright, makes sense! Later this week, I'll revisit the casual sheet and do an example render for socials so you can see what I have in mind for it.

**Comment by Vianvolaeus** [comment]
Thanks! I was happy to see a bit of life come into it!

>  bandages + suspenders, which seem tubular at this stage but should be fabric planes

This can be fixed up easily enough. I recommend having *some* thickness so they're not entirely paper. It's pretty negligible on polycount, but avoids things being invisible on the backface. 
This is less of a problem for the bandages, which can just have a rim to fake the effect.

The suspenders were a little thick but also smooth shaded, making them look a bit too round, so I'll fix that up.

> if the suspenders are “hair” we would have a nice extra flair with that in the wind

On characters / VRM, anything that's rigged to a bone can have a spring bone component added to it, I had this in mind already 😄 

Just have to be mindful of performance with collisions and number of bones is all.

> This is starting to fool me that it is done

It'll need a proper go over for polish and cleanup, but that's promising 👍

Final note for now - we do have this other face texture which adds a bit more definition. Currently the facial features get a bit lost. We could find a medium between the two if needed. 

left: original, right: alt

![image](https://user-images.githubusercontent.com/80061436/125778624-da52e212-a903-41a1-890f-59d59df8dc33.png)

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/125782724-7ada6c08-698b-4c7a-8de6-eadda012f39a.png)

Bandages and straps reduced in thickness, shading fixed.

**Comment by avaer** [comment]
I honestly think the original one on the left with less detail is better. IMO its very soft neutral makes the expressions more lively in contrast.

Also re: I he suspended planes, one good part in the design is the suspenders traces along the pants.

IMO that makes the design stronger, as the lines are all flowing cohesively rather than being a new appendage. That is also why I think the plane is the way to go. The bone stuff is just set dressing compared to how it looks in static shots, so even if we can’t properly bone a tight flow like that I think it would still be better.

![A2E1F2D1-8592-45A0-93B1-0E45815A0E52](https://user-images.githubusercontent.com/6926057/125886882-61545fb8-fc41-4065-a0de-1fcabec6721f.png)

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/125942260-caf334e5-dd05-4175-9935-687993498644.png)

Updated. Bones on this will be a pain as you've said, but the uniform look carries when they're weighted to the legs like this. It looks more like they're hitched under the large pocket under movement. 

I could add a small patch to tie them down to the leg if we don't want them to seem like they're stuck or floating, etc.

**Comment by avaer** [comment]
> I could add a small patch to tie them down to the leg if we don't want them to seem like they're stuck or floating, etc.

I don't think we need any additional geo, but I'd like to try the bones. I think I've done this before; selecting that object as the only influence should work, no?

Also, I did notice though that the belt is pretty hardcore, like a thicc harness, wheras itseems more a flush fabric belt in the concept. If there is no reason for that bump in the geometry we should also keep it flush.

Other than those two things I think this seems done and we can move onto the other models.

**Comment by Vianvolaeus** [comment]
It can be done, easiest way to stop clipping and the like is to add a collider component for the spring bone component.

we can rig the straps seperately and parent those to the leg bones so they move in uniform though, yes.

This character would benefit from a proper go-over and polish IMO, but if we can start nailing other concepts down that'll be good.

![image](https://user-images.githubusercontent.com/80061436/125952974-ea35b91e-4c2e-40d3-897f-ee9fe408fdc2.png)

Updated geo.

**Comment by avaer** [comment]
> It can be done, easiest way to stop clipping and the like is to add a collider component for the spring bone component.

That sounds like the best approach. I believe the VRM colliders should be supported if added.

I agree there is still cleanup to do here, and we should do it, but getting _some_ ok version of each avatar is more impactful than polishing one by one, since it allows us to push media earlier.

**Comment by GaladWarder** [comment]
I plan to get the other avatar sheets out this week, or at least as many as I can so that there's something to start working on.

I think if the avatars are essentially my only focus this week, I can get sheets for all of them done, along with any needed alts.

**Comment by avaer** [comment]
To recap: probably the best one to start with is MC/Scillia https://github.com/webaverse/app/issues/1382, so there is a direction for VRM edits.

Can finish up engineer concept to look more like the ava, but it is looking already good enough to post.

**Comment by avaer** [comment]
We also discussed that the charas could have "normal"/school and "job" attire (for example casual and drop hunter mode), which is a good idea, but it is best to get some version of the initial avas out first before we do variations.

**Comment by Vianvolaeus** [comment]
Also, a quick recap on workflow (will treat as if it's a brand new character)

- Initial lore concept (who they are, where they fit in the story, etc)
- Moodboard / shotgun design inspiration
- 2D concept art w/ expressions
- 3D kitbash w/ expressions
- 3D refinement
- Final VRM 

will edit as needed, but probably good to nail this down

**Comment by GaladWarder** [comment]
I see that this is still P1, is there anything further needed on the concept art side for the Engineer character?

**Comment by avaer** [comment]
I don't think so, not right now. We'll probably need to loop back once we have the full set of charas but this one seems like it's obvious how to complete it.

**Comment by plankatron** [comment]
![Jun_Concept1](https://user-images.githubusercontent.com/5592454/128423425-dcb6e800-c279-4196-b477-f91d2da39ea2.jpg)

**Comment by avaer** [comment]
Tried in VRChat:

- [ ] The shapes are good, but we need more detail around the pants/belt/clips/staps areas to make them more detailed than just flat shaded polygons.
- [ ] The pants are kind of floating above the hips. If you look at it in person you get the impression that they are going to fall down. Either we should tighten it or close it off at the top 
- [ ] De-cartoonify the face a bit, to make it seem more like Scilly and Jun are from the same set. Jun should feel like an older half-sister to Scilly. I suspect to increase that perception, it's in the eyes and cheeks.

![image](https://user-images.githubusercontent.com/6926057/128571900-27106c23-dd9e-4ca7-838e-005af5ba129d.png)

**Comment by madjin** [comment]
Jun pureref: https://cdn.discordapp.com/attachments/641036402829819914/875797001596444692/jun.pur

![jun3](https://user-images.githubusercontent.com/32600939/129399005-8f25909e-cfbb-4808-9f33-5b133f749cdb.png)

**Comment by NotFuji** [comment]
![jun_v2](https://user-images.githubusercontent.com/38316883/135899318-bba4c628-d2eb-4d19-9ea9-3ae87447e114.png)

**Comment by Vianvolaeus** [comment]
VRM & Blend is in relevant sections of drive, based on Fuji's concept. It is forgoing wearable accessories like goggles / backpack weapon since these were previously stated to *not* be included in final avatars since they can interfere with any wearable system implemented. 

Shots are taken from within Blender! There's a setup we can use without changing our material nodes to get a rough idea of what the toon looks like there - will be adding it to char docs. 

![image](https://user-images.githubusercontent.com/80061436/140046936-ba2c48ff-719c-425e-8f91-09f8e8ce30ff.png)
