### ISSUE TITLE
Art: street design

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1349]
Youtube video:

https://www.youtube.com/watch?v=gtH5_sTC37w

I took a crack at an animated street design that can be easy to recognize, draw, and logo-ize. I kind of threw everything in so we can take parts away and shift around. Colors can be changed.

![image](https://user-images.githubusercontent.com/6926057/124850465-a904e900-df6e-11eb-9745-fd2f234b432b.png)
![lolgo3-04](https://user-images.githubusercontent.com/6926057/124850493-b326e780-df6e-11eb-949f-2e39a6724f53.png)

Some elements are procedurally generated and animated (like the fake LCD kanji), but could be textured.

If there's criticism or other ideas, this is the thread for it.

**Comment by avaer** [comment]
I expect the street would differ each season but we should establish some common visual language that carries over.

**Comment by Vianvolaeus** [comment]
Couple of things to consider would be how it would feel in different zones, and how it'd interact with the Great Filter concept (though that may be more about the street itself rather than the styling).

I'm not sure what the middle triangular areas/ icons are meant to be? 

The ruler stops and what i'm assuming are boosters on each side work, I think. The arrows could use a bit more spacing  just to define the directional shape a bit more, since at a distance it's hard to tell which way is which. 

I think something to section off horizontally every x distance / block might be an idea as well (could be on the larger stops)  - something to encourage the player to stop and look around, a unit of measurement the inhabitants could use to determine street distance (x location is y blocks / bars up or down the street)

**Comment by madjin** [comment]
My favorite part are the side bars going up and down, the measuring stick seems useful too - especially as it comes to parcels.

The middle part is interesting, reminds me of conways game of life. Heck, could it be conways game of life?

I want to see other variations of the middle, like a simple grid - inspired by a holodeck. Also, maybe seamless textures to see how those might look (light dirt, road, grass, etc). That way it will give us some ideas about what parts stay consistent between seasons and how it may look with different themes.

Also here's a look at the inverted colors just for show:

![image](https://user-images.githubusercontent.com/32600939/124972923-e7df8100-dff8-11eb-82a5-09673b4d4b56.png)

**Comment by madjin** [comment]
couple other ideas might worth exploring involve thin light strips on the side and either textured or non textured ground. Non textured could make avatars really stand out.

minimal tron style

![](https://i.imgur.com/bCeja.jpg)

neon street

![image](https://user-images.githubusercontent.com/32600939/124980235-1f9ef680-e002-11eb-8a37-4a5decbfe820.png)

**Comment by madjin** [comment]
For reference, this is what the current street design looks like
![image](https://user-images.githubusercontent.com/32600939/124980415-58d76680-e002-11eb-926d-86846060fd76.png)

**Comment by avaer** [comment]
Seems like the sides of the street (some sort of color and animation, possibly arrows) is the best consistent part. The internals can be painted in many ways each season, or not at all if we're being minimal.

**Comment by avaer** [comment]
> The ruler stops and what i'm assuming are boosters on each side work, I think. The arrows could use a bit more spacing just to define the directional shape a bit more, since at a distance it's hard to tell which way is which.

The ruler is indeed meant to be some sort of marker. I agree about the arrow spacing being increased at distance. This was not really meant to be boosters (it is a DDR hold arrow), only a distinct edge to the street.

However now you got me thinking they could be boosters which you can hook into to go fast. That's probably an idea to explore at some point.

> I'm not sure what the middle triangular areas/ icons are meant to be?

The idea was to hint at lanes, but mostly just flair and adding more arrowlike features.

> I think something to section off horizontally every x distance / block might be an idea as well (could be on the larger stops) - something to encourage the player to stop and look around, a unit of measurement the inhabitants could use to determine street distance (x location is y blocks / bars up or down the street)

I like that idea, it is an expansion of the ruler concept.

**Comment by Vianvolaeus** [comment]
In terms of the booster system - perhaps the player / character could approach a block marker with their device (#1339) and they can activate / enable a fast travel / rapid transit? 

The main problem in terms of gameplay I could see having booster strips along side the street would be activation / deactivation. Having a permanent high speed area you could easily walk on would be problematic.

**Comment by avaer** [comment]
If there is a fast street travel it should be more visceral, especially if a use can do it. The tablet could be involved somehow but generally the tablet seems a not very action heavy device. Maybe you could turn it into a hoverboard but that is getting complicated.

Inspirations that come to mind (me, but AI):

Shadow flame shoes, Sonic grinding, Spider-man, and YT (snow crash).
