### ISSUE TITLE
Multiplayer street

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1351]
We need to bring back a multiplayer implementation for the virtual world (street).

For now the goal is too hook up a “room code” based multiplayer implementation to the webaverse engine. The user opens UI and enters the room code of their choice, which is some alphanumeric text, and they are connected and synced to the room state and players who also entered that room code.

This involves bringing up two backend services and some client implementation work.  This must speak a web protocol (we generally use WebRTC).

The two backend services are

* a world server which acts as presence and possible SFU for client voice, video, user pose data (currently JSON, but it could be binary), and entity state (matrix plus key value store)
* a management server which exposes a REST interface to CRUD world servers, gas unused rooms, and provides some basic anti abuse like a number of live world servers cap

The client uses these two backend services to connect to rooms via an in world UI.

Almost all of the required backend code already exists and I recommend using it, I just took it offline since I didn’t want to maintain it at the time. The client side is also implemented on the front end in prototype form (features working).

Poses are just fanned out to clients, which do basic lerp client side.

Entities work similarly and are a key value store, tracked with y.js on both client and server side. The server side (world server) persists this and also fans out updates to clients, as well as syncs clients up to the current state when they join. There is really nothing special done here yet; we’re just syncing JSON updates and it is up to the client to make sense of it.

All of our servers currently run in AWS as node server ec2 instances. It is unclear what the optimal mapping between this to world servers is. To start it could probably be one large ec2 with worker processes,  but ultimately we will want to have some sort of sharding solution. Note that ec2 machines take forever to start so would not be a workable solution unless they are buffered.

It is possible Vircadia (a HiFi fork) might provide a WebRTC entity server for us in the future but it is not ready yet. We can have a meeting if needed.

The task would be to deploy and debug the two backend services and hook them up to the client (I can help on the client side).

I can post code pointers here.

**Comment by avaer** [comment]
Management server (orchestration) code exposing a creation endpoint: https://github.com/webaverse/multiplayer-backend/blob/main/routes/worlds.js
World server, started by the management server: https://github.com/webaverse/dialog (note the use of the `hack` branch!)

Client connection using the above: https://github.com/webaverse/app/blob/c2d6c00939db674ef0929cfbac692b214904a10b/world.js#L97

**Comment by avaer** [comment]
The above might very well be out of date, desynchronized, or buggy, so if that code is used, the main task would be to debug it.

We don't have any tests for this but writing some via `puppeteer` or something would probably be a good TDD technique.

**Comment by DavinciDreams** [comment]
Overlaps issue https://github.com/webaverse/app/issues/966
