### ISSUE TITLE
Art direction: School map

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1353]
Now that it's more clear what schools are , we should create something like this to spell out the locations, rooms, and how they fit in.

It could be in a very rough image form:

![garden](https://user-images.githubusercontent.com/6926057/125009698-0cf0e580-e033-11eb-8753-a4a5307d63da.png)
![garden2](https://user-images.githubusercontent.com/6926057/125009792-3c075700-e033-11eb-8e7f-0aa25e7224f2.png)

Related: https://github.com/webaverse/app/issues/1348

**Comment by madjin** [comment]
How high of a priority is this? If its low this can be a bounty for SILK.  We can have under construction props with sections / works in progress for social media posting to attract designers.

Things one can search for inspiration:

- school floor plan
- simple school map
- Hogwarts
- School building plan
- Campus

At the moment I have models of auditoriums, classrooms, and know many VR locations we can shoot scenes in for the trailer. These can all be used for further inspiration to design the full thing.

Also an idea: think it might be easier to design this map once we have progress on the wave function collapse city https://github.com/webaverse/app/issues/1365

**Comment by avaer** [comment]
I think this is mostly a matter of drawing a map for the trailer.
