### ISSUE TITLE
Set up new logos

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1359]
* [ ] Webaverse
* [x] Upstreet

I'll post some versions here.

**Comment by avaer** [comment]
Ingredients:

https://www.shadertoy.com/view/NtsSzS
![street](https://user-images.githubusercontent.com/6926057/125181125-ae14a300-e1cf-11eb-9300-2858bdad0332.png)

**Comment by madjin** [comment]
1. 
![image](https://user-images.githubusercontent.com/32600939/125181215-af929b00-e1d0-11eb-9f38-2080682a3b09.png)

2.
![image](https://user-images.githubusercontent.com/32600939/125181203-9558bd00-e1d0-11eb-8cf8-43b4285dc801.png)

3. 
![image](https://user-images.githubusercontent.com/32600939/125181206-98ec4400-e1d0-11eb-80bd-32dd4c9299f3.png)

4. 
![image](https://user-images.githubusercontent.com/32600939/125181208-9c7fcb00-e1d0-11eb-88c9-631fd97fd7f1.png)

5. 
![image](https://user-images.githubusercontent.com/32600939/125181212-a30e4280-e1d0-11eb-889d-6f782dd44948.png)

**Comment by avaer** [comment]
https://cdn.discordapp.com/attachments/498315766509338636/863612193497284638/electroharmonix.zip

**Comment by avaer** [comment]
Light mode variations are possible:

![image](https://user-images.githubusercontent.com/6926057/125181275-537c4680-e1d1-11eb-800e-8bdac8fb113e.png)

**Comment by avaer** [comment]
The W logo can be very simple: 
![image](https://user-images.githubusercontent.com/6926057/125181310-8e7e7a00-e1d1-11eb-9166-fbfe0b41d3d7.png)

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/125183434-aad7e200-e1e4-11eb-956e-9a89d93b7664.png)

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/125183467-cb07a100-e1e4-11eb-966e-83c4a1c4f987.png)

**Comment by avaer** [comment]
Updated the spacing.

![image](https://user-images.githubusercontent.com/6926057/125190635-200add80-e20c-11eb-94ba-6da3be34a7bb.png)

**Comment by avaer** [comment]
More symbology:

![image](https://user-images.githubusercontent.com/6926057/125255908-e9939800-e2c9-11eb-96f9-23d3e0298f2a.png)

**Comment by madjin** [comment]
I love those little ghost things, the logo is looking great.

**Comment by madjin** [comment]
I think the symbols in the background should stay within the rainbow boundaries, afterwords I think this is pretty close to done. I like it a lot.

**Comment by avaer** [comment]
![lolgo3-07](https://user-images.githubusercontent.com/6926057/126007995-1f217b37-33af-4117-b60e-8af3d35c33d0.png)

**Comment by avaer** [comment]
Which font is more legible and/or impactful?

![image](https://user-images.githubusercontent.com/6926057/126038315-c8402fbd-2da4-443d-82a5-0a1d3e1ba7af.png)

**Comment by madjin** [comment]
The first one

**Comment by madjin** [comment]
> The W logo can be very simple:
> ![image](https://user-images.githubusercontent.com/6926057/125181375-211f1900-e1d2-11eb-8628-7e2ae967a2c3.png)
> ![image](https://user-images.githubusercontent.com/6926057/125181369-0a78c200-e1d2-11eb-99dc-85cd725ab577.png)

Think we'll need to make circular / square variations

**Comment by avaer** [comment]
I was thinking of putting the W in a globe or a circle. It doesn't need to be elaborate.

**Comment by Vianvolaeus** [comment]
> Ingredients:
> 
> https://www.shadertoy.com/view/NtsSzS
> ![street](https://user-images.githubusercontent.com/6926057/125181125-ae14a300-e1cf-11eb-9300-2858bdad0332.png)

Couple of questions:
a) Is the working link still available?
b) do we have a defined set of these shapes we're using, or are we pulling from this as a reference sheet?

Either way, I can divide this and make a set of alphas - will be handy for texturing on my end :)

**Comment by avaer** [comment]
All of those shader toys should have been public, sorry. I’ll get that unlocked when I get home.

**Comment by avaer** [comment]
Unfortunately they cap how much can be public, sad :(.

I'll put these up on another account.

**Comment by avaer** [comment]
Here's the shader: https://www.shadertoy.com/view/st2SDh

**Comment by avaer** [comment]
> do we have a defined set of these shapes we're using, or are we pulling from this as a reference sheet?

This is a sheet of random ones I generated but this shader will give you infinite. I also have a singular version.

**Comment by avaer** [comment]
Single letter generator: https://www.shadertoy.com/view/stjXDh

**Comment by avaer** [comment]
The way I use these sheets is generate them in the shader, then vectorize in Illustrator, then use as a vector wherever. If we're doing logos (including the W) then it should be a vector.

**Comment by Vianvolaeus** [comment]
Appreciate it, thank you. I'm not 100% on if Substance etc wil allow SVGs as alpha, but it's pretty painless to go back and forth on something this simple. I'm likely just going to use it in a grid formation as a pattern, nothing too standout or logo based in the texture work unless explicitly needed
