### ISSUE TITLE
Upload lore docs

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1364]
To Wikia or something, where it is more collaboratively editable and accessible.

Jin is not a fan of WikiML.

**Comment by avaer** [comment]
There is still tons of raw ai lore to filter down, but it could be dumped to hackmd or elsewhere.

**Comment by madjin** [comment]
https://community.fandom.com/wiki/Help:Start_a_new_community

**Comment by avaer** [comment]
Yeah, I've done it before, it worked out pretty well.

**Comment by madjin** [comment]
It's setup and the interface is actually quite pleasant and easy to use. I'd like to figure out how to create an Upstreet category before sharing link similar to https://nintendo.fandom.com/wiki/Nintendo_Wiki with the portals section.

**Comment by avaer** [comment]
I think pages just get tagged with categories.

**Comment by madjin** [comment]
Ideas for main site: http://nintendo.fandom.com/

Ideas for materials page
https://fortnite.fandom.com/wiki/Materials_(Battle_Royale)

**Comment by madjin** [comment]
All the text from the synopsis hackmd are transferred to the wiki: https://webaverse.fandom.com/wiki/Special:AllPages

We will need to tineye all the reference images we use for each piece: https://tineye.com/
There are also info boxes we can use for traits: https://en.wikipedia.org/wiki/Help:Infobox

**Comment by avaer** [comment]
If you can't find one of these, I think most if not all are on my Pinterest dumping: https://www.pinterest.ca/wansinagorg/pins/

**Comment by avaer** [comment]
The upload is done, now it needs actual covers and explanations.
