### ISSUE TITLE
Art: Silk Fountains

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1366]
Throughout the world are Silk Fountains, which spawn matter called Silk for anyone to pick up. Silk is a necessary ingredient to create Cards. These fountains are the virtual world equivalent of a coin faucet.

First we need the concept design for what the Silk Fountain looks like. Open to suggestions and trying different things.

Here's an example concept, though I'm not really sold on the design.
![photo!UNITO-UNDERSCORE!2021-07-10!UNITO-UNDERSCORE!03-47-19](https://user-images.githubusercontent.com/32600939/125156058-9686dd00-e131-11eb-9602-6873c2db566b.jpg)

Another idea could be some alien looking plants that drip silk . Rick and Morty always has interesting ideas.
![image](https://user-images.githubusercontent.com/32600939/125171762-e2fb0880-e183-11eb-93a4-66ea72bf192b.png)

Couple other ideas SILK comes from a mushroom looking thing that spews silk from its pores or drips out. I think it'd be cool to have giant mushrooms that wisp out SILK from underneath, like an upside down fountain.

![image](https://user-images.githubusercontent.com/32600939/125171882-a8de3680-e184-11eb-8f8e-f39c21357cc2.png)

Perhaps its an object that can be cracked open, and the SILK flies out. Or maybe SILK is dug out of the ground? Discuss.

**Comment by avaer** [comment]
I don't recommend shoving silk up your butt.

**Comment by avaer** [comment]
Related to Silk design: https://github.com/webaverse/app/issues/1338

**Comment by madjin** [comment]
> I don't recommend shoving silk up your butt.
Haha I just remembered what Rick and Morty were doing in that world

The other idea I forgot to list was one you mentioned about an opening in the ground that is like an empty kleenex tissue box which wisps some SILK from it every now and then.
![image](https://user-images.githubusercontent.com/32600939/125178764-c8da1e00-e1b5-11eb-84f2-7105c905cbf8.png)

**Comment by avaer** [comment]
If Silk is designed closer to a windy tissue than a blob, it could a hole that spews tissues -- as if you put a fan under a box of Kleenex.

This could be combined with the idea of digging for Silk, similar to Knuckles gameplay from Sonic Adventure/2: https://www.youtube.com/watch?v=fpB0oTcbf9w

## Gameplay idea

- Go to the Silk-rich area, which has a specific look (reminiscent of the Silk material).
- Attack the ground to cut a hole, which presents as a decal or small hole model.
- If you are lucky, Silk spills out and you have to catch it. If you are unlucky, you have to move elsewhere and dig again.

**Comment by avaer** [comment]
## Gameplay idea

- Go to the Silk-rich area, which has a specific look (reminiscent of the Silk material).
- Attack the ground to cut a hole, which presents as a decal or small hole model.
- If you are lucky, Silk spills out and you have to catch it. If you are unlucky, you have to move elsewhere and dig again.

**Comment by avaer** [comment]
## Gameplay idea

A tree (or a field) of Silk fruits that you run around and pop to get the Silk out.

![Fruit Concept by splatpixel on DeviantArt](https://user-images.githubusercontent.com/6926057/125179516-a697ce80-e1bc-11eb-92d7-e2115a9afe0e.png)

**Comment by avaer** [comment]
## Gameplay idea

A special type of pet craps out Silk, `kopi luwak` style: https://en.wikipedia.org/wiki/Kopi_luwak

![Gallery3](https://user-images.githubusercontent.com/6926057/125179544-ee1e5a80-e1bc-11eb-9d65-e40abc99c6ec.png)

**Comment by madjin** [comment]
Chop plants, get silk?

![image](https://user-images.githubusercontent.com/32600939/125179557-2aea5180-e1bd-11eb-91a9-f5d065ab1327.png)

**Comment by avaer** [comment]
> https://github.com/webaverse/app/issues/1366#issuecomment-877721465

It can work, if the plants are distinct and this is taught somehow.

It would somewhat defeat the gathering spot nature of silk fountains if the grass could be anywhere -- but the tradeoff is that exploration would be more rewarded.

**Comment by madjin** [comment]
maybe its a type of plant enemies that pop up in such fields and drops silk?

![image](https://user-images.githubusercontent.com/32600939/125179614-d5627480-e1bd-11eb-8964-9698bf435cb4.png)



> ## Gameplay idea
> A special type of pet craps out Silk, `kopi luwak` style: https://en.wikipedia.org/wiki/Kopi_luwak
> 
> ![Gallery3](https://user-images.githubusercontent.com/6926057/125179544-ee1e5a80-e1bc-11eb-9d65-e40abc99c6ec.png)

reminds me of llamas in fortnite season 7, when you hit them they start galloping around away from you while dropping ammo/potions until they teleport to a new location (unless you can get its HP down fast enough)

**Comment by avaer** [comment]
IMO you should not kill anything to get silk. There should be some action to perform but if that action is killing something it makes it unappealing for pacifists. Grass or a nonmoving plant makes sense but not a deku baba.

**Comment by avaer** [comment]
The silk fountain design could just be Silk-colored splotches on the ground, like if Silk was Splatooned.

And then we just need some decal which represents when you use your weapon to cut into that ground.

**Comment by madjin** [comment]
Throwing in some references here

![image](https://user-images.githubusercontent.com/32600939/126015231-001e6a4f-c5cb-4543-8a91-ff5b3e8ee892.png)

![image](https://user-images.githubusercontent.com/32600939/126015242-c0bc39f4-e492-4a1b-8eaa-d9b7a88a63e3.png)

![image](https://user-images.githubusercontent.com/32600939/126015261-a0733721-764d-4806-9344-38535076bad2.png)

**Comment by madjin** [comment]
https://texture.ninja/textures/Blood/11  (CC0)
![image](https://user-images.githubusercontent.com/32600939/126016337-9d53dc2d-533a-42d6-83e8-043e48ea9364.png)

**Comment by avaer** [comment]
Yup exactly, I’m gonna play around with this to see if anything else is needed, like some sort of mounds or worms.

I don’t like any of those cuts since they don’t really open up, so we might need our own.

**Comment by Sunny3D** [comment]
![image](https://user-images.githubusercontent.com/65556189/144877501-1ecd9aa4-1c40-4f28-bc07-e628e944d833.png)
Silk Fountain 3d model Updated Pertoday
