### ISSUE TITLE
Art: Title Deeds

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1367]
A special type of Card is the Title Deed, which grants the right to use (and restrict access to) real estate on The Street.

![image](https://user-images.githubusercontent.com/32600939/125172401-8699e800-e187-11eb-9851-9d139b592354.png)

The information it might display include:

* Season / Zone at the top 
* Title name
* Transaction date
* Hash string
* Certified to ___
* Description
* Signed by ___ on [date]
* Signature
* Stamp seal (QR code)

Example title deed from meatspace:

Old

![image](https://user-images.githubusercontent.com/32600939/125172592-86e6b300-e188-11eb-92f6-34d541f7da86.png)

New

![image](https://user-images.githubusercontent.com/32600939/125172700-27d56e00-e189-11eb-843d-3fb0f9797199.png)

https://www.govtech.com/biz/heres-what-a-blockchain-property-deed-looks-like.html

**Comment by madjin** [comment]
One question I have is how different of a design might these be from the AR hologram windows?

![AR_Popup_InitialDesign_V1](https://user-images.githubusercontent.com/32600939/125173667-57d34000-e18e-11eb-9b66-673081531024.jpg)

![2 - bbWuhZV](https://user-images.githubusercontent.com/32600939/125173673-60c41180-e18e-11eb-9ea7-02738b1e715b.jpg)

**Comment by avaer** [comment]
Should these be listed along with regular cards, or should they look different, being displayed a different page?

I’m thinking it is a different page and the deeds are larger than a card, with a standard paper size (similar to the case with cards).

Either way, this should be an SVG which can be filled in and rendered, like the card base.

We will indeed need a separate ui style for preview goggles mode of parcels, but right now that layout happens in engine. The main thing to decide is which details to display.

**Comment by avaer** [comment]
- [ ] decide on paper size
- [ ] design svg with named blanks
- [ ] preview server rendering path for title deeds
- [ ] design hover preview details

**Comment by madjin** [comment]
Title deeds should be on the same page as the map but I don't object to them being listed as their own category on the main site under LAND.

**Comment by avaer** [comment]
Both make sense to me. Whatever is in world would mirror the site.
