### ISSUE TITLE
Art: Origin Tablets

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1368]
At the beginning of the street is a set of cryptographically signed tablets on which are written the rules of the world. These are called the Origin Tablets (OT). The Origin Tablets spell out the basic lore of the world, mostly specifying rules that are designed to keep the simulation running to completion without a rogue AI ruining it.

## Inspiration

![image](https://user-images.githubusercontent.com/32600939/125173497-b0eea400-e18d-11eb-875a-c2c0db2258bb.png)

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/125180035-77389000-e1c3-11eb-88b6-fc0cff1d0dfc.png)
https://www.artstation.com/artwork/VakEX

![image](https://user-images.githubusercontent.com/32600939/125180040-815a8e80-e1c3-11eb-86d0-e30adfeed889.png)

![image](https://user-images.githubusercontent.com/32600939/125180049-8c152380-e1c3-11eb-8531-be99003c8e03.png)

Perhaps another idea could be Ethereum inspired stone shape or inscriptions on the stone

![image](https://user-images.githubusercontent.com/32600939/125180141-7d7b3c00-e1c4-11eb-8851-e9819fafc85b.png)

gameplay ideas: perhaps there's a soft hum coming from the stone or the closer you approach the tablet the quieter the rest of the world becomes (if there's music / background sound). Maybe the stone awakens somehow with an emissive material running through it.

**Comment by avaer** [comment]
Something that evokes Ethereum+Upstreet brandings is probably the way to go.

**Comment by GaladWarder** [comment]
I'd love to take a stab at these, I have some ideas. I'll add them to my docket this week, shouldn't take long

**Comment by madjin** [comment]
symbology issue is related with whats inscribed on the tablets https://github.com/webaverse/app/issues/1336

**Comment by avaer** [comment]
One idea that came out of Jin's presentation is to put the OT's directly into the internet archive.

**Comment by madjin** [comment]
Grant will have some Origin Tablet art ready later tonight. I assumed since the reference art suggests these are large outdoor pieces they wouldn't be in an indoor space. I see the Archives as part of the storytelling in which the Internet history was preserved without corruption, the ultimate training dataset for AIs, digital immortality getting achieved in which not only was the web preserved but eventually simulated again.

If the tablets aren't humongous I could see holograms or tablets there, similar to ToT.
![image](https://user-images.githubusercontent.com/32600939/125507375-f0aecf3b-4df0-4212-8eb4-77e69bd34e8f.png)

**Comment by avaer** [comment]
IMO the oot+ia vibes work better than the open space. The whole thing feels like a ruin you visit, and the tablets are part of that ruin complex.

But there are many good ways of expressing this.

**Comment by GaladWarder** [comment]
Came up with a few ideas - trying out a new workflow that will allow for a little illustration as well.

![OriginTablets_V1 copy](https://user-images.githubusercontent.com/29031531/125618201-9f323e28-b7f6-4c7e-87a8-e26e978c8b5f.jpg)

I think having them 'feel' like stone, but maybe have some higher chroma colors that suggest something more digital is the way to go. Of course, all the pictography in this could be changed in the final - I just threw the generated one in for an example.

These would also work quite well in the open air - maybe on a little hill, at the start of the Street? Different vibe, but either could work. For the mockup, I placed them in ruins.

**Comment by madjin** [comment]
Beautiful concept art. I really like the symbol art on the stone + higher chroma colors.

I'm not sure about the shape design and potential sizes of the stones. Perhaps lets to explore different shapes such as something close to a 3D Ethereum logo. It looks like the top of 4 is almost one. Also I'm also not sure how destroyed looking they should be in a simulated reality.

If they were more tablet / slab shaped we can inscribe symbology on them more prominently: https://github.com/webaverse/app/issues/1336
 
![image](https://user-images.githubusercontent.com/32600939/125720699-c7dcd289-84af-4655-a13c-5d33e674d963.png)

Sumerian tablets could be a good shape inspiration. What if the origin tablets are way simplified versions of the cards?

![image](https://user-images.githubusercontent.com/32600939/125721290-5bd7fbf7-d139-4131-8d10-6b75cdaf1de1.png)

It may be quicker to try some ideas with 3D modeling especially once we have the material / texture.

**Comment by avaer** [comment]
Those all look good. I especially like how 2 doubles as a sort of screen, and feels like it was cut out of something else. I'm less a fan of floating debris.

> Also I'm also not sure how destroyed looking they should be in a simulated reality.

Weathering would still be possible, caused by people breaking chunks.

It is also plausible that it was simply designed this way from the start. If _we_ are designing it this way, and we think it looks cool, then it makes perfect sense to me that this design gets dropped into the world.

**Comment by avaer** [comment]
I also think it's probably a good idea to have an unbroken Ethereum in there somewhere.

**Comment by GaladWarder** [comment]
Awesome, thanks for the feedback guys! Will circle back around to this most likely next week for  second pass - right now, just trying to get a first pass on as many of these design issues as possible.

The floating crystals aren't needed for the design; they are just a concept art trope that makes things pop. Can easily be omitted.

Can also pull in the Eth logo more prominently, as it is I was just playing off of those shapes obliquely. In round 2 I'll pull harder on that logo.

**Comment by plankatron** [comment]
fun art test time : 
![origin_tablet](https://user-images.githubusercontent.com/5592454/126012261-c9766467-6d55-4b77-b415-398a7b43b752.jpg)

**Comment by madjin** [comment]
3D model of the ETH logo

![image](https://user-images.githubusercontent.com/32600939/126014255-bd2f96ef-df43-4115-a261-11b0683ccaf8.png)
https://cdn.discordapp.com/attachments/641036402829819914/865721130966188032/ethlogo.glb

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/126018134-b5b28594-aab5-4a2b-9fb6-177d0596a358.png)

**Comment by avaer** [comment]
That art looks good, and I can see a path to the solid Ethereum motif up top. It doesn’t need to be complicated, I think carving it in there is fine.

**Comment by plankatron** [comment]
![origin_tablet2](https://user-images.githubusercontent.com/5592454/126677048-f453f3ca-d480-46d4-adc7-a23bfbf1b67e.jpg)

**Comment by avaer** [comment]
> https://github.com/webaverse/app/issues/1368#issuecomment-885059886
@plankatron is that available in the GDrive?

**Comment by GaladWarder** [comment]
Looks like this is has stalled slightly, is another concept pass needed?

**Comment by avaer** [comment]
I don't think so, it is already looking great in tests.
