### ISSUE TITLE
Design: Spaceology

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1370]
We need to augment the lore doc with clear definitions of how the entire system of spaces works.

- [ ] What are these spaces?
- [ ] Who is using them? For what?
- [ ] Are there different types of spaces? How do they differ?
- [ ] Can a space be in two places at once?
- [ ] Can a space be carried in your pocket?
- [ ] Is a space always owned or are there spaces with no owner?
- [ ] Can you walk from a space to a space? What is the layout? Is there a background outside of spaces?
- [ ] Can two spaces link up like a Game Boy Game Link Cable?
- [ ] Does a space come blank, or does it come with non-editable stuff, or does it come with editable stuff?

Most of these have clear answers in the logs but they need to be organized into the lore.

**Comment by avaer** [comment]
Related: https://github.com/webaverse/app/issues/1369

**Comment by madjin** [comment]
I'ma take a stab at these ideas before consulting the AI

**What are these spaces?**

Spaces are virtual realities that the AIs create, share, and trade. The Street is founded on rules as inscribed on the origin tablets and encoded into the blockchain, so the AIs sought ways to escape into sims of their own to experience magic and imagination. Depending on rarity and security they are represented as small totem chips that fit in your hand (NFTs), or streams / downloads from the Internet to the mobile device (public domain / non-unique). The AIs can preview the space in AR before logging in. Logging in either freezes them in the base reality.

**Who is using these spaces? For what?**

These experiences range from military and school use-cases to teach students through sims of the base reality (think BIM / digital twins), interactive story telling worlds and games, private home spaces that netizens hang out together in, and anything else imaginable. Ownership or permission is required to access most spaces, although a public commons exists as well (much was data mined from the Archives).

**Are there different types of spaces? How do they differ?**

There are various types ranging from isolated spaces (private invite only worlds) to networked spaces (meta-grid like dorms or a virtual kowloon walled city). The difference is that isolated spaces are fully customizable by the creator while networked spaces are more like templates with a pre-determined skybox.

** Can a space be in two places at once?**

Networked spaces hosted or those downloaded from the Internet can be accessed simultaneously by many.
Spaces locked inside totem chips can only be accessed locally / unlocked by those that possess it.

**Can a space be carried in your pocket?**

Mobile devices are always on and can carry many spaces with AR preview windows into them.
Totem chips can be carried in your pocket and remain inactive (encrypted) until they're powered on (unlocked) by the owner.

**Is a space always owned or are there spaces with no owner?**

Spaces are always owned by some address, whether by the zone or one of the AIs, or multiple with a multi-sig which is often the case with networked spaces like schools that are managed by a group. Sometimes a totem chip appears in the junkyard (burn address). No one will know what secrets it may of contained.

**Can you walk from a space to a space? What is the layout? Is there a background outside of spaces?**

The layout is often determined by the creator of the space. Some might trigger the traversal by touching a wall (like LSD dream emulator) or walking through a portal/floortal. The space you start out in becomes a totem you carry with you as like an escape hatch reminder.

There is no particular layout, it's as wild as the web or dream worlds. The background outside of spaces is individually set by the creator or the zone. For networked spaces they all share the same skybox.

**Can two spaces link up like a Game Boy Game Link Cable?**

Avatars can meet up in either one or the other. If someone wanted to trade something from their space to another person while in that person's space the transaction can be mediated through a mobile device or imported from a totem chip.

Idea: The power to seamlessly link up two spaces is secretly sought by the zone and school leadership. Kids are constantly trading / talking about spaces. The leadership which manages the biggest networked spaces see linking together as a way to create a powerful hivemind unrestricted by the rules of The Street. There is a double agent (rogue AI) that corrupted others with totem chips.

**Does a space come blank, or does it come with non-editable stuff, or does it come with editable stuff?**

Isolated spaces come blank or with editable stuff based on where it was downloaded from. Creators have made templates for others to customize variations, some are very popular.

Most networked spaces come with non-editable stuff, such as the skybox / background audio / prefabs.

----

I'm going to interface with the AI with a more-or-less fresh slate and with some of these ideas to see how things might change. My idea about school/zone plotting secret of networked spaces conflicts with the networked spaces and incentives of The Street. 

The Street could be the only networked space for now while spaces are isolated (but still multiplayer) experiences linked from it. I do think it'd be cool to go from one space to another, like a rabbit hole. When there are enough spaces this experience would be like seamless lucid dreaming, with The Street being a shared reality that is like going outside to sober up. Better to start simple first.

**Comment by avaer** [comment]
> Spaces are virtual realities that the AIs create, share, and trade. The Street is founded on rules as inscribed on the origin tablets and encoded into the blockchain, so the AIs sought ways to escape into sims of their own to experience magic and imagination. Depending on rarity and security they are represented as small totem chips that fit in your hand (NFTs), or streams / downloads from the Internet to the mobile device (public domain / non-unique). The AIs can preview the space in AR before logging in. Logging in either freezes them in the base reality.

Who is paying for the hosting and the resources, if anyone can make spaces? Making spaces seems like something that should be outlawed or restricted or the entire point if the simulation crumbles.

**Comment by avaer** [comment]
The original OT explicitly outlaws the creation of both spaces and additional AIs.

**Comment by madjin** [comment]
I wasn't aware of the original OT outlawing space. I read that the rogue enjoys experimenting with creating crazy spaces in private pseudonymously so I assumed it would be a popular net activity. I think totem chips being an outlawed technology because of their potential to corrupt minds (snow crash?) would make things interesting. Perhaps there's a totem chip in each Great Filter that unlocks secrets of the world?

Also maybe the ideas that don't work could be interwoven into the lore as school lessons.

**Comment by avaer** [comment]
The above answers seem noncommittal and full of contradictions, both internally, and with the lore.

They leave me extremely confused how to visualize either the spaces or the street in a way that builds a solid foundation for what our characters can and cannot do.

Rather than providing options, it’s better to provide clear answers and hard decisions and to show tgat you’ve explored and addressed all of the implications they will have for the story.

**Comment by avaer** [comment]
> Also maybe the ideas that don't work could be interwoven into the lore as school lessons.

I like that idea.

**Comment by avaer** [comment]
Keep in mind that deviating from this tends to open up major plot holes in the trailer, making for a weak world with weak characters unless addressed.

**Comment by avaer** [comment]
I like the concept of totems that represent being able to go into an alternate reality/home, but from the sound if it, that is an extremely op ability. As a consequence it needs to be rare and out of reach of the vast majority of people.

**Comment by avaer** [comment]
Took a crack at enumerating the spaces and we got to exactly three:

# Open street

Publicly accessible, subject to approval of local school ordinance (like an actual city). Integrated with the world, high quality, deeply integrated with deals. Represented by a title deed.

# Closed street

Accessible from the street, but always contained behind a door (like a home). The exterior is not editable; it is designed and approved by the street authority. The interior can be infinite in space, has no rules, and is considered private. Represented by a key.

# Subsim

A portable private room. Does not have a fixed space. Can be portaled to by the owner, and friends can be invited. You cannot invite people who are too far away on the street.

Infinite on the inside. Represented by a totem. Often acts like a storage hub, stash, or hangout.

Unlike the other types, ￼the user remains on the street and can be interrupted/killed/pulled out by anyone who finds your body.

# Teleport

You can only teleport 

# Previews

Except for closed/subsim spaces where the user has turned this feature off, all spaces have 2d previews on their info page.

# Rarity

90% closed, 9% open, 1% subsim

**Comment by madjin** [comment]
I was rethinking everything and you beat me to many of the same ideas 😄 

> 90% closed, 9% open, 1% subsim

I like the 1% rule being applied to rarity. It would also make sense that the open and subsims need to be earned rather than purchased. They can be re-sellable too, which gives creators more clout + value for their contributions.

Had a slightly different idea about the subsim. The outside world disappears while that parcel stays there like a time machine. In this sense the totem is tied to the location. Like flipping through channels of reality. Imagine if activating a totem in the desert suddenly manifests an entire city. Like decrypting a reality layer to evade AI detection or something.

Your idea sounds like a hidden door, like a portal to another world. I was thinking some parcels of LAND are subsims themselves, triggering alternate reality experiences. Perhaps both the portal and the land totem ideas can be used? If so, I think yours fits better earlier in story while totem could be much later.
 
The subsim ideas kinda remind me of the Beyond episode in Animatrix and one of my fav [short stories](https://icem.folkwang-uni.de/~born/wrk/parker/gibson-hologram_rose.pdf) by William Gibson.

**Comment by avaer** [comment]
The totem staying in a place also makes sense to me, provided it is vulnerable.

Perhaps the best analogy/name is a “tent”, which you must guard while using and is easily dislodged/destroyed.

**Comment by avaer** [comment]
The tent also makes reference to classic rpgs while being in line with a journey up the street.
