### ISSUE TITLE
Generate avatar previews

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1371]
Cryptopunks have a good avatar pose that signals membership:

![image](https://user-images.githubusercontent.com/6926057/125419710-ff1a4652-6e6a-4d8d-a777-3005f13610a9.png)

We already generate VRM previews, and we can apply poses to them. Therefore it shouldn't be hard to generate a new endpoint that will give cryptopunk-style previews.

On top of posing the avatar correctly (looking to the side), we should generate a shader plane for the background of this screenshot, keyed by the "id" (NFT token id, or URL), and then put through a hash function (like `alea`, which we use) to select the generation offset (seed) for the shader to use.

Here is the raw shader:

https://www.shadertoy.com/view/ftsSR2

And here are some of the symbols it renders so it is clearer how it works:

![image](https://user-images.githubusercontent.com/6926057/125420615-40d9a6a4-8fa6-4a64-a249-6583e256592d.png)

https://svgshare.com/s/Z6p

**Comment by avaer** [comment]
Here is the shader for it:

https://www.shadertoy.com/view/ftsSR2

**Comment by avaer** [comment]
Here are some ways it can look like:

![image](https://user-images.githubusercontent.com/6926057/125422658-752b6105-76c4-4ab8-a4ff-6a189325e26b.png)
![image](https://user-images.githubusercontent.com/6926057/125422832-eeadfe62-0ed8-4a0a-aeaf-edd1a7d1dfb7.png)

**Comment by madjin** [comment]
To better understand the pose / angle of the headshot here's a couple other avatar projects for inspiration that are higher resolution than punks.
![image](https://user-images.githubusercontent.com/32600939/125484687-fd9987f6-babb-46be-a64a-0054c8833f4d.png)
![image](https://user-images.githubusercontent.com/32600939/125484613-aa425db6-35d6-4c8c-9fc7-982bca168d0b.png)

Made a couple headshot poses to get an understanding, its also better when the eyes don't always face towards you
![image](https://user-images.githubusercontent.com/32600939/125485047-26e5e151-9f87-4d23-b75d-4213d2a5d304.png)

**Comment by Vianvolaeus** [comment]
The bottom headshots are great. I think we should avoid both direct camera facing as mentioned and any kind of default rigging pose eg: t-pose / a-pose.

I think it's worth trying to generate a preview that's good enough that you'd want to use it on social media as a profile picture. That *is* a layer of identity transfer for digital characters / avatars that's very well documented as being desirable. 

Note: VRoid Hub (or Studio?) *forces* you to provide a headshot and bodyshot before you can fully publish a character, and has a little camera suite to do so. 
I think there's lessons to be learnt there in terms of avatar display (and potentially a marketplace), some of which we've implemented to a degree already in the FE (non-static previews, posing)

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/125541748-cb118489-1f3b-446a-acf4-d3c59b065f6b.png)

VRoid Studio's has gradually become quite feature rich over time, with custom poses, preset animations, facial posing etc, and is generally quite user friendly and fun to use. It won't let you upload to Hub until you take these photos.

**Comment by Vianvolaeus** [comment]
Characters with an animation when you press like on them! This is a pretty nice feature. 
![image](https://user-images.githubusercontent.com/80061436/125541980-820e72bb-adac-48b5-8aff-6ce2b1b3961b.png)

**Comment by avaer** [comment]
> I think there's lessons to be learnt there in terms of avatar display (and potentially a marketplace), some of which we've implemented to a degree already in the FE (non-static previews, posing)

Though that would be a different feature from the socials avatar mode. Part of this feature is that it is standardized, and you are not choosing it, you are only choosing the avatar.

Nothing is preventing an actual photo booth from existing, but the output of that would serve a different purpose, not linking avatars together using social media.

**Comment by Vianvolaeus** [comment]
Bringing in some previews from @avaer that were posted in the discord.

I think the first is great, as evidenced by the pure black hair on top of it, it looks like it works fine even with very dark colors on top of it.

![image](https://user-images.githubusercontent.com/80061436/126175408-86c504c0-5dee-4d1d-aca5-72dfeb564951.png)
![image](https://user-images.githubusercontent.com/80061436/126175417-dda98d86-13d0-4f0e-ac90-b93b5c4752b7.png)

**Comment by avaer** [comment]
Toon shader:

![image](https://user-images.githubusercontent.com/6926057/126210796-91acd94d-2bf1-41d7-9c80-58a90dbd79ec.png)

**Comment by avaer** [comment]
I will also try my "challenger" outline + background gradients.

**Comment by madjin** [comment]
Lore drop preview

```
Name: Annette Falsworth
Username: Ex0naut
Class: Booster
Favorite weapon: pistol
Description: A drop hunter, who is really good at her job.
Style: Professional, usually wearing a business suit and a tie
Homespace: A large office with a big window overlooking the city. It is filled with papers and binders.
Activities: Managing Scillia's schedule, keeping track of her inventory, finding loot for her
Favorite food: fish and chips
Favorite time of day: Winter, so she can wear her new coat
Likes: Keeping busy, working out, routine, logic, following the rules
Dislikes: Losing her loot, being wrong, being bad at her job
```

**Comment by madjin** [comment]
Ideas about ID NFTs:

- On-demand
- Open edition
- Batch minting
- Pre minted?
- Does it include names?
  - Can names be changed?
- Does it include avatars?
  - Can avatars be changed?

Town NPCs people can own and sometimes wear / control. The future would be embodied AIs behaving on their own that are intelligent on their own.

In virtual world, see someone, there's already a premade story you can see using the AR popups.
