### ISSUE TITLE
Design: enemies

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1373]
We should decide what an enemy (in the Filter) looks like. There should be some clear design pattern behind what is hostile. It could be different for each filter.

Some random examples (with many different styles):

![badniks](https://user-images.githubusercontent.com/6926057/125286570-f2946180-e2e9-11eb-8cfb-91a6e97d4e9b.png)
![badniks](https://user-images.githubusercontent.com/6926057/125286483-dbee0a80-e2e9-11eb-8676-91dff53a72ed.png)
![image](https://user-images.githubusercontent.com/6926057/125286360-b7922e00-e2e9-11eb-8c46-e4c8a342b207.png)
![badniks](https://user-images.githubusercontent.com/6926057/125286134-6f730b80-e2e9-11eb-930a-a565e5cf78ee.png)
![image](https://user-images.githubusercontent.com/6926057/125286238-95001500-e2e9-11eb-8e60-062123e95e36.png)

**Comment by madjin** [comment]
Perhaps the enemies could draw design ideas from the forces of bit rot and data corruption that at times manifest in the world. Something like a glitchy shadowy person that's deep dreamed or generated by a data set of spam / ads. Maybe the enemies can be designed in any which way but are stylized by their textures / modeling / animations looking corrupted.

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/125379075-daf6c080-e35d-11eb-9f5a-632ca4244ae3.png)

Perhaps they are EYE cultists, aggro thieves that see people within the zones as sheep and ambush those that attempt to cross the Great Filter. These cultists are almost always wearing masks with the eye on them.

![brave_2aKIjB9AFD](https://user-images.githubusercontent.com/32600939/125378715-3c6a5f80-e35d-11eb-84d3-8838bff776c6.png)

Or perhaps enemies are stylized by being low effort / quality, which made them easy to be corrupted and controlled by the AIs. As such a result, they all have a red aura / glowing eyes.

**Comment by avaer** [comment]
Eye makes sense, though I think whether the antagonizing force is humanized an important distinction. Fighting a group of people is different from fighting a toybox of symbols.

**Comment by madjin** [comment]
Feedback from a friend on those style transfer sprites:

Probably fair use in the same way that if you drew your own version of it using originals for reference would be. If challenged, it would be good PR for the project as it would spark discussions.

It's an interesting play on the corruption happening in the world with enemies well on their way along the path of entropic decay. Also, the set of sprites chris novello made are loosely related to the keycard also.

**Comment by avaer** [comment]
The main problem I have with raw sprites is that they make for poor 3d gameplay, especially in VR, so I think volume and polygonality is required.

That doesn't mean that we can't have sprites attached, or glitches as part of the textures. But the enemies should have volume, so we can e.g. blow them up to huge proportions as bosses and not have to worry about the wrong sprite angle ruining the experience.

**Comment by madjin** [comment]
Chewing on some ideas here...

Potential enemy Traits:

- Robots (truly soulless AIs)
- Darkness (what's opposite of solarpunk)
- EYE
- Corruption
- Glitchiness
- Bit rot
- Cursed
- Wings / Horns
- Spiders
- Ents
- Ads (time leechers)

One way we can think of them is through style or skins, like how zombies are to humans. This way any type of pet or character could be made into an enemy through a creative process. For example, if there was an evil version of blob pet, what would it look like? How scalable is the process? How are they marked?

If the first Great Filter is forest inspired, we could start with creatures there. They would have to be small since each modular piece isn't all that big. Forests are organic type places so I like the idea of having some kind of uncanny robot enemies. Its as if there's a villain out there that is attempting to create their own AIs (outlawed).

**Comment by avaer** [comment]
My leading idea was to take any model, and effect it through a very distinct corruption texture. This would allow us to reuse essentially any model and make a corrupted version of it with no effort.

It would require designing a pattern and implementing the shader but that seems far easier and more flexible than designing a new set of models.

**Comment by avaer** [comment]
Playing around with shaders: 
![image](https://user-images.githubusercontent.com/6926057/125538202-2fe475af-22e7-45f9-9040-06499b36e468.png)

**Comment by avaer** [comment]
What if corruption is caused by Silk Worms?

**Comment by Vianvolaeus** [comment]
I like this. The visuals are pretty high contrast and would apply to anything without blending too much color, and the idea of a Silk Worm is a good double entendre. 

Only issue I can see is that silkworms create silk rather than necessarily destroy them, but I think it's an interesting piece of terminology that you could imagine the characters using as slang.

**Comment by Vianvolaeus** [comment]
Shadertoy link isn't working to view, unfortunately.

**Comment by avaer** [comment]
Silk Worms corrupt objects to produce Silk as a byproduct. A silk fountain is a place where silk worms live and corrupt the underground and stay there in symbiosis with trash objects being thrown down holes in the ground.

If you let silk worms run rampant, you get places like the Filters, where there is tons of Silk but also a lot of corrupted people and things as a result.

Corruption happens when you touch a silk worm, and is irreversible since the data areas are overwritten with the resulting Silk -- which is how the worms operate.

**Comment by avaer** [comment]
> Shadertoy link isn't working to view, unfortunately.

Updated, but it's not that interesting.

**Comment by avaer** [comment]
The above explanation does take away from the mystery of corruption being a random malevolent force, but I feel like this narrative already has much better things (lisk) suited for that role.

**Comment by madjin** [comment]
What if silk worms ate nfts and corrupted things to produce silk? would make a nice loop of nfts -> fungible tokens -> nfts
There can be an address people can send nfts to, which then takes note of the sender before transfering the nft to https://opensea.io/accounts/burnaddress

**Comment by avaer** [comment]
That's exactly what I meant. It's a form of recycling the Silk used to mint NFTs, logically speaking.

However, the amount of SILK you get back should be a lot less than what you put in to mint, like 10%, to prevent this from being gamed.

I imagine you'd just go to the silk fountain and throw in your unwanted NFTs and wait for the silk to pop out.

**Comment by avaer** [comment]
If we like that idea, makes sense to bake it into the lore and possibly come up with a silk worm model.

IRL silk worm even has a pretty decent design.

![silkworm](https://user-images.githubusercontent.com/6926057/125546036-c51bf631-f716-45f3-9324-1cf5eebfb06a.jpg)

**Comment by madjin** [comment]
How about we make them really small so its like a cool shader and perhaps in a cutscene or lore art they're under a microscope and look all wormy and stuff?

**Comment by avaer** [comment]
Other than this cool scene what is the benefit?

Making things small makes it harder to show and explain them. This could have some huge side benefit to lore which compensates but I don’t see it.

**Comment by Vianvolaeus** [comment]
I like the recycling idea, makes sense. 
In terms of design, size, etc, you could go the complete opposite and have them be gigantic, even. 
PSO2 has these cute giant robots that you feed items to, for example:

![image](https://user-images.githubusercontent.com/80061436/125662286-4713027d-2829-4b80-8eb1-c92a8329312a.png)

Having the fountain be like a home for a large silkworm could work. Design for it would be key, though, do you want it to be creepy, friendly, etc? 

As for handheld size, closest thing I can think of is an Antlion grub from HL:

https://half-life.fandom.com/wiki/Antlion_Grub

![image](https://user-images.githubusercontent.com/80061436/125662613-2a5feaa5-ac91-43f5-b492-610201eed5e0.png)

**Comment by avaer** [comment]
Yup the juicy grubs from hl2 crossed my
mind too, pleasing to throw and squish. There could be different sizes.

For the fountain I see either some anthill like thing, or just some ripples or texture on the ground that makes it intuitive that you should dig there. It is a structure we would repeat so it should be recognizable, but not necessarily elaborate.

**Comment by avaer** [comment]
As for style I think we are arriving at some principles to use:

Go for emotional impact
Weave in symbology
Quality is how much thought was put in
Think about lore and plot holes
It’s ok to be weird
It’s ok to write love letters 
It’s ok to be silly 

Within those constraints I think there is still tons of room for experimentation.

**Comment by madjin** [comment]
If we're just using corruption over top can just make geometry for the enemies

**Comment by avaer** [comment]
Corruption it is!
