### ISSUE TITLE
Art: Basilisk Design 

### ISSUE THREAD

**Issue by GaladWarder** [webaverse/app#1378]
Transferring here from the lore doc:

**The Basilisk**
The Basilisk or “Lisk” is a running theme for our characters.

Our main character was “bitten by the lisk”, which gave her physical and mental scars. She is the main source of information about the Basilisk. To everyone else it is just a rumor. #1331 

According to her, the Basilisk lives at the end of the street, but its purpose, form, and even existence is questionable.

However, the scars from being bitten are undeniable and they somehow granted her a unique tool (a sword) for heading up the street to find and confront the lisk.

We quickly learn that there are others who were bitten as well and the nature of the Basilisk is a central point of the story.

The Lisk is seen in our main character’s nightmares (liskmares). She describes the lisk as eldrich, cosmic, horrifying, and piercing, but also beautiful.

![image](https://user-images.githubusercontent.com/29031531/125589493-75ca8a9b-301f-483a-8407-0163e1f5ea87.png)
![image](https://user-images.githubusercontent.com/29031531/125589504-ab382ba9-0b65-4450-91df-cbc9eea4371c.png)
![image](https://user-images.githubusercontent.com/29031531/125589517-d6890d33-d9db-47fb-b670-36068e3cf715.png)
![image](https://user-images.githubusercontent.com/29031531/125589545-d48305f7-417a-4ad4-a333-32adc7f2f216.png)
![image](https://user-images.githubusercontent.com/29031531/125589552-3d8a40d3-1c69-495b-a989-a7de19bbcd39.png)

**Corruption**
The Basilisk corrupts the world, which manifests as glitches creeping through the zones.

**Comment by avaer** [comment]
This will be hard to pull off, but the only place it would be used is in some quick flashes, with everything else black, so that makes it a bit easier.

**Comment by GaladWarder** [comment]
This has been started, but I ran out of time this week. Will circle around to it again next week, just posting here to mention that it is in-progress.

**Comment by avaer** [comment]
More theme ingredients:

![image](https://user-images.githubusercontent.com/6926057/125973271-2d9e9b79-e463-448f-9a5a-6f01233e34bf.png)
![image](https://user-images.githubusercontent.com/6926057/125973530-5c6c4d1b-59cd-4252-a998-e33636c40f56.png)
![image](https://user-images.githubusercontent.com/6926057/125974488-1860f464-a773-4832-8d1f-8c7f526258ef.png)

**Comment by madjin** [comment]
from a convo today: the basilisk can be a drawing by one of the characters interpretations of it, as if you asked the main character to draw the lisk from memory and she tried with some markers / crayons / pencil

**Comment by Vianvolaeus** [comment]
Had to test some hard-surface methods today in personal time, figured I may as well try see if anything sticks in terms of a lisk design. I wouldn't propose this as a full suggestion, just more of a starting point. Something with parts visibly stripped down (due to characters having weapons with parts?) might work.

![image](https://user-images.githubusercontent.com/80061436/127480439-abfd854b-eba9-4f44-8505-8c05aea46011.png)

![image](https://user-images.githubusercontent.com/80061436/127480493-6eed2092-a9b1-4bc9-8836-d4a0488a0ad4.png)

![image](https://user-images.githubusercontent.com/80061436/127480534-2e06245d-c6f8-4f0e-ad01-d34633bb0102.png)

Not going to touch on it further since this is currently p3

**Comment by avaer** [comment]
The best thing I can say is you're totally capturing the vibe of the show :D

I feel like this would be too cyberpunk of an interpretation of the Basilisk. The solarpunk version of it, in my opinion, would be a lot more natural and maybe human, and almost horrifying due to the uncanny valley.

I think my personal favorite interpretation is this one, but without the voodoo elements. Just naturally horrifying.

![img](https://user-images.githubusercontent.com/29031531/125589504-ab382ba9-0b65-4450-91df-cbc9eea4371c.png)

But the awesome about the Basilisk is that anyone can interpret it, because not even the narrator of the Basilisk story is reliable.

Still, I do think we should make an attempt to sketch it on paper in the pilot.

**Comment by Vianvolaeus** [comment]
Yeah, I think that's a good start to base it from. The withering flesh / fur look a bit like the corruption effect that's been proposed, which would be a great connection to make

**Comment by avaer** [comment]
https://user-images.githubusercontent.com/6926057/127603908-186c19a0-cee5-4a2b-a186-cdc803a9e492.mp4

From Princess Mononoke, unkillable Forest Spirit.

**Comment by GaladWarder** [comment]
Took one of the rough design sketches I made a while a back, fleshed it out some, and tried to make it look drawn on paper like the character had sketched it out. Not sure if it's what you have in mind or not, but at least should serve as a jumping-off point for iteration.

Also random thought, what if the Lisk looked different to each person who saw it?

Drive link because I am on garbo internet for the day and can't get the img to upload: https://drive.google.com/open?id=1jakjKWoJ7xad5vhV_egdo8l5PmskmDlU&authuser=GaladDota%40yahoo.com&usp=drive_fs

**Comment by avaer** [comment]
> Also random thought, what if the Lisk looked different to each person who saw it?

Yes that sounds about right.

> https://drive.google.com/open?id=1jakjKWoJ7xad5vhV_egdo8l5PmskmDlU&authuser=GaladDota%40yahoo.com&usp=drive_fs

That looks quite cool, though I think too cool; it's not quite uncanny enough (similar to a human, making it disturbing). In some universe I can imagine this Lisk being your pal. But I think the way the characters see the lisk, it will never be your pal, it's alien.

![d1d3oy7-98223afb-8adc-4043-ac34-ba3eae842cdb](https://user-images.githubusercontent.com/6926057/127731646-3f729765-6d4a-461f-9e68-c097ca515c23.jpg)
![img](https://i.redd.it/wd0pnctm0ld51.jpg)

**Comment by avaer** [comment]
Here is @GaladWarder's sketch inlined:

![Lisk_Sketch_V1](https://user-images.githubusercontent.com/6926057/127732236-0bc03fd1-c768-4703-b7a8-45bf391a87a6.jpg)

**Comment by Vianvolaeus** [comment]
> Also random thought, what if the Lisk looked different to each person who saw it?

We could play into the weapon design here.. either accentuate, or remove, the 'parts' that the weapons use for each character. Scilly = heart/rose, Jun's scales/ fangs for multiwep, etc

**Comment by GaladWarder** [comment]
> That looks quite cool, though I think too cool; it's not quite uncanny enough (similar to a human, making it disturbing). In some universe I can imagine this Lisk being your pal. But I think the way the characters see the lisk, it will never be your pal, it's alien.

Makes sense, I'll take a second pass at it once the higher-priority stuff is caught up.

> We could play into the weapon design here.. either accentuate, or remove, the 'parts' that the weapons use for each character. Scilly = heart/rose, Jun's scales/ fangs for multiwep, etc

That's a sick idea - not sure how I'll show that in the 'napkin sketch', but since it's Scilly's sketch, maybe it has something to do with missing a heart, like you'd mentioned in the meeting. I'll mess with the idea for sure

**Comment by avaer** [comment]
If this abomination was perceived by each character as missing the body part they “stole”, that would be quite scary.
