### ISSUE TITLE
Design: corruption

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1379]
Took a swing at it, I think it works fine as a design (with world and charas).

![image](https://user-images.githubusercontent.com/6926057/125611786-2015c205-5ee1-4f89-8eb5-7011391f290c.png)

Youtube clips:
https://www.youtube.com/watch?v=hPJpEUu0SFY
https://www.youtube.com/watch?v=ngb7eDf6saw

**Comment by avaer** [comment]
Related: https://github.com/webaverse/app/issues/1373

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/125612668-1d879fe3-44e1-4fdf-bcbd-a201c639f7d2.png)
![image](https://user-images.githubusercontent.com/6926057/125612886-ce5bfb83-a05a-406d-b9dc-de64a6f59609.png)

**Comment by Vianvolaeus** [comment]
I think it does! only thing I would say is it's not immediately obvious that it's *silkworms* per se, if that's still what we're going for, but it definitely reads as corruption.

**Comment by avaer** [comment]
I can tone down the vertex shading or remove it and go more for a dynamic fragment.

This pattern itself IMO looks like something wormed itself through, but it is hard to tell if there is too much noise.

**Comment by Vianvolaeus** [comment]
I'm wondering if rather than noise it should be following a singular direction (even if that changes as part of the animation)

A lot of glitch art follows this principle of following the shape but destroying it in a single direction (intentional or otherwise). 

I think it'd break the shapes less, but be more readable as to what it is that's corrupted. 

Let me get an example for a character in Blender.

**Comment by Vianvolaeus** [comment]
Here is a vertex displacement on the entire model vs effecting a set vertex group:

![image](https://user-images.githubusercontent.com/80061436/125784017-a62a4d20-7976-4478-9823-bc430aed9083.png)

I'm not sure how you'd go about doing this in engine, unless you could assign it on a per model basis, perhaps?

If you can read a vertex group from a model and apply the corruption effect to that, we could add this group in as part of the art pipeline. Could be a much simpler way I'm not aware of 😄

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/125784273-cdd5d57b-92f3-4a1b-a785-6cce4173f6c3.png)
Here's another, set only to displace on the X axis.

**Comment by Vianvolaeus** [comment]
Here's an example with the following:
Corruption texture applied, simple diffuse only shader
Texture coordinates panned
Displacement only on X. 
https://user-images.githubusercontent.com/80061436/125786008-abd051e0-74b9-4bfd-a04e-53d9a9d3b08e.mp4

**Comment by avaer** [comment]
These are all good ideas to try, but hard to visualize until there are MRR completed scenes to see how it fits with everything else, especially animated charas.

I do like the singular direction offset idea but the current is just to not offset the vertices at all.

**Comment by GaladWarder** [comment]
I was messing with some Blender stuff today for the hero images and came across this - it's a particle system with the seed driven by the frame number. Not sure if the effect could be recreated in-engine, but I thought it gave a really cool effect potentially for the corruption since it's sort of stylized motion.

![Corruption](https://user-images.githubusercontent.com/29031531/131785778-793caa3a-355e-4074-af2c-b3f62ee7e495.gif)

May be totally useless, but figured it was worth uploading.

**Comment by avaer** [comment]
Cool design, better than mine. If you have some sort of code reference I could see about converting it to a shader.

**Comment by Vianvolaeus** [comment]
Maybe some kind of noise driven vertex displacement & alpha scroll could so
something like this, only thing I can think of off the top of my head

**Comment by GaladWarder** [comment]
> Cool design, better than mine. If you have some sort of code reference I could see about converting it to a shader.

I don't have a code reference, but can upload the blend file if that would be helpful. It's a node setup with geometry nodes generating stylized strokes on the mesh, the seed is driven by the frame number.

I was just using it to see if I could get a painterly feel out of this, it's a node group I found from a 3D guy I follow that I was messing around with.

**Comment by GaladWarder** [comment]
Here's the Blend. I know none of this carries over to the shader, but it may be useful to ref if you plan to convert it

https://drive.google.com/file/d/1ziSKjbfIGwCS-eOm3NAn_-aD8FbzrLZ6/view?usp=sharing
