### ISSUE TITLE
Idea: avatar referencing chat commands / emoting

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1381]
This will make a bit more sense when I can get some references, but a system like PSO2 cut-in display might work really well both in app and for storytelling. It's basically a chat command that can display a comic / anime style cut in of your character.

There's also flair for chat bubbles, etc. Depends on chat system / emote system. 
It is quite fun, especially for those with accessibility limits / mute, etc. 

https://ohpso2.fandom.com/wiki/Chat_Commands#Cut-in_Display

I know this isn't important, but wanted to file it just in case. 

![image](https://user-images.githubusercontent.com/80061436/126209238-362a94be-c7a6-427d-9940-753b7c0b72da.png)

![image](https://user-images.githubusercontent.com/80061436/126209253-153df6bb-7993-4c9b-8a94-f623fb6d7d85.png)

I'll get a better preview of the system when I have a spare few minutes.

**Comment by avaer** [comment]
I briefly played with this in a phone call like system (though I don't have any shots of it). But it seems we're on the same page about the utility of these.

I didn't know about the extra blams on the side for emotion, that is also a very cool idea.

**Comment by Vianvolaeus** [comment]
This is a brief visual example of what they can do. I believe these are intended to be used with some kind of auto-chat feature for the most part, in which the character will automatically do preset things like this based on things like HP%, out of magic, etc


https://user-images.githubusercontent.com/80061436/126802678-39f1d3b7-2c23-4908-9281-1f4264d35c1f.mp4
