### ISSUE TITLE
Art: Gardening asset kit

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1385]
This is mainly for the WFC city https://github.com/webaverse/app/issues/1365

![image](https://user-images.githubusercontent.com/32600939/126331760-ef2feb02-6462-4fcf-8944-78446cfbf712.png)

**Inspiration**

- https://www.pinterest.com/pin/62628251055851421/
- https://www.pinterest.com/search/pins/?q=solarpunk%20interior&rs=typed&term_meta[]=solarpunk%7Ctyped&term_meta[]=interior%7Ctyped
- https://www.youtube.com/watch?v=MS-sJQkr0H4 (chobani commercial)

![image](https://user-images.githubusercontent.com/32600939/126404366-1c7cc8ea-aa9e-4983-8516-16db780641e2.png)

**List**
- potted plants (many various sizes)
- hanging plants
- garden boxes
- bonsai trees
- tables and chairs (long / circle table)
- vertical farm

**Comment by avaer** [comment]
- bookshelves

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/126493859-14d93bdd-e871-48ae-9d57-7a0905838838.png)

progress made today

**Comment by avaer** [comment]
I think these are good sign styles to make (though not exactly that text -- it could use our fractal text, smoothed, or something else):

![image](https://user-images.githubusercontent.com/6926057/126515173-dda78908-a8f2-4e65-ba69-77c7dc6eb89c.png)
![image](https://user-images.githubusercontent.com/6926057/126515248-3a57db34-da8e-4446-96d5-283da1aba899.png)

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/126650734-24cfa95d-b46a-4ed2-b261-f39eefe951f5.png)

Progress on the garden kit, some vertical farms being made

**Comment by madjin** [comment]
Dreamco working on UV maps
![image](https://user-images.githubusercontent.com/32600939/126797667-9aa49149-83c8-4248-a82e-1e9b2fb7ce7a.png)

Think the kit could use some hanging plants also
![Screenshot at 2021-07-23 10-33-17](https://user-images.githubusercontent.com/32600939/126797683-ba1f61f0-9744-4aac-a782-46092776282d.png)

**Comment by madjin** [comment]
Update
![image](https://user-images.githubusercontent.com/32600939/127034930-b91d9b61-5763-4340-9cac-7350df816661.png)

**Comment by madjin** [comment]
update:
![image](https://user-images.githubusercontent.com/32600939/127375012-066afe28-83b4-46c5-854c-f512f5e706c5.png)
![image](https://user-images.githubusercontent.com/32600939/127375021-20d14470-5977-4119-834d-9d59d610e51b.png)
![image](https://user-images.githubusercontent.com/32600939/127375031-6fec86c7-ab37-410d-9971-cc9295049395.png)

**Comment by madjin** [comment]
texturing work done 
![image](https://user-images.githubusercontent.com/32600939/127509171-e2688c07-94cb-4625-aa0f-6c413a593943.png)

**Comment by madjin** [comment]
Finished textures:

![image](https://user-images.githubusercontent.com/32600939/128740804-96b8db6f-997a-4b7f-a087-261ab03be619.png)

**Comment by madjin** [comment]
exported, now testing 
![image](https://user-images.githubusercontent.com/32600939/128890935-fa718f4a-7e5b-40a8-82ff-c30981ad587d.png)
