### ISSUE TITLE
Art: holographic fish w/ swim anim

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1389]
Not sure what these are required for or how important, but we need a holographic fish with a swim / wiggle animation.

Below were the quick concepts made already:

![image](https://user-images.githubusercontent.com/80061436/126673682-690267e9-2345-441d-b523-cd66f5ff298d.png)

**Comment by Vianvolaeus** [comment]
Swim animation:

https://user-images.githubusercontent.com/80061436/126679741-9bc8a898-aae2-46cd-8e2d-4d227d0c51a9.mp4

If the vertical isn't needed, I can remove that.

**Comment by Vianvolaeus** [comment]
Animation actions have been split from the main full animation, exported as glb successfully. 

Under Misc. in Drive.

**Comment by avaer** [comment]
Perfect, these are just some decorations I needed for one of the charas home spaces.

**Comment by Vianvolaeus** [comment]
In that case - I should be able to transfer the animations to the other variations, if they're also required for variation in the home space aesthetically.

**Comment by avaer** [comment]
I think we should be able to get away with just the one variation for now.

**Comment by Vianvolaeus** [comment]
I presume this can be marked as complete - I'll move it there.

**Comment by avaer** [comment]
Yes, thank you.

**Comment by Vianvolaeus** [comment]
I presume this one can be closed - it's done, we've previewed it on socials, etc. Closing for now.
