### ISSUE TITLE
[Inventory] Cannot scroll on smaller screens

### ISSUE THREAD

**Issue by avaer** [webaverse/app#139]
<img width="1440" alt="Screen Shot 2020-10-14 at 6 22 42 PM" src="https://user-images.githubusercontent.com/6926057/96051890-75b38480-0e4a-11eb-8cfb-ad3dc99b6298.png">

See right hand side.

**Comment by ChrisEddy** [comment]
https://github.com/webaverse/app/pull/144

**Comment by ChrisEddy** [comment]
finished
