### ISSUE TITLE
Art: Influencer Character ('Hya')

### ISSUE THREAD

**Issue by GaladWarder** [webaverse/app#1390]
Transferring here from the lore doc:

Name: Hyacinth Bubbles (“Hya”)
Class: Pet Whisperer (beastmaster)
Grade: 11
Weapon: Hya Brand Leash (whip/lasso)
Color: Purple

![cLUhUnF](https://user-images.githubusercontent.com/29031531/126674727-6bf823be-0657-4a5d-8185-197e0b432323.png)
![GsxKkeY](https://user-images.githubusercontent.com/29031531/126674736-bf7aa368-a33e-4c21-a0b9-27c77ed0f707.png)
![HGnYFz7](https://user-images.githubusercontent.com/29031531/126674740-2915eafd-04a2-4620-b22e-58fba13b7032.jpeg)
![Kbkv5AQ](https://user-images.githubusercontent.com/29031531/126674746-4a836d62-d7e8-46f8-bf70-e61d56cb2d78.jpeg)
![kjCWKLU](https://user-images.githubusercontent.com/29031531/126674767-1918209f-c13e-465f-9ffb-d578980fa125.png)
![Vl8T9wo](https://user-images.githubusercontent.com/29031531/126674780-370ebf79-1879-4b87-bd31-952e056a702c.jpeg)

![NeOgFS6](https://user-images.githubusercontent.com/29031531/126674808-74dcef87-c5e1-4689-b214-58c7d46a7275.png)
![BW5xom1](https://user-images.githubusercontent.com/29031531/126674824-4fe536db-d742-4ee1-a406-322381aa8fa1.jpeg)
![cAn1UVf](https://user-images.githubusercontent.com/29031531/126674828-5c3d9574-5c96-4bde-8c37-4981b333eddc.jpeg)
![cf0UWvi](https://user-images.githubusercontent.com/29031531/126674834-85db4a20-e5c2-4547-bc7d-15ee85ef22a4.png)
![hDNwFp5](https://user-images.githubusercontent.com/29031531/126674847-1165588d-4aa5-4857-8864-3743f0794fa3.jpeg)

![9cr9v3H](https://user-images.githubusercontent.com/29031531/126674874-779d71cf-e163-48b5-8b46-8876abcf64af.jpeg)
![vz4pgHY](https://user-images.githubusercontent.com/29031531/126674877-ee8e11f1-2a76-4242-995e-3b6f021e094c.jpeg)
![wu6G26j](https://user-images.githubusercontent.com/29031531/126674881-bc5632ad-1d74-428a-8543-c101c99af2ab.png)

Description: An independent artist with a large following on social media. Her thing is that she wants to get a photo with every pet in the street, which she calls the “million pets challenge” to her followers. She is very outgoing, fashionable, popular, and well liked. She is also a major trend setter and fashion/pet designer. A third of the pets in the local zone were made by her and she signs their feet as her trademark.

She is very optimistic but not always rational; she doesn’t really listen when her friends tell her the million pets challenge makes no sense, since people are constantly making new pets and the world might not even be finite.

Her fashion is very vibrant, trendy, floral, natural, and even animalistic. She is the most likely to wear a kigirumi. She isn’t a furry but wouldn’t object to it.

She is the rich but bad with money. She once overbid on a clothes auction because she liked the color, changed her mind and bought another, and then never picked up the items.

Our other characters often point out how wasteful/insulting this behavior is for someone with her following, but she genuinely does want to better the world — by creating+sharing art and experiences people love. She tags the city with art, something people generally accept, because she greatly increases value of real estate with her brand.

Pets naturally flock to her. Her weapon is a whip/lasso/leash which she uses to tame and control an entire flock of pets at once. Although she is physically weak, she is a proficient pet tamer and rider, which gives her unique and varied strengths through her familiars.

She kind of inserts herself into our protagonists quest because she thinks a photo with the basilisk would be the ultimate post. Nobody in the group objects, since it seems win win.

She is secretly unsure if people like her because of her fame, or if she got famous because people like her. The rest of the group are unsure if she is just using them.

Traits: Attractive, Optimistic, Creative, Fashionable, Social, Vain, Wasteful, Kind, Flirty, Materialistic
Motivation: Get the photo with the basilisk
Strength: Communication, Artistic, Social, Romantic
Weakness: Naive, Inconsistent, Selfish, Questionable Values
Growth: She will learn to focus on quality over quantity. She will learn to value her friends and not post everything to social media. She will learn to be more frugal and use her followers to get what she really wants.

**Comment by GaladWarder** [comment]
This is currently in progress, need a few more hours on it tomorrow and will push a bashed rough concept sheet.

**Comment by avaer** [comment]
I actually did not post this yet since I thought it needed tweaking before concepting could start. But if it's already started we might get lucky 😁

**Comment by GaladWarder** [comment]
This is what I came up with for a first pass on the influencer character; didn't end up including the umbrella after all since it looks like Texta is working on it, it doesn't make sense to have two different designs happening asynchronously

![Influencer_V1](https://user-images.githubusercontent.com/29031531/126806444-cb6e2a3b-d42a-48e2-8dfe-7f881ffa6b81.jpg)

**Comment by GaladWarder** [comment]
Request for review on this - I'm getting close to done with the stylesheet and orthos for Ann, and can roll right into Hya if this design is greenlit.

Also, do we still need an umbrella concept sheet as well? I know Texta was working on a rig at one point, not sure what all has been done + no need to redo stuff that's working already

**Comment by madjin** [comment]
Hya pureref: https://cdn.discordapp.com/attachments/641036402829819914/875799790108180500/hya.pur
![hya2](https://user-images.githubusercontent.com/32600939/129400019-bb44c9c8-1a4a-49c8-bc48-1792a35519fb.png)

**Comment by Vianvolaeus** [comment]
Is a base design finalised for this yet? I like the concept a lot (I do wonder how it'd look without the jacket, though). This'll creep up on us soon, would be a good idea to get a design ok'd and some orthos underway when possible.

**Comment by avaer** [comment]
I think it needs another design from Grant, mostly for clothes.

Rather than artsy, I think we should try gamer girl and a punkish t-shirt. I don’t think we need another large jacket. The hat could stay.

Feel fee to take a crack at it, but I’ll try to post Pinterest tomorrow.

**Comment by GaladWarder** [comment]
I am pretty booked out for this week with the hero image and the blog image, but plan to work as regular this weekend - I'll add it to my weekend docket for a V2.

If a pinterest pass happens before that then great, but if not it'll be fine - I have some ideas I can just throw down and go from there!

**Comment by Vianvolaeus** [comment]
Took some reference passing on this today. 
Looking into the more punkish and gamer-girl concepts etc out there, it seems disproportionately sexualised compared to other theming, so rather than a direct approach in that direction, it might be best to twist the original ideas into more of a punky / gamer direction - whether that be *literally* taking the spray paint and spikes to high fashion or not remains to be seen whether it's a good idea 👍

Dropping some gathered images here: 
![image](https://user-images.githubusercontent.com/80061436/133107933-e870e888-a682-4e57-a7de-559d1298bd50.png)
![image](https://user-images.githubusercontent.com/80061436/133108005-30cd6f72-76c0-4d45-a11e-18285ae6bd85.png)
![image](https://user-images.githubusercontent.com/80061436/133108029-61a4bff1-6aec-4c84-9452-dd565dab5146.png)
![image](https://user-images.githubusercontent.com/80061436/133108082-294a09dc-1e28-4f9c-a247-eaecf6fff333.png)

These are some of my favourites from these, even if they're more jacket focused I think there's elements that work really well: 
![image](https://user-images.githubusercontent.com/80061436/133108274-f4e7e2da-4328-48ae-804d-3916753d0f69.png)

**Comment by Vianvolaeus** [comment]
Another source for inspiration and concepting ideas might be to look at digital fashion designers themselves: 
https://www.artstation.com/digitalgarment

**Comment by GaladWarder** [comment]
Yoo, this is sick Vian! These are going to be super useful.

I'll most likely end up doing a pass on this today, unless something comes up during the meeting that has a higher priority. I was planning to do it this past weekend, but wound up spending the whole weekend working on the hero image stuff.

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/133133528-bc471870-93b6-4562-980d-ab9396638df6.png)

Great find, this is the one, we can just do this flavor on top of either Shilo or the Shilo remake.

The context is Hyacinth is an amazing artist and that's her only skill, so all of her clothes are made by her and look cool for no reason -- they are not functional so do not need to make lore sense. She's older and kind of a mentor to Scillia, since Scillia is crazy. She got Scillia into 0xdeadbeef and they share the friendship bracelets. Hyacinth solves problems with charm, diplomacy, art, and pets. Most people would say she is cooler than Scillia so there is a bit of a friendly rivalry.

**Comment by Vianvolaeus** [comment]
Mentions of using the Shilo base to work from. That's available here in .blend format: 
https://drive.google.com/file/d/171XflTWMjzYFkBRmpcYYE4kNXAOyX5Hi/view?usp=sharing

**Comment by avaer** [comment]
Another top pick from existing references, you can see how it's basically the same character archetype.

![](https://user-images.githubusercontent.com/29031531/126674780-370ebf79-1879-4b87-bd31-952e056a702c.jpeg)

**Comment by GaladWarder** [comment]
Took a V2 pass at this; I want to revisit the more 'casual' version on the right and maybe find a middle ground between the two - some RGB/tech but not tons - but out of time for today. Also figured I would get feedback before putting more time in.

![Hya_V2](https://user-images.githubusercontent.com/29031531/133179312-68f2d175-caa0-4d3f-a54a-17ebf862f53f.jpg)

**Comment by avaer** [comment]
Can we soften it? The face is kind of aggressive, and the hair looks a bit similar to the engineer.

My mental model here is a bit like Lindsey Stirling, but for some new metaverse art form rather than violin. Very skilled at the art and will show off, but giving off friendly vibes rather than competitive ones. She isn’t actually a gamer, she just dresses like one since it is a vintage aesthetic (in this future world).

**Comment by avaer** [comment]
The hair could be blond or tinged with a secondary color, like violet. Since we have two darks we can also have two lights and having lighter hair shows more of a link to Scilly.

**Comment by GaladWarder** [comment]
Sure, I'll do a second pass on it today. 

This hair is mostly just a placeholder, I assume we will use the hair currently modelled on the Shilo remake. I can plug it in if needed though!

As far as the Lindsey Stirling vibes, I think I know what you mean - I'll soften it and go a bit less gamer/aggressive and more friendly/open.

Light hair is no problem, too - I'll play with that as well!

**Comment by GaladWarder** [comment]
Just an update - this is in progress but was having some tech issues today. Will upload tomorrow morning for feedback/another round of revision if needed!

**Comment by GaladWarder** [comment]
Alright, honestly struggling with the balance between 'cool' and 'approachable' on this one. Here's what I came up with - I'm not sure that it's working, but want to get feedback before putting more time in.

![Hya_V3](https://user-images.githubusercontent.com/29031531/133697067-517270f3-f250-4ef0-81bd-82148b6a67f7.jpg)

Tried to go away from the aggressive/competitive vibes while still maintaining the cool factor. Also, tried to stay away from too much craziness on the top with jackets/etc. One issue presented by that is that it goes into 'generic' very quickly. Here I'm using the skateboard to break the silhouette, but I'm worried that this is trending too much toward middle-of-the-road anime girl.

The hair on the left is in the value range for pretty bright purple, and on the right is in the range for like a pastel pink or dirty blonde.

**Comment by avaer** [comment]
I think it's treading some of the right waters. This is definitely _a_ character, possibly even a good one, but I agree that for Upstreet it's a bit generic since it's hard to point out a strong defining feature as part of the cast.

Honestly I think we can be much more influenced by the casual Scillia style of dress, and similarly inspired heads ![](https://cdn.discordapp.com/attachments/886249386030555207/888171770589360138/scillav2.png).

We can basically age that up, change the face to look less cute and more trustworthy as a mentor, and switch the aesthetic to more more overtly gamer/artistic and that would probably work. I can do another pinterest pass.

**Comment by avaer** [comment]
The closest IMO is still https://user-images.githubusercontent.com/6926057/133133528-bc471870-93b6-4562-980d-ab9396638df6.png, but we'd need an interpretation of that which isn't _quite_ that cartoony.

**Comment by GaladWarder** [comment]
Do you want me to just try to recreate that ref in a more 'anime' style? That may get us a good starting spot, if it's very close to what you have in mind

**Comment by avaer** [comment]
Sure, that might work. I'll post the Pinterests as I get them so it can add ideas into the mix.

![](https://pbs.twimg.com/media/E6lVHsJVIAA0UYc?format=jpg&name=4096x4096)
Very casual, different from the rest, nod to Scillia, some cool stuff (could have even more cool stuff).

**Comment by avaer** [comment]
Literally "Lindsey Stirling anime".

![](https://i.pinimg.com/564x/a6/0e/4a/a60e4adde159d19009ae2ba868295900.jpg)

**Comment by avaer** [comment]
One thing to note is I think it's important that the characters keep spiky hair rather than strandy hair. That is simply because it takes a lot less skill to draw it.

**Comment by avaer** [comment]
If she wasn't bored there is a seed here ![](https://i.pinimg.com/564x/23/2d/55/232d55f46acf2e1e3a815644eaec6281.jpg).

**Comment by avaer** [comment]
I like what's going on here with the pets and clearly some kind of performance:

![](https://i.pinimg.com/564x/c0/28/d8/c028d82006f2ba5f7b58c30f30686b21.jpg)

**Comment by avaer** [comment]
Serena from Pokemon offers inspiration in clothes and style. She is too young for the role generally but she is aged up decently here.

![](https://i.pinimg.com/564x/9e/de/47/9ede47c0fe2ebec93dc34734e803a3d3.jpg)

**Comment by avaer** [comment]
Good aesthetics:

![](https://i.pinimg.com/564x/a3/ec/fe/a3ecfe9ce6d8fd2c39a2b16102e9ae10.jpg)

**Comment by avaer** [comment]
Cool and casual, knows what's up, you go to her for advice. She is going places.

Slightly not artsy enough but the shirt is really cool.

![](https://i.pinimg.com/564x/eb/1b/62/eb1b62d3dc3646332b3f613dd8559d2a.jpg)

**Comment by GaladWarder** [comment]
Alright, I started with just getting a sort of 'style port' of that one ref, since it seems to be very close to the look we're going for. Brought it into the bashed style we've been working with and adjusted to be less cartoony.

I also went with spikier hair as suggested, trending away from Jun's hairstyle. I think a short spiky bob could actually look really good and fit the character well. Current value range is for a rich pastel-y purple.

![Hya-V4](https://user-images.githubusercontent.com/29031531/133867289-48a64d89-8fb7-47ae-87a8-f234e53aebd5.jpg)

I'm in process of making some changes to the V1 as well, I was looking back over the feedback and saw that the main comments were on the angularity/sharpness of the face and hair, and the attitude. I think there's some stuff there that can easily carry over to a more friendly/open look.

**Comment by NotFuji** [comment]
![hyacinth_v1_sm](https://user-images.githubusercontent.com/38316883/134224246-dfff1390-2cd9-4fb5-bfc4-78418443f4a1.png)
![hyacinth_v2](https://user-images.githubusercontent.com/38316883/134224248-81ea82e2-01e3-439a-b820-c61bb7b164c2.png)

Latest manga-style concepts

**Comment by Vianvolaeus** [comment]
Are we close to a final design decision on this? I think there's elements of everything here that could work. The pinned up hair is great, I think, and I like the clothing on the e-catgirl as well.

**Comment by avaer** [comment]
Yup, I think the last concept is great, we can just implement it as is.

**Comment by GaladWarder** [comment]
These are so slick, Fuji! 

Vian, do you need orthos for these, or are you good to model them as-is?

**Comment by Vianvolaeus** [comment]
Quietly confident I'll be okay without, but it might be something we will want / need in future for consistency across the concept art anyway, since those were planned to be marketed / sold as well. 

Design's great!

**Comment by Vianvolaeus** [comment]
work towards the outfit today - also started reconfig on the base, and remaking hair, but they're both still WIP 
![image](https://user-images.githubusercontent.com/80061436/134722077-5fca77d0-0a3a-4a51-9155-649a73920333.png)

**Comment by avaer** [comment]
Yeah I think this coat is supposed to be very straight, without many crinkles, similar in theory to scilllia.

**Comment by Vianvolaeus** [comment]
Some clarification on the hairstyle would be good - I'm not sure whether there's a layer of loose hair on top of the pinned back bun, or it's just perspective making it difficult. I'd personally pin it all back and have the front bangs only, but not sure what it's supposed to be. Having a layer of loose hair on top of it being pinned back seems kind of strange: 

![image](https://user-images.githubusercontent.com/80061436/137539142-64377a57-6781-4811-954a-6620f7fe7d65.png)
