### ISSUE TITLE
Fe: Front page web design (discord bot)

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1391]
# Discord bot Frontpage

The current site that explains the Discord bot doesn't do a good job of explaining the usefulness of the bot: https://webaverse.com/discordbot

Based on some research, most Discord bot websites are same colored as Discord and explain the utility right away with actual screenshots. I put together some quick initial mockups, there needs to be more revisions done.

![image](https://user-images.githubusercontent.com/32600939/126708932-6b8c0fba-9930-449f-9ad5-84b93d73a4e9.png)

![image](https://user-images.githubusercontent.com/32600939/126709072-0eff48c4-2306-4c76-b767-3ba5a064cf26.png)

## Inspiration

- https://tatsu.gg/
- https://tacoshack.dev/
- https://mee6.xyz/
- https://carl.gg/

![Screenshot_2021-05-26 Tatsu Your Community Engagement Platform](https://user-images.githubusercontent.com/32600939/126707965-337bcca8-da72-4c51-a5a5-9dce0212ed6b.png)

I've scraped ideas together on Miro. Could go over this with other builders to improve the mockup designs.

![image](https://user-images.githubusercontent.com/32600939/126708200-592f270c-2c56-455d-bf17-febe7d7dbedf.png)

**Comment by madjin** [comment]
progress shot from a builder!
![image](https://user-images.githubusercontent.com/32600939/127589904-bd3398e9-93e7-492f-a6f8-ad9f2f0c31f5.png)

**Comment by madjin** [comment]
Update: Images have been added in
![image](https://user-images.githubusercontent.com/32600939/127714017-74280627-9f1c-4c58-9d5d-664ef3b2ce51.png)

Going to think of new text to update with

**Comment by devnjade** [comment]
Live Link

https://webaverse-web.vercel.app/discordbot

**Comment by madjin** [comment]
Text changes:

Boost your Discord community
Build a meme economy in your server with a CLI to Web3

There's no initial wallet setup required, everyone in the server will have an Ethereum address generated for them.

Mint anything from images, 3D models, avatars, and more! The files automatically upload and pin to IPFS.


Create TRADING CARDS for METAVERSE NFTs

Every NFT minted gets a trading card generated with randomized battle stats.

Upgrade your Discord server today

**Comment by devnjade** [comment]
The Contents have been updated, you can check it out
https://webaverse-web.vercel.app/discordbot

**Comment by devnjade** [comment]
I've made a Pull Request
https://github.com/webaverse/webaverse.com/pull/53

**Comment by madjin** [comment]
Merged, great work! First builder contribution! :raised_hands:
