### ISSUE TITLE
Art: blobs blend messiness

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1394]
The blob pets are fine, but the composed multipet blend file has detached pet wearables floating around (they should be part of the object) and the blobs are animated in their position for some reason. This makes that file very messy to work with. If it is the basis we are using for pets then it should be cleaned up.

**Comment by madjin** [comment]
Fixed the issues and have a few notes on verifying
![image](https://user-images.githubusercontent.com/32600939/127016783-7562fbdc-f827-4cbe-89e0-55b5f66b51a7.png)


1. Change animation

Go into pose mode (select armature, then pose mode)
Go into action editor then change animation to check

![image](https://user-images.githubusercontent.com/32600939/127015164-9988e765-6be7-407e-8050-28559089b24b.png)
 
 2. Change color
 
 Go into object mode
 Open shader editor, select diff colors
 
 
![image](https://user-images.githubusercontent.com/32600939/127015356-02026c33-f19f-4f7c-8407-925a9e4da74b.png)

The .blend has been updated and reuploaded to the drive.

**Comment by avaer** [comment]
Thanks!
