### ISSUE TITLE
Redo concept sheets structure

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1396]
This concept sheet looks great, including the chara, but is not Webaverse branded. I don't know what a concept sheet would look like with Webaverse branding, but I don't think the symbols on the current sheet will be repeated elsewhere, so it is a bit off-brand.

![img](https://user-images.githubusercontent.com/29031531/126806223-04f79725-a473-4793-9580-29143b52533c.jpg)

**Comment by avaer** [comment]
This doesn't need to be complicated, I think the core of what we need is here. We should just make the symbols match across media.

**Comment by GaladWarder** [comment]
Updated; pulled in the shapes and textures from the current logo

![z_CONCEPT TEMPLATE_WEBAVERSE](https://user-images.githubusercontent.com/29031531/127401482-97e5bc2f-5dd3-42ed-8d6b-18eb6a697b88.jpg)

**Comment by avaer** [comment]
This looks good! I'll just need to play with some fonts to see if Roboto is the one to use.

**Comment by GaladWarder** [comment]
Sounds good - it can be easily switched for any font you settle on, so no worries there. Just let me know if you change it and I'll update the sheet accordingly

**Comment by GaladWarder** [comment]
Saw that @plankatron was looking for an SVG version recently - figured I would upload one here with the glyphs and all. The text will have to be overlaid, but this should work as a general use template. 

Can't upload SVG to issues, so here's a link:

https://drive.google.com/file/d/1jzTrPgy278gv7V0ZSEQxLgD_TJ40YcN1/view?usp=sharing

**Comment by GaladWarder** [comment]
Can this be closed? The font can easily be changed at any time and it seems the new design is working

**Comment by avaer** [comment]
Yup, it's done.
