### ISSUE TITLE
Art: souls concept

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1401]
For NFTs.

## Influences
* Hayao Miyazaki's work
* Secret Sky
* Yo-Kai Watch

**Comment by plankatron** [comment]
not really meant to be a final model in any respect but i thought i would just take a quick stab at this , maybe it can give galad some ideas. 
![ghost](https://user-images.githubusercontent.com/5592454/127543287-89f62f08-de49-49e4-8e7b-06cfc511a78f.png)

**Comment by madjin** [comment]
secret sky avatars are great inspiration, 1 draw call, inspired by the forest spirits in princess mononoke
![](https://i.imgur.com/RkeC0EB.png
![brave_XBRhOEPFOk](https://user-images.githubusercontent.com/32600939/127543282-cdec122f-94e2-49a7-b2fb-2358994e1b85.png)
)

I'm a fan of these ghost tails
![gimp-2 10_z0FNMorioX](https://user-images.githubusercontent.com/32600939/127543244-2e1df489-7356-49e6-a963-134d18d586e9.png)

Perhaps symbols can be considered into the design: https://github.com/webaverse/app/issues/1336
![image](https://user-images.githubusercontent.com/32600939/127543028-aa4a5bfc-6685-443d-abbc-1e20ec1c8a55.png)

Requirements: cuteness, originality, >8+ traits

Will drop more ideas here later

**Comment by plankatron** [comment]
oh right , we technically have that one ghost model as a base as well.. i guess well see what galad wants to do
![untitled](https://user-images.githubusercontent.com/5592454/127544876-be9ef583-eb21-4a91-98c7-f07649bf0766.jpg)

**Comment by avaer** [comment]
Those are all cool ideas, but none of them feel enchanting enough yet. We need a defining feature that would make the design unmistakable, like Scilly's bitemark.

**Comment by avaer** [comment]
It's definitely worth a concepting pass.

**Comment by avaer** [comment]
@plankatron was nibbling on the right idea of bulbs floating around, but I don't feel like that's quite good enough. If you took that concept, and made it 5-10x more emotionally impactful then we would have the design we need.

**Comment by madjin** [comment]
# Ideas for lore

AIs are self aware about humans studying transhumanism technology and roadmaps, and that they're part of the sim. Each iteration scientists generate a new 'seed' to see if its the right formula to take us towards the best possible future.

![brave_tLA3baBDJU](https://user-images.githubusercontent.com/32600939/127682754-f6fdcd5c-9f17-4c45-8674-5a0a36d03757.png)

Along this scale, the main character would be around a 3 because of her robotic arm. The world contains a spectrum of types, the sages suspect that the Origin Tablets are an 8. Souls are 0, since they have no attachment to a body yet.

![image](https://user-images.githubusercontent.com/32600939/127682742-692ce4ec-f6a3-4ec7-9144-4c116f406a72.png)

## Spirit Inspiration

What can inspire more joy, making a sad ghost happy or having an always happy ghost? What creates better substance and emotional connection? It's a rarity to find truly happy people in this world. I think people will bond over things that are like them.

Traits:

- Emotes
  - Same emotes for VRM: smile, sorrow, anger, joy, surprise, neutral
- Traits inspired by semiotics
- Cool hats
- Smiles (fanged tooth)
- Flames
- Masks


### Hayao Miyazaki

![image](https://user-images.githubusercontent.com/32600939/127676599-5fc7c5c4-966c-4194-9690-6587baac992e.png)
Symbolism of fireflies: "The firefly becomes a haunting symbol of the film as it represents both the deadly fire bombs that wrecked the children's city but as well as an icon of hope and perseverance".

![image](https://user-images.githubusercontent.com/32600939/127677103-ffcfde52-e1ae-4575-8c6d-1e8f6320bc19.png)
Calcifer from Howl's Moving Castle: Calcifer is in a magical contract with Howl. He was originally a falling star, whom Howl was able to catch before he fell to earth and extinguished.

### Poes (LOZ: OOT)
Poes are spirits of the dead that became monsters because of an unresolved attachment to the mortal world. There's a poe collector that offers Link rupees **and points** for the poes he captures, more if its a big poe. 1000 points = bottle.

![poes](https://user-images.githubusercontent.com/32600939/127675615-6fae9711-7805-401d-8c1f-e1b74a122297.png)

![image](https://user-images.githubusercontent.com/32600939/127686153-28114822-6a2b-4f45-aff7-0f2c306bba22.png)

**Comment by Vianvolaeus** [comment]
> Along this scale, the main character would be around a 3 because of her robotic arm. The world contains a spectrum of types,

This is all fantastic research but I need to point something out, and it's especially prominent in this poster.
Perceived gender is very... blatant, with a lot of prototypical android(male)/gynoid(female)/mecha being very overblown in the designs. There's a handful of examples I can think of that don't weigh into this, (Titanfall 2's STIM/Phase Shift pilots being a good example) 

This is something we should really consider if we go through a mecha route (which i'm definitely not against!)

**Comment by Vianvolaeus** [comment]
> (Titanfall 2's STIM/Phase Shift pilots being a good example)

I suspect the breastplate was added as a means to differentiate the two genders here.. without it they'd simply look like variations. 

![image](https://user-images.githubusercontent.com/80061436/127690117-1905a478-a1b1-4c6a-8806-eb4138d43f11.png)

**Comment by madjin** [comment]
## Concept: Seeds / Eggs / Chips / Prisms / Ether Shell

**Name pending**

Inspired by pokeballs, poe bottles, digivices, and monster prisms (craftopia), these are the most primitive shells for which souls are contained and captured in.

![image](https://user-images.githubusercontent.com/32600939/127689056-5a21b260-00b3-47fb-bc5f-5d25b85ee502.png)

![image](https://user-images.githubusercontent.com/32600939/127686643-1d6921cd-fe6c-4c7e-ace7-ab7efb1ed0dc.png)

### AI Companion

It's a bit weird for pets to be intelligent enough to talk perfect english to their owners. For a intelligent companions, these vessels can fly around the owner autonomously and be conversational similar to Navi in LOZ.

![image](https://user-images.githubusercontent.com/32600939/127689696-6e4e1ef2-b103-4fdd-8137-73a36fb2cca8.png)

Here's an avatar that has multiple flying drones around her.

![brave_ddaOs9tTvc](https://user-images.githubusercontent.com/32600939/127689892-382fe011-6424-4e79-95e5-290270f3faa7.png)

We saw something similar at Vket4 as well with the avatar that had 3 flying orbs which could turn into lights / attack mode:

![](https://i.imgur.com/YUZPl1j.png)

**Comment by Vianvolaeus** [comment]
There's room here to explore a Ship of Theseus-esque transhuman narrative. If one starts 'human' and gradually progresses over the scale, are they still the same individual?

**Comment by madjin** [comment]
Yeah totally. I have more ideas that are composable with all of this that I'd like to present later. It's about adding more utility into the seed/prism/shell idea to give owners choices and make it possible to do epic collabs. Curious what ya'll think so far if its useful or headed in the right direction.

**Comment by avaer** [comment]
Hm…

You know how originally in The Matrix the humans were supposed to be a biological neural net powering the simulation, which makes sense, but executives thought that would fly over people’s heads so they turned them into batteries, which does not make sense, but still made for a beloved story?

That is kind of how I see the simplification of characters into mecha or not.

I’m not saying it is a bad idea, but it is an executive dumbing down of something more complicated, with a possibly good result.

**Comment by avaer** [comment]
Scratch that, when Jin fully explained this idea I think it's amazing.

I was kind of assuming that the digital/robot divide was a new narrative driver, or some new mechanic that reroutes the themes, but when explained this actually matches really well in the current framing.

I thought we were going to introduce mechas that fight for their pilots or something, but really, these are just very appropriate embodiments of souls.

**Comment by avaer** [comment]
I also love the poetry in @Vianvolaeus's idea, that could even be woven in somehow to the design, like the Ether Shell is a vessel for the journey.

**Comment by avaer** [comment]
> AIs are self aware about humans studying transhumanism technology and roadmaps, and that they're part of the sim. Each iteration scientists generate a new 'seed' to see if its the right formula to take us towards the best possible future.

I think we have a powerful idea in the script, which is that the AIs were dumped alone into this world with only the origin tablets to go off of, and the drop storms their main interaction with reality. This provides a very clean, non-abritrary interaction point with the story and other universes.

The AIs know one of them is gonna be "supernal", which means having something superior (AI) combined with inferior (humans) to make it even more superior. And then we tell a very human, character driven story about the first supernal AI, showing a metaphorical journey up the street, which is both a comedy and a tragedy.

**Comment by avaer** [comment]
I also gotta say it really works if Scilli is crossing the gap between human <-> machine, and she is still more human.

**Comment by avaer** [comment]
## Ecosystem design

Each soul is a head in a bubble floating in some liquid. There can be a small ecosystem inside this bubble.

![image](https://user-images.githubusercontent.com/6926057/127737718-b9311a21-ddef-4a58-958c-4561e6ea98d1.png)

## Slime Rancher design

Slime rancher has a bold single shape to start.

![image](https://user-images.githubusercontent.com/6926057/127736924-3726ba9d-d840-4d6e-8e8f-c7d2d11b6a82.png)
![Boom Slime](https://user-images.githubusercontent.com/6926057/127736226-512330b0-b8fc-456c-a3ec-dd3b1ee5dd26.png)

## Ghost design

So they have both a "head" and a "body".

![image](https://user-images.githubusercontent.com/6926057/127737265-1396e2ee-c3de-4eb5-bae0-a6f184f4e0b4.png)
![image](https://user-images.githubusercontent.com/6926057/127737885-d6adcad0-eae3-4452-ab9f-82a01709f07c.png)

## Ghost cat design

![image](https://user-images.githubusercontent.com/6926057/127739154-aa34e30a-0314-4c87-91ae-ef89bd244b02.png)

## Yin yang design

Every soul is chopped in two and arranged in a yin yang fashion.

![image](https://user-images.githubusercontent.com/6926057/127737773-41477445-b87e-486d-9a94-534d93febada.png)

## Cloths design

It is a floating cloth that makes distorted face shapes.

![image](https://user-images.githubusercontent.com/6926057/127739195-d71807d6-698d-4abf-98b4-0d9ea595bcb4.png)

## Weird animal parts

![image](https://user-images.githubusercontent.com/6926057/127739219-f52b0721-d96e-4038-9f6f-5d3f2fbee3e9.png)

## Wearing dead versions of themselves

The ghosts are skins of an animal.

![image](https://user-images.githubusercontent.com/6926057/127737019-bce7ef5d-1681-4794-a4ce-2f18d9fecaf3.png)

## Eyes

I do believe the eyes are going to be very important. We shouldn't copy slime rancher, and I think it should be more human. Maybe it should lean more to the vibe of "should I be concerned?".

"Everyone has crazy eyes"
![image](https://user-images.githubusercontent.com/6926057/127736803-e4fb49b3-86a0-44c1-a7a5-b9277682fda2.png)

"Why can't I see anything eyes"
![Jellybots - JellyJam (new on Patreon!), Nicholas Kole](https://user-images.githubusercontent.com/6926057/127736909-0027f77d-e84b-4ff3-b5fa-625b28444271.png)

"One eye only" mode
![image](https://user-images.githubusercontent.com/6926057/127737327-680a7bef-f24a-447c-89d7-2f7bb82200a6.png)

## Embodiment

We give them little hands so they can interact with the world.

![image](https://user-images.githubusercontent.com/6926057/127736269-ee30c30a-1016-4951-b3bd-ab715d31efb5.png)

They can have 1, 2, or more "hands", which can be tails, shells, wings.

![Hunter Slime](https://user-images.githubusercontent.com/6926057/127736290-8bc5661a-d5cd-4a47-aaaa-c9f86eca6949.png)
![Tabby Star Slime](https://user-images.githubusercontent.com/6926057/127736618-0c533cdf-ae7c-4b83-b281-982a4b9ddf65.png)

**Comment by madjin** [comment]
> Scratch that comment, after Jin fully explained this idea I think it's amazing.
> 
> What flipped my perspective is: The characters in the world are perfectly aware that these seeds are just a metaphor (which is great), rather than us trying to tell a story involving actual seeds (which I wouldn't attempt).
> 
> I was kind of assuming that the digital/robot divide was a new narrative driver, or some new identity mechanic that reroutes the themes, but when explained this actually matches really well in the current framing and enhances the theme.
> 
> I thought we were going to introduce mecha identities that fight for their pilots or something, but really, these are just very meta-appropriate embodiments of souls and the characters agree.

Glad you agree! I'm ogoing to explain the idea here to keep it all organized / proof of work:

The name pending seed/shell/crystal/prism/digivice is the primitive, like the bottle that captures fairies or pokeballs.

![image](https://user-images.githubusercontent.com/32600939/127746298-6ccad4b3-2fcd-4697-be69-a586e6c310b6.png)

Souls can go in/out of them. If you wanted to make a robot, the seed primitive then becomes a one way crafting item.

![image](https://user-images.githubusercontent.com/32600939/127746353-c6a16e46-e7e7-4033-92b9-3b044648be83.png)

The idea is part inspired by an old post by Vitalik Buterin about a day in an Ethereum run future (can't find the post) where humans and machines both have crypto addresses. It's a metaphor for this likely future.

Scilly is the beginning of convergence (robot arm) and machines can converge / compose too (think gundam / power rangers robots). Mechas are a pathway for collaboration with other projects on multiple levels as they evolve, starts simple at the beginning.

![image](https://user-images.githubusercontent.com/32600939/127746800-93e614cd-ca51-4a7a-b584-deebcde3fa76.png)

Side note: Navi looks like 0x overlapping :open_mouth:

**Comment by Vianvolaeus** [comment]
Side note: Navi looks like 0x overlapping 😮

So does this wee fella here: 
![image](https://user-images.githubusercontent.com/80061436/127753989-22d7aa93-3008-4d64-9e63-7d4dbbc6431c.png)

would imply that these are branded, though - does this fit lore?

**Comment by avaer** [comment]
It makes sense if it's the in-brand brand. They could make ghost shells too.

**Comment by avaer** [comment]
Smearing a ghostly trail, like a snail.

![image](https://user-images.githubusercontent.com/6926057/127859880-2c50dc42-8554-44d4-a738-68d008f489af.png)

**Comment by madjin** [comment]
The small flames is how I imagine the seeds to look, similar shapes.

![image](https://user-images.githubusercontent.com/32600939/128378899-e4ef4572-3b7f-442c-be96-e32b668f78ea.png)

![image](https://user-images.githubusercontent.com/32600939/128378947-4a986395-102c-4f2d-870a-7dfad7798598.png)
