### ISSUE TITLE
Art: Main character's *cool hat*

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1403]
![image](https://user-images.githubusercontent.com/80061436/127909993-37a619f8-bd78-4a0c-9965-15fe36dcad9a.png)

![image](https://user-images.githubusercontent.com/80061436/127910016-9d603f67-e34e-4502-9312-16833f6597ea.png)

![image](https://user-images.githubusercontent.com/80061436/127910030-0a4b8945-0e02-4900-a05f-a9ded402f3a8.png)

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/127910280-5d62f516-5317-4b86-85c7-c39e99b79f46.png)

What about a cap or beanie with cat ears?

**Comment by avaer** [comment]
This was one of the original inspirations.

![](https://i.kym-cdn.com/photos/images/original/001/322/169/76e.png)

**Comment by Vianvolaeus** [comment]
As much as a beanie does work, it might go at odds with the sweater we *might* be using - character might look *too* casual (even if they are effortlessly the best).

We could even mash the cyber cat ears with the cap. They could work like speed boosters! Scilly could go 'hat-on-backwards-badass' mode for that extra speed gain.

I'll do a mockup shortly, some other stuff needs doing first. 
![image](https://user-images.githubusercontent.com/80061436/128035276-1dcd2221-2ba9-4268-a278-97964f21086e.png)

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/128510599-94e273ec-5712-4590-85fb-07ea3bc3dac1.png)

This is close to done, but priority is decreased since it's not going to be part of the main design anymore.

**Comment by avaer** [comment]
As a janitorial matter, I'm going to close this for now.

The hats look great, and I imagine we will shortly need them, but until it pops up in a script we should stash it.
