### ISSUE TITLE
Art: detail / SVG of 0x logo

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1405]
A refined and high quality capture logo for the 0xDEADBEEF brand is probably a good idea - unexpectedly became more important than a simple detail on some shoes. 

The interpretation of `0x` was that it was akin to a skull and cross bones. I tried to imagine a simple to draw / graffiti tag that might be used for it (skull/crossbones can be surprisingly complex) 

It's implied this is a high quality brand / gear set that Runners would use. 

Here's the logo on the DH's upgraded shoes: 
![image](https://user-images.githubusercontent.com/80061436/128358190-aa592ce8-e31b-4d8a-9c28-53f778d753f5.png)

Here it is without any spray paint effects: 

![image](https://user-images.githubusercontent.com/80061436/128358300-84ef7b8e-291e-45fc-844a-dd563abd9eb5.png)

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/128365668-39a6efb1-6f3e-4f9d-a9f2-2dda48bb2acd.png)
Went ahead and did this, will do for now.

**Comment by Vianvolaeus** [comment]
Drive (svg) :
https://drive.google.com/drive/u/1/folders/1HxLNBoYhsX3aNADePdvC2jyXSgOnxAJz

PNG 
![deadbeef_0x](https://user-images.githubusercontent.com/80061436/128366375-5bc3311d-344a-4120-adf4-768d098aaab5.png)

Alpha stamp for SP, etc

![deadbeef_0x_alpha](https://user-images.githubusercontent.com/80061436/128366461-a34e40a8-261a-4de7-9b8d-0f6797a39c6e.png)

**Comment by avaer** [comment]
Looks good, thanks!
