### ISSUE TITLE
Art: Digitize sword

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1408]
The megasword is overall great, but the texture lightning bolt doesn't come out well in many scenes. It also isn't animated, but a large part of the point of the blade is to be mesmerizing to look at, like a glowing light saber.

We should add some animation/shader to the blade. It seems it's possible to do in Blender: https://github.com/patriciogonzalezvivo/glslTexture

The core of the blade should be an emissive color gradient, but blended with a decent shader. Here are a some examples of what I am talking about.

https://www.shadertoy.com/view/stBSzd
https://www.shadertoy.com/view/sds3RX

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/128610343-aef00947-7e9c-4b34-b4bd-6d4eb7e87c4a.png)

**Comment by avaer** [comment]
![](https://cdn.discordapp.com/attachments/737801646364557394/873832411971080252/Untitled2.jpg)

Applied shader, this is in the GDrive, but requires https://github.com/patriciogonzalezvivo/glslTexture to open.

We should also add a backface outline (black?) to more clearly define the border of the blade.

Note that the UV's of the sword are not quite even right now (hard break in the middle) -- this is possibly because the texture is intended to be repeatable.

**Comment by GaladWarder** [comment]
@plankatron Please put an update through here when you have a sec, I know progress has been made on this but I am not sure how much

**Comment by plankatron** [comment]
I had some issues getting the glsl addon to work 
- did not want to install on 2.93 , going to investigate that further *edit , while it installed much of the functioinality did not work, you could use the test file but when tweaking it you could get blender to crash or the addon would become unresponsive, refuse to update anything.
- crashed a lot 
- i managed to get the test file to work but was not able to adequately tweak it to get any look beyond what was originally done. instead i worked off of the two shaders that were posted to come up with a look just with blender's material node system, here are the tests. 
![megasword_digitize1](https://user-images.githubusercontent.com/5592454/139606649-bd6295d9-6e90-4d16-8adc-3ac1f053fb4d.jpg)
![megasword_digitize](https://user-images.githubusercontent.com/5592454/139606652-7d594120-3d5d-4d08-9bf1-9058bf0c4276.jpg)
- we could potentially have two materials on the megasword and use that to do a material override so shader programmers could add this effect , but in terms of the shader programming that is a bit out of my wheelhouse.

**Comment by avaer** [comment]
It looks pretty, but I think we'll just shade this in engine.

The GLSL plugin is actually very slow to update in Blender (cannot do dynamic shaders in realtime) because it does a full render pass to texture file each frame. The engine doesn't have that restriction.

**Comment by GaladWarder** [comment]
No problem, we have a version with a static texture already being tested in the engine, we'll leave the GLSL to the engine side 👍

**Comment by GaladWarder** [comment]
@textametron Need an export, two mats - one for sword and one for shader

**Comment by GaladWarder** [comment]
updated megasword glb 
* Animations : 
  * Active_Sword Armature
  * Closed_Sword Armature
  * Sword_Activate_Sword Armature
  * Sword_Deactivate_Sword Armature
  * Trigger_Sword Armature
* Materials 
  * megasword
  * glass
  * sword (this is the override material)

Animated Megasword
https://drive.google.com/file/d/1J15xHJ-WLdpZvTI_SO-Jz8_65i1LmRSM/view?usp=sharing

Non Animated Megasword
https://drive.google.com/file/d/1AjEV9vzFcuo3lv7p6QxGdA7JOJjd_5tw/view?usp=sharing

* Bugs 
![Screenshot at 2021-11-09 16-49-19](https://user-images.githubusercontent.com/5592454/141011457-70c11eb0-9085-4754-a2f3-e670c1a1f258.png)
![Screenshot at 2021-11-09 16-49-01](https://user-images.githubusercontent.com/5592454/141011543-551f3102-f9f7-44fb-9c1d-c62eb4bd7a20.png)

there is a depth buffer issue with this sword
