### ISSUE TITLE
FE: Transferable / non-transferable header text does not toggle

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1412]
![image](https://user-images.githubusercontent.com/80061436/129768071-38f761e9-b9a5-4d1a-a7dd-d2dd1fdb1a60.png)

Description toggles, header does not, shows both as transferable.

**Comment by avaer** [comment]
Note that this is not implemented in the contract yet. There is a list of things we should be adding there before we perform a migration.

Once that is done then we could hook up this UI.

**Comment by avaer** [comment]
https://github.com/webaverse/contracts
