### ISSUE TITLE
Deploy new Webaverse website

### ISSUE THREAD

**Issue by softwarebycl** [webaverse/app#1415]
Related to: #1258 

The [current website](https://webaverse.com) can be hosted at dashboard.webaverse.com

The [new website](https://webaverse.org) will need to be given a Webaverse org repo and deployed on vercel to webaverse.com

**Comment by avaer** [comment]
The repo has been moved and there is a new repo in place here: https://github.com/webaverse/webaverse.com

We just need the code inserted there and then we can deploy with Vercel.

**Comment by avaer** [comment]
for now I will deploy a copy of the old `webaverse.com` on `webaverse.com`.

**Comment by avaer** [comment]
This repo can be deployed over with the new code and Vercel should pick it up.

**Comment by softwarebycl** [comment]
closed by https://github.com/webaverse/webaverse.com/pull/1
