### ISSUE TITLE
Fe: Discord bot gif 404

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1428]
![2021-08-18-18:04:25](https://user-images.githubusercontent.com/32600939/129992106-59d1a2ae-dd33-4f90-8954-6847c69e62c1.jpg)

**Comment by softwarebycl** [comment]
fixed by https://github.com/webaverse/webaverse.com/commit/6e9e612e7907ef9cf6000a52343924477a6f184b

![bot0](https://user-images.githubusercontent.com/29695350/130085995-507dc0f2-10db-42f8-ad8e-bbe12ef31c86.PNG)
