### ISSUE TITLE
Fe: Blogs not showing up

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1429]
Noticed the blog posts are no longer at the bottom of the front page and that https://webaverse.com/blog is empty

**Comment by softwarebycl** [comment]
Thank you, good catch, will fix that right now.

**Comment by softwarebycl** [comment]
fixed by https://github.com/webaverse/webaverse.com/commit/3f1a0fee93b108515a4d8a7ea466fa2aecb1c23c
