### ISSUE TITLE
Fe: Login doesn't work

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1430]
I'm unable to login to the frontend website using "Connect wallet"

I think Login might be a better word instead of "Connect wallet" because one of the sign in options before was Login with discord

**Comment by softwarebycl** [comment]
Yeah the feature isn't actually setup, that button currently a placeholder. I'll hide it for now until that is added by #1417

**Comment by softwarebycl** [comment]
https://github.com/webaverse/webaverse.com/commit/97fe8540494181369e3b61acc83610c687a76b32
