### ISSUE TITLE
Fe: Main frontpage website feedback

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1437]
Interoparability -> Interoperability

Lots of text, could use more pictures. Perhaps we can have an about section for transferring the text into. Then we can add the roadmap to fill in the gap.

Missing metadata for discord / twitter autopreviews

Add explainer on listing pages: https://github.com/webaverse/app/issues/1425

**Comment by avaer** [comment]
I agree about adding more pictures, @GaladWarder was trying some things there.

**Comment by softwarebycl** [comment]
- Fixed Interoparability -> Interoperability
- Fixed Missing metadata for discord / twitter autopreviews

> Lots of text, could use more pictures. Perhaps we can have an about section for transferring the text into. Then we can add the roadmap to fill in the gap.

Added some more images, let's break this out into https://github.com/webaverse/webaverse.com/issues/3 -- we need to write out the roadmap in a way that would fit on the landing page, right now it is rough bullet points.

> Add explainer on listing pages: #1425

Going to add this, Let's break that out into https://github.com/webaverse/webaverse.com/issues/8
