### ISSUE TITLE
Avatar metadata and storage

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1444]
Topic came up after creating an avatar that had both NFT and non-NFT purchased wearables. How do we handle such that gives confidence to both users and creators? It feels wrong to "mint" something that isn't completely original to you. Note: no one seems to be handling wearables that well yet, this is a new frontier.

Ideas:

* Add metadata for wearables attached to the glTF models similar to how VRM does it. This could be part of a blender plugin.
* Meebits strategy where a render of the avatar (perhaps also doom sprite) is the NFT that unlocks file storage using a session cookie after proving ownership
* Use 3rd party to upload like VRoid hub -> Webaverse for avatars containing restrictions.

**Comment by avaer** [comment]
Here is the most important link: https://github.com/kitsune-ONE-team/KITSUNETSUKI-Asset-Tools/blob/master/blend2vrm.md

**Comment by madjin** [comment]
Perhaps this is also relevant here: https://github.com/common-metaverse/urn-namespaces (https://github.com/webaverse/app/issues/794)

Say I upload an avatar like this, would I need to verify ownership of the NFTs in such a process? I say not, it was complicated enough to add them in the first place.

![blender_tdyFjWS7FF](https://user-images.githubusercontent.com/32600939/130335993-1327a7c5-024c-43cd-bcb7-65273196118f.png)

The better way of doing it is proving ownership of NFTs online, similar to Craftopia and Cryptovoxels when signed into Metamask. Attached to bones automatically. Then they can also unlock special abilities in-world, otherwise they're just another model when uploaded in this fashion.

![Craftopia_1UbzhUGrxr](https://user-images.githubusercontent.com/32600939/130336116-08f61471-50b3-475f-b564-9babff5bb9a9.png)

![mspaint_icSPj219Rw](https://user-images.githubusercontent.com/32600939/130336117-864a1c9d-d80a-44d4-9b40-a91f8bbca8f8.png)

![image](https://user-images.githubusercontent.com/32600939/130336163-22f78e13-160f-4dce-b97f-71fcbc13cdd7.png)

I'm aware that this is already how Webaverse handles it, which is freaking awesome! Just needs some controls to make slight adjustments.

![wearables2](https://user-images.githubusercontent.com/32600939/130336182-807b4191-6251-43b0-b8f2-0b54dad454cd.gif)

So far this handles the NFT wearables cases well, even from different collections. For avatars that have non-NFT items with tight terms of use I think the VRoid SDK option will be the safest bet for the time being.

**Comment by avaer** [comment]
Most of these assets are not on chain and even if they are, they are lacking rights info (other than vrm). And even if that were the case, it would be easy to bypass.

I don’t think we can check it automatically yet but we should make rights annotation as part of the Blender plugin export pipeline.
