### ISSUE TITLE
Bot: cannot add to other servers

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1449]
Tried to add bot using the new site and received this error adding it to a server:

![image](https://user-images.githubusercontent.com/80061436/130441069-08e65fd3-4b69-4741-82c7-49c75633f5fe.png)

**Comment by avaer** [comment]
I think we broke the limit. This was warned about previously.

**Comment by Vianvolaeus** [comment]
This appears to be settled now, have been able to add it.
