### ISSUE TITLE
Unknown extension: wbn

### ISSUE THREAD

**Issue by softwarebycl** [webaverse/app#1450]
This error happened when attempting to mint / load in a [wbn](https://github.com/softwarebycl/drone-pet).

![unknownwbn](https://user-images.githubusercontent.com/29695350/130496307-7366ca6d-8442-4518-bf6b-bcdc0c9d8fee.PNG)

**Comment by avaer** [comment]
We removed support for `wbn`, it will need to be minted bare on IPFS.

**Comment by avaer** [comment]
Won’t fix.
