### ISSUE TITLE
Art: loot pose

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1471]

**Comment by GaladWarder** [comment]
Putting the shirt models here for easy ref later
https://drive.google.com/drive/folders/1j2eVskwdXxmKL6Qn-LvhbJqhDOPmZvE1?usp=sharing

**Comment by GaladWarder** [comment]
![Loot Pose Image_V1](https://user-images.githubusercontent.com/29031531/132801094-aa053a65-b274-48c4-910f-2d94ff480bbe.jpg)

Here's what I came up with, just let me know what you want the banner to say and I can add it in!

Current PSD: https://drive.google.com/file/d/1L8u9gxsxc3_7GgcQK0nHqffTqAgq88gF/view?usp=sharing
Current Blend: https://drive.google.com/file/d/1XNz7iVTmmxt5ScJg6xPwrOymsGiz29Fx/view?usp=sharing
