### ISSUE TITLE
Art: Scillia VRM finalisations

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1483]
We need to do some testing, optimization and mastering of the final VRM for the #1382 character.

Art:

* [x] replace shoes with tech shoes
* [x] bring color (saturation) in line with other default avatars in app

Technicals: 

* [x] Blendshapes under VRoid naming convention (Expressions, AEIOU, etc) 
* [x] test hair bone naming convention in webaverse
* [x] reduce filesize
* [x] reduce hair transforms
* [x] rigging / anims correct in webaverse

**Comment by Vianvolaeus** [comment]
We can, as a (destructive!) edit once everything is absolutely final on the materials, bake everything out into a texture atlas / bake in Blender. This does limit per material in-engine editing, of course, but will reduce drawcalls & texture usage. 

Even if it's not used on the main characters, it's something to consider for 'static' NPCs, etc.

**Comment by avaer** [comment]
It's totes fine to do that destructive edit/mixdown, but is there any way to make it automatic vs manual? So we can do it again later?

**Comment by Vianvolaeus** [comment]
Right now the flow would be final master file from Blender > bake down materials via script/plugin in Blender > export to Unity > remove unused shapekeys on VRM export via uniVRM. 

Not sure what you mean by do it again later. On the same model, or for others?

**Comment by Vianvolaeus** [comment]
Unity had been upscaling textures to 2k *automatically*, so that's another tripwire to watch out for. Should substantially reduce filesize, especially when combined with the blendshape export settings. Seeing a large reduction already. (Full res, no compression, all blendshapes is about 140MB - correct sizing, compression, and removing blendshapes not referenced by BlendShapeClips in VRM is about 30MB)

**Comment by avaer** [comment]
> Not sure what you mean by do it again later. On the same model, or for others?

On the same model, after edits.

**Comment by avaer** [comment]
30MB is still a _little_ bit large; any way to halve that?

**Comment by Vianvolaeus** [comment]
Even after very aggressive texture compression, we're not seeing much in the way of filesize reduction. If I remember correctly, gltf is quite bloated in regards to shapekey filesize compared to other formats. This is with everything nuked except blink / AEIOU and ALL.expressions (Joy, etc) 

We'll have to implement the above material work, but even with a singular blank mat across the board exports are still hitting 10MB+. 

As for rebaking on the same model, it depends on the type of edit. If it's a texture edit, it can be rebaked and the material can be updated on the VRM. If it's a geometry edit then you're going to break the model anyway, so you'd have to redo the process. 

If it's something like a clothing swap, then we should be able to have a baked material base model, and then bake out the clothing set as it's own material.


This is going to take more time to finish off than I'd hoped. Unity has decided gravity is backwards for spring bones, which needs debugging.

**Comment by Vianvolaeus** [comment]
Only other thing I can think of is a misnamed UVmap that's adding an extra to the count (VRoid content uses a different naming scheme for whatever reason, which has to be manually changed)

**Comment by Vianvolaeus** [comment]
Trying to test in-engine and it seems like weba is constantly refreshing, along with some other issues. Filing now.

**Comment by avaer** [comment]
Thanks for filing! Definitely bugs. Looking into it.

**Comment by Vianvolaeus** [comment]
Atlassing and reducing material count does help on the filesize front. Unity seems either incorrectly read or otherwise change externally compressed textures... will have to look into this. Compressing internally doesn't appear to export correctly. Unity thing. 
Either way, atlassed mats with Diffuse / Normal only for MToon, as well as reduction of geo normals for morphs, etc, appears to put us under the 15MB target. 

I still need to test within Weba for naming conventions and animations / rigging, but having problems @ mint

**Comment by avaer** [comment]
> atlassed mats with Diffuse / Normal only for MToon, as well as reduction of geo normals for morphs, etc, appears to put us under the 15MB target.

That sounds like the right solution, thank you researching this.

> I still need to test within Weba for naming conventions and animations / rigging, but having problems @ mint

Yup, bugfixing that.

**Comment by Vianvolaeus** [comment]
Unity & uniVRM, while a bit more friendly on the UI side, also has it's own pitfalls. 

Unity will occasionally appear to not import an FBX correctly with modifiers enabled. While this is isn't a limiting problem in terms of functionality, it does mean that changes have to be applied prior to export (destructive) if we don't want to gamble on Unity working or not working. 

The problem I was having here was in regards to shapekeys not being present on the export with the Apply Modifiers setting enabled in the Blender exporter - yet just one export prior, it had worked completely fine (no edits, just wanted a clean import in a new project) 

uniVRM tries to extract all textures from the model according to the unity console, even though they may not be used in the current shader setup, which will halt / abort the VRM exporting process. (In this case an unused roughness map halted the process - shaders were changed to gtlf unlit) 

Lastly - springbone component code appears to rely on having a child bone present (even if unweighted). This is a bit of a pain for interop to other formats since it adds bone count in other physics solutions. There is an option to add leaf bones (empty child bones) on the initial export of a model from Blender which would be an 'autofix', at the cost of a additional +1 child bone on every bone chain of a model.

**Comment by Vianvolaeus** [comment]
Comments from @avaer on v1: 

"for scillia.vrm I think we gotta age the proportions up a little to get it out of child zone, test a scar, and maybe improve the hair folds a bit but it's good enough to at least be able to see how it fits with a set of other models"
