### ISSUE TITLE
FE: No option for Discord login (?)

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1485]
I could be being stupid, but I can't find an option on the new site to login via Discord, which is currently where all of my mints etc are - given the history of minting being done though the Discord bot, this could be effectively locking out a large number of people. 

#1484 is blocking me from logging in via the bot.

**Comment by avaer** [comment]
Might have to go back to the old site (https://dashboard.webaverse.com/)

**Comment by Vianvolaeus** [comment]
That works - minting has resulted in something odd? In the media preview there's a video of someone using rave gloves? I'm trying to mint a VRM here, no idea why that's coming up: 
![image](https://user-images.githubusercontent.com/80061436/133118025-034eae7a-93ad-49b7-bf31-97e8a63e0a1a.png)

Tested with another file (JPEG) and a random *VRM* has popped up. I assume the preview's doing something weird... 
![image](https://user-images.githubusercontent.com/80061436/133118507-f8b0d2d3-140a-4744-aef3-62bed93c06dc.png)
