### ISSUE TITLE
Homespace upgrade

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1495]
Let's make the back part of this home space. It's just the inside/extension of the homespace we have (Original files: https://drive.google.com/drive/folders/1AwGkySjs5LhtCxHR_m9_BSFpEowc3Lmo)

This is Scillia's apartment, where you can fly into. It's parked at the top of a skyscraper. No need to make the actual skyscraper though, it just explains the purpose of the window that looks down onto the city.

I drew a rough layout.

![image](https://user-images.githubusercontent.com/6926057/134965077-caf244f0-3673-4f0f-98f8-3fd7b8bff95b.png)

**Comment by Vianvolaeus** [comment]
Posting Dream's shots here: 
![image](https://user-images.githubusercontent.com/80061436/135494777-32ae77b0-0c62-430b-b1f9-de799dce005d.png)
![image](https://user-images.githubusercontent.com/80061436/135494790-d4f85a46-0b51-42d6-8c6a-2a7e3af58e2d.png)

(feedback was it needed to be less techy, more homely) 


![image](https://user-images.githubusercontent.com/80061436/135494721-09bdcb8b-6e7e-46c8-9d92-4a91e99e9833.png)

**Comment by avaer** [comment]
One thing to keep in mind here, is we should have a door for the interior that slides open
