### ISSUE TITLE
feature request : spawn feature to scn json 

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1512]
please add , k thnx

**Comment by skaljac** [comment]
Implemented in https://github.com/webaverse/totum/pull/33

**Comment by skaljac** [comment]
Players spawn position, rotation can be set in .scn file with this settings
{
"type": "application/spawnpoint",
"content": {
"position": [30, 10, 30],
"quaternion": [0,0.7071,0,0.7071]
}
},
