### ISSUE TITLE
sun_light SCN properties 

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1515]
how about something like : 

    {
      "azimuth": [
        0-360
      ],
      "elevation": [
        0-360
      ],
      "cast_shadow" : true,
      "color": [
        0-256,
        0-256,
        0-256,
      ],
      "intensity": [
        0-256,
      ],
    },

**Comment by avaer** [comment]
Currently it's:

```
{
      "type": "application/light",
      "content": {
        "lightType": "ambient",
        "args": [[255, 255, 255], 2]
      }
    },
    {
      "type": "application/light",
      "content": {
        "lightType": "directional",
        "args": [[255, 255, 255], 2],
        "position": [1, 2, 3]
      }
    },
```
which closely matches THREE.js parlance: https://threejs.org/docs/#api/en/lights/DirectionalLight

Scene lighting is now using this in the scene file: https://github.com/webaverse/app/blob/7409a2f16b056bcaa0fae1db5236b9b729d8cf33/scenes/treehouse.scn#L4

**Comment by plankatron** [comment]
working great ! is it possible to get shadow support at least for directional light ?

**Comment by avaer** [comment]
> working great ! is it possible to get shadow support at least for directional light ?

Yes; note that shadow map support is a full thing, regardless of light type. It's either all light types or nothing.
