### ISSUE TITLE
App: Fix avatars with no upper chest bone

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1521]

**Comment by Vianvolaeus** [comment]
(adding detail at request of @ahadshams)

Not all VRM armatures are the same - some models make use of [optional bones](https://github.com/vrm-c/vrm-specification/tree/master/specification/0.0#defined-bones) in the VRM spec. 

The most frequent appears to be an unincluded upper chest bone (which currently our in-house avatars *do* have). 

Equipping an avatar without optional bones at the moment results in it teleporting (to origin?) and not equipping. 

https://user-images.githubusercontent.com/80061436/139651035-96388c69-cbd2-4b3e-95a6-37c3e6b51aac.mp4

The avatar is valid as per VRM spec, but doesn't contain (notably) finger bones, as well as eyes, toes, or an upper chest bone. 

![image](https://user-images.githubusercontent.com/80061436/139651241-271da22b-8b37-4fb9-94ea-e74956327d39.png)

**Comment by avaer** [comment]
Can this be closed now?

**Comment by Vianvolaeus** [comment]
This appears to be working (at the moment). I'm not sure on the specifics of #1744 fix, but both appear to be cleared.
