### ISSUE TITLE
App: add loading indicator while not bring able to move

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1523]

**Comment by Vianvolaeus** [comment]
Something like chillout VR's wireframe > full textured world load could make for an interesting transition in the future

**Comment by 0xmetabad** [comment]
+1 to this, when I load into Webaverse I know that the scene is just loading.. but tested this with other people and they had no idea that things were loading and just clicked off. 

This is common in online gaming, users are more comfortable and inclined to wait if they know things are loading and working as expected.

**Comment by 0xmetabad** [comment]
Related issue:
- https://github.com/webaverse/app/issues/752
