### ISSUE TITLE
App: Glitching animations on monitors higher than 60hz

### ISSUE THREAD

**Issue by GaladWarder** [webaverse/app#1530]
https://user-images.githubusercontent.com/29031531/136836414-363bdf25-7bab-40ad-bd27-845908057d11.mp4

Console is clean, monitor settings below:
![image](https://user-images.githubusercontent.com/29031531/136836452-555da92a-0695-4534-8285-a89e99d20434.png)

Reproducible on clean refresh too

**Comment by avaer** [comment]
I implemented a potential fix here: https://github.com/webaverse/app/pull/1698

Could you test again?

**Comment by GaladWarder** [comment]
Just tested this, there's definitely a change - previously most of the glitching happened during running, now it's primarily during walking. It does seem less frequent/extreme though

https://user-images.githubusercontent.com/29031531/139603044-6aa2664a-b939-438a-97ef-7c9358276b70.mp4

**Comment by avaer** [comment]
@GaladWarder Thanks, I just pushed another set of updates to help with this. Can you try again?

**Comment by GaladWarder** [comment]
Looks *much* better. The weird glitch thing is gone, as far as I can tell! There's some 'jittering' with the hair, but it's honestly barely there, and it could be something with the hair physics, hard to tell.

https://user-images.githubusercontent.com/29031531/139708685-66e9d197-3f83-44ff-9e21-511a8610c818.mp4
