### ISSUE TITLE
Geometry readback memory overflow

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1531]
this works locally but i imagine that is because i havent pulled in a day or so
https://app.webaverse.com/?src=https%3A%2F%2Fplankatron.github.io%2Fdcl_remix%2Fdcl_remix.scn

**Comment by avaer** [comment]
Is the geometry too huge?

**Comment by avaer** [comment]
My first guess is it looks like the physics system cannot handle the size of the models being loaded.

**Comment by avaer** [comment]
https://github.com/webaverse/app/blob/dcd3bec5140109f1a8e922b2c9c347703cb7d3a2/physx.js#L873

**Comment by avaer** [comment]
https://cdn.discordapp.com/attachments/897887454839848981/904832714077798451/Screenshot_2021-11-01_at_21.40.30.png

**Comment by skaljac** [comment]
We have increase buffer for position and indices so now this is no longer a problem
 const positionsBuffer = allocator.alloc(Float32Array, 1024 * 1024 * 2);
 const indicesBuffer = allocator.alloc(Uint32Array, 1024 * 1024 * 2);
