### ISSUE TITLE
App: Discord/sidechain login

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1543]
Currently we log in only with Metamask when you click the top left button.

![image](https://user-images.githubusercontent.com/6926057/137202988-4eb92801-04b2-4df5-b240-8cd631dfaa0f.png)

To bring back Discord compability and being able to see and use tokens minted in discord, we should have a dropdown there which allows you to log in with:

1. Metamask
1. Discord
1. Email (maybe)

Note that the Discord flow actually starts with the bot, which passes data via query string: https://github.com/webaverse/ethereum-bot/blob/88d3a13afe49886b197fa25866177d4a727a3fce/discordbot.js#L2658

The (disabled) old code for handling logins is here and would need to be fixed. It was based on form submissions in UI that no longer exists, but we can use that code if it makes sense. https://github.com/webaverse/app/blob/master/login.js

The backend for login codes is here (lmk if you need access): https://github.com/webaverse/api-backend/blob/abee48e54b6faccd20fd5faac3e25d291c110e3f/index.js#L468

Side note: in the we also log into the Ceramic network for storing metadata. That doesn't need to work yet with the sidechain (there is a whole key procedure to it), so we can skip it in the sidechain/email part: https://github.com/webaverse/app/blob/1e1c36bdc0275455aa5942530d2b538ea485e244/src/Header.jsx#L234

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/137220545-5f072bec-8a7e-4519-aea4-3e69cc260950.png)

**Comment by cris-coder** [comment]
Currently when I click on Log in , it does nothing. When are you going to fix it ?
