### ISSUE TITLE
App: physics collision frequency

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1560]
We should not be able to walk through walls ever -- we need to be able to ram a thin wall at very high speed and bounce back without glitching. Currently this is glitched because the character restitution test is too sparse for fast velocities.

There are many techniques to fix this; I believe physx supports CCD, which we are not using for the character capsule currently. Another approach would be to scale the collision test to the velocity by doing the correct sphere math, point to point, based on velocity vector and magnitide (that might be a quicker way to hack it).

We should do whatever gets us to fast, non glitchy physics in the least effort.

**Comment by avaer** [comment]
Our PhysX build, we can add or remove anything from Physx if we expose the functions: https://github.com/webaverse/app-wasm
PhysX docs talking about CCD: https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/AdvancedCollisionDetection.html

**Comment by amnaarshed4224** [comment]
Fixed with CCD.
