### ISSUE TITLE
App: bare windows not working

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1583]
Although our code should be windows-compatible (it is pure JS), currently the windows bootstrap is broken. We should fix this to make development easier.

```
This line
const srcUrl = '${this.srcUrl}';

It gets replaced with file:///D:/Webaverse/app/scenes/street.scn
On windows, wile on Mac it gets replaced with 
/scenes/street.scn
and because of that browser is throwing error: TypeError: NetworkError when attempting to fetch resource.
```

This is because [`metaversefile`](https://github.com/webaverse/metaversefile) is appending CWD in some cases from the windows paths, which are not web-compatible: https://github.com/webaverse/metaversefile/blob/487ab1f5a500c7d26ff6ac985de3e2a4276545d6/types/metaversefile.js#L5

**Comment by avaer** [comment]
The reason we never ran into this is all devs are on either non-windows or using WSL, which do not have this problem.

**Comment by avaer** [comment]
I don't know if the above info is still relevant, but reports are that the Windows default load does not work. We still would like to fix that.

**Comment by amnaarshed4224** [comment]
fixed
