### ISSUE TITLE
App: default avatars

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1594]
We will probably provide a selector for male/female avatars to start.

I made the current one if VRoid studio with a decent default texture pack, but perhaps we want something that doesn't look like a naked boi?

![](https://cdn.discordapp.com/attachments/897887421180547092/900065484907610163/Screenshot_from_2021-10-20_00-58-02.png)
![](https://cdn.discordapp.com/attachments/897887421180547092/900065619993571338/Screenshot_from_2021-10-20_00-58-14.png)

**Comment by Vianvolaeus** [comment]
Is it a temporary or long term solution we're looking for here? If we want some strong defaults they can be whipped up after the main characters, or if we need something *now* I can see what I've got sitting around.

**Comment by Vianvolaeus** [comment]
I can find the tex set, I recognise it. Bear with.
