### ISSUE TITLE
App: first person model clipping / FPS neck model

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1609]
Right now there is basically no head model tracking for first person and the camera just locates above the hips. This works great but creates glitches when in first person, especially moving and running around.

![](https://cdn.discordapp.com/attachments/831974724510810172/900776470253826128/Screenshot_from_2021-10-22_00-03-48.png)

For better first person view in keyboard and mouse, we can use an IK neck model (possibly the existing IK) to move the head forward/backward via neck model as the user looks around. With this, although we lose aiming accuracy for first person, it would look a lot less glitched.

Related: https://github.com/webaverse/app/issues/1608

**Comment by skaljac** [comment]
Rosolved with
https://github.com/webaverse/app/pull/2031

**Comment by ahadshams** [comment]
i still see this

![image](https://user-images.githubusercontent.com/44798013/147745185-5d0d7845-2cce-48db-9be5-647bc49efe14.png)

**Comment by avaer** [comment]
@ahadshams Better repro instructions would be appreciated. We cannot debug this without clear instructions on how to get it to happen.

Filling in for ahad: this seems to only happen on macOS for a very specific angle.

**Comment by avaer** [comment]
This bug is quite likely due to the fact that macos scrolls are not quantized.; they are smooth. This is probably tripping some code split where the code is checking z dustance/position differently, and having a near-zero value trips the code split.
