### ISSUE TITLE
App: avatar CCD

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1610]
We need to move the avatars/pets/npcs to a CCD-based system. Instead of owning the character controller and computing positions, we can give it to the physics system and simply set the velocities.

By using CCD, which is based on velocities, we will be able to avoid the tunneling bugs, allowing for much more dynamic gameplay. However, this requires a large rewrite of the character controller to integrate, at least hours of work.

We have physx CCD support enabled and supported for the capsule type, and we can create CCD-enabled capsules already: https://github.com/webaverse/app/blob/806d6c50cb280041d84362cbdd5713a69dbf4b1b/physics-manager.js#L197

**Comment by avaer** [comment]
https://github.com/webaverse/app/tree/ccd-test
https://github.com/webaverse/app-wasm/tree/wasm-ccd

**Comment by avaer** [comment]
Here is how to do this step by step:

## Step 1: get capsule geometry working in physx

Seems like we're done this.

## Step 2: render character capsule

Get rid of the avatar (do not add to scene) and create an accurate visual Capsule Geometry and make it align perfectly with the physics.

We can get rid of all of the fancy camera logic here: the camera should center on the capsule we draw, keeping the mouse wheel zoom scroll support. The math is very simple for this, it's a vector offset.

At this point we should make sure that every system works with the new capsule geometry driven physics, including ruinning, crouching, flying, etc. None of it should glitch. If it's glitching then we should be able to tell exactly why because we are already drawing the perfectly accurate capsule. And if we are not then we need to fix the render.

Note: this step has the side effect of creating a capsule visualization layer which we can turn on at any time (we should keep it around). This capsule rendering code will be used in PVP hit detection + visualization.

## Step 3: Once we have our stupid capsule stable, turn on avatars

Now we can paste the matrix from the capsule to the avatar instead (in `rig.js`) and hopefully our avatar works. If we did the capsule job correctly, our avatar will look good when attached like this.

## Step 4: fix the camera

Background:

![image](https://user-images.githubusercontent.com/6926057/139652394-ec93b8e5-de14-43ea-adfd-1d862756d4b4.png)

https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/Geometry.html

We want a good camera for our avatars, not aimed at the hips, unlike with the capsule. So we now need to change the camera target. There are a few ways to make this work, I don't know which is best.

### Option 1: offset up

One is to take the character capsule and offset up by "half eyes height". This gives a stable run that does not head bob.

### Option 2: eyes bone position

We can align the camera exactly to the eyes bone, which should be quite accurate.  This option would be more lifelike and would have head bobbing and other effects. However we would not copy the quaternion from the bone, 

### Option 3: eyes bone position + quaternion

If we want true immersion we can copy the eyes position + quaternion and add a neck model which will .

This would feel quite immersive but would require animation cleanups.

### Option 4: honor VRM gltf extension metadata

VRM contains information for for to behave in first person node, what bone to bind to, etc. We can simply honor this binding, possibly still applying our neck model if needed.

However we fix the camera, once that is done CCD capsules should be shippable.

**Comment by avaer** [comment]
Note that in the above I am indeed suggesting we delete a lot of the camera controls/character controller code, which lacked a good sense of truth for where the character is.

With this, we can say it's "their character capsule", which has a strong definition that aligns with the renderer, physics engine, and our own systems.

It would also make the camera subservient to the capsule, whereas previously it was often the camera which would set the capsule.

**Comment by avaer** [comment]
The rig height is computed for you by the avatar rig system: https://github.com/webaverse/app/blob/f8c2d3b25c72ade6dd5a1f2419a2cf9dab7d600d/avatars/avatars.js#L1191

It is a good thing to base the capsule on.

As for radius, good fatness for an avatar seems to be 0.3, which makes it 0.6 fat.

**Comment by amnaarshed4224** [comment]
Fixed with CCD
