### ISSUE TITLE
App: SFX pack

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1633]
We should get an SFX pack and create a sound system to trigger them. Sound is easy but pretty important for the final product.

**Comment by skaljac** [comment]
This sfx pack for anime games should be interesting for Webaverse:
https://assetstore.unity.com/packages/audio/sound-fx/anime-epic-combat-sound-effect-pack-206061


Maybe this is also interesting
https://assetstore.unity.com/packages/audio/sound-fx/vintage-anime-sfx-158863


Here we have some basic sfx sounds
https://assetstore.unity.com/packages/audio/sound-fx/eastern-sfx-74043


All of the assets can be seen here:
https://assetstore.unity.com/top-assets/top-paid?category=audio&q=anime&orderBy=1&page=1
