### ISSUE TITLE
App: HTML DOM physics shape is wrong

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1643]
It should be the size of the HTML.

https://user-images.githubusercontent.com/6926057/138612693-dbfca873-b7eb-426e-9a16-dd4b7e9797e8.mp4

See `classroom.scn`

**Comment by yaserOSource** [comment]
How do you get this scene to show that html box?

**Comment by avaer** [comment]
Related: https://github.com/webaverse/app/issues/1730

**Comment by avaer** [comment]
It was showing up but not alpha-punching through.

**Comment by yaserOSource** [comment]
I see it in the world objects now after deleting classroom glb.


Now Im just trying to bring up that blue outline you had when you created the initial issue here. @avaer

**Comment by msm0823** [comment]
https://github.com/webaverse/app/issues/2984
