### ISSUE TITLE
App: Debug stats view

### ISSUE THREAD

**Issue by Loryhoof** [webaverse/app#1650]
We need some kind of performance monitor for in-game stats like FPS, draw calls etc.
Shouldn't be very hard to add. 

https://github.com/mrdoob/stats.js/

**Comment by ahadshams** [comment]
@Loryhoof whats the update on this one.. i thought it was already done

**Comment by ahadshams** [comment]
might be helpful for implementing advanced stats

https://github1s.com/mozilla/hubs/blob/HEAD/src/components/stats-plus.js

ignore the A-Frame ones..

![image](https://user-images.githubusercontent.com/44798013/141103150-efe0f70d-2996-4ee7-8968-e3de4a8bf47c.png)

**Comment by 0reo** [comment]
addressed in #2620, closing
