### ISSUE TITLE
Art: Weapons Retexturing for Drake

### ISSUE THREAD

**Issue by GaladWarder** [webaverse/app#1658]
Drake's weapons have been modelled already and are in the Drive: https://drive.google.com/drive/folders/1bJmebudUbGp5mZ2CMKSJEEpPp4pXcTKD?usp=sharing

but they need a retexture to bring them into the same world as the other weapons. 

Pull from the Styleguide: https://hackmd.io/@Galad/SJ_ibG18Y

And from some of the previous weapons we've made: https://drive.google.com/drive/folders/128bQhgaMBotN3KPUfLLGxojUuywjkiGs?usp=sharing

And retexture or tweak geo as needed to get these to look correct in the context of the Megasword or the Multitool.

**Comment by Sunny3D** [comment]
![image](https://user-images.githubusercontent.com/65556189/139674625-5deab5d5-e86f-4f6e-a7c9-dfb8cdb54bd7.png)
Update Progress for the weapon model retextures

**Comment by Sunny3D** [comment]
![image](https://user-images.githubusercontent.com/65556189/139674877-70e4a8e2-cf8c-4acd-8212-1ec45565294f.png)
Close up detail textures

**Comment by Sunny3D** [comment]
https://drive.google.com/drive/folders/1Q3fFZz6UbFT8_cONxFRNN-jhsB4IVVA1?usp=sharing
The files already updated here

**Comment by Sunny3D** [comment]
Next pertoday will start working on the remodel the pistol into SMG and retextures the model itself

**Comment by Sunny3D** [comment]
![red](https://user-images.githubusercontent.com/65556189/139846740-982c86d2-b064-4b90-a8d4-4e5c756e8a94.png)
This one is the red version of the drake shotgun

**Comment by GaladWarder** [comment]
These look awesome, strong work!

**Comment by Sunny3D** [comment]
![SMG_Drake](https://user-images.githubusercontent.com/65556189/140066955-f04b7e81-a283-45c3-9ece-3fe18ef4a3c6.jpg)
Updated model and UV map of the smg for the drake weapon

**Comment by Sunny3D** [comment]
![SMG_UZI](https://user-images.githubusercontent.com/65556189/140290611-0aef53fe-b319-447c-8608-8a83956c15b0.png)
Smg Model Textures updated pertoday
and the model been uploaded to the drive
