### ISSUE TITLE
Art: Documentation for each asset type

### ISSUE THREAD

**Issue by GaladWarder** [webaverse/app#1661]
We need docs for internal and external use on pipelines and export parameters of various assets.

@plankatron : Standard GLB asset documentation, FBX animation documentation as it applies to the Mixamo rig we are using.

@DreamCo: GLB environment creation and export documentation, including optimization and atlasing techniques. Also, any relevant export parameters for sets such as the Homespace.

@Vianvolaeus : Character creation and export documentation, especially as it applies to VRM exports.

@Fuji: Current manga panel creation pipeline, including brush settings, color palettes, and layout guidelines.

@GaladWarder : Concept art docs, including location and correct use of the concept templates and naming/VC system.

**Comment by plankatron** [comment]
fbx animation exporting : http://7rnx.net/fleeky-monotome/#webaverse/fbx_animation_export.md

**Comment by plankatron** [comment]
https://hackmd.io/yltwcS81TWWhXZsTszohbg <-- glb exporting 
https://hackmd.io/bt0Q7Y2hTYSgYK00Pg9iHw <-- fbx animation exporting
