### ISSUE TITLE
App: avatar animations do not use toes bone

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1663]
It would add slightly to the immersion to use that bone: https://github.com/webaverse/app/blob/36e31e00307a1522cee8d0ebaf46fcea25cba077/avatars/avatars.js#L2049

It mostly needs testing.

**Comment by avaer** [comment]
The animations should already have these bones ready for coyping: https://github.com/webaverse/app/tree/master/public/animations

**Comment by yaserOSource** [comment]
https://user-images.githubusercontent.com/51108458/140406718-9b35226b-a274-473b-9397-135415a46d2b.mp4

Ive added a video of how the avatar looks when the IK is enabled, (without toes for now).

It looks like its T-posing on the bottom half of the body @avaer

**Comment by yaserOSource** [comment]
https://user-images.githubusercontent.com/51108458/140409947-51167d62-b162-49f7-b7bb-153fbd8a3a45.mp4

So this video is how the toes look with IK

**Comment by avaer** [comment]
Looks ok to me. We wouldn't enable IK here but the toes should not look broken when we do 👍.
