### ISSUE TITLE
App: clean up keys on loss of focus

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1674]
Right now it is possible for ioManager to get stuck with keys down:

* Make sure you are not pointer locked
* Walk by holding WASD
* While still holding WASD, right click
* Character will keep moving, keys are not reset

https://github.com/webaverse/app/blob/68e17500e50b1cf767091a19681cf710c5f461be/io-manager.js#L52
https://github.com/webaverse/app/blob/68e17500e50b1cf767091a19681cf710c5f461be/io-manager.js#L66

**Comment by 0reo** [comment]
@ohmed is this UI related?
