### ISSUE TITLE
Animations: diving pose

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1685]
For this we need a simple dive loop. I couldn't find any such thing in the Mixamo repertoire.

![image](https://user-images.githubusercontent.com/6926057/139172006-ac50d256-affe-4160-bd34-6dcfbb2f1c8f.png)

The main requirement is that the body is generally angled down, so we could easily change the angle.

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/141222074-903619f3-00f9-4093-bfe9-f2533eb0dc70.mp4

**Comment by plankatron** [comment]
here is a test diving animation , currently the player is horizontal but can be rotated 90 to point down if required 

https://drive.google.com/file/d/1AtUv2hByY3g9yUR7ljm1crBEONv4BLYR/view?usp=sharing
