### ISSUE TITLE
App: 7-way walk/run blend

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1695]
It will be necessary to interpolate walk/run smoothly due to frame timing differences. We don't want to get into a mid-frame case where the run was triggered when we should have been walking. Smoothing the frame difference will look way better, and no longer look like it's glitched.

**Comment by avaer** [comment]
Run speed is currently an if statement in `avatars.js`: https://github.com/webaverse/app/blob/85507766f4d885456eb303d4d3b2d6a31e55d0cc/avatars/avatars.js#L2178

**Comment by avaer** [comment]
This is the code that would need to change: https://github.com/webaverse/app/blob/fff5eb51dbe255d7530990c91cdd69e8fbfb2f56/avatars/avatars.js#L1847

**Comment by skaljac** [comment]
Issue solve with
https://github.com/webaverse/app/pull/1947
