### ISSUE TITLE
Art: Updated Zone 0 Map

### ISSUE THREAD

**Issue by GaladWarder** [webaverse/app#1716]
Similar to https://matrixworld.org/map , but in the Webaverse universe. Outlining where land plots may be, and how the various parts of the zone fit together.

Scope currently confined to Zone 0

Need some info on end product - will this be a webpage? In engine? ahadshams

**Comment by avaer** [comment]
Note that we already have a map rendering system which uses the engine to dynamically tile the world (can be exported as images). Any scene laid out in engine should be supported with that.

A fully rendered scene/flyover is also possible.

Or maybe you guys wanted something more stylized?

**Comment by GaladWarder** [comment]
Ah yes - Via had mentioned that in the meeting, I am going to see what use Ahad has in mind for it, if a 2D map will work then we'll probably use the system already made. If it needs to be more stylized, we'll make a one-off asset for it.

Thanks for the heads up, you beat me to it! I was planning to dig through the github and see what the map rendering system was able to do. 🙏

**Comment by ahadshams** [comment]
cool..

i guess first order of business is to produce that map (what goes where)
we should utilise the map rendering system and then later do any visual / stylistic changes we want

**Comment by GaladWarder** [comment]
Alright, so this will be a 2D map, not a 3D one then, is that correct @ahadshams ? I just want to confirm since the example you linked was 3D.

Either way, I have already started on getting placements nailed down, so once I know for sure what end product you're looking for we'll get it made! Should be a super fun project

**Comment by ahadshams** [comment]
yes 2D map..its more like town planning / landscape architecture exercise at this point rather than how we render it.. if you know what i mean... :)

**Comment by GaladWarder** [comment]
This is updated - placement of landmarks is blocked in. There's a V1 going strictly off of the Synopsis, and a V2 with updates based on a brainstorm session and gameplay requirements.

https://drive.google.com/drive/folders/1ue_TSrzn8o2OOfUEwbicRFzGFiFSzWnN?usp=sharing
