### ISSUE TITLE
App: HTML planes punchthrough broken

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1730]
This is probably due to the post processing step not supporting a punch-through alpha strategy like we were using: https://local.webaverse.com/?src=.%2Fscenes%2Fclassroom.scn

Note that if you delete the classroom.glb (so you do not have any depth overwrite) then you can see the intended HTML page punches through the alpha: 
![image](https://user-images.githubusercontent.com/6926057/140010358-ded32b9b-0933-43d9-8238-d0b7f645cce5.png)

The scene can be edited: https://github.com/webaverse/app/blob/master/scenes/classroom.scn

**Comment by avaer** [comment]
The way the punch-through alpha (used to) work is that not only do we use a CSS matrix to position the DOM node, but we also render the equivalent plane in the world and make sure it clears alpha.

Then the dom node goes _undernerath_ the transparent canvas, with the hole perfectly punched though.

That was broken because something in our new post processing stack does not correctly pass through this alpha zero render.

**Comment by avaer** [comment]
Here is where we render the plane as well as manage the CSS matrix for this node: https://github.com/webaverse/metaversefile/blob/cf1021962fef13cd21c7680f864b7ea2ef7740d1/type_templates/html.js#L23

**Comment by skaljac** [comment]
Solved
