### ISSUE TITLE
Previews: faster than realtime video

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1765]
Right now in our preview logic (`screenshot.js`), we use [canvas `captureStream`](https://github.com/webaverse/app/blob/c519948461f597b0d797f185d0daa95108631681/screenshot.js#L706) to make videos in the preview system. Because we have no idea how fast/slow it will be to render, we pass `0` for the frame rate, we pre-render all frames into buffers, and we control the final composition of frames ourselves. Then we use [`requestFrame`](https://github.com/webaverse/app/blob/c519948461f597b0d797f185d0daa95108631681/screenshot.js#L733) to snap actual frames to video by drawing the buffers. We use a [`setTimeout` hack](https://github.com/webaverse/app/blob/c519948461f597b0d797f185d0daa95108631681/screenshot.js#L734) to time the frames at the frame rate we want.

This is already problematic because `setTimeout` is not actually reliable, it only means the time waited was _at least_ that much. When the page is not focused, we are heavily throttled so setTimeout waits a very long time, and the frame capture is completely busted when you focus back; this is pretty easy to reproduce.

But also, this means that rendering a 3s video is impossible in less than 3s, even if the hardware renders it instantly, due to how the API works and times things. Almost all of that time is wasted just waiting for timeouts so the API works.

Is there a way we can make our system work without introducing this pointless lag into the system just to please the API? I'd rather not do something crazy like use our own video encoder in WASM but that would probably fix this issue...

**Comment by avaer** [comment]
https://discourse.wicg.io/t/allow-non-realtime-use-of-mediarecorder/2308

**Comment by avaer** [comment]
https://github.com/GoogleChromeLabs/webm-wasm

**Comment by avaer** [comment]
My current top pick seems to be to use the webm wasm encoder for this specific case. Even though it's WASM and more bulk than we need, I still think it would be a large speed boost over the timeouts.

**Comment by avaer** [comment]
Another option is to use `WebCodecs` https://www.w3.org/TR/webcodecs/#video-encoder-config which is probably going to be the fastest and best version, with the possibility to use it in realtime constexts.

**Comment by abeersaqib** [comment]
Closing as issues is resolved using 

https://www.npmjs.com/package/webm-writer
