### ISSUE TITLE
Art: Nighttime Cubemap for Homespace

### ISSUE THREAD

**Issue by GaladWarder** [webaverse/app#1772]
We need a simple cubemap for the Homespace scene.

It should be a nighttime cubemap, night sky with faraway stars.

**Comment by GaladWarder** [comment]
[cube.zip](https://github.com/webaverse/app/files/7507686/cube.zip)

^ Example cubemaps for formatting

**Comment by GaladWarder** [comment]
Initial cubemap created: https://drive.google.com/drive/folders/11xp4F9svFCIiAyG4w89IPmMG4XFevSHM?usp=sharing

We have the .blend file as well, and can adjust it as needed

**Comment by plankatron** [comment]
here is a basic night time scene, 
[night_time.zip](https://github.com/webaverse/app/files/7508302/night_time.zip)
