### ISSUE TITLE
App: shaders.js shaders not ported to log depth buffer

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1773]
https://github.com/webaverse/app/blob/master/shaders.js needs to be ported to use log depth buf shader chunks.

This is currently causing things like tilde edit mode and the hit damage mesh to be depth-incorrect and glitchy.

**Comment by avaer** [comment]
I would assume that all shaders there need to be ported, if they are used by anything. We can trace their usage through imports.

**Comment by avaer** [comment]
This might also be a good time to clean up and document what all of these shaders are doing; they have clear purposes. Some of them aren't even that good and need to be rewritten.

**Comment by avaer** [comment]
Damage meshes are still broken after https://github.com/webaverse/app/pull/1792. Pick up the sword and use the regular hit mechanic.

**Comment by avaer** [comment]
Before this issue can be closed all of the shaders need to be tested again for regressions.

**Comment by yaserOSource** [comment]
Looking at testing the damage mesh, how does hit work again? You swing the sword and it should show a highlight mesh overalay right? I can see the object vibrating but no highlight. This is it right?

**Comment by avaer** [comment]
You should be able to go back in time before depth was changed to see it.

Use the sword to hit anything with the click to use mechanic when if ya equipped.
