### ISSUE TITLE
Apps: bugfix pixelsplosion depth buffer

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1774]
The explosions firing from our gun are a sub-app of https://github.com/webaverse/pistol, which is called  https://github.com/webaverse/pixelsplosion. Currently it is incorrectly depth sorted due to missing the shader chunks. We need to add the shader chunks.

Note that to work on this, you need to check out both `pistol` and `pixelsplosion`: https://github.com/webaverse/pistol/blob/3a1025a912d0eaf6acedb29a5aa5a429c135433b/index.js#L57

**Comment by avaer** [comment]
You can find the pistol at shadows.scn: https://github.com/webaverse/app/blob/d4a43f0da1b67471bf1c382de8b31f56a277b93a/scenes/shadows.scn#L150

**Comment by yaserOSource** [comment]
Merged 

https://github.com/webaverse/pixelsplosion/commit/ecb1f6e73eacfbd01a3c82809b4f58bebd9a0532
