### ISSUE TITLE
Apps: sprite-avatar is incorrectly depth-sorted

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1775]
The same issue as https://github.com/webaverse/app/issues/1774, but for https://github.com/webaverse/sprite-avatar

You can find this app at shadows.scn: https://github.com/webaverse/app/blob/d4a43f0da1b67471bf1c382de8b31f56a277b93a/scenes/shadows.scn#L79

**Comment by yaserOSource** [comment]
https://github.com/webaverse/sprite-avatar/pull/1
