### ISSUE TITLE
App parameter "physics" does not work

### ISSUE THREAD

**Issue by skaljac** [webaverse/app#1780]
If we change "physics" parameter in app description in .scn file, there is no effect

{
      "position": [0,0,0],
      "quaternion": [0,0,0,0],
      "physics": false,
      "start_url": "https://webaverse.github.io/canyon/canyon.glb"
    }

Physics is always turned on

**Comment by skaljac** [comment]
Physics parameter will work if we define it like this:
{
      "components":[{"key":"physics", "value":false}],
      "position": [0,0,0],
      "start_url": "https://webaverse.github.io/canyon/canyon.glb",
}

Should I make it work this way?

{
      "physics": false,
      "position": [0,0,0],
      "start_url": "https://webaverse.github.io/canyon/canyon.glb",
}

**Comment by avaer** [comment]
I think it should be a component `"components":[{"key":"physics", "value":false}],`, it makes sense within that framework.

**Comment by skaljac** [comment]
As suggested this is the way to disable physics.
Add this line in app description
"components":[{"key":"physics", "value":false}],

**Comment by avaer** [comment]
Thanks for the clarification, I didn't think this was already working but if it is then 👍.
