### ISSUE TITLE
App: https://webaverse.github.io/plant-particle/ required logdepthBuf_ fix 

### ISSUE THREAD

**Issue by yaserOSource** [webaverse/app#1785]
The shaders being used : three.quark.esm.js is missing common shader chunk which includes isPerspectiveMatrix

https://github.com/Alchemist0823/three.quarks

Will need to update it with the new common chunk and rebuild, and then update in repo

The other solution is editing three.quarks.esm.js directly which is unorthodox

**Comment by skaljac** [comment]
This is now solved
