### ISSUE TITLE
Site: fix low res texture

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1794]
For the site, we need the ground textures fixed. In some cases there is 0.2 texels per meter due to the UV map

![image](https://user-images.githubusercontent.com/6926057/141450454-ae202402-b8c9-4c04-b5ce-c68d29fcfe75.png)
![](https://i.gyazo.com/26678abf2f14944bb31c3433ed882bd4.png)

Later, this fix would be useful in engine.

**Comment by ahadshams** [comment]
@Tids pls make sure that this is fixed as part of our next release or asap.. the team has reworked on the textures.. 

https://github.com/webaverse/app/issues/1794
