### ISSUE TITLE
Screenshot.JS broken

### ISSUE THREAD

**Issue by abeersaqib** [webaverse/app#1800]
The recent screenshot system has removed the type variable from the system causing this error. 

![image](https://user-images.githubusercontent.com/5277220/141517295-9b44db97-1614-4fb6-b594-232afd2a5612.png)

**Comment by avaer** [comment]
Possibly fixed with https://github.com/webaverse/app/commit/a9dca2677f2820a82f7076d01b12750650dd4704

**Comment by avaer** [comment]
Confirmed that we can render with screenshot.js again: https://local.webaverse.com/screenshot.html?url=https://local.webaverse.com/avatars/gear.vrm&type=webm

![image](https://user-images.githubusercontent.com/6926057/141521111-6955e75e-ef4b-48e7-8ed9-edcf5f5c4cd2.png)
