### ISSUE TITLE
App: metaverse modules depth porting

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1801]
The metaverse modules (default apps we preload) all need to have the depth resolution in their custom shaders ported: https://github.com/webaverse/app/tree/master/metaverse_modules

Related: https://github.com/webaverse/app/issues/1773

**Comment by avaer** [comment]
This is `button`: 
![image](https://user-images.githubusercontent.com/6926057/141525557-fecbbe7c-4ff5-4168-bdbb-35b43b26e27c.png)

**Comment by avaer** [comment]
`arrow-loader`: 
![image](https://user-images.githubusercontent.com/6926057/141525971-1a09810c-795e-4976-afd4-fd8ae18fc280.png)

**Comment by yaserOSource** [comment]
https://github.com/webaverse/app/issues/1898

Linked
