### ISSUE TITLE
App: ramp shader depth porting

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1803]
![image](https://user-images.githubusercontent.com/6926057/141537968-cb53a061-fd12-457d-9a40-3e1017c5c633.png)

https://github.com/webaverse/ramp

Related: https://github.com/webaverse/app/issues/1776

┆Issue is synchronized with this [Jira Task](https://webaverse.atlassian.net/browse/EN-1770) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://webaverse.atlassian.net/secure/attachment/10004/Screenshot+2021-11-23+at+11.45.28+PM.png">Screenshot 2021-11-23 at 11.45.28 PM.png</a>

**Comment by avaer** [comment]
The above should have an arrow up the ramp.

**Comment by avaer** [comment]
This is still not fixed in `master` as far as I can tell, therefore reopening.

![image](https://user-images.githubusercontent.com/6926057/142951497-cd15e595-92d6-4e1e-b057-fb8f4d873c87.png)

**Comment by yaserOSource** [comment]
This is not a depth porting issue. Even with the Log Depth Buffer switched off this still occurs in the main scene 😵

<img width="811" alt="image" src="https://user-images.githubusercontent.com/51108458/142970665-47857a42-dbb0-40c4-a28b-fccbf5b7722d.png">

i see that both the stripe mesh and base ramp mesh are made out of the same geometry.  Could this be the issue..

**Comment by avaer** [comment]
It might have regressed during the post processing stack addition, which is what originally gave us the depth issues we needed logdepthbuf to solve. But this is definitely not a correct render.

> i see that both the stripe mesh and base ramp mesh are made out of the same geometry. Could this be the issue..
Yes that is probably it, but it is still depth related.

**Comment by yaserOSource** [comment]
This has now been fixed in this PR

https://github.com/webaverse/ramp/pull/2
