### ISSUE TITLE
Art: Origin Tablet redesign

### ISSUE THREAD

**Issue by GaladWarder** [webaverse/app#1808]
Redesign of Origin Tablets to pull them more into the current style. 

Feedback has been that they need to be more organic, less saturated overall.

Intending to go more in the direction of stone tablets with cryptographic and solarpunk properties.

**Comment by GaladWarder** [comment]
## Docs in Need of Update 
https://webaverse.notion.site/Webaverse-3a36b223e39b4f94b3d1f6921a4c297a

## Style References:
https://www.epicgames.com/fortnite/en-US/creative/docs/Attachments/What_is_Fortnite_Creative.pdf

http://www.macmothership.com/gallery/gallery3.html

https://medium.com/angularventures/the-long-road-to-creating-a-category-fc02e1616ed6

**Comment by GaladWarder** [comment]
Updated concepts, ready to take to model:
![origintablets_V2_galad](https://user-images.githubusercontent.com/29031531/141885091-90754ae3-a1e9-4a3d-81a5-c88a8ee5b39c.jpg)

@Sunny3D I'll leave this in your capable hands. Please set up the runes as a separate material so that we can add shaders easily in engine.

**Comment by Sunny3D** [comment]
![Untitled-1](https://user-images.githubusercontent.com/65556189/142422982-b3391bc4-739e-45db-a8ac-a51272cd0112.jpg)
Preview Update the base model and textures pertoday :)

**Comment by Sunny3D** [comment]
![image](https://user-images.githubusercontent.com/65556189/142621155-1df682a4-7ade-4d27-a4fb-599ec70f05c0.png)
Update Origin tablet base textures and model, and also adding the splatmap to seperate the rock and grass model

**Comment by Sunny3D** [comment]
![image](https://user-images.githubusercontent.com/65556189/142856280-5e92a131-b312-4027-b318-497d1671eed6.png)
![image](https://user-images.githubusercontent.com/65556189/142856319-45dcebfa-1d7c-4b19-b6cf-9564ed28716f.png)
Updated model pertoday the glb model already included the splatmap inside of it
