### ISSUE TITLE
App: no shadows lighting on avatars

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1811]
https://user-images.githubusercontent.com/6926057/141698302-c58ff029-693e-40a3-b4b5-07a3d7ca01f8.mp4

This was working before.

**Comment by Vianvolaeus** [comment]
Looks like that's an old version of the avatar. Current VRM version in the drive works fine. 
![image](https://user-images.githubusercontent.com/80061436/141698571-202d68ab-5d8a-4ca9-a1b1-ad7ada10a0a8.png)

**Comment by Vianvolaeus** [comment]
https://drive.google.com/file/d/1hz3n_JwwCl8YHprFmg21gaSokR6PZZCH/view?usp=sharing

Direct link if you need it.

**Comment by avaer** [comment]
Yup you're right, updated in `master` now. Thanks!
