### ISSUE TITLE
App/art: upgrade toon shader to improved MToonMaterial

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1817]
![width=200,height=183](https://cdn.discordapp.com/attachments/909925202106933288/909925259900223559/unknown.png)

The old ToonShader looks bad and did not take into account many features of the models materials such as outline, rim lighting, and other cool toon shading features

Now we have a new toon shader which looks better.

**Comment by avaer** [comment]
The toon tone mapping is controlled by tone map images files:

https://github.com/webaverse/app/blob/master/public/textures/threeTone.jpg (currently used)
https://github.com/webaverse/app/blob/master/public/textures/fiveTone.jpg (alternate)

These are used in the VRM toon shaderification material replacement: https://github.com/webaverse/metaversefile/blob/21780ec1513140259cf21b85327dafc8b2b927d0/type_templates/vrm.js#L48

**Comment by avaer** [comment]
We are not using the actual `three-vrm` toon shader: https://github.com/webaverse/metaversefile/blob/ee12bd7cb44cff801d21bda29cfe09613fd3034f/type_templates/vrm.js#L106

Perhaps we should try it: https://github.com/pixiv/three-vrm/blob/760b9ca07530537b527d07c886810830d46fb6fd/packages/three-vrm/src/material/MToonMaterial.ts

**Comment by yaserOSource** [comment]
You need to checkout the branch properly
