### ISSUE TITLE
Art: Silk Worms

### ISSUE THREAD

**Issue by GaladWarder** [webaverse/app#1821]
These will be the first enemies the player encounters, in the BR fields. 

They have a drop chance for SILK on kill. They should also feel like enemies, but not be overly scary - more of a farmable mob.

**Comment by GaladWarder** [comment]
![silkworm_concept_V1_galad](https://user-images.githubusercontent.com/29031531/142242633-5ea4c3df-90e6-47a2-aaf3-111dcda53939.jpg)
Initial concept

**Comment by Vianvolaeus** [comment]
![image](https://user-images.githubusercontent.com/80061436/142674173-a4c91b2c-a567-412e-8527-b1d276699ceb.png)

https://user-images.githubusercontent.com/80061436/142674192-48267b61-ef48-4046-8ab0-658c54f90e8b.mp4

This is mostly complete on the modelling end, has a simple rig - the blend is in drive for animating and further tweaks, which will come after engine tweaks to shaders.
