### ISSUE TITLE
Logistics: rename metaversefile

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1827]
https://github.com/webaverse/metaversefile

The repo is named after the file but the repo is really implementing a loader, not the file format.

Moader? Metaverse loader.

**Comment by avaer** [comment]
The top vote was for Totum.

![image](https://user-images.githubusercontent.com/6926057/144090291-eee02ff9-2912-48f1-8df8-2bbc25f0d4f5.png)

**Comment by amnaarshed4224** [comment]
implemented
