### ISSUE TITLE
App: sit positions broken

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1841]
![image](https://user-images.githubusercontent.com/6926057/142857619-65ba8bb8-ea31-4618-9c76-fc6df5455032.png)

This regressed recently, probably due to massive avatar skeleton refactors.

┆Issue is synchronized with this [Jira Task](https://webaverse.atlassian.net/browse/EN-1765) by [Unito](https://www.unito.io)

**Comment by avaer** [comment]
The fixes were merged, this needs verification before closing the issue.

**Comment by Vianvolaeus** [comment]
Appears to be working fine. 

![image](https://user-images.githubusercontent.com/80061436/143258360-69952d29-17af-4b3f-8e05-b71d7528cafe.png)

**Comment by avaer** [comment]
Thanks, I saw it working fine too.
