### ISSUE TITLE
AI synthesis prompt codeset

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1846]
Relatively secret Webaverse feature: you can talk to your weba client and have things happen in the world magically. We integrate OpenAI Codex with a custom prompt that explains how to use the metaversefile API, and on invocation it gives us the runnable `app` code which we can load in the world, which makes the thing happen.

One of the main goals of the meteversefile api is to be AI-driven in this manner (possibly by voice), and this already works quite well for queries similar to examples provided in the prompt.

However, the prompt is limited in size so there is a limited set of things we can teach Codex to do at a time. While there is plenty of room to teach Codex about teleportation for example, we have many other concepts that we want to support. A single prompt isn't enough to teach the entire API surface very well.

To make this truly mindblowing, we need a testable, curated, and labeled codeset full of the useful kind of code we want to be able to support, and then we should run a preliminary, fast fulltext search over this (using the user's query as a key) to build the best prompt we can for the examples that are relevant to the query. Then this optimal prompt is shipped off to the AI and we should get amazing results no matter the query.

This codeset should also be 100% tested with our testing framework, on a mocked metaversefile api, to make sure all apps are actually valid. That would free us to make basically unlimited examples, and each one would add to our confidence in the API while making the AI smarter.

Whoever takes this on would probably need to be comfortable with understanding, redefining, changing, and debugging the metaversefile api, since I am sure we would need to change it to better support these AI queries, but it would be quite a fun job.

Posterity note: metaversefile and the api are probably going to be renamed

**Comment by avaer** [comment]
https://github.com/webaverse/app/blob/master/ai/ai-prefix.js

**Comment by abeersaqib** [comment]
Taking up the task as it's quite fun and interesting. 
For the first step, I will go through the Prompt flow end to end. The task's code set's expansion will also a lot of debugging in the metaverse file.

**Comment by abeersaqib** [comment]
Running into error during model load. Debugging and working on and then move to the other codesets one by one. Started with the task today will be working on the weekend too on it. 

![image](https://user-images.githubusercontent.com/5277220/143660662-f360ead6-dab2-48b2-98ba-3aa3af099add.png)

**Comment by avaer** [comment]
It would be helpful to paste the line. Looks like the app has no `contentId`?

Also the header should probably not be being loaded for this, we don't need UI running in this test.
