### ISSUE TITLE
Get rid of Jira/Unito comments in GH

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1862]
It seems the entire GH has been polluted by Jira notifications.

Can we get rid of that and remove all of the pollution? 

![image](https://user-images.githubusercontent.com/6926057/143246763-7d8e67a2-5b8f-48b8-8740-e90031f0d02d.png)

**Comment by avaer** [comment]
All of those notifications should be removed from existing issues. There is really no reason for that to be there.

**Comment by avaer** [comment]
We should also revoke permissions of the bot so it cannot make this mess again.

**Comment by ahadshams** [comment]
its done... Jira comments are not synced with gh now..

**Comment by avaer** [comment]
I still see the messages on the issues.
