### ISSUE TITLE
Animation : Grab Animations

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#1873]
here is a set of grab animations , they are a first draft , not a final draft. they will need coder support in engine to be able to test all of them. 

* grab_forward
* grab_down
* grab_left
* grab_right
* grab_up
https://drive.google.com/drive/folders/1BbOrhq70V2fJm10lwbUJnULviK-VU66s?usp=sharing

**Comment by skaljac** [comment]
I have send request for access.

**Comment by skaljac** [comment]
Implemented with
https://github.com/webaverse/app/pull/2061
