### ISSUE TITLE
Physx: make build steps clean

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1874]
The suffixing edits in the app-wasm build steps can be automated, making the physx build more appealing to edit.

**Comment by avaer** [comment]
https://github.com/webaverse/app-wasm/blob/master/README.md#use-it-in-webaverse

**Comment by Loryhoof** [comment]
Yeah it's pretty annoying, will fix.

**Comment by Loryhoof** [comment]
https://github.com/webaverse/app-wasm/pull/8
