### ISSUE TITLE
App: error in fresh build

### ISSUE THREAD

**Issue by madjin** [webaverse/app#1888]
someone said they had error when trying to run app, did a fresh build on ubuntu server and got this error after running `node index.mjs`
![image](https://user-images.githubusercontent.com/32600939/143940247-4bddf86e-767f-4876-b4ff-c2f047437d2b.png)

**Comment by avaer** [comment]
Looks like an older node version? (needs 16+)

**Comment by madjin** [comment]
changed to node 16 via nvm, then I noticed it was a permission error so I started the app using sudo and it worked
a friend is having similar issues but in his case the address is already in use
seems possible to change port in line 60 of index.mjs to workaround

**Comment by avaer** [comment]
Should use 3000 now.
