### ISSUE TITLE
App: footstep sound effect synchronization

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#1909]
Description: 
There is still lack of sync between footsteps sound and animation. It turns out it can be an fps dependent issue.
One example attached. I will attach more examples soon.

Related PR:
#1864 

https://user-images.githubusercontent.com/35926530/144501937-375b1924-0b10-4e21-9e6b-1c95a22b3056.mp4

**Comment by ahadshams** [comment]
also @skaljac i noticed that naruto run has the same footsteps as normal run

**Comment by amnaarshed4224** [comment]
being redone.
