### ISSUE TITLE
App: fix VRM toon shader

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1914]
we want to use the vrm shader for avatars which request it. Totum performs our material swap: https://github.com/webaverse/totum/blob/main/type_templates/vrm.js#L42

We had it working but the toon shader implementation was reverted due to showstopper scene switch bugs in `master`: https://github.com/webaverse/totum/pull/34

We should re-enable the vrm toon shader and make it work with scene switches (so it does not crash).

**Comment by yaserOSource** [comment]
being updated here:

https://github.com/webaverse/totum/pull/45
