### ISSUE TITLE
NarutoRun + crouch

### ISSUE THREAD

**Issue by skaljac** [webaverse/app#1918]
Naruto Run from crouch mode should not be possible.

Steps to reproduce:
Press C for crouch mode
Press Double shift to activate Naruto Run

This is how it looks

https://user-images.githubusercontent.com/4487857/144668920-1593486b-5b10-4ff9-9f24-135f2f8410a8.mp4

**Comment by avaer** [comment]
Related: https://github.com/webaverse/app/issues/1938

**Comment by skaljac** [comment]
Implemented in https://github.com/webaverse/app/pull/1995
