### ISSUE TITLE
App: Mid air Walk/Run while flying

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#1919]
While flying if F is pressed, instead of falling down directly, the avatar can walk/run if W or Shift+W is kept pressed.

https://user-images.githubusercontent.com/35926530/144669791-22561a66-379c-4ec1-8bcf-a1499fd50762.mp4

https://user-images.githubusercontent.com/35926530/144669808-063bc6c1-e17b-4263-bc9a-b37b9e50844b.mp4

**Comment by skaljac** [comment]
I can confirm this bug:

Steps to reproduce:
Press W all the time
Fly up with one press on F
Then, in air - press F few times and player will walk in air

**Comment by skaljac** [comment]
Solved with new CCD system
https://github.com/webaverse/app/pull/1954
