### ISSUE TITLE
app: First Person View

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#1920]
The First person view seems really odd while running/walking. The body should not appear like this. Either there can be hand movements only.

https://user-images.githubusercontent.com/35926530/144670192-1c7f884f-fc5c-44ff-8898-9dfc745cca3b.mp4

https://user-images.githubusercontent.com/35926530/144670144-66729ad8-296f-4fff-83af-053c926f337f.mp4

**Comment by skaljac** [comment]
Duplicate:
https://github.com/webaverse/app/issues/1609

**Comment by amnaarshed4224** [comment]
Right. The View while Running needs a fix too.

**Comment by avaer** [comment]
Closing in favor of #1609, it is a dupe
