### ISSUE TITLE
app: Slipping while Walking.

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#1921]
The walk of avatar if watched closely appears as if it is slipping through the steps it takes.

https://user-images.githubusercontent.com/35926530/144670483-a0cd40fe-cac5-43cc-8ea9-5d6055ac3097.mp4

https://user-images.githubusercontent.com/35926530/144670437-bbff172d-14be-438a-9764-254db536543d.mp4

**Comment by avaer** [comment]
Good catch.

The walking and animation speeds need to be synchronized. This is a matter of tweaking either or both constants. I would vote to keep the current movement speeds roughly the same, since they are chosen for good game feel. The animation speed can be changed to match the movement.

**Comment by avaer** [comment]
This should be better in the latest, where the walk speed has been reduced to feel nicer with the character controller.

**Comment by amnaarshed4224** [comment]
Improved.
