### ISSUE TITLE
APP : Crashes during scene switch. 

### ISSUE THREAD

**Issue by torchesburn** [webaverse/app#1925]
Switching scenes, go to darkness, then switch to shadows then go street and back to shadows, and eventually it will pop.

![image](https://user-images.githubusercontent.com/51108458/144722692-d71697e9-00fc-4bf5-87cb-41ea755508d1.png)

Tested on master e99d2ae

**Comment by yaserOSource** [comment]
Happens on recent master e99d2ae68b1ceacd9ab6b417501e07b1151d3f48

**Comment by yaserOSource** [comment]
![image](https://user-images.githubusercontent.com/51108458/144723173-3d0d55ed-0af0-43f5-b7f8-313b625c98bd.png)

**Comment by yaserOSource** [comment]
![image](https://user-images.githubusercontent.com/51108458/144748445-40896c91-8e91-434c-8832-9d0005572c61.png)

**Comment by yaserOSource** [comment]
![image](https://user-images.githubusercontent.com/51108458/144748646-7a60fa66-4587-43d6-9450-751f2591c87a.png)

**Comment by yaserOSource** [comment]
switching to treehouse and this jar seems to be an issue

**Comment by yaserOSource** [comment]
![image](https://user-images.githubusercontent.com/51108458/144749380-88ff5679-bc80-47cd-97d8-3b425831134f.png)

**Comment by yaserOSource** [comment]
![Uploading image.png…](

tested on https://github.com/webaverse/app/commit/e99d2ae68b1ceacd9ab6b417501e07b1151d3f48

**Comment by avaer** [comment]
The jar morph issue seems a separate issue. It happens whenever you load the jar, and doesn’t seem to have any effect beyond this warning.

**Comment by avaer** [comment]
Losing context is usually a resource limit issue. It could be we are just loading things and not cleaning them up, and when we run out of memory we get this crash.

One good idea might be to detect the context being lost and throw up an error screen with the error, asking the user to refresh.

**Comment by avaer** [comment]
We can find out if it is a resource issue with profiling and memory leak analysis.

Leaks might be fixable by caking threejs dispose methods.

**Comment by yaserOSource** [comment]
I’ll do some profiling and find out

**Comment by yaserOSource** [comment]
App cleanup will be a good place to look, I’ll also debug the type templates

**Comment by yaserOSource** [comment]
![image](https://user-images.githubusercontent.com/51108458/144952159-389ad828-684c-4736-965b-d69bfcb0572b.png)

**Comment by yaserOSource** [comment]
![image](https://user-images.githubusercontent.com/51108458/144952344-c969a054-bb4d-4ed1-a187-b72419e1008d.png)
 2/2
