### ISSUE TITLE
Crash during equip (wear) event on lantern

### ISSUE THREAD

**Issue by yaserOSource** [webaverse/app#1926]
![image](https://user-images.githubusercontent.com/51108458/144722734-8f0ac49c-0989-4044-9461-d5285a8baa8b.png)

**Comment by avaer** [comment]
This could/should have been detected with test infrastructure which reports app use failures.

Unfortunately that is still not done.

**Comment by amnaarshed4224** [comment]
Duplicate :
https://github.com/webaverse/app/issues/1825
