### ISSUE TITLE
Login UX problems

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1932]
The login UX looks bad right now.

Clicking Metamask and closing the MM window will keep on "Logging in..." text.

![image](https://user-images.githubusercontent.com/6926057/144734128-b7d00a3a-f82e-4ec4-bf37-377f389b56f5.png)

There is a style layout shift/FOUC every time we open the login options. This is probably due to the images and us recreating the image nodes each time?

![image](https://user-images.githubusercontent.com/6926057/144734176-772b230b-c75d-4266-9e82-0e726ebadae4.png)

The login options seem separate from the login UI in a very weird way. The animations are not connected at all.

![image](https://user-images.githubusercontent.com/6926057/144734149-90e58945-a996-4b0c-a29e-a5e94a897cf6.png)

**Comment by 0reo** [comment]
closing in favor of #2640 and #2647
