### ISSUE TITLE
App: UI redesign

### ISSUE THREAD

**Issue by avaer** [webaverse/app#1937]
We need to do a full UI design pass on the app. This has many dependencies before it can be successfully executed, like:

* the sidechain
* caching server working
* local iframe preview engine
* preview server working

However, we can start a serious design/mockup pass right now. The goal is to have a very gamelike experience in terms of smoothness and accessibility, though we can probably accomplish most of this with well designed DOM elements in SVG.

The first step might be to take what we have an design a clean game interface around it.

IMO the things we should be inspired by are actual game UIs, from actual games (not mobile games or web sites).

**Comment by 0reo** [comment]
@ohmed this is set to In Progress, but it's also 3 months old and some of this may have been addressed elsewhere.  If this is in progress, please reference the PRs and/or other issues addressing this.  Otherwise, 
- please remove from in progress
- let's reconfirm the scope of this issue
