### ISSUE TITLE
Fox is physics-less when equipped

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#1949]
The fox rn is physics-less when equipped. Avater can pass through it. Also If more than one fox are equipped,(One form one scene and 2nd from another scene) They appear as if merged into each other(appears as if its one fox with 8 legs)

https://user-images.githubusercontent.com/35926530/145096041-e0d424fe-ee49-4e67-bdcc-5dd3fca54116.mp4

**Comment by aryasalehi** [comment]
Fixed : https://github.com/webaverse/fox/commit/b850b02b7aa2e8d4ec8dcef347f1d0d96d8c1ce8

**Comment by aryasalehi** [comment]
Actually the fox has physics it's not activated, but when we "wear" / "activate" the fox it becomes physic less 
REOPENING
