### ISSUE TITLE
animations: Climb against vertical slopes

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#1953]
Climbing against vertical slopes appears a bit odd. It needs to be fixed someway by either not allowing the avatar to climb vertically or by adding some animation for vertical climb

https://user-images.githubusercontent.com/35926530/145103206-7568a5e7-6dae-40b7-a089-4372dbc34b8c.mp4

.

**Comment by avaer** [comment]
Should be fixed with the new character controller.
