### ISSUE TITLE
Movement speed is reduced on devices with low FPS

### ISSUE THREAD

**Issue by skaljac** [webaverse/app#1960]
Movement speed is not the same on all devices.
It is in relation to FPS on that device.

https://user-images.githubusercontent.com/4487857/145310941-2ffe36c9-bfdc-426a-aab4-46fb86caea9b.mp4

**Comment by amnaarshed4224** [comment]
Yes I can confirm this and on devices with fps somewhere around 10-15, There is no run animation. It just starts walking a bit more fast when shift is pressed.

https://user-images.githubusercontent.com/35926530/145439004-5733acc0-af65-4a38-a285-4c6befa7c2e2.mp4

.
