### ISSUE TITLE
app: Avatar falls on naruto run

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#1962]
The naruto run seems to be working without any physics, it works for flat surfaces. On areas with slopes such as shadows scn's dunes, The avatar falls down the floor.
Steps to reproduce:
-Switch to any scn with slopes(shadows)
-press shift twice facing towards the dunes

https://user-images.githubusercontent.com/35926530/145467024-74124115-aaf7-4298-8d9d-5320e9271d8a.mp4

**Comment by Loryhoof** [comment]
Was fixed with https://github.com/webaverse/app/issues/1610
