### ISSUE TITLE
app: no shadows while switching scenes

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#1975]
While switching scenes, Object shadows don't get loaded in any of the scenes. Reloading the scene loads the shadows and they appear fine.
Steps to reproduce:
Go to street scene
Switch to any of the scenes with shadows(prototype,grid,shadows)
reload the scene by refreshing the page.

https://user-images.githubusercontent.com/35926530/145690752-a1579742-4eb8-45f1-9b92-14e1359c2bf1.mp4

no object shadows After switching scene from street to shadows:

![shadowsissu2](https://user-images.githubusercontent.com/35926530/145690781-7f937dbb-733e-41cc-8711-a151ac3aad9d.PNG)

Shadows appear after reloading the page:

![shadowisu](https://user-images.githubusercontent.com/35926530/145690790-096a0c03-b634-43c5-a976-a4e74da35fda.PNG)

**Comment by avaer** [comment]
I don't think this is a bug. Shadows are part of the scene config. While the scene is changing there is no defined shadows because nothing is loaded.

I think this can be cleaned up by having a better transition between scenes, and adding our zone loading interstitials.
