### ISSUE TITLE
Geometry WASM / Character-physics errors in master 

### ISSUE THREAD

**Issue by yaserOSource** [webaverse/app#1985]
commit hash af027f65ee22ba887152e144d71891bc25a0baa9

![image](https://user-images.githubusercontent.com/51108458/145871179-06469abd-0b69-4552-b110-08c12e5a511a.png)

Happens on load

**Comment by avaer** [comment]
I think I know what might be happening. If the bones math is wrong, the height could be NaN or undefined, which would indeed create an incorrect character capsule: 
![image](https://user-images.githubusercontent.com/6926057/145879017-47ff6dc0-6a27-4895-8b29-6aa48d839b66.png)

**Comment by yaserOSource** [comment]
Ok got it
