### ISSUE TITLE
app: Avatar passes though certain objects

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#1992]
Avatar still passes through certain objects while flying. Examples attached

https://user-images.githubusercontent.com/35926530/145878227-01a5a9fe-c67f-4756-9128-6319ed6d31ca.mp4

https://user-images.githubusercontent.com/35926530/145878250-5d0ece31-46f2-4b0d-8c07-5caad2770dd3.mp4

.

**Comment by ahadshams** [comment]
reproducible with these objects only.. could be a backface / frontface related issue?
