### ISSUE TITLE
street.scn ground missing

### ISSUE THREAD

**Issue by Loryhoof** [webaverse/app#2037]
Ground not spawning on https://app.webaverse.com/

**Comment by avaer** [comment]
That app is not maintained and is several months old.

**Comment by avaer** [comment]
We should at least include the stack when opening bug reports.

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/146723023-ad3c3515-0ad3-44bd-9843-43bb43a9f800.png)

**Comment by avaer** [comment]
I redeployed the alpha in the meantime.
