### ISSUE TITLE
Utils: port over mesh cut code

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2045]
https://github.com/exokitxr/mc-wasm/blob/3e67da300269d3783db2511f44dbddc67c18b75d/cut.cc#L5

It's needed for some combat special effects.

**Comment by avaer** [comment]
1. We should port over that code, including the dependencies, into `app-wasm`.
1. We should get the mesh cut APIs working with a test app.
1. We should add uv tracking and interpolation support to the C++, so we can keep textures when we cut meshes; I've done this before but I can't find the code for the edit. Essentially we can add uvs tracking to the structure: https://github.com/exokitxr/mc-wasm/blob/3e67da300269d3783db2511f44dbddc67c18b75d/xs/src/libslic3r/TriangleMesh.cpp#L45
and then interpolate the uvs during the slice when generating the split triangles: https://github.com/exokitxr/mc-wasm/blob/3e67da300269d3783db2511f44dbddc67c18b75d/xs/src/libslic3r/TriangleMesh.cpp#L752

**Comment by skaljac** [comment]
1. is done here:
https://github.com/webaverse/app/pull/2117
and here
https://github.com/webaverse/app-wasm/pull/16

2. is done here:
https://github.com/webaverse/mesh-cut-example

**Comment by skaljac** [comment]
Sphere cut in half

https://user-images.githubusercontent.com/4487857/147933750-265e737b-71b5-4606-8e4e-90553162f6b6.mp4

**Comment by avaer** [comment]
Here is really great work by @gonnavis synthesizing the solution in JS. https://github.com/gonnavis/annihilate/blob/a538d8cd0dffefb4d6d1a618703b1e3b15311040/src/index.js#L57

It could be ported to C++ but it's probably already good on its own.

We should have a `webaverse-toolkit` repo to collect these utilities. We can import that module from webaverse core.

**Comment by avaer** [comment]
New repo for the purpose: https://github.com/webaverse/metaverse-utils

We can make it a package here: https://github.com/webaverse/app/tree/master/packages
