### ISSUE TITLE
app: Pistol aim animation while walking/running

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2066]
Currently, aiming through pistol and walking/running simultaneously, is not smooth. It is jerky.

https://user-images.githubusercontent.com/35926530/147289318-da92ec33-18b7-4329-85f5-3c3feb1e6627.mp4

**Comment by skaljac** [comment]
I believe I know what is thee problem.
I have encounter this problem in in this PR
https://github.com/webaverse/app/pull/2031/files

It is about CharacterPhysics this.updateCamera(timeDiffS);
this have to be called after avatar update function.

I believe this is solution for it.

So when we apply First person model clipping / FPS neck model PR this will be solved also.
