### ISSUE TITLE
App: forest scene broken

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2083]
![image](https://user-images.githubusercontent.com/6926057/147420013-4d18d784-b476-42e8-ac72-8adbfafda94f.png)

**Comment by ahadshams** [comment]
if its done, can we close the issue pls

**Comment by amnaarshed4224** [comment]
It is still broken, the grass is separate from rest of the scene

![1112](https://user-images.githubusercontent.com/35926530/147973601-a8061585-83ac-4b47-86b0-a8dd0a9db256.PNG)
![1113](https://user-images.githubusercontent.com/35926530/147973610-5ab62b24-b663-46ac-9ecd-e16dc04571e6.PNG)
.

**Comment by avaer** [comment]
This scene was removed for now; I think the functionality will go in the silk-fountains scene.
