### ISSUE TITLE
Cannot grab objects when in first person

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2087]
![image](https://user-images.githubusercontent.com/6926057/147474240-35e60605-32d6-44a0-96f5-21baab402219.png)

It works fine in third person, but something is wrong with the first person math.

**Comment by amnaarshed4224** [comment]
I guess its an issue of angle of grab at which 'E' appears.
as in the video, Grab button appears at a certain angle in first person but not appears at other angles.

https://user-images.githubusercontent.com/35926530/150345224-6502fca3-dd49-4fd3-a97d-f7f038420645.mp4
