### ISSUE TITLE
app: Avatar direction in first person

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2099]
avatar usually faces backward(Towards the camera) while walking running backwards('S' key). While as we move into first person the avatars direction changes towards front.(Still towards the camera) I am not sure if this is an issue and what could be the alternate solution. Maybe We should sync the directions in both first person and distant view.

https://user-images.githubusercontent.com/35926530/147589232-602e3cff-25a8-4764-a58d-039d315d135f.mp4

.

**Comment by avaer** [comment]
Looks correct to me. In first person mode it is assumes to avatar's head should be pointing where you are looking. This is a feature, not a bug.
