### ISSUE TITLE
Going into `air` state too often when downhill.

### ISSUE THREAD

**Issue by gonnavis** [webaverse/app#2104]
Hello, I found that when player downhill, even gentle slopes, will into `air` state too often.

![image](https://user-images.githubusercontent.com/10785634/147603237-a8a66fb9-12b3-4850-a326-2f289305dd68.png)

**Comment by amnaarshed4224** [comment]
Duplicate:
https://github.com/webaverse/app/issues/2006

**Comment by amnaarshed4224** [comment]
duplicate #2006
