### ISSUE TITLE
App:  E selector requires items to be raised off of the floor

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#2125]
`E` selector seems to not work with items on the floor, it requires items to be pretty high off the floor. This makes selecting impossible when items are smaller and are being picked up off the floor.

https://user-images.githubusercontent.com/29695350/147862863-0944445f-b3aa-4d2f-be51-bfe4819a68dd.mp4

**Comment by avaer** [comment]
It is collision based, with a capsule in front of the player which must collide. This could be made smarter, but if you don't control collisions with the floor (go all the way down) then you will always be using the floor object.
