### ISSUE TITLE
App: World editor uses rotation, scn uses quaternions

### ISSUE THREAD

**Issue by softwarebyai** [webaverse/app#2126]
The `Z` world editor menu makes editing scenes (`scn`s) a lot easier, the one thing that is tricky is the world editor allows editing a rotation vector, but `scn` uses quaternions and does not seem to use a `rotation` field.

**Comment by 0xmetabad** [comment]
It might be better to use either rotation or quaternion to be able to easily port over the values from the editor to the scn file.

**Comment by avaer** [comment]
I think ideally there is a mode switcher in the UI. The problem is that eulers are terrible for storage, and quaternions are terrible for display and editing (not obvious to interpret).
