### ISSUE TITLE
App: Lag when near multiple selectable assets

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#2128]
It looks like having a lot of selectable assets in close proximity of each other causes some heavy computing, it looks like it might be related to the selector logic.

Scene: https://app.webaverse.com/?src=https%3A%2F%2Fshop.metabad.com%2Fshop.scn

https://user-images.githubusercontent.com/29695350/147863119-7762a44c-2980-467e-acbe-c208da8bcc56.mp4

**Comment by avaer** [comment]
I was trying to debug this but could not repro since most of the donuts have been eaten.

![image](https://user-images.githubusercontent.com/6926057/148136819-a71f929d-1cd7-4f8a-aa90-e05a7632a68e.png)

**Comment by 0xmetabad** [comment]
Re-added donuts, new shop.scn should be deployed to GH pages: https://github.com/metabad-org/shop/commit/69c55fed5a79efece64a7c33f28aaa9f414bae5e

Viewable again at https://app.webaverse.com/?src=https%3A%2F%2Fshop.metabad.com%2Fshop.scn

**Comment by avaer** [comment]
Thx!

I'm actually seeing that physx collision is taking forever, which makes me think there is something wrong with the way this geometry was constructed.

We usually see this problem when we try to put 10MB of geometry at the origin, and physx must walk 10MB of vertices to collide the face.

**Comment by avaer** [comment]
Looks like 1MB for the donut, all of which is contained in the collision capsule and therefore affects its collision. This case can probably be detected/fixed at the physx level.

**Comment by 0xmetabad** [comment]
> 1M vertices for the donut

Thanks for looking into this.

I didn't try to optimize these at all, I just noob-ily made these in sculpting apps and exported them. That's a lot of extra vertices calories in those donuts.

I think new 3d modelers or people coming into Webaverse new to 3d items in general might do the same thing, import models from sketchfab or sculpt on an app with no regards for optimizing the assets.

Most people know gifs / images should be under 40mb, 100mb would be a huge image, but that isn't so obvious coming into 3d.

Maybe we could help educate users / new 3d builders to what good numbers are. Or block them like Discord:
![image](https://user-images.githubusercontent.com/29695350/148144414-0c9ea7c4-2bff-4caa-b801-4fec9a4ec541.png)

**Comment by avaer** [comment]
Actually I consider this more a physics bug. You're not the first person or last to hit it.

I'll just invent a smarter algorithm that doesn't need to know the penetration depth. I'm pretty sure I can get physx to bail on this physics test and be quite fast.

**Comment by avaer** [comment]
The bug is that this call is inherently slow if all vertices collide: https://github.com/webaverse/app-wasm/blob/ea126e2a1f0b374d5393f31c38d96fe0ffad6340/physics.cc#L1154 (you cannot get the correct result without looking at all the vertices by definition).

But we don't need to do that, we can simply check collisions and sort more intelligently, if we do not actually want to restitute the capsule (and in this case we don't).

**Comment by avaer** [comment]
I fixed one of the slow functions in https://github.com/webaverse/app-wasm/pull/18, but now moving the character is running into the same problem, where in the worst case we need to look at a ton of vertices.

![image](https://user-images.githubusercontent.com/6926057/148165470-36f13165-763f-4238-8013-4d613729ccb4.png)

I think the way we will fix this is to detect this crazy case (very small geo with tons of vertices) and error out of creation of the physx geometry.

Then totum can handle that case and replace the geometry with a capsule of similar size, so it still kind of works. If you have that small of an object, the vertices are probably not even useful to use.

**Comment by avaer** [comment]
https://github.com/webaverse/app/pull/2158

**Comment by ahadshams** [comment]
> Maybe we could help educate users / new 3d builders to what good numbers are. Or block them like Discord:

I think it will be very cool if we can actually show (optional) some of the perf numbers when you upload a model (drag and drop) or publish a scene

Inspiration from Mozilla spoke below:

![image](https://user-images.githubusercontent.com/44798013/148205769-6428fbde-4ae0-4fd9-9bfc-94c08dc5bb44.png)
