### ISSUE TITLE
app: Footsteps sound 

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2139]
Currently in app.webaverse.com and master there is sound for jump but sound for footsteps is not consistent. Most of the time there is no sound for footsteps, but it randomly has sound sometimes. in video below sound can be heard from 19 sec onwards.

https://user-images.githubusercontent.com/35926530/147948194-8525a1f9-be64-4b3e-99a2-5dda36b13645.mp4

**Comment by avaer** [comment]
Yes, the footsteps are broken. The improvement PR (https://github.com/webaverse/app/pull/2025) did not make it out of WIP.
