### ISSUE TITLE
app: CCD for forest scene

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2142]
Currently, The forest scene seems to be without any kind of physics. The avatar can pass through all the objects as if they don't exist. Also there is no camera view switching when obstacle comes in the way. It seems to be like a pre CCD scene.

https://user-images.githubusercontent.com/35926530/147974028-4128f46f-0f95-4853-9d91-802a30642acc.mp4

**Comment by avaer** [comment]
This is really old, I'm going to remove this scene.

**Comment by avaer** [comment]
https://github.com/webaverse/app/commit/c15515af39f45efa0b5eb75d8d94e7b65658b399
