### ISSUE TITLE
Latest screenshot.js is broken

### ISSUE THREAD

**Issue by abeersaqib** [webaverse/app#2150]
The recent screenshot.js is broken after the recent updates made in last few days.

Two bugs happened in the system currently.

* fitCameraToBox commented out in util.js 
* After uncommenting the metaversefile-api throws an error

**To reproduce the error:**

- Run the application in dev mode
- Visit. 
[http://localhost:3000/screenshot.html?url=https://webaverse.github.io/assets/male.vrm&hash=screenshot&ext=vrm&type=png&width=1000&height=1000](http://localhost:3000/screenshot.html?url=https://webaverse.github.io/assets/male.vrm&hash=screenshot&ext=vrm&type=png&width=1000&height=1000
)

![image](https://user-images.githubusercontent.com/5277220/148089280-f1d3f384-ff6b-4b00-a05c-f02d96116e4b.png)

![image](https://user-images.githubusercontent.com/5277220/148088997-d9b05490-94b2-4b7b-8553-f7aa9a30c3ca.png)

**Comment by avaer** [comment]
This issue does not provide a repo case.

**Comment by avaer** [comment]
Repro case was still not posted, but it was provided in Discord:

```
https://localhost:3000/screenshot.html?url=https://webaverse.github.io/assets/male.vrm&hash=screenshot&ext=vrm&type=png&width=1000&height=1000&dst=http://127.0.0.1:8999/3
```
```
https://local.webaverse.com/screenshot.html?url=https://webaverse.github.io/assets/male.vrm&hash=screenshot&ext=vrm&type=png&width=1000&height=1000&dst=http://127.0.0.1:8999/3
```
