### ISSUE TITLE
app: Browsers compatibility 

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2151]
Currently, the app doesn't works on Firefox due to webworker modules.

![fffff](https://user-images.githubusercontent.com/35926530/148108300-faac46e9-fa9c-446c-bdfe-06261d8a5ccd.PNG)

**Comment by yaserOSource** [comment]
Looks like a bad URL

https://app.webaverse.com/

**Comment by yaserOSource** [comment]
Works fine on Edge for me

**Comment by yaserOSource** [comment]
Does not work on firefox due to a web worker error for me

**Comment by amnaarshed4224** [comment]
yes. On edge its fine with https.

**Comment by amnaarshed4224** [comment]
Updated.
But is it solvable?

**Comment by avaer** [comment]
> But is it solvable?

Yes but it would make the app worse for everyone, especially developers.

This is the features page: https://caniuse.com/mdn-api_worker_worker_ecmascript_modules
