### ISSUE TITLE
pointerlockerror when returning back to browser

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#218]
How to reproduce:
1. look at object with box selector around it
2. press esc to exit pointer lock
3. double click back on object / box selector area

![pointerror](https://user-images.githubusercontent.com/29695350/101406655-5c094900-389f-11eb-9980-1641f036fbf8.PNG)

**Comment by avaer** [comment]
I saw this too but I actually don't know what causes it so far :/.

**Comment by chrislatorres** [comment]
https://github.com/mrdoob/three.js/issues/20329 might be it

**Comment by avaer** [comment]
That's probably it.

**Comment by avaer** [comment]
We can't do anything about this right now, so closing.
