### ISSUE TITLE
Incorrect in-world profile picture

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#220]
![diffprofilepic](https://user-images.githubusercontent.com/29695350/101431327-42cac180-38cc-11eb-9750-5c49d291e70f.PNG)

**Comment by avaer** [comment]
I believe that label is currently hard-coded.

**Comment by avaer** [comment]
https://github.com/webaverse/app/blob/665ffd1adffcc5acabebe3c074adc780e64ad56d/rig.js#L42
