### ISSUE TITLE
App: sky shader

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2208]
It should have a day/night cycle with a sun, stars, and possibly clouds (though we could use the clouds we already have, which workd great and are cheap to render as planes.

Here are some good starting shaders:

Horizon glow:
https://www.shadertoy.com/view/NsXyDN
Space clouds:
https://www.shadertoy.com/view/fdXyDN

**Comment by ahadshams** [comment]
The links above do not load

**Comment by Noobulater** [comment]
Are we happy with https://github.com/webaverse/skybox-anime? Seems nice, and could be extended it to have day/night + stars

![image](https://user-images.githubusercontent.com/4164318/149376163-47d732bf-e25c-4fad-bba5-75ed20f6db9e.png)

**Comment by avaer** [comment]
> Are we happy with https://github.com/webaverse/skybox-anime? Seems nice, and could be extended it to have day/night + stars

Yeah, I'm extending this one with a full day/night cycle. I think with the lighting being properly reflected the effect will be good and generally usable.

**Comment by avaer** [comment]
> The links above do not load

The links were unpublished; I published them now.

**Comment by avaer** [comment]
Done.
