### ISSUE TITLE
app: login through discord reloads whole app to starting point

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2213]
Currently, logging in through discord reloads the whole app. It loses any previous state even changes the scene to street scn's starting point.

https://user-images.githubusercontent.com/35926530/149630854-c867c935-a93a-4484-a3cb-05b79800e29a.mp4

**Comment by abeersaqib** [comment]
@avaer

What are your thoughts on this issue? I pressed `F5` and it reloaded and the state was not saved either.

**Comment by amnaarshed4224** [comment]
No, on refresh, the same scene gets refreshed and state(equipped items, current position) is not saved here too. 
With discord login, the app gets refreshed to the starting url app.webaverse.com.

**Comment by amnaarshed4224** [comment]
BTW, after discord login, refreshing retains the logged in user. But after metamask login, refreshing doesn't  retains the logged in user.
That is a separate issue. Right?

https://user-images.githubusercontent.com/35926530/153232246-af25da09-817c-490b-8673-451b1b962c10.mp4

**Comment by msm0823** [comment]
https://github.com/webaverse/app/issues/2864

related
