### ISSUE TITLE
app: Assets(Discord login) not in sync with discord bot's inventory

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2214]
Currently, logging in through discord shows all the assets minted by a person even if they have been transferred to someone else and no longer exist in a persons inventory.

https://user-images.githubusercontent.com/35926530/149631004-71cd1877-7620-4a96-a8e3-03ecdad84c8f.mp4

![inventory](https://user-images.githubusercontent.com/35926530/149631011-0711a79f-626d-4f00-ba93-2b8f48b5823a.PNG)

**Comment by avaer** [comment]
@hamzatrq fixed it.

**Comment by hamzatrq** [comment]
@avaer please merge the PR I created. The issue has to do with the currentOwner property. Which in old code always returns the minter.
