### ISSUE TITLE
app: Diorama view can be improved

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2233]
currently in both character tab, and ']' test diorama, the view of camera while running, Naruto running, crouch walk seems out of sync . I guess it need to be adjusted.

https://user-images.githubusercontent.com/35926530/150348539-0bdb835d-f6f4-4d80-b28b-71357bf36095.mp4

https://user-images.githubusercontent.com/35926530/150348549-df0029a7-d2c7-4c44-b664-d32916937cbd.mp4

**Comment by msm0823** [comment]
https://github.com/webaverse/app/issues/2319

related
