### ISSUE TITLE
app: WASM running out of geometry memory

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2238]
After multiple iterations of scene switching, these errors appear and break the scenes. Also after multiple switching, the app goes blank and doesn't loads.
Steps to reproduce:
-Switch all the available scenes in first iteration
-It will break probably at start of 2nd iteration of switching scenes

![20](https://user-images.githubusercontent.com/35926530/150554739-d0d63b8e-3a50-4237-976d-290cde0cde3a.PNG)
![19](https://user-images.githubusercontent.com/35926530/150554747-06d9c28c-f108-4c7e-add1-10e036eacffa.PNG)

**Comment by msm0823** [comment]
https://github.com/webaverse/app/issues/2735

related
