### ISSUE TITLE
app: Disable UI zoom in/out

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2256]
Currently, the UI zoom in/out isn't disabled. Trying to zoom in/out sometimes result in unintentionally zooming in/out the UI. 

https://user-images.githubusercontent.com/35926530/150651371-49b4a6d8-d5de-45ca-87c1-e3dc4325c0e5.mp4

**Comment by ohmed** [comment]
Duplicate ? https://github.com/webaverse/app/issues/2571
