### ISSUE TITLE
KTX2 assets optimization

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2263]
With KTX2 textures enabled (which I don't think was the case), we could get away with larger sizes on our assets.

The textures on the home space are really low quality, especially out to the edges.

Looking at my bake renders from the homespace concept, I think we could do a lot better. Baked lighting for some emissive elements seems effective.

![image](https://user-images.githubusercontent.com/6926057/150787082-eb5ca78f-fa07-447d-96b9-3811aa186d89.png)

**Comment by avaer** [comment]
Additionally, I think with KTX2 textures enabled (which I don't think was the case), we could get away with larger sizes.

**Comment by GaladWarder** [comment]
Just an update on this: I am currently testing trying to compress the homespace textures with KTX2 and some of the other KTX options (algorithms?). 

So far the results I have gotten are definitely compressed, but causing some pretty insane pixellization of the textures.

Also, an amendment; I was incorrect when I said that Blender uses KTX2 in their compression. They are currently integrating it, and some of the alpha builds have it, but it has not been integrated yet, which means our models are only Draco compressed currently.

Attached is one of the tests I ran, using the splatmap for the homespace to test the level of 'crunch'. It's pretty extreme.
![image](https://user-images.githubusercontent.com/29031531/151623056-22ef4e2b-adbc-4c54-b136-3be82ade9da3.png)
![image](https://user-images.githubusercontent.com/29031531/151623115-b32bac4a-fe11-4202-9615-5e16605e5432.png)


If we can get it to work, it'd be amazing; KTX2 is cutting the filesize by almost a *third*. I just need to figure out if there's some way to do that without the massive texture pixellization. Will keep you posted.

**Comment by GaladWarder** [comment]
Unable so far to find a way to compress that doesn't involve massive pixelization. The docs seem spotty and I haven't been able to figure out a good way to set criteria for how much to crunch it - it seems like there's basically just 4 primary options that each do their own thing. Using command line could give more flex, but no dice on that approach, always just crunching into pixelzation territory.

Going to look into getting crisper textures without KTX2, could possibly try compressed JPG's with sharper detail? The easiest way by far to get this as crisp as you want though would just be to separately load the interior and exterior so they are different scenes. Then we could push more texture detail into both sides and just have it be two different models

**Comment by avaer** [comment]
Why not just use https://github.com/zeux/meshoptimizer? It has flags for this.,

**Comment by avaer** [comment]
![image](https://user-images.githubusercontent.com/6926057/153239419-fb4b2ec2-8749-4885-b262-eb1b6b579eac.png)

https://github.com/BinomialLLC/basis_universal
https://github.com/HacksawStudios/basisu

**Comment by GaladWarder** [comment]
Sounds great, thank you! Will figure out how to get it up and running and will pass assets thru
