### ISSUE TITLE
app: Master isn't loading due to sound error

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2272]
Currently, master isn't loading and throwing this error. Its just a blank white screen.

![23](https://user-images.githubusercontent.com/35926530/150991143-631c141a-8ba0-4b44-a21d-eac7f8f5cb78.PNG)
![22](https://user-images.githubusercontent.com/35926530/150991149-dd9763f2-fc3b-4495-b124-2d76f8665077.PNG)

**Comment by avaer** [comment]
Added here: https://github.com/webaverse/app/commit/412c858a7eb2a6c736689ad3b4750383aa4f6f63

**Comment by amnaarshed4224** [comment]
Working fine now
