### ISSUE TITLE
app: grass.scn skybox isn't loading

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2275]
Grass.scn is throwing this warning.

![25](https://user-images.githubusercontent.com/35926530/151048961-12187c83-b510-4463-bcb6-651c55c4f520.PNG)
![24](https://user-images.githubusercontent.com/35926530/151048975-b95b1f3a-65e7-4fe8-8d91-423f81a23e82.PNG)

**Comment by avaer** [comment]
Thanks! https://github.com/webaverse/skybox-360 was not published but now it is.
