### ISSUE TITLE
App: Safari performance issues.

### ISSUE THREAD

**Issue by TheoTheDev** [webaverse/app#2282]
Looks like Safari browser is supported, but starting at some point performance dropped dramatically.
Not only for the app, but for all webGL experiences [even basic threejs examples are slow].

Browser version:
- [x] Safari 15.2
- [x] Safari tech Preview Release 138 (Safari 15.4)

Platform:
OS: macOS Big Sur v11.6.2
GPU: Radeon PRO 5500M
CPU: Intel i9

**Comment by ohmed** [comment]
I checked again with latest Safary and what I got:
- All webgl examples/apps work fine like 60fps [before all of apps had issues].
- Webaverse now is like 7-15psf [before 1-2fps], better but still super laggy, so most likely our app has some slow code for Safary. Needs investigation.
