### ISSUE TITLE
App: Chrome support issue on mac [KHR_parallel_shader_compile extension].

### ISSUE THREAD

**Issue by ohmed** [webaverse/app#2284]
Cause of missing extension KHR_parallel_shader_compile error view and controls are broken.
Screenshot attached.

Browser version:
* [x] Google Chrome 97.0.4692.99 (Official Build) (x86_64)
* [ ] Google Chrome Canary 99.0.4840.0 (Official Build) canary (x86_64) [works ok]

Platform:
OS: macOS Big Sur v11.6.2
GPU: Radeon PRO 5500M
CPU: Intel i9

![image](https://user-images.githubusercontent.com/1478866/151242705-77f7c43b-eba8-467e-b8be-a0b383179549.png)

**Comment by avaer** [comment]
The controls are broken because they will not unlock until a successful initialization.

We can rewrite `compileAsync` to handle this case, and perhaps do a no-op in this failure case. The experience will suck but it will work.
