### ISSUE TITLE
Animations: directional sword walk, run, crouch

### ISSUE THREAD

**Issue by torchesburn** [webaverse/app#2293]
Due to some issues with hip direction not being correct when using sword attacks and sword aim with walk, we need to create **directional sword walk, run and crouch.**  We can also source some of these assets and modify the animations, thats fine too. 

We are looking for a 1 step loop of each direction for sword walk and run cadence.

We are probably going to need the same for each type of weapon, but to begin with the sword animations would be good to have.

Key types: 
**walk**, **run**, **crouch**
Animations:
forwards, backwards, strafe

We can try mirroring the animations where possible

**Comment by avaer** [comment]
Can strafe for sword be mirrored? My guess is no.

**Comment by plankatron** [comment]
ok so : 

so sword walk , run crouch , and each set should consist of 8 animations ?
forward
backward
diagonal right forward
diagonal left forward
strafe left 
strafe right 
diagonal right backward
diagonal left backward

**Comment by plankatron** [comment]
i checked out the app recently and i dont see any strafe in the sword control , also no directional animations afaik ? in light of that here is a sword_walk and sword_walk_backwards

https://drive.google.com/drive/folders/1RLJdldLIg30HEutXAgZjMi-Mn10AKT4X

**Comment by plankatron** [comment]
these animtions have been made
