### ISSUE TITLE
Animation: DBZ charge up

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2296]
References:

![](https://c.tenor.com/13GycDCcsfQAAAAC/dragon-ball-z-goku.gif)
![](https://static.wikia.nocookie.net/dragonball/images/2/29/Goku_over_8%2C000.jpg/revision/latest/scale-to-width-down/250?cb=20120619184108)
![](https://static.wikia.nocookie.net/dragonballfighterz/images/4/4a/KiCharge.png/revision/latest?cb=20181031181427)

Any of those variations is ok. We only need one, and I think any of these would work, but the more the better.

The animation should be a pure loop of the character getting pumped with energy. No intro/outro needed.

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/151717833-32047101-43ff-4c52-a6c6-94288da25b7d.mp4

**Comment by plankatron** [comment]
another stab at the quick variation , also which branch and which animation is currently being used so i may test this in engine?

https://user-images.githubusercontent.com/5592454/151879097-ee49b5a5-2b85-483c-bd2e-194c256e9a17.mp4

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/151882046-10a881a9-5ca3-4b18-b890-9e688f3e11c1.mp4

**Comment by avaer** [comment]
Th above looks like a power lifter first taunting the enemy with a mock flex, and then screaming at the world like a wrestler.

It's pretty far from what we need.

**Comment by avaer** [comment]
Throughout this motion the character should maintain their focus on the fight, and stay ready for attacks at any time. That's why the arms should be facing forward the whole time.

**Comment by plankatron** [comment]
if its supposed to be instantaneous then how bout we just choose which pose you prefer
![untitled2](https://user-images.githubusercontent.com/5592454/151884721-0fb5ce27-89ac-4037-b33d-51916608370d.png)
![untitled1](https://user-images.githubusercontent.com/5592454/151884723-3b313a78-a5fd-4a45-99d0-9bee954bca23.jpg)

**Comment by avaer** [comment]
The top pose is better:

![](https://user-images.githubusercontent.com/5592454/151884723-3b313a78-a5fd-4a45-99d0-9bee954bca23.jpg)

It is active and focused on the fight, my only concern with it is it evokes a bit too much of a power lifter and it may or may not work on a female avatar -- worth trying.

What I had in mind is a halfway point between the above and the below, with the arms closer to the body.

![](https://i.pinimg.com/564x/07/17/b4/0717b43d8694cc871a8c9d4cbd7dd11b.jpg)

**Comment by plankatron** [comment]
that character's proportions are super off compared to the proportions of ybot also any character with a skirt will turn this pose into a crotch shot, heres an adaption 
![untitled4](https://user-images.githubusercontent.com/5592454/151887482-ecf594b9-6ea5-4f19-99ed-f8d72e9f03ba.jpg)

**Comment by plankatron** [comment]
slight variatio
![untitled5](https://user-images.githubusercontent.com/5592454/151887646-2901aa74-e355-496a-a667-7c67a76fdfaa.png)

**Comment by avaer** [comment]
> that character's proportions are super off compared to the proportions of ybot also any character with a skirt will turn this pose into a crotch shot, heres an adaption

Yeah I agree, I wouldn't use the bottom half of it. I was only referring to the hands.

Those poses look good.

**Comment by avaer** [comment]
> also , can i check out the sss branch to test this on an actual vrm ? i think that would help us all figure this out

It's in `master`.

**Comment by ahadshams** [comment]
can we close this? @plankatron

**Comment by plankatron** [comment]
animations have been done : https://drive.google.com/drive/folders/11TSHoJNjzzNAP8LMv3DkBYhJc3AUyqds
