### ISSUE TITLE
app: Footsteps Sound 

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2301]
The sound is now in synchronization with the footsteps, but the sound doesn't quite seems in sync with the type of surface avatar is running or walking on. Right now the sound for walking/running feels like as if avatar is walking on gravel, even though there is no gravel yet. Same is the case with jump. And for naruto run, it feels as if avatar is running on a sheet of iron or steel. I guess these sounds should change based on the type of surface. For sand, grass, iron, gravel etc

https://user-images.githubusercontent.com/35926530/151712488-f17d2403-9b3a-425d-bae8-46f2ffe22748.mp4

https://user-images.githubusercontent.com/35926530/151712264-5c98ecdd-588e-48af-9db0-4fd178889a1c.mp4

**Comment by ahadshams** [comment]
asking 2am if we have sfx for different surfaces
