### ISSUE TITLE
Using new animation clips gives you animationIndices error in character-sfx

### ISSUE THREAD

**Issue by yaserOSource** [webaverse/app#2311]
![image](https://user-images.githubusercontent.com/51108458/152097423-120f2fd1-57e9-4dc5-9a52-a2173b7f6d3a.png)

This is the problematic line, and it goes on from there.

**Comment by yaserOSource** [comment]
Will add more info to this one but can be triggered by replacing the walking animations

**Comment by avaer** [comment]
Are step indices being generated in the baker for the new animations?

**Comment by avaer** [comment]
https://github.com/webaverse/app/blob/fb85f7833107507220fab343e4c96ac44945ff63/animations-baker.js#L295

Note that this is a requirement for any animation that touches the ground. Fine tuning the step offsets to be a perfect match is usually required.

**Comment by avaer** [comment]
I'm closing this. I'm assuming it was a temporary dev issue and the dev forgot about the issue they opened.
