### ISSUE TITLE
Delete stats panel

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2313]
I think we should just delete the stats panel entirely for now.

Right now it is providing inaccurate info, nobody understands the way the stats work, and multiple PRs have failed to fix it.

**Comment by avaer** [comment]
This can hopefully be replaced by a solution that is not based on copy pasted THREE.js stats.

**Comment by Sirahi** [comment]
I fixed it. It was a small issue of not calling the info reset at the right place due to which my PR failed.

**Comment by avaer** [comment]
https://github.com/webaverse/app/pull/2335 was reverted due to bugs.

**Comment by ohmed** [comment]
Will just use this one https://github.com/webaverse/app/issues/2285
as one issue and close this one.
