### ISSUE TITLE
React UI: Add To Loadout

### ISSUE THREAD

**Issue by shawwwwwwww** [webaverse/app#232]

**Comment by madjin** [comment]
This got added in

![brave_Dy1Oihnygi](https://user-images.githubusercontent.com/32600939/121790319-32adda80-cbac-11eb-8798-1b418781c76f.png)

![brave_bVqisWKU7D](https://user-images.githubusercontent.com/32600939/121790320-35103480-cbac-11eb-9fd4-c782cee30b55.png)
