### ISSUE TITLE
Remove HSTS

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2324]
Getting hit with HSTS warnings when hitting a local dev server via hosts file. This makes dev impossible without hacks. I managed to clear it by wiping chrome internals, but that's not a solution.

![image](https://user-images.githubusercontent.com/6926057/152686766-a40fa0b8-b272-4bcb-8bde-12960b027874.png)

![](https://cdn.discordapp.com/attachments/895727315730968667/939897303588798524/unknown.png)

@rob-webaverse why is the site serving HSTS?

**Comment by avaer** [comment]
Details can be viewed in chrome://net-internals/#hsts

**Comment by avaer** [comment]
I believe the HSTS came from upstream ai endpoints. In that case we should filter out the headers as they come back. Most likely it can just be a whitelist of headers we actually want, like type and CORS.

**Comment by abeersaqib** [comment]
We have to add the local development certs for the ai-webaverse as well so the dev process can be smooth.
