### ISSUE TITLE
app: option feature breaks the app with miku 

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2336]
the options feature breaks the master when the following steps are performed. 

1-equip miku avatar
2-Click option and click on first one "sprite sheet" 
3-Click on "switch style"
4-Now click on the second one "optimized avatar" and click switch style

https://user-images.githubusercontent.com/35926530/153084429-0d0c9a49-5993-481c-b0d4-d5b5a2a4dd8c.mp4

![32](https://user-images.githubusercontent.com/35926530/153084498-ac26cd11-d566-40ce-ac98-ebd4f34ad050.PNG)

**Comment by avaer** [comment]
Thanks, I wonder why it fails to add allocate.

**Comment by alisaad673** [comment]
not related anymore
