### ISSUE TITLE
app: No option to go back to default avatar style in option panel

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2339]
Right now we have two of the avatar styles implemented but we do not have an option to go back to original default avatar. Only way is to reload the app.

**Comment by avaer** [comment]
I think the way we will do it is instead of deleting the old avatar when we switch, we will leave the old avatar in place.

**Comment by amnaarshed4224** [comment]
Or we can add another option for default avatar style as a 5th option. Can we?

**Comment by avaer** [comment]
Maybe we are talking about different things. I was talking about the ability to wear an avatar in-world, and still having access to the previous avatar.

If this is about changing avatar render modes, but not changing the avatar, then I think we should just finish implementing all of the settings in the options panel. There is no need for a 5th option. The default will be auto-detected from one of the existing four options.
