### ISSUE TITLE
app: Option feature performance comparison

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2344]
Device:
Dell precision 7710
Nvidia Quadro m5000m
Core i7 7th gen

Comparison:

Avatar1(model149.vrm): 
Sprite sheet:
Before: 43
After: 49
Difference 5-6fps

Optimized:
Before: 43 
After: 48
Difference 5 fps 

Avatar2(scillia...v15.vrm):
Sprite sheet
Before: 42 
After: 60
Difference 18fps

Optimized avatar:
Crashes(allocation fails)

Avatar3(gear.vrm)
Not much improvement only 2-3 fps

Other scillia avatars(previous versions) have even better performance difference. It is based on the avatars geometries.

**Comment by avaer** [comment]
We still use the avatar base mesh for depth test so there wouldn't be much performance difference yet.
