### ISSUE TITLE
app:Mirror isn't loading in app.webaverse.com

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2345]
It is throwing this error/warning

![apperr](https://user-images.githubusercontent.com/35926530/153256214-7187ce93-fe1e-4070-9ad6-a85e70c941e0.PNG)
![apperrs](https://user-images.githubusercontent.com/35926530/153256224-5098b60a-2187-4f8e-ae3c-693ca54634da.PNG)

**Comment by amnaarshed4224** [comment]
Its still happening.

**Comment by avaer** [comment]
We switched over the app so this should no longer be an issue.
