### ISSUE TITLE
app: FX texture errors in master

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2357]
![ferr](https://user-images.githubusercontent.com/35926530/153714904-df6b09f1-ccc9-4a0a-bf94-2b5afa7070f2.PNG)

**Comment by avaer** [comment]
This is because the app at that location is very outdated. It simply bit rotted.

**Comment by amnaarshed4224** [comment]
yes sure.

**Comment by amnaarshed4224** [comment]
Particle system one seems solved. This one still persists while switching to treehouse.scn. @avaer 

![fZERRR](https://user-images.githubusercontent.com/35926530/153720037-3427820f-9615-4a31-aa70-1310fdfb91fc.PNG)

![fzzzz](https://user-images.githubusercontent.com/35926530/153720040-70d9712d-779f-4ba8-8ffd-71153bcdd6d8.PNG)

**Comment by rob-webaverse** [comment]
I've just switched dns to point at the ecs architecture instead of the ec2. Seeing errors now?

**Comment by avaer** [comment]
Can you be more clear about which issues we are talking about? How is ECS related to this? Is it working now?

**Comment by amnaarshed4224** [comment]
Nop. I have the latest master. Still this error.
![36](https://user-images.githubusercontent.com/35926530/153870306-551514cc-dfc4-4dbe-b4a5-6cf770d45b72.PNG)

**Comment by avaer** [comment]
It should not be loading those files from `localhost`. Can you expand the full request initiator chain for that request? It's in the Network panel. You can find that request and see the chain of code calls that initiated it.

![image](https://user-images.githubusercontent.com/6926057/153896058-3120f384-015d-47ea-bd30-73cc65aa3c6c.png)
![image](https://user-images.githubusercontent.com/6926057/153896302-811b9ca6-6ca6-4e2c-8231-f3c6ddfdaa07.png)

**Comment by amnaarshed4224** [comment]
Here:
![network err](https://user-images.githubusercontent.com/35926530/153920047-6cfeb765-d75d-4e9c-b214-5bc5d9578575.PNG)

**Comment by avaer** [comment]
Thanks, this is because the treehouse is using a dead app (particle-mesh) which has since been made into a first-class particle system.

For future, this is one of the most useful screenshots when debugging an app load ☝️ .

**Comment by avaer** [comment]
Hopefully this is fixed with https://github.com/webaverse/app/commit/c22488ecd300cbf15106269835b191d3010e951f

**Comment by avaer** [comment]
Please close if fixed.

**Comment by amnaarshed4224** [comment]
Fixed!
