### ISSUE TITLE
app: Delay in voice packs sound and captions

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2359]
The voice pack Feature is quite cool. But there seems a delay in the captions and the sound. The sound starts after the end of captions in some cases. Example  attached.

https://user-images.githubusercontent.com/35926530/153722337-a6e8dec8-6edb-4dcf-89a2-32fbeb5f90f4.mp4

**Comment by avaer** [comment]
I've been making a lot of changes in this area and it might be a bit better now.

Can you try again and report on the new version?

**Comment by avaer** [comment]
I'm going to close this but please _do_ open another issue with a fresh evaluation.
