### ISSUE TITLE
app: Voice packs not working

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2362]
I am getting these errors while trying to switch between voice packs.

![voice err](https://user-images.githubusercontent.com/35926530/153917643-d95db8d4-b29f-491e-9cc4-ad153fefb433.PNG)

https://user-images.githubusercontent.com/35926530/153917586-25f41b91-148a-4e32-b899-6b7be0e258a5.mp4

**Comment by avaer** [comment]
Thanks! It's an API difference that needs to be patched.

**Comment by avaer** [comment]
Candidate fix in https://github.com/webaverse/app/commit/f0e2d045b5b3dfd69c812d674f6440340738852d.

Please close if it's fixed on verification.

**Comment by amnaarshed4224** [comment]
Fixed.
