### ISSUE TITLE
app: Delay in sound and captions of voice packs

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2367]
There are a lot of improvements from before. for example, the caption panel doesn't gets closed before the sound has ended. Also the avatars lip reading seems aligned with the sound.
But still the sound starts after the caption is completely written in the panel. My point is if we can make the word the is being shown in the captions panel aligns and syncs with the sound. It would sound and feel great.

https://user-images.githubusercontent.com/35926530/154284870-2ceac612-57e2-4f87-962d-16d9f3da3291.mp4

**Comment by avaer** [comment]
This is fixed in our demo repo, but I will leave this open for when we merge it after reveal.
