### ISSUE TITLE
App doesn't load

### ISSUE THREAD

**Issue by aryasalehi** [webaverse/app#2369]
When I reload the page the UI appears but nothing loads
![unknown](https://user-images.githubusercontent.com/64514807/154329355-9e429e30-0690-47c7-940a-882c2f5d7951.png)
[Profile-20220216T211614.zip](https://github.com/webaverse/app/files/8082433/Profile-20220216T211614.zip)

**Comment by avaer** [comment]
Looks like extremely long load is timing out?

**Comment by avaer** [comment]
Closing due to timeout.
