### ISSUE TITLE
app: Crashes while trying to wear equipables through drag and drop

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2374]
Even In the stable Branch, while trying to wear any object brought in through drag and drop of .metaversefile crashes the app.
It was working fine yesterday.

![erraapp](https://user-images.githubusercontent.com/35926530/154491037-0ea35f3f-974f-4273-945b-90256639de8b.PNG)

https://user-images.githubusercontent.com/35926530/154490962-0cfb45a6-332a-4779-b1e5-2d717b5d777c.mp4

**Comment by avaer** [comment]
Have you followed pull procedures for sub modules?

**Comment by avaer** [comment]
Please re-open if it's still happening!
