### ISSUE TITLE
app: Room creation doesn't works

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2385]
Getting this error while trying to create new room.

![room](https://user-images.githubusercontent.com/35926530/154705964-5365158a-e6a5-4ed0-985c-db3e71eb3d47.PNG)
![roomerr](https://user-images.githubusercontent.com/35926530/154705979-9b2795a7-33fe-4f55-8b24-5b0d5acb0200.PNG)

**Comment by lalalune** [comment]
Fixed in master
