### ISSUE TITLE
app: sound for vehicles needs to be changed or disabled.

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2387]
Currently, vehicles have the same sound as walking/running/dash footsteps sound. It should either be changed of disabled for vehicles.

https://user-images.githubusercontent.com/35926530/154739479-3c29254b-680d-4a9d-bb2a-9993c6612f9e.mp4

**Comment by avaer** [comment]
Agreed. We could provide default sound classes, similar to animations.
