### ISSUE TITLE
app: No diorama for default avatar model

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2396]
The default avatar model doesn't have the view of diorama by either pressing "]" or in the character tab.

https://user-images.githubusercontent.com/35926530/154809381-89757660-774f-49bf-a8c3-33c4d8361ddf.mp4

**Comment by avaer** [comment]
Working here in both cases on `master`. Will need to find out what environment is required to reproduce.

**Comment by amnaarshed4224** [comment]
Just checked Works fine in app.webaverse.com too. Will see what causes this on my local.

**Comment by amnaarshed4224** [comment]
This issue is also being caused just because of a plugin named "Moesif CORS" that i used. My bad. Its working fine right now. Closing the issue.

**Comment by amnaarshed4224** [comment]
Working fine now on local too. Closing the issue.
