### ISSUE TITLE
Missing avatar in-world

### ISSUE THREAD

**Issue by madjin** [webaverse/app#240]
When logging in via `ftu=0` and `o=21` at the end of the URL the avatar rig seems to be detached and on the floor while I am floating around invisible. I tried using one of the default avatars on the menu. Can't move unless I hit `x` first. Tested on Chrome, Firefox, and Brave.

![image](https://user-images.githubusercontent.com/32600939/101976036-4c1e9b80-3bf6-11eb-96fb-3db957592d63.png)

Brave console log

![image](https://user-images.githubusercontent.com/32600939/101976045-5b054e00-3bf6-11eb-938a-a5bb395ea3b0.png)

Firefox console log 

![firefox_4dnTWFS7RA](https://user-images.githubusercontent.com/32600939/101976047-6193c580-3bf6-11eb-8384-97f621171070.png)

**Comment by avaer** [comment]
This looks like an issue of the default avatar not loading, when no avatar is set. Will fix.

**Comment by avaer** [comment]
Default avatar should be animated now.
