### ISSUE TITLE
app: Minimap Improvements

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2408]
Following improvements can be made in the minimap right now.

1-The minimap should fit inside the circle of compass.
![minimap](https://user-images.githubusercontent.com/35926530/154946484-28110bfe-5e96-4f05-9bbb-a38ea29861de.PNG)

2-The knob of pointer that represents avatars movement can be misleading, Like my first impression was that the knob is pointing in the opposite direction to the face of the avatar. Thats because right now the wide angles side of pointer is pointing towards avatar direction.
My recommendation is to either make it the opposite(Knob pointing towards avatar's direction) or we can use a simple "point"(circle) that only shows avatars movement and not its facing direction.

https://user-images.githubusercontent.com/35926530/154947030-ade94904-1b7d-4bf5-97ee-45b11eff0ff6.mp4

**Comment by avaer** [comment]
Clearly the math is wrong.

**Comment by avaer** [comment]
What is your `window.devicePixelRatio`? That is the amount of pixels per logical pixel on the screen. You can get it from the console.

**Comment by avaer** [comment]
For 1), can you check that it's fixed in `master`?

**Comment by amnaarshed4224** [comment]
Yes 1 is fixed.
![fixed](https://user-images.githubusercontent.com/35926530/154998436-e019310b-e943-41ec-b4a4-164bcdfd2dbd.PNG)

Pixelratio:
![pixeels](https://user-images.githubusercontent.com/35926530/154998562-5f1d5417-cdac-4dd7-a3eb-60af9fefc969.PNG)

**Comment by amnaarshed4224** [comment]
One thing is its just lagging a little bit in loading the map. As you can see in the video, While we are moving fast there is a gap for a short moment that takes time loading. But i guess that is not much of an issue?

https://user-images.githubusercontent.com/35926530/154999225-700f7c02-6bc6-4540-b2df-ffcfe759ea0e.mp4

**Comment by avaer** [comment]
☝️ this is indeed an issue, it's a matter of rendering wider/changing the zoom to not hit the edges of the map as it comes in. We will fix it when we add speed-zoom to the map.

**Comment by avaer** [comment]
LMK if it's fixed with https://github.com/webaverse/app/pull/2419

**Comment by amnaarshed4224** [comment]
Yes, The zoom in/out has fixed the spaces while map was loading.
One thing i noticed is when we are flying with shift or doing a Naruto run, The pointer gets way too small. Maybe we should fix it so that it doesn't gets zoomed in/out with the map?

https://user-images.githubusercontent.com/35926530/155139266-b0aaf6f4-fbe5-477c-aa46-1bdd7d9d5bc5.mp4

**Comment by avaer** [comment]
Yeah, that it a good observation but I deliberately made it stay the same size, since it is so big that it gets in the way of seeing details while in naruto run.

That is worth revisiting but if it's the only thing remaining I think we can close this issue.
