### ISSUE TITLE
Trade window bug when adding FT

### ISSUE THREAD

**Issue by madjin** [webaverse/app#241]
User A started a trade, B added 500 FT, preview window only shows +5
![image](https://user-images.githubusercontent.com/32600939/101977462-6eb6b180-3c02-11eb-8873-f3fa8c6af4a2.png)

After the trade was finished, 500 tokens was transferred. The bug is the preview window showing incorrect amount. I think it's because my name is too short?

**Comment by avaer** [comment]
Expanded the header size to at least 8 characters for now. If that's not enough we'll re-open and figure something else out.
