### ISSUE TITLE
app: Classroom.scn errors

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2437]
These errors appear when shifting to classroom.scn
![8](https://user-images.githubusercontent.com/35926530/155570163-5751d5d4-5b04-474f-8bae-89a1abc4c4f1.PNG)

**Comment by avaer** [comment]
Looks like the HTML totum handler does not parse.

**Comment by avaer** [comment]
The proxy is serving back the app: https://local.webaverse.com/@proxy/https://https-vrchat-com.proxy.webaverse.com/

It should be serving the proxied content. This is a `totum` feature.

**Comment by avaer** [comment]
https://github.com/webaverse/totum/blob/da65086a54e5c3798aa8ae955463977726d2f39b/util.js#L34

**Comment by avaer** [comment]
This should be going through the proxy to load the VRChat home page:

![image](https://user-images.githubusercontent.com/6926057/183239328-7621a445-db5c-4ec4-995e-63dd4460690f.png)

Instead, it errors.

```
metaversefile-api.js?t=1659763895440:435 error loading "/@proxy/https://https-vrchat-com.proxy.webaverse.com/" SyntaxError: Unexpected token ':'
```

**Comment by alisaad673** [comment]
Fixed
