### ISSUE TITLE
Wallet/UI throws on app load

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2441]
![image](https://user-images.githubusercontent.com/6926057/155607463-69667d13-c5be-4ed1-bf2b-cb8f4f36d323.png)

```
TypeError: Failed to execute 'sign' on 'SubtleCrypto': parameter 2 is not of type 'CryptoKey'.
    at Wallet.sign (wallet.js?t=1645736520007:164:46)
    at Wallet.walletPromise (wallet.js?t=1645736520007:116:31)
    at Wallet.autoLogin (wallet.js?t=1645736520007:184:17)
    at User.jsx:95:32
```

This could be a recent UI regression.

CC @ohmed @hamzatrq

**Comment by hamzatrq** [comment]
This issue is related to weba-wallet and occured due to latest PR. With metamask and weba-wallet trying to access same address. Creating another PR for it's correction.
