### ISSUE TITLE
app: Character inventory should name objects just as infobar does.

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2454]
Character inventory should also name items just as the infoBar does. It is difficult to guess the items based on what appears there right now.

https://user-images.githubusercontent.com/35926530/155739796-ef12c32e-30b1-4cc1-80e0-92c7aacef75a.mp4

**Comment by avaer** [comment]
Yes, the tokens UI + character UI should get more aligned with the infobar.

I deliberately designed the loadout rendering/object snapshotting to be pluggable into these other slots, we just need to hook it up to React.

**Comment by avaer** [comment]
Labels are pulled from totum apps now, since I had a few minutes working on related code.
