### ISSUE TITLE
app: Metamask login not working

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2477]
Getting this error while trying to login through metamask.

![26](https://user-images.githubusercontent.com/35926530/156035601-f2dfa614-38a5-4e53-9c45-6c104f01d487.PNG)

**Comment by avaer** [comment]
CC @hamzatrq @abeersaqib

**Comment by hamzatrq** [comment]
This means that your wallet is locked and the request for accounts has already been sent. If you see your metamask there will be a badge. Best way should be to show a error notification to user that says "Unlock your metamask to continue"
