### ISSUE TITLE
Hurt animations upgrade

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2480]
The current hurt animations on NPCs need a lot of work. They look really unnatural.

**Comment by plankatron** [comment]
worked on these with galad yesterday : 

https://user-images.githubusercontent.com/5592454/156579551-a55990d4-ca38-4585-8732-8ff5472ef8c5.mp4


https://user-images.githubusercontent.com/5592454/156579554-e28d324c-e5bb-4194-b8e8-fdb049db52a7.mp4

**Comment by plankatron** [comment]
could not get a useable preview in webaverse however : 

https://user-images.githubusercontent.com/5592454/156579702-bbe60094-8ffa-4dce-a4d6-ff5c15651500.mp4

was recommended to redo these animations and reduce leg/hip movement to see if we can make something work

**Comment by plankatron** [comment]
tried to redo the animation with less hip movement using a mixamo animation as a base : 
https://user-images.githubusercontent.com/5592454/156580220-b44a8439-35a5-46fc-9448-e91bc502342f.mp4

output still not acceptable : 
https://user-images.githubusercontent.com/5592454/156580355-2c0e83e1-029e-4648-bfc3-65bd7703a4e8.mp4

**Comment by ahadshams** [comment]
The first question is - what counter animation(s) are used which cause hurt to the character as well as the weapon used..

without knowing these - i dont think a meaningful hurt animation can be made

@plankatron have you factored that?

**Comment by plankatron** [comment]
the requested animations were a hit from the front , behind , and a pain animation where the character clutches there stomach.

**Comment by ahadshams** [comment]
do you know the counter animations?

Hit in the stomach? On the face? A slash? A punch?

**Comment by GaladWarder** [comment]
Presumably, since these locations were specifically requested - though in my opinion we will want to eventually move to a physically-based system like most fighting games use: https://youtu.be/ufNdp3Nm3mg?t=37

That way the animation will appear correct based on location and velocity. I know that's more dev time though, so for now I assume the specific animations are for things Avaer has planned specifically

**Comment by avaer** [comment]
> The first question is - what counter animation(s) are used which cause hurt to the character as well as the weapon used..

The current set involves a body slash as well as arbitrary-angle bullet hits. We know the incoming angle and can trigger hurt based on that.

**Comment by avaer** [comment]
I agree with @GaladWarder that ultimately we'll want to do physical based hits, but we have several PRs required before that, including:

1) fortnite geometry deform hits on objects (much easier version of this, will allow code reuse)
2) ragdolls (needs an owner, I half completed it)
3) per-bone hit detection

**Comment by avaer** [comment]
Also note that these animations play while the character is in fast motion, so "stepping" would need to be built with a run/walk blend in mind.

**Comment by avaer** [comment]
IMO this animation set is the best one: https://github.com/webaverse/app/issues/2480#issuecomment-1058069935

Other than the fact that the stepping would be a problem when blending, it has a good immediate response to the hit.

**Comment by plankatron** [comment]
can definitely make a variant with this in mind 
> IMO this animation set is the best one: [#2480 (comment)](https://github.com/webaverse/app/issues/2480#issuecomment-1058069935)
https://github.com/webaverse/app/issues/2480#issuecomment-1058071289  <-- still need a way to preview animations on the vrm without any specific code influence, this is important for setting baselines,
