### ISSUE TITLE
app: NFT drag and drop doesn't works for discord assets

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2482]
Unable to bring in nfts through discord assets

![nft](https://user-images.githubusercontent.com/35926530/156396970-b4657689-bf22-4e83-9216-32e1b77a5ace.PNG)

https://user-images.githubusercontent.com/35926530/156396983-5c83bf69-a471-4f37-9ba7-caa6e60fcd38.mp4

**Comment by lalalune** [comment]
This was moved to character panel, we should still test the drag and drop of assets on sidechain and in wallet, but this menu no longer exists.
