### ISSUE TITLE
lisk collision models 

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#2491]
was requested to make a lisk with collision models based on the omi spec : 

here are two collision model tests , one that is autogenerated with vhacd : https://github.com/kmammou/v-hacd
![lisk_export](https://user-images.githubusercontent.com/5592454/156582858-06208c04-215b-435d-84c1-c3dd77bc2756.png)

and one hand modelled : 
![lisk_export1](https://user-images.githubusercontent.com/5592454/156582883-07c52267-fe17-47b8-bcfc-26190d54c802.png)

https://github.com/omigroup/gltf-extensions/pull/63/files/140166b48eb4aac39f7f6545d24903d6c1939fa5#diff-b24fb3ba88c0a903f39d0627f741655786cdece3f113bef243b3c31c1913dc1b

spec has not been finalized , there is no exporter that can export the appropriate metadata , everyone in the gltf omi group recommended *not* to try to make a model for this however this task is still a priority so the only option is to export the gltf in ascii form and edit it by hand. 

main issue i have right now is that i need help to understand the structure of the gltf file before i can properly edit the gltf file with the appropriate metadata which looks as follows : 

when i go and search for the object name of the collsiion objects "dragon-col" i find : 

### Dragon Collision data in lisk-col.gltf
```        {
            "mesh" : 0,
            "name" : "dragon-col",
            "skin" : 0
        },
```

### JSON Schema
```json=
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "Collider",
    "type": "object",
    "required": ["type"]
    "properties": {
        "type": {
            "type": "string",
            "description": "The type of collider this node represents",
            "enum": [
                "box",
                "sphere",
                "capsule",
                "hull",
                "mesh",
                "compound"
            ]
        },
        "radius": {
            "type": "number",
            "description": "The radius to use for the collision shape. Applies to sphere/capsule",
            "default": 0.5
        },
        "extents": {
            "type": "array",
            "description": "half-extents for a Box (x, y, z).",
            "default": [0.5, 0.5, 0.5]
        },
        "height": {
            "type": "number",
            "description": "The height of the capsule shape.",
            "default": 1
        },
        "mesh": {
            "description": "A reference to the mesh from the `meshes` array to use for either the Hull or Mesh shapes. The mesh MUST be a trimesh. Make sure your mesh is actually a convex hull if you use Hull, and try to avoid a full Mesh since they are very slow.",
            "allOf": [
                {
                    "$ref": "glTFid.schema.json"
                }
            ]
        }
    }
}
```

Please Provide an example of how to change the data correctly

**Comment by avaer** [comment]
We should not be making a model for the collisions. That is done by the physics engine and has nothing to do with Blender.

**Comment by avaer** [comment]
Also I don't think we should be manually editing any GLB files.

**Comment by avaer** [comment]
The easy way to do this is to not deal in hulls, but attach basic shapes for now.

**Comment by plankatron** [comment]
So as the model author how should i specify how the model should decompose?

> We should not be making a model for the collisions in Blender.
> 
> That is done by the physics engine and has nothing to do with Blender, especially Blender's decomposition hulls. The physics engine computes hulls after all of the modeling is done and we are done with Blender (this part could be part of the final export phase in the Blender plugin).
> 
> Note that I am talking about the hull data, not the hull mesh -- the hull mesh can be extracted from the baked data but generally would not be visible. Either way it is not made by authors of the model.
> 
> The only thing the model author would have to do is specify how to decompose.

I agree that editing glb's by hand is not really a good idea, is there any other alternative you have in mind ? currently there isnt an exporter that can export this data afaik.

> Also I don't think we should be manually editing any GLB files (I think most editors will corrupt it).

Do you mean attach shapes in blender? p.s. all the shapes in both of the above models  are convex and under 255 triangles 

> The easy way to do this is to not deal in hulls, but attach basic shapes for now.
