### ISSUE TITLE
app: "]" key for diorama crashes the master

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2492]
In Master, Pressing "]" for diorama, crashes the app and this error pops up.

![diorama crash](https://user-images.githubusercontent.com/35926530/156572913-711aa59b-fa17-43c6-9713-169d0d7f906d.PNG)

https://user-images.githubusercontent.com/35926530/156599704-4d4af39e-af16-441d-8db5-4555be55d70c.mp4

**Comment by avaer** [comment]
This key will not be used anymore, but we shouldn't crash.

**Comment by avaer** [comment]
This key hack was removed.
