### ISSUE TITLE
app: Miku avatar issue in master

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2493]
In Master, In street, grid, prototype, canyon scenes when we try to switch avatar with miku, the avatar goes invisible and this error pops up.

![grid invisble avatar](https://user-images.githubusercontent.com/35926530/156572778-c7cdc18e-750d-4781-b228-adbb17ae66dd.PNG)

https://user-images.githubusercontent.com/35926530/156572812-cd8fcca1-21bb-4316-a8f4-8ea0f5c9efa6.mp4

**Comment by avaer** [comment]
This is coming from `three-vrm` upstream update. The `center` object does not have a `matrixWorld`.
