### ISSUE TITLE
app: No diorama view in master

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2494]
Right now in master, there are no No diorama view for any avatar. Also pressing "]" crashes the app.

![nodiorama'](https://user-images.githubusercontent.com/35926530/156572974-5f1e5761-1619-4490-b866-b0847e6601a9.PNG)

**Comment by avaer** [comment]
Same issue as https://github.com/webaverse/app/issues/2494

**Comment by avaer** [comment]
Related: https://github.com/webaverse/app/issues/2492

**Comment by avaer** [comment]
Should be fixed.
