### ISSUE TITLE
app: Crash after using voice endpoints

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2495]
In latest master, App crashes for voice endpoints. When we press enter and write something, the app crashes after voice is finished up. this error pops up.

![voice pack crash](https://user-images.githubusercontent.com/35926530/156573238-d87f2284-08c5-4785-baf9-c31330f3612a.PNG)
![voicepackcrashnt](https://user-images.githubusercontent.com/35926530/156573275-453aa23e-557b-4ff4-9335-4ba4e0095629.PNG)
![voicepackcrsh nt2](https://user-images.githubusercontent.com/35926530/156573282-181b220b-a1fd-46a9-81fc-986cfd24a375.PNG)

https://user-images.githubusercontent.com/35926530/156573308-96704a3c-2d4f-4e92-9de1-5e80e8d9fd9e.mp4

**Comment by avaer** [comment]
Thanks, confirmed.

**Comment by avaer** [comment]
Should be fixed.
