### ISSUE TITLE
Implement an option to remove the damages objects receive

### ISSUE THREAD

**Issue by platote** [webaverse/app#2497]
Currently it seems that all objects can be destroyed by weapons, it would be great to activate/deactivate the option easily

**Comment by avaer** [comment]
Yeah, especially for terrain.

**Comment by platote** [comment]
Actually found a way, with this code 

Now I need to figure out how to change HPs

```
import * as THREE from 'three';
import metaversefile from 'metaversefile';
const {useApp, useScene} = metaversefile;

export default e => {
  const app = useApp();
  const scene = useScene(); 
  const ground_url = `./platote_assets/training_ground/terrain_05.glb`;
   
  let groundApp = null;
    
  e.waitUntil((async () => {
    const u = ground_url;
    const m = await metaversefile.import(u);
    groundApp = metaversefile.createApp({
      name: u,
    });
    
    console.log(groundApp);

    groundApp.updateMatrixWorld();
    groundApp.setComponent('physics', true);
    groundApp.setComponent('activate', true);

    await groundApp.addModule(m);
    scene.add(groundApp);
  })());
  return app;
};
```

**Comment by avaer** [comment]
I believe the above would result in an object that is in the scene, but not known by the engine, so it has no notion of HP and cannot be hit.

IMO this would be better done with a new e.g. `hittable` component that keeps the object inside the engine, but allows for decision of whether to cause damage or not based on the switch. And then we would not need any such code, it could be declared in the scene per object.

**Comment by platote** [comment]
That would be great indeed, I need to figure out how to create components
