### ISSUE TITLE
Drake Avatar: Rubber-like hands and head problem.

### ISSUE THREAD

**Issue by gonnavis** [webaverse/app#2500]
https://user-images.githubusercontent.com/10785634/156737395-9f27b014-9892-42c8-b854-e4d7eed9df7d.mp4

**Comment by avaer** [comment]
From some light debugging, this can be fixed by mapping through the GLTF json and getting the node from the gltf scene by name.

**Comment by avaer** [comment]
This regressed in a `three-vrm` update.
