### ISSUE TITLE
app:"[" shortcut key error

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2501]
This error pops up while we press the "[" shortcut key.

![err](https://user-images.githubusercontent.com/35926530/156765219-2edafe31-09e9-4919-bc22-058027831063.PNG)
![err1](https://user-images.githubusercontent.com/35926530/156765223-692ba2d9-8547-45a2-beb7-83f46a30d6f4.PNG)

**Comment by avaer** [comment]
Good catch. I think we can delete this key, it was only used for testing mouth flaps.

**Comment by avaer** [comment]
Fixed with https://github.com/webaverse/app/commit/14581e96d8ac2dd808542e45489960896eaf4a3a
