### ISSUE TITLE
app: Error in gunroom.scn

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2503]
This error pops up in gunroom.scn. The scene loads just fine. Could it be an issue on my local?

![gunroom err](https://user-images.githubusercontent.com/35926530/156768878-352e02cf-f3ef-475c-a580-a7791cf5982d.PNG)

![gunroomerr1](https://user-images.githubusercontent.com/35926530/156768883-fdd8dcf5-053e-4647-87f9-622e862beb96.PNG)

![gunroomerr2](https://user-images.githubusercontent.com/35926530/156768885-3e0709d5-16c2-40b6-8501-ebe5da41e04f.PNG)
![gunroomerr3](https://user-images.githubusercontent.com/35926530/156768886-be4aca83-47c7-4ee2-8edb-94969848192d.PNG)

**Comment by avaer** [comment]
Looks like the totum `Text` type.
