### ISSUE TITLE
app: Asset's loading errors in master

### ISSUE THREAD

**Issue by amnaarshed4224** [webaverse/app#2516]
These assets aren't  loading in latest master.
Street scene:
![mirror err](https://user-images.githubusercontent.com/35926530/156887524-293b338e-1504-402f-bf20-1fe10e842df2.PNG)

Grass scene:
![grassscn err](https://user-images.githubusercontent.com/35926530/156887542-d2021a87-e7ba-4ac8-94b5-a3a74cdad818.PNG)

**Comment by avaer** [comment]
Thanks, this looks like a simple case of scenes being updated to run locally.

**Comment by avaer** [comment]
I think all of the references have been fixed now. Please re-open if there's more!
