### ISSUE TITLE
App: Avatar.js should be broken up to better separate concerns

### ISSUE THREAD

**Issue by 0reo** [webaverse/app#2519]
Avatars file is huge, want to clean it up to make implementing an animation state system more manageable.

- move classes to their own files
- move related configs to new class files
- move _applyAnimation and related animation code into a separate file so animation refactoring can be continued while master continues to be updated(this file will be changed/removed in future updates)
- move animation functions into variables for readability, rather than defining them in an if/else block

**Comment by avaer** [comment]
Yeah, this is probably one of the most impactful refactors we could do.
