### ISSUE TITLE
Edit mode (tilde grabbing)

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2527]
Edit mode (`tilde`/`~` to enable) was working a few weeks ago but now it's broken; it doesn't grab objects correctly. When you grab right now, objects will teleport to origin and stay there.

It was previously working like Fortnite, though the matrix inversion was always wrong and caused spatial skipping when clicking the object, which is a bad experience that we can fix.

When you click the object it should stay in place but attach itself to your character. Moving camera should move the object to the new transposed location based on the camera difference. We also have keys like `E` (rotate left), `R` (rotate right), `V` (toggle colliders) which should be respected. to control the grabbed object.

The code for this lives in `game.js` but that's not good abstraction. This control mode should be its own file, communicating with `io-manager.js` to get keys and the other managers (like physics) to effect the correct transforms when in edit mode.

**Comment by avaer** [comment]
Code pointers:

https://github.com/webaverse/app/blob/0666fe84e933f629f322b3aaaa57b12edd234f79/game.js#L760
https://github.com/webaverse/app/blob/0666fe84e933f629f322b3aaaa57b12edd234f79/game.js#L787
https://github.com/webaverse/app/blob/0666fe84e933f629f322b3aaaa57b12edd234f79/game.js#L314

**Comment by TheoTheDev** [comment]
> @ohmed is this actually UI related?
like 50/50, I would move the logic from the game.js to editor-block component [react/UI].

**Comment by avaer** [comment]
> like 50/50, I would move the logic from the game.js to editor-block component [react/UI].

I disagree with this, this is purely engine related. We want this working with no UI.

**Comment by TheoTheDev** [comment]
ok, moved all keyhandling to io-manager.
