### ISSUE TITLE
app: Un-wearing the avatar with "medium" settings dispatches an unusable avatar instance

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2530]
When switched to the "Medium" settings of character details, and then we try to change the avatar, there is another unusable instance of previous avatar left there, Also this instance goes along with the avatar to any scene that we switch to.

https://user-images.githubusercontent.com/35926530/157256309-16c14da4-460e-41ee-bb15-53b7a036a200.mp4

**Comment by 0reo** [comment]
https://github.com/webaverse/app/issues/2549 will resolve this.  totum PR's 76 & 79 are dependancies.
