### ISSUE TITLE
Remove event state machine from React

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2544]
This event juggle-based global call code needs to be removed:

https://github.com/webaverse/app/blob/4acbb17277ebaee46426b5a08ca0fd7f6cd8c744/src/Header.jsx#L149
https://github.com/webaverse/app/blob/4acbb17277ebaee46426b5a08ca0fd7f6cd8c744/src/Header.jsx#L165

These global variable calls-by name make it hard to understand how the menu system is supposed to respond, and it's impossible to do type checking or call analysis on this, in addition to large risk of name conflicts and duplication of state/events from `io-manager`.

**Comment by ohmed** [comment]
Closed with this PR https://github.com/webaverse/app/pull/2526
