### ISSUE TITLE
Keyboard shortcuts interfere while chatting

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2576]
The chat is really broken after the last few refactors, since it starts to trigger many of our hotkeys.

We need to debug and separate these cases out in the code. It should be possible to open chat and type any character on a ~US-eng keyboard and not have it trigger a hotkey.

**Comment by avaer** [comment]
This also applies to any input, like the settings AI API key field, where the user is typing.

**Comment by alisaad673** [comment]
fixed
