### ISSUE TITLE
FE AI issues

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2585]
1-The openai isn't working in master. Whenever i try to put the api key got from the openai platform, in setting panel and then press apply, the key disappears and nothing happens. Are we missing out something?

https://user-images.githubusercontent.com/35926530/158594865-9b6d4aa4-b117-4156-ac59-dc6a5ea88420.mp4

2-The goose ai gives this error whenever we try to talk to any of the npc. This error comes instead of response

![goose ai err](https://user-images.githubusercontent.com/35926530/158594936-703d2f05-3a25-4cd3-87ff-46d3dcf02866.PNG)
![goose ai](https://user-images.githubusercontent.com/35926530/158594942-298b4176-8ed2-4863-ace1-e38913a6f0d3.PNG)

https://user-images.githubusercontent.com/35926530/158595073-aff0ac60-5a0a-418d-a102-9bd1a289a635.mp4

3-While trying to switch to a121 from either goose ai or openai, we need to refresh the app for it to work properly. If we don't refresh, the response is there in the log but no voice or chat box from the npc.

https://user-images.githubusercontent.com/35926530/158595190-21feb04b-ef8f-409e-a5a8-646667f42715.mp4

4-On A121, while we try to talk to drake by name, the hyacinth interferes in the talking. Same happens when we go to hyacinth.

https://user-images.githubusercontent.com/35926530/158595333-861090f6-826d-40ba-9891-1a3a5eb773cf.mp4

https://user-images.githubusercontent.com/35926530/158595514-e48105a7-f24e-4e40-9209-b1b4004b3bd4.mp4

https://user-images.githubusercontent.com/35926530/158595592-02ab90f0-d079-4762-a815-27edf3fc56bd.mp4

**Comment by avaer** [comment]
Our goose API key ran out of credits; that's the goose bug.

**Comment by avaer** [comment]
OpenAI key setting should be fixed with https://github.com/webaverse/app/pull/2600.

Setting the api key should make the field green. Additionally, when in debug mode, there is an extra text box in the AI tab for testing.

**Comment by avaer** [comment]
This is because `master` is out of sync with deployment again.

**Comment by rob-webaverse** [comment]
the stable branch has been updated with master and so now https://app.webaverse.com has been updated as well. Also, it seems as if browser extensions are what are interfering with the openai key saving properly.

**Comment by avaer** [comment]
Do we have a list of extensions that interfere?

We know about Search by Image.
