### ISSUE TITLE
App: building from scratch error

### ISSUE THREAD

**Issue by madjin** [webaverse/app#2604]
Started a fresh project, followed exact instructions with node 17+, I get connection reset error for https://preauthenticator.webaverse.online/preauthenticator.js which prevents scene from loading 

![image](https://user-images.githubusercontent.com/32600939/158901518-68df58c0-7fe3-448d-900a-deee24407575.png)

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/158901848-7e08a4a1-efe0-4345-8959-8b4ebc8ae9ed.png)

This what my console says

**Comment by madjin** [comment]
Found out that it was my router's security software was blocking the URL 😅

**Comment by alisaad673** [comment]
solved..
