### ISSUE TITLE
Dropping helm offsets model from collision

### ISSUE THREAD

**Issue by madjin** [webaverse/app#2605]
Equipped helmet, walked a little bit, then dropped it, and it looked like it disappeared but really the model is just far away for some reason

![image](https://user-images.githubusercontent.com/32600939/158902905-71f1710b-23b0-46d9-8ca9-5c1549daaa67.png)

links to help test / reproduce bug
https://github.com/webaverse/app/blob/master/scenes/street.scn#L212
https://github.com/webaverse/helm/blob/main/.metaversefile

**Comment by alisaad673** [comment]
Related: https://github.com/webaverse/app/issues/2373

**Comment by alisaad673** [comment]
Fixed
