### ISSUE TITLE
SFX integration list

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2634]
The following tasks should be worked on as separate issues/prs

- [x] #2693
- [ ]  Make voice packs a property of the worn avatar/npc — needs character select UI
- [x] #2707
    - [ ]  Jump
    - [ ]  Sword
    - [ ]  Landing
    - [ ]  Hurt
    - [ ]  Naruto run
    - [ ]  Gasp when running
    - [ ]  Eat (infinifruit)
    - [ ]  Drink (potion)
- [ ]  Recompile SFX pack to include new sounds
- [x] #2709
    - [ ]  Sword
    - [ ]  Pistol
    - [ ]  Bow
- [ ]  Add UI sound effects

**Comment by tcm390** [comment]
Hi Avaer, this is the PR for 'Compile and integrate all new voice packs from 2AM (4 total, 2 male, 2 female)'
https://github.com/webaverse/voicepacks/tree/integrate-new-voice-packs
