### ISSUE TITLE
app: UI and LoadingBox related errors in Master

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2644]
Getting these errors in master
![image](https://user-images.githubusercontent.com/35926530/159491430-7a432074-9cec-40ed-94db-5f66ff6fda63.png)

![image](https://user-images.githubusercontent.com/35926530/159490693-da3cff91-cef5-4050-9a7b-d05b8779ce5a.png)

LoadingBox err:
![image](https://user-images.githubusercontent.com/35926530/159491485-b814b185-abe2-4a5a-893c-488943adf9df.png)

**Comment by avaer** [comment]
This should be fixed. It was a missing file.

Please re-open if it's still there!
