### ISSUE TITLE
app: "Drop to World" in vrm drag and drop gives un-equippable avtars

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2653]
In master, While drag and dropping the vrms, If we choose "equip to self", it works fine. But if we choose, drop to world, it isn't equip-able. Also, the avatar that appears doesn't seems to have collision mesh.

https://user-images.githubusercontent.com/35926530/159928818-6f533e39-5ef0-419d-b77c-1d1a33537f72.mp4

**Comment by avaer** [comment]
I think this is not related to the avatar, but rather the `physics` component is probably not set on drops (same physics-less symptom with other assets). Either that or the physics are being added in the wrong place.
