### ISSUE TITLE
Avatar screenshot not appearing

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#269]
![unknown (1)](https://user-images.githubusercontent.com/29695350/102449993-2250e480-3ffb-11eb-9ff9-efd1b2b4d4dc.png)

**Comment by avaer** [comment]
This was because `OrbitControls.js` was missing on `https://preview.exokit.org/5832523458517407413c3a96291904a1fa5d59dd0a731c98a4cea611873b5694.vrm/preview.png`

**Comment by avaer** [comment]
https://github.com/webaverse/app/commit/2979e42b0509f652ba3968543af72a96c5b89673

**Comment by avaer** [comment]
![preview](https://user-images.githubusercontent.com/6926057/102456330-f8a1b880-400e-11eb-8b5d-c883366edbf8.png)

**Comment by avaer** [comment]
https://app.webaverse.com/screenshot.html?url=https://storage.exokit.org/5832523458517407413c3a96291904a1fa5d59dd0a731c98a4cea611873b5694&hash=5832523458517407413c3a96291904a1fa5d59dd0a731c98a4cea611873b5694&ext=vrm&type=png
