### ISSUE TITLE
Multiplayer: Items duplicating on re-wear

### ISSUE THREAD

**Issue by lalalune** [webaverse/app#2701]
In my latest branch, items are working intermittently over multiplayer.

We need to make sure items work properly for all users in multiplayer, when they join, leave or start a new session together.

- [ ] test example

**Comment by avaer** [comment]
Can you replicate this in single player?

**Comment by DavinciDreams** [comment]
I think this closes this issue - https://github.com/TheNexusCity/webaverse-app/pull/43
