### ISSUE TITLE
app: master crashes while trying to equip a second item

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2703]
Master crashes while we try to equip another item while already having an item in inventory. Equipping the first item works fine without any issue. Equipping the second item throws this error.

![1](https://user-images.githubusercontent.com/35926530/160917797-de20b97e-0a23-4e5c-9038-5ad42fe94ecc.PNG)

**Comment by avaer** [comment]
Could you check again? Might be fixed with https://github.com/webaverse/app/pull/2736

**Comment by alisaad673** [comment]
Fixed.
