### ISSUE TITLE
app: object-spriter.js errors in master

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2711]
These errors are appearing in latest master.

![mastererr1](https://user-images.githubusercontent.com/35926530/161089945-a3147784-770d-4fa9-b6ea-5b94977abacb.PNG)
![mstererr2](https://user-images.githubusercontent.com/35926530/161089954-bbad1eeb-81d9-42b6-90c4-a9805167a0d0.PNG)

**Comment by avaer** [comment]
Thanks, probably a double-encoding issue.

https://github.com/webaverse/totum/pull/91

**Comment by avaer** [comment]
I think this was caused by the UI refactor rewinding `totum`: https://github.com/webaverse/app/commit/01c2d01243624e0884678fffa37d281c567e9e67

That PR was reverted, so it should be ok in `master` now -- please confirm.

CC @ohmed @0reo

**Comment by alisaad673** [comment]
Resolved.
