### ISSUE TITLE
Animations: leaning against objects

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2718]
We're plugging in NPCs with the ability to interact with objects in the scene, but it is uncanny that they cannot lean, sit, lie down, etc. against any object because we don't have the animation for it.

The original plan for this was to add noise to a set of static poses, but I think custom animations will look a lot better.

We need a set of animations and pose loops for a set of basic poses in a typical environment (5-10 or so of the most common non-standing poses for humans).

- Lean back against wall
- Lean arm against wall
- Sit on floor (many possible variations)
- Kneel on floor
- Lie on floor
- Sit against wall

**Comment by plankatron** [comment]
https://drive.google.com/drive/folders/1mDP7FzsxbxOT4uetU1_pvoV_reU6XH6m?usp=sharing
