### ISSUE TITLE
Test Uberduck.ai endpoint

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2723]
We have our own TTS via https://github.com/webaverse/tiktalknet, but we want to try to see if it can be run remotely.

The Uberduck endpoint needs to be tested to see if it is as realtime as our implementation. There is a clock on this as it costs money to run the model either way.

**Comment by avaer** [comment]
It should take no more than an hour to deliver a verdict on this.

**Comment by 0reo** [comment]
waiting on secret key to start this

**Comment by 0reo** [comment]
current tests show our system is 3 times as fast as uberduck.  they are looking into if they can improve, but closing this for now.
