### ISSUE TITLE
Animation : Morpher animations

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2732]
The morpher has fly-to-idle (misnamed) and walk-to-fly animations. These aren't consistent with each other.

IMO we should have the fly animations only go to/from idle.

**Comment by avaer** [comment]
We could also use a set of animations for going into/out of watch mode. There is no need for scaling; we only need to fold the legs horizontally in a ring, similar to how we spread the wings for flight.

**Comment by plankatron** [comment]
request was satisfied, closing issue
