### ISSUE TITLE
Animation : Silkworm evolution models animations

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2738]
There silkworm evolution models have the all of the actions we need (namely idle, walk, and attack). However, they are all in a single animation based on time. We need these broken out instead into NLA tracks, as with all other models.

https://github.com/webaverse/assets/blob/master/silkworm-biter.blend
https://github.com/webaverse/assets/blob/master/silkworm-bloater.blend
https://github.com/webaverse/assets/blob/master/silkworm-queen.blend
https://github.com/webaverse/assets/blob/master/silkworm-runner.blend
https://github.com/webaverse/assets/blob/master/silkworm-slasher.blend

**Comment by avaer** [comment]
These each have a corresponding repo where the exported GLBs are:

https://github.com/webaverse/silkworm-biter
https://github.com/webaverse/silkworm-bloater
https://github.com/webaverse/silkworm-queen
https://github.com/webaverse/silkworm-runner
https://github.com/webaverse/silkworm-slasher

**Comment by plankatron** [comment]
SilkWorm Variants Export : https://drive.google.com/drive/folders/1S4nnMUXBJcuekdDcmxe8vLDsdB-9yRFa?usp=sharing
SilkWorm Variants Blends : https://drive.google.com/drive/folders/1G7yVUY_erKa62vrGedz2wpt4ZY_fA2U_?usp=sharing
![Screenshot at 2022-04-05 14-53-37](https://user-images.githubusercontent.com/5592454/161829667-aef1f9bb-9470-4049-9745-223ead7e668c.png)

**Comment by plankatron** [comment]
closing this issue as it seems to be satisifed
