### ISSUE TITLE
integrate NFTs

### ISSUE THREAD

**Issue by 0reo** [webaverse/app#2756]
NFT's need to be integrated into the webaverse app.  @hamzatrq needs to provide the outstanding information for this.

according to our conversation, we can test anything related to nfts on polygon mainnet, but not sidechain
- there is an existing nft PR we can reference, please add a link to that PR @hamzatrq 
- ryosuke can address this task once the outstanding information has been provided

**Comment by avaer** [comment]
Is this referring to wallet NFTs or ones on Webaverse chains?

**Comment by avaer** [comment]
It's unclear what this issue is.
