### ISSUE TITLE
Drag and dropped assets do not get teleported along with avatar

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2793]
Issue#1
-The drag and dropped assets such as swords bow, etc do no get teleported along with avatars as we switch scenes. 
-Only the asset itself isn't there with avatar
-The action/animation related to asset still get performed as it can be seen in the video below
-Unable to drop the silsword wit "R" key.(Dropping bow with R key works here)

https://user-images.githubusercontent.com/35926530/162500635-1c61ccc6-6e8f-4a52-9484-e9a5322e54a0.mp4

Issue#2
In the above case, after we have changed the scene after equipping a drag & dropped asset, Dropping the object and again changing the scene produces this error:
Steps to reproduce:
1-Equip a drag and dropped asset
2-Switch the scene (the object doesn't gets teleported along with vrm)
3-Drop the object by pressing "R"
4-Again switch the scene

![image](https://user-images.githubusercontent.com/35926530/162503878-8f7d0a83-c689-41cd-a44e-b2205e4c779d.png)

**Comment by avaer** [comment]
Yes, looks like an item AppManager ownership problem.

**Comment by avaer** [comment]
Note however that this kind of "teleport" will not exist and that menu will not be there.

**Comment by alisaad673** [comment]
Updated the issue with some more info.

**Comment by alisaad673** [comment]
Fixed
