### ISSUE TITLE
app: Two instances of infinityfruit get equipped instead of one

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2821]
Right now in latest master, if we try to equip the infinity fruit, Instead of one, two instances get equipped as it can be seen in the video below

https://user-images.githubusercontent.com/35926530/163436627-af64a59b-213f-45f2-a2f7-59e2607bb076.mp4

**Comment by avaer** [comment]
Good catch!

Should be fixed with https://github.com/webaverse/infinifruit/commit/ee53cb37e97d63fe9f96c4e097c85b6c2205d8e5

This regressed when we moved wearing to become a first-class component in the engine.
