### ISSUE TITLE
Animations bake is impossible

### ISSUE THREAD

**Issue by avaer** [webaverse/app#2828]
The naruto run animation has been corrupted for a long time, and this was never fixed, but now the script makes it impossible to bake any animations at all due to the corruption.

```
bake error Error: This track has invalid values.  All scale transforms must be set to 1. Aborting.
 Animation: naruto run.fbx, Track: mixamorigHead.scale, values:
 0.9999999403953552,0.9999999403953552,1,0.9999999403953552,0.9999999403953552,1
    at /home/a/app/animations-baker.js:353:19
    at Array.map (<anonymous>)
    at baker (/home/a/app/animations-baker.js:315:53)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/a/app/animations-baker.js:571:5
```

**Comment by avaer** [comment]
Looks like this was broken in this PR: https://github.com/webaverse/app/pull/2639

Seems like this check was added and nobody bothered to even run the code.

@gonnavis You've run into this too I imagine?

**Comment by gonnavis** [comment]
Yes, I think this is something in progress, waiting changing of animation files.
So just reverted the codes locally, not make issue.
![image](https://user-images.githubusercontent.com/10785634/163663963-a74ee59b-03dd-4874-bbf1-3bed4b807095.png)
