### ISSUE TITLE
Ui : Emote UI not showing up when called

### ISSUE THREAD

**Issue by plankatron** [webaverse/app#2837]
am on chromium , linux and when i press q to bring up the emote pie menu all i see is the cursor but no menu, the menu works it just does not display itself so you can click and make the emotes happen just no visual.

**Comment by avaer** [comment]
May be fixed with https://github.com/webaverse/app/commit/86bddc413ea54655bc6c046549dbfc973c14a4e9

**Comment by avaer** [comment]
Fixed.
