### ISSUE TITLE
.GLB animation -- support multiple animated meshes

### ISSUE THREAD

**Issue by balsamic-bz** [webaverse/app#2847]
My GLBs for my upcoming NFT collection have many different objects with animations.  In webaverse the animations on only **one** of the objects is playing.  

Any insight into how the GLTF loader treats animations?

FWIW currently the animations are NOT grouped in separate NLA tracks, they are all the same track.  I'll update here if I test separate NLA tracks and it works...

see below comparison between webaverse and a different three.js environment:

https://user-images.githubusercontent.com/91762032/164129536-5c9e6bdb-3f0a-4d64-b2f0-e38576c9fd46.mp4

https://user-images.githubusercontent.com/91762032/164129768-558f68ec-b47b-43fa-90d5-3c2dd008c258.mp4

**Comment by balsamic-bz** [comment]
hmm ok so I did a test with animations exported on separate NLA tracks and it is broken in a slightly different way:

https://user-images.githubusercontent.com/91762032/164130690-c6fa7c9c-e50d-4c84-973a-d95f2c122a79.mp4

**Comment by avaer** [comment]
Thanks for filing, this actually sounds like a legit bug in the GLB loader. (https://github.com/webaverse/totum/blob/35224decaa75a35e18c50c4ab29d994d0cd30e5c/type_templates/glb.js#L30)

This is mostly deferring to THREE.js to animate so I expect it's not that complicated of an issue.

Do you have a test scene/repo with this issue you could provide?

**Comment by lalalune** [comment]
@balsamic-bz sorry to be getting to this so late, but this is fixed in master
