### ISSUE TITLE
app: new animations bar in character panel gets blocked by UI

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2851]
when we play The new animations from animations bar in character panel, the actions by avatar are being blocked by the UI of character panel. We need to come up with a fix of some sort so that the animations don't get blocked by the UI

https://user-images.githubusercontent.com/35926530/164302044-f80fb007-8f89-4c49-96da-1e4cab7777ea.mp4

**Comment by avaer** [comment]
We could close the panel so that you see it on the character, but IMO this is working as intended. To see your emotes while playing, the alternative is the quick menu (Q).

This setting is mostly for the multiplayer case where you do not have a keyboard to open the quick menu with.
