### ISSUE TITLE
Mirror depth buffer glitching

### ISSUE THREAD

**Issue by avaer** [webaverse/app#286]
Also the performance is bad, as if there were several clears.
<img width="980" alt="Screen Shot 2020-12-17 at 4 51 27 AM" src="https://user-images.githubusercontent.com/6926057/102471763-999a6e80-4023-11eb-9de9-d6f128d1546c.png">

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/118407853-abbf1e00-b650-11eb-9e70-f9a11fd444bd.png)
Works now
