### ISSUE TITLE
app: Discord & Metamask login isn't working in master

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2864]
With the new UI, Both discord and metamask logins are not working. While we click on login, after authentication, it keeps saying "logging in". but doesn't gets logged in.

https://user-images.githubusercontent.com/35926530/164520443-77576acd-509f-4220-abca-254ce7396770.mp4

https://user-images.githubusercontent.com/35926530/164520476-608a24c5-f9f1-4e2f-aa64-9e5c0f19e1fa.mp4

**Comment by avaer** [comment]
The first video is unwatchable on my end.

**Comment by avaer** [comment]
Thanks, this regressed in https://github.com/webaverse/app/pull/2841 and is probably holding up deployment.

In this case I don't think we should be reverting anything since the previous integrations were, on the balance, worse than than the current state.
