### ISSUE TITLE
app: Avatar disappears on low avatar quality settings

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2866]
right now, avatar disappears on low avatar quality settings and throws this error.

![image](https://user-images.githubusercontent.com/35926530/164530947-7f25f5e1-a208-4b95-9fe9-b11bf7c5e9ac.png)

https://user-images.githubusercontent.com/35926530/164530962-8431b67a-def6-4e5f-9bdc-c1c809612df1.mp4

**Comment by avaer** [comment]
`localRig.emotes` was renamed.
