### ISSUE TITLE
app: malloc error in staging after discord login

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2867]
In current staging candidate, Right after i try to log in through discord, I get this malloc error.

![image](https://user-images.githubusercontent.com/35926530/164533047-bbc7da8e-4de4-4ad8-85d5-65c29edb6bcb.png)

https://user-images.githubusercontent.com/35926530/164533065-96a649b9-710c-4e90-872c-c2d0f2bdf9b6.mp4

**Comment by avaer** [comment]
This one I don't know; I don't think this is a login issue, but some earlier error that triggers a cascade.

**Comment by avaer** [comment]
@alisaad673 Is this still reproducible?

**Comment by alisaad673** [comment]
no more reproduceable. Closing
