### ISSUE TITLE
Performance: Wear/Unwear vehicle repeatedly.

### ISSUE THREAD

**Issue by gonnavis** [webaverse/app#2876]
If wear/unwear ( key E/R ) vehicle repeatedly, the performance will drop dramatically.

![image](https://user-images.githubusercontent.com/10785634/164714630-74488a1a-1eb5-4fcf-b6aa-687a8deb759d.png)
![image](https://user-images.githubusercontent.com/10785634/164714642-e8b907b1-a635-4d89-8444-bc2962225330.png)

**Comment by avaer** [comment]
Interesting, it is keeping the actions around somehow?

**Comment by avaer** [comment]
Looks like something in `zjs`.

**Comment by avaer** [comment]
To fix this I would investigate the actions adding/removal code more deeply, especially things like the listeners and callbacks, to make sure everything is correctly cleared when the app is unworn.

**Comment by avaer** [comment]
I noticed that wearing/unwearing the sword will cause similar glitches. The actions are definitely getting stuck.

**Comment by gonnavis** [comment]
Reopen because of revert https://github.com/webaverse/app/pull/2916#issuecomment-1123095807

**Comment by gonnavis** [comment]
Closed by https://github.com/webaverse/app/pull/2916#issuecomment-1126847544
