### ISSUE TITLE
app: Uzi and Thompson guns doesn't damages the objects

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2878]
The two new guns uzi and thompson, both have no damage effect on objects, All we get are decals and object remains as it was before and doesn't disappears.
We should include the damage property to it just as pistol has. Videos attached for reference.

https://user-images.githubusercontent.com/35926530/164747340-e69171ff-71ae-4401-a90c-f698d5ecd979.mp4

https://user-images.githubusercontent.com/35926530/164747621-cb0e2f10-4347-4ba5-9ef7-42f5d913d276.mp4

**Comment by Loryhoof** [comment]
was fixed
