### ISSUE TITLE
We see our own nametags

### ISSUE THREAD

**Issue by madjin** [webaverse/app#290]
I'd say this a bug since other VR platforms don't show nametags when you look straight up. Plus, when you look up you can't really appreciate the birds / sky because the nametag obscures so much of the view.

![image](https://user-images.githubusercontent.com/32600939/102585066-8ab3ca80-40bc-11eb-874e-c4f28c2aad81.png)

**Comment by avaer** [comment]
Old issue: https://github.com/webaverse/app/issues/263

Closing in favor of this.

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/118408359-4587ca80-b653-11eb-9b10-8b9e78793532.png)
now there's no nametags, is this a multiplayer only feature?
