### ISSUE TITLE
Gizmos implementation: move/rotate/scale object

### ISSUE THREAD

**Issue by madjin** [webaverse/app#291]
There's no indication that [delete] key deletes things, just instinct. Would be useful to add to the list on the tab menu. Also, EQRF key's aren't doing anything at the moment, tested on Brave + windows 10.

![image](https://user-images.githubusercontent.com/32600939/102585435-4aa11780-40bd-11eb-8ed0-511e01a4fd18.png)

**Comment by madjin** [comment]
Also, pressing F initiates Fly mode while in edit mode so the Texture button doesn't work

![image](https://user-images.githubusercontent.com/32600939/102585645-981d8480-40bd-11eb-9f56-9b7c5f296d41.png)

**Comment by avaer** [comment]
Added delete key where it is used.

These keys weren't implemented yet, so will repurpose this issue to implement the gizmos it describes. (We'll need to change the key combinations as well per our reasearch tonight).

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/103444503-a58a5100-4c1d-11eb-8571-3003a695a56a.png)

Here's current edit mode UI, missing an option to add scaling.
