### ISSUE TITLE
app: Ranged Weapon's aim isn't working

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2926]
Right now the aim of ranged weapons isn't working. It seems to have been regressed by some recent pr.
Here as you can see, while we press the aim click, the weapon doesn't moves up along with the aim

https://user-images.githubusercontent.com/35926530/165997785-d35c575b-a5a6-4e58-91af-d7cfcf4ea6ab.mp4

**Comment by gonnavis** [comment]
Caused by this patch https://github.com/webaverse/app/pull/2915#issuecomment-1112367014

Need to add `ikHand` to ranged weapons now. https://github.com/webaverse/pistol/pull/10/files

**Comment by Loryhoof** [comment]
uzi and machine-gun were fixed with gonnavis' suggestion

**Comment by avaer** [comment]
Is this fixed now? Please close if that's the case.

**Comment by alisaad673** [comment]
Fixed for all three ranged weapons.
