### ISSUE TITLE
app: Pressing m for map plays the music but doesn't stops after closing it

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2950]
When we click m for map, It plays the music. 

https://user-images.githubusercontent.com/35926530/167199840-7035038e-eadb-45eb-930a-829ed506c6de.mp4

.

**Comment by avaer** [comment]
The main bug seems that these musics continue outside of their screens. We should make sure to fade out/stop any sort of themes when the menu is closed.

**Comment by alisaad673** [comment]
Yes, Same is the case with character select tab.
