### ISSUE TITLE
Screen will turn black if the fruit is equipped and scene is changed.

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#2972]
When I tried to switch to the some other scene like battlion after equipping fruit from the treehouse scene, it will make all the other scenes black

![image](https://user-images.githubusercontent.com/104460803/167882198-a21eb89f-394d-43ca-a33b-5088e499f6ac.png)

https://user-images.githubusercontent.com/104460803/167885641-1ba7e45f-03bf-404b-a22e-f0d907c744ff.mp4

**Comment by alisaad673** [comment]
This is a general issue with all the equipped items, The crash occurs when we try to Switch scene after equipping any item.
Related: https://github.com/webaverse/app/issues/2992

**Comment by msm0823** [comment]
Duplicate #2992
