### ISSUE TITLE
Avatar loses textures on scene switch (space pod scene)

### ISSUE THREAD

**Issue by ahadshams** [webaverse/app#2975]
Upon scene switch avatar loses textures.. i could not reproduce in other scenes except space pod

@alisaad673 can you pls test and confirm

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/44798013/168015060-117a7692-e737-4fff-a565-83d61505d66e.png">

**Comment by alisaad673** [comment]
Fixed.
