### ISSUE TITLE
Ramp not working

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#2979]
Vehicle is not going over ramp. It just pass through it. The scene resolution also get affected at some points and show lines.

https://user-images.githubusercontent.com/104460803/168108774-4e00a535-0aeb-452b-b89f-f5ca85741def.mp4

**Comment by alisaad673** [comment]
This is basically an issue with vehicle physics, not with the ramp. And the lines are due to the edit mode that you might have accidently turned on.
Closing in favor of this issue: https://github.com/webaverse/app/issues/2980
