### ISSUE TITLE
Error while switching Greenhill scene

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#2982]
While we try to switch greenhill scene to some other scene, It Throws this warning and the other scene doesn't loads.

![image](https://user-images.githubusercontent.com/35926530/168116102-43c6cb7e-0c89-415a-92e4-52c980eee9dd.png)

https://user-images.githubusercontent.com/35926530/168116136-db9f6243-0e6e-4d86-b61b-9ed7235693db.mp4

**Comment by tcm390** [comment]
fixed. Could you please test it again?

**Comment by alisaad673** [comment]
Fixed
