### ISSUE TITLE
Head shown out of the roof

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#2990]
While going upstairs, if the roof is closed, the character should bent down or should not able to move further. But the avatar keeps on moving and his head goes out of the roof.

https://user-images.githubusercontent.com/104460803/168308499-b06c46dd-6361-4eb0-9dd7-ef83be745163.mp4

**Comment by avaer** [comment]
This is a test scene. The assets are arranged for testing corner cases.

Note this scene will probably not exist once there is an overworld.
