### ISSUE TITLE
Avatar passes through buildings (objects) in parkour scene

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#2993]
Avatar passes throught the buildings while it should stop after hitting the buildings.

https://user-images.githubusercontent.com/104460803/168328674-13e62ab9-4508-489e-90a8-4cb35ab40d47.mp4

**Comment by alisaad673** [comment]
Can you try this again too? This might be due to the OOM error?

**Comment by msm0823** [comment]
Yes, the issue is fixed now. Maybe it was a bug due to OOM

**Comment by alisaad673** [comment]
Closing.
