### ISSUE TITLE
Can't go beyond a certain point

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#2997]
Avatar is not able to go beyond a certain point in Crypt scene.

https://user-images.githubusercontent.com/104460803/168358884-dcb180ee-6e6e-4c66-8f0c-c728cd56b680.mp4

**Comment by alisaad673** [comment]
Can you please Try it again?
I wasn't able to reproduce it?
@msm0823

**Comment by msm0823** [comment]
It's working fine now. I guess it's a bug

**Comment by msm0823** [comment]
https://user-images.githubusercontent.com/104460803/171230177-3087a7c0-0949-41fc-922e-c99c4b289c3b.mp4
