### ISSUE TITLE
Bug - undefined pose using teleportation.

### ISSUE THREAD

**Issue by ChrisEddy** [webaverse/app#3]
![Capture](https://user-images.githubusercontent.com/27584221/92312263-ede97900-ef73-11ea-9da3-cd301df0fd26.PNG)

![bbb](https://user-images.githubusercontent.com/27584221/92312275-12455580-ef74-11ea-9ddd-eae106b9ce57.PNG)

`pose` is not defined

**Comment by avaer** [comment]
Thanks, yeah we still need to hook up the VR in engineless.

**Comment by ChrisEddy** [comment]
👍

**Comment by avaer** [comment]
Fixed, thanks!
