### ISSUE TITLE
Pressing "F" while riding vehicles should unwear the vehicle

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3006]
Right now, if we press F while riding a vehicle, the Avatar just flies away, but the vehicle stays in the quick select menu and we have to press "R" separately to unwear the vehicle. This also makes it impossible to ride the vehicle again without pressing R.
Pressing F should simply unwear the vehicle just like "space" and "R" does.

https://user-images.githubusercontent.com/35926530/168610559-b472f47b-5856-4b66-8d1f-688a76d96fbd.mp4

**Comment by lalalune** [comment]
This is fixed in our multiplayer branch
