### ISSUE TITLE
The graphics in shadows scene are not visible.

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3007]
I'm unable to view the objects in shadows scene. The graphics are also not user friendly.

![image](https://user-images.githubusercontent.com/104460803/168619156-80263a90-90ad-45ed-b0e2-59845eab4bf0.png)

**Comment by alisaad673** [comment]
Related: https://github.com/webaverse/app/issues/2483

**Comment by msm0823** [comment]
Plaza scene is too bright as well

https://user-images.githubusercontent.com/104460803/169852304-ba65398c-6987-4652-bc9f-199bea9de7b2.mp4

**Comment by msm0823** [comment]
https://github.com/webaverse/app/issues/2483

Duplicate
