### ISSUE TITLE
Pipe Hitting - Prototype Scene

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3013]
After hitting the boundary wall of the passage in prototype scene, it goes inside the pipe instead of hitting back from it. The avatar should stop but it keeps on going inside

https://user-images.githubusercontent.com/104460803/168871551-9d3407fd-df9c-4cf3-a96c-845d5321f5cc.mp4

**Comment by alisaad673** [comment]
Same issue: https://github.com/webaverse/app/issues/3014
Currently the physics mesh is not working for backside/downside of the models
