### ISSUE TITLE
Unable to Unequip Piano

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3016]
When we equip the piano, we are not able to unequip it.

https://user-images.githubusercontent.com/104460803/168891537-6c8a313f-62be-421c-90fb-22defe842fa9.mp4

**Comment by alisaad673** [comment]
We can unequip it with space but that is not much of a good solution. The reason we can't uneuip it with "R" is because the piano's R is interfering with unequip key "R".

@Loryhoof Can you look into this?
