### ISSUE TITLE
Movement blocked - Desert scene

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3018]
Unable to move beyond a certain point in desert  scene.

https://user-images.githubusercontent.com/104460803/168900484-da87e2ae-ae5b-4c5d-9d4a-48a4efa47da7.mp4

**Comment by alisaad673** [comment]
I wasn't able to reproduce this. Can you Check it again. Btw Make sure the key above "tab"  shouldn't be pressed as it is a secret edit mode. I am talking about the "~" key

**Comment by msm0823** [comment]
Yes, this issue is fixed now.
