### ISSUE TITLE
Unable to go upstairs without jumping

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3021]
We are unable to go upstairs without jumping in tanabata city. The user experience must be improved. Repeated jumping will annoy the user.

https://user-images.githubusercontent.com/104460803/169069041-8dd0be60-09a9-4577-a33f-bace1e4a239c.mp4

**Comment by alisaad673** [comment]
This is just because the scale of the environment is larger rn. We can lower it down.

**Comment by alisaad673** [comment]
Fixed.
