### ISSUE TITLE
Traced Mountain No Ground

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3022]
Avatar is not able to walk or stand on the ground. It can only fly in Traced Mountain. 

The same issue is with Tron Gothic City.

Unable to stand, walk, run in stage scene.

https://user-images.githubusercontent.com/104460803/169074181-01445df4-0c02-4a83-ae14-c5ae05220a19.mp4

https://user-images.githubusercontent.com/104460803/169076623-3cd2eb22-f388-4c7b-aec1-610d8b393025.mp4

https://user-images.githubusercontent.com/104460803/169078132-97a84db1-ff48-4ede-8a6d-984357de5821.mp4

**Comment by alisaad673** [comment]
This Happens when It runs out of device memory. As currently the cached memory is not being cleared.
So you can try reloading the scene. 
Once the OOM error appears, it would happen in any of the scenes
