### ISSUE TITLE
We are unable to stand in boxes in street scene

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3028]
We are not able to stand in boxes in the street scene although there is no error.

https://user-images.githubusercontent.com/104460803/169363732-06bb49f0-e15d-497d-9e19-504631323fa4.mp4

![image](https://user-images.githubusercontent.com/104460803/169363906-c8c3539a-55a0-4735-af48-555c69ce20b7.png)

**Comment by alisaad673** [comment]
The issue is same that we don't have support for meshes on models from backside/downside
Similar:
https://github.com/webaverse/app/issues/3014
