### ISSUE TITLE
Falling Avatar

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3037]
When I try to change scene, the avatar keeps on falling

https://user-images.githubusercontent.com/104460803/169584641-3dfa727a-73ab-49ad-a29c-d2f001f4436c.mp4

**Comment by alisaad673** [comment]
Once you are out of the limits of environment, avatar will keep falling.

**Comment by alisaad673** [comment]
Duplicate: https://github.com/webaverse/app/issues/3008
