### ISSUE TITLE
Tree House scene merged into street scene

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3044]
Upon switching quickly from street scene into the treehouse scene, both scenes are merged.

https://user-images.githubusercontent.com/104460803/169662522-6becc5df-0db9-4c5a-9d41-67aa73e1a05a.mp4

**Comment by lalalune** [comment]
Actually the treehouse has the street in it in the file

**Comment by alisaad673** [comment]
This is actually treehouse. as said by lalalune above.
