### ISSUE TITLE
Black Avatar

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3048]
Avatar became black after switching the scene.

https://user-images.githubusercontent.com/104460803/169850985-d1a64ff0-9843-48f6-8f5c-98a41331c677.mp4

**Comment by lalalune** [comment]
@msm0823 it looks like light isn't loading on yours. I just tried it on mine and it looked OK. Any steps to repro?

![image](https://user-images.githubusercontent.com/18633264/170145896-81cc8242-6f57-4656-92b7-56ad139664b1.png)

**Comment by alisaad673** [comment]
This was fixed. It was because you were on an old version of master
