### ISSUE TITLE
Lag in Walking/Running

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3049]
There is too much lag in walking and running in plaza scene even at above 50fps

![image](https://user-images.githubusercontent.com/104460803/169857450-97b82a8f-6ba7-4871-a765-47d629aec9cd.png)

https://user-images.githubusercontent.com/104460803/169857673-3640e623-24ab-45bd-ad84-b68f29a7c729.mp4

**Comment by lalalune** [comment]
Hmmm, the mutliplayer update may fix this since it's a velocity stutter issue. Once we pull that in we should review this, we make need to interpolate velocity on the local player so that it feels smooth and physics don't jitter.

**Comment by msm0823** [comment]
https://github.com/webaverse/app/issues/2467

**Comment by avaer** [comment]
I think this got worse with more recent multiplayer merges. Now the animation will seemingly short circuit itself on a low frame rate, as if there is a manual restart triggered on every slow frame.

**Comment by alisaad673** [comment]
Fixed: https://github.com/webaverse/app/pull/3422
