### ISSUE TITLE
The text to speech dialogue box do not disappear

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3053]
The text to speech dialogue box do not disappear even if we turn off the microphone and speech option

![image](https://user-images.githubusercontent.com/104460803/169876074-2f3363a2-321f-4490-812e-fa29df1ad36b.png)

**Comment by lalalune** [comment]
This should be fixed in our multiplayer branch, most likely an error where speech server not voicing

**Comment by alisaad673** [comment]
@msm0823 this seems to be working fine now. Can you try again. Closing it for now, Reopen if it persists.
