### ISSUE TITLE
Blurry Graphics

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3061]
After sometime, the graphics quality of the game begin to decrease and we have reduced graphics quality.

https://user-images.githubusercontent.com/104460803/170105111-304fb571-cf68-4438-9964-cbd1e10edfeb.mp4

**Comment by msm0823** [comment]
![image](https://user-images.githubusercontent.com/104460803/170106242-fe29ebb9-20ac-4f66-93d1-27a4ea43e554.png)

**Comment by avaer** [comment]
I think this happens when you fall far outside of the limits of the world (we don't have terminal velocity), and then the vertex rounding error starts to become visible.

This can probably be fixed with

1) terminal velocity
2) kill floors/respawn when out of bounds
