### ISSUE TITLE
Avatar falls while firing

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3062]
https://user-images.githubusercontent.com/36644824/170112560-264f07b9-1ef2-4684-bf42-494bf31793af.mp4

**Comment by alisaad673** [comment]
Yes, This Bug is due to the range being hit by the bullets, This bug is being solved for sword only in this PR by vis,  where we can set which objects will get damaged and which will not. The same can be applied to guns and other weapons too i guess.
https://github.com/webaverse/app/pull/3040

**Comment by gonnavis** [comment]
OK, I'll add `vincibility` logics to pistol/rifle too, and other weapons if any.

**Comment by gonnavis** [comment]
@msm0823 @alisaad673 First try for machine-gun https://github.com/webaverse/machine-gun/pull/1
I'm keep adding to other weaponos.

**Comment by msm0823** [comment]
ok

**Comment by gonnavis** [comment]
All ranged weapons and shooting-range scene should be fixed now.
