### ISSUE TITLE
Mirror is black when character is close

### ISSUE THREAD

**Issue by lalalune** [webaverse/app#3064]
Right now the mirror distance is based on the camera, so it turns off when the camera is far. However, it should ideally be activated by proximity of the local player to accomadate third person cameras.

![image](https://user-images.githubusercontent.com/18633264/170149989-9dbb6027-103a-452a-9510-2b591ef4fb17.png)

**Comment by msm0823** [comment]
It is working fine and I am unable to reproduce it. Can you please retest?

https://user-images.githubusercontent.com/104460803/170251308-43fd83c9-2bb9-434c-a9d7-b3de63e1e8b7.mp4

**Comment by msm0823** [comment]
I have put the camera far away and mirror turns on when the character is near to it. Can you please test it again?

https://user-images.githubusercontent.com/104460803/170251782-e0b5d918-8e73-45a1-bcab-bb07a3dcaa4f.mp4

**Comment by avaer** [comment]
I'm actually not sure how to feel about this. I feel like if the camera is far away, regardless of where the avatar is, the mirror should be disabled.

This can be improved with a temp mirror that's an env map or texture or something.
