### ISSUE TITLE
We cannot select mode through keyboard in toggle menu

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3068]
In toggle menu, there should be an option for the change of mode through some keyboard keys. We need to select separately from mouse instead of keyboard.

https://user-images.githubusercontent.com/104460803/170330681-eec58126-f88a-438f-82bf-28087eee3d33.mp4

**Comment by alisaad673** [comment]
This seems unrelated, You see the design of it(pressing "q") is dependent on mouse/touchpad. Would be messed up with keys.
