### ISSUE TITLE
Asset-Request: Crouch Attack ( one-handed sword ).

### ISSUE THREAD

**Issue by gonnavis** [webaverse/app#3090]
- Start from and return to current crouch animation

a            | b | c
:-------------------------:|:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/10785634/171221403-6d901901-e7c6-4e02-bd63-268ceb68242c.png)   | ![image](https://user-images.githubusercontent.com/10785634/171221851-eee1e56b-df65-41f7-84c1-7f54d3d3e664.png) | ![image](https://user-images.githubusercontent.com/10785634/171222457-23241d1d-4675-472c-b733-e66a314df2b1.png)

- Do the attack like this https://www.youtube.com/watch?v=qlgx7BteUKU&t=53s
![image](https://user-images.githubusercontent.com/10785634/171225447-f6334b5b-09f1-4abb-a36c-065438931927.png)

- All in crouch mode, do not stand up.

**Comment by plankatron** [comment]
shouldnt the sword's blade be pointing down ?

**Comment by gonnavis** [comment]
@plankatron Got it! I'll try to fix it in silsword repo.

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/172436792-49d40f5d-daca-40a3-9d60-5c2661c0838c.mp4

**Comment by plankatron** [comment]
https://user-images.githubusercontent.com/5592454/172436892-874673d4-5fdb-45b3-bd10-886b5664609e.mp4
