### ISSUE TITLE
Avatar Standing in Air in Crypt Scene

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3091]
Avatar is not falling and is standing in the air in crypt scene.

https://user-images.githubusercontent.com/104460803/171228039-3ac4d00e-fdc4-4ca4-97d2-0f855d04d2c0.mp4

**Comment by alisaad673** [comment]
I wasn't able to reproduce this and it appears the issue on your side is due to some already existing bug. Can you try it again?
@msm0823
