### ISSUE TITLE
helm in street scene throws error

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3092]
The helm when weared, is throwing this error

![image](https://user-images.githubusercontent.com/35926530/171228317-c4049082-e8d6-4377-b2f4-afd9f417f2a4.png)

**Comment by ultrabot2022** [comment]
This issue seems to be solved before.

https://user-images.githubusercontent.com/80860637/180859673-9a95f1f8-90a7-4bc2-8f5e-8e2fc7323801.mp4
