### ISSUE TITLE
Asset-Request: New Jump/Double Jump Animation.

### ISSUE THREAD

**Issue by gonnavis** [webaverse/app#3093]
> I was expecting a new set of animations that make a lot more sense in fast combat, with strong emphasis on power jumping and landing

> compatible with these kinds of fast gameplay moments

https://github.com/webaverse/app/pull/3080#issuecomment-1140338078

Refs:

https://user-images.githubusercontent.com/10785634/171231483-97239a2f-9afd-4c92-8ed5-24724d812381.mp4

https://user-images.githubusercontent.com/10785634/171231492-69f5da54-5d35-4411-b2ce-324e387304c4.mp4

**Comment by gonnavis** [comment]
https://user-images.githubusercontent.com/10785634/171229991-601d7ae9-8dd5-411e-8e13-123720cbdbc3.mp4

My feedbacks of current version ( fast implementation ):
I think generally ok, but needs some detailed tweakings.
- Hands can raise up much faster.
- Leg stretching can be smoothed, now too sudden.
- Feels the landing timing not correct. Should crouch very fast, but stand up slowly, now reversed?

https://user-images.githubusercontent.com/10785634/171230336-2180564a-c3d9-47ef-a6ea-479ab18e4462.mp4

- The whole animation looks "robotic", especially the arms jitter in the end. Need to be smoothed out generally.
![image](https://user-images.githubusercontent.com/10785634/171231062-f36c3916-ab61-40e3-b518-69844acc6943.png)

**Comment by msm0823** [comment]
> Current version ( fast implementation ):
> 
>  a31fa4b4400e9888b2caa49fd9ddd1d0.mp4 
> I think generally ok, but needs some detailed tweakings.
> 
> * Hands can raise up much faster.
> * Leg stretching can be smoothed, now too sudden.
> * Feels the landing timing not correct. Should crouch very fast, but stand up slowly, now reversed?
> 
>  503ffea6fc9bab03e0357dd55534e541.mp4 
> * The whole animation looks "robotic", especially the arms jitter in the end. Need to be smoothed out overall.
>   ![image](https://user-images.githubusercontent.com/10785634/171231062-f36c3916-ab61-40e3-b518-69844acc6943.png)



Can be made more faster as shown in the sample above

**Comment by gonnavis** [comment]
> Can be made more faster as shown in the sample above

Ok, I see. The current air time is 999ms, I already tried to reduce it to 666ms ( same as the reference ). Will reflect the change in afterward updates.

**Comment by plankatron** [comment]
double jump looks good but the character needs to rise while the initial part of the flip happens, so far i have not been able to see this result changing the actual animation so i assume the hip is controlled by code?

https://user-images.githubusercontent.com/5592454/172212966-624ff7c6-f456-41dd-89c5-a777670d7c8e.mp4
