### ISSUE TITLE
Short/Chibi Avatars float in mid-air instead of standing on the ground.

### ISSUE THREAD

**Issue by GuiltyRegicide** [webaverse/app#3101]
![image](https://user-images.githubusercontent.com/58578426/171481241-40ff81bb-24be-4d0a-8d06-3bd56368cb34.png)

This has been an ongoing issue with small avatars. Avatar height calculation methods need to be changed so that any size and shape of avatar will stand on the ground properly.

**Comment by ultrabot2022** [comment]
I'd appreciate you could provide a small avatar sample.

**Comment by ultrabot2022** [comment]
@GuiltyRegicide. Please let me know how to reproduce this issue.
And I'd appreciate you provide a sample Short/Chibi Avatar.

**Comment by aryasalehi** [comment]
This is fixed in the engine.
But also this avatar's model-bones should be adjusted 
We calculate the height based on **Head Bone Position**, and the width based on **Shoulder Bones Width(distance between them)**
so those should be adjusted
