### ISSUE TITLE
discord authentication isn't working 

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3110]
For some reason, discord login authentication fails with this error:

![image](https://user-images.githubusercontent.com/35926530/172197448-38aa2a4d-1167-4725-8ea4-fdc9abf595a3.png)

**Comment by mwmwmw** [comment]
This is probably because you're running it from localhost? 

I can still log into app.webaverse.com

**Comment by alisaad673** [comment]
Actually, I have tried it on Dev.webaverse.com, Its deployed and pointing to latest master.
While app.weba is pointing to an older version.

**Comment by mwmwmw** [comment]
Is dev.webaverse a valid redirection URL though? 

This could just be a configuration issue

**Comment by alisaad673** [comment]
Yep Just tested again. This is a redirection issue for dev.webaverse.com. Its working fine for local master too,
@rob-webaverse Can you check this out for dev.webaverse.com?
