### ISSUE TITLE
Own host - Quick start steps does not work for me

### ISSUE THREAD

**Issue by sumeru-digital** [webaverse/app#3115]
After following below steps in Quick start it does not show any url and shows just this
root@nodejs:/var/www/html/app# npm run dev

> webaverse-app@0.0.1 dev
> node index.mjs

What is wrong? I went to ip address of server and tried there  with http://ip:3000 and without port as well and nothing comes.
Help is needed. thanks.

----------------

# Clone this repository
git clone --recurse-submodules https://github.com/webaverse/app.git
# Go into the repository
cd app/
# Install dependencies
npm install
# Run the app
npm run dev
**# Navigate to the URL mentioned in the terminal**

**Comment by alisaad673** [comment]
This is actually part of the build process. You just need to wait for a bit after doing `npm run dev`.
The Url would appear once the build completes.

https://user-images.githubusercontent.com/35926530/172625152-f5ed0b57-94aa-4ff7-9640-266200639c2d.mp4

**Comment by qmiiinc** [comment]
Tried that now and got following error. What could be the reason? thanks

root@nodejs:~# cd /var/www/html/
root@nodejs:/var/www/html# cd app
root@nodejs:/var/www/html/app# PORT=3000 npm run dev

> webaverse-app@0.0.1 dev
> node index.mjs

/var/www/html/app/node_modules/esbuild/lib/main.js:1237
        return callback(new Error(error), null);
                        ^

Error: The service was stopped
    at /var/www/html/app/node_modules/esbuild/lib/main.js:1237:25
    at /var/www/html/app/node_modules/esbuild/lib/main.js:629:9
    at Socket.afterClose (/var/www/html/app/node_modules/esbuild/lib/main.js:607:7)
    at Socket.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
root@nodejs:/var/www/html/app#

**Comment by alisaad673** [comment]
Have you installed node modules through `npm install` ?

**Comment by qmiiinc** [comment]
yes after cloning the git and cd into app folder and installed npm as follows,
still the same error. What is the issue?

Node.js v17.9.1
root@nodejs:/var/www/html/app# npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @pixiv/three-vrm@0.6.7
npm WARN Found: three@0.134.0
npm WARN node_modules/three
npm WARN   three@"./packages/three" from the root project
npm WARN   3 more (@react-three/fiber, troika-three-text, troika-three-utils)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer three@"^0.133.0" from @pixiv/three-vrm@0.6.7
npm WARN packages/three-vrm
npm WARN   @pixiv/three-vrm@0.6.7
npm WARN   node_modules/@pixiv/three-vrm
npm WARN
npm WARN Conflicting peer dependency: three@0.133.1
npm WARN node_modules/three
npm WARN   peer three@"^0.133.0" from @pixiv/three-vrm@0.6.7
npm WARN   packages/three-vrm
npm WARN     @pixiv/three-vrm@0.6.7
npm WARN     node_modules/@pixiv/three-vrm

up to date, audited 1331 packages in 11s

136 packages are looking for funding
  run `npm fund` for details

26 vulnerabilities (8 moderate, 17 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
root@nodejs:/var/www/html/app#

**Comment by mwmwmw** [comment]
did you `git pull --recurse-submodules`?

**Comment by qmiiinc** [comment]
yes all of it is done sir as below. Not sure why I am getting this issue?

Clone this repository
git clone --recurse-submodules https://github.com/webaverse/app.git

Go into the repository
cd app/

Install dependencies
npm install

Run the app
npm run dev

**Comment by qmiiinc** [comment]
**Tried several time on ubuntu 20+, worst experience. just does not pass beyond this error. pathetic documentation and support from them.** check below. clueless


abjgd@lamp-ubuntu-s-2vcpu-4gb-blr1-01:~$ pwd
/home/abjgd
abjgd@lamp-ubuntu-s-2vcpu-4gb-blr1-01:~$ # Clone this repository
abjgd@lamp-ubuntu-s-2vcpu-4gb-blr1-01:~$ git clone --recurse-submodules https://      github.com/webaverse/app.git
Cloning into 'app'...
remote: Enumerating objects: 69679, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 69679 (delta 82), reused 75 (delta 41), pack-reused 69540
Receiving objects: 100% (69679/69679), 1.30 GiB | 10.85 MiB/s, done.
Resolving deltas: 100% (45496/45496), done.
Updating files: 100% (1487/1487), done.
Submodule 'packages/three' (https://github.com/webaverse/three) registered for p      ath 'packages/three'
Submodule 'packages/three-vrm' (https://github.com/webaverse/three-vrm) register      ed for path 'packages/three-vrm'
Submodule 'packages/totum' (https://github.com/webaverse/totum.git) registered f      or path 'packages/totum'
Submodule 'packages/wsrtc' (https://github.com/webaverse/wsrtc.git) registered f      or path 'packages/wsrtc'
Submodule 'packages/zjs' (https://github.com/webaverse/zjs.git) registered for p      ath 'packages/zjs'
Cloning into '/home/abjgd/app/packages/three'...
remote: Enumerating objects: 4883, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 4883 (delta 5), reused 9 (delta 4), pack-reused 4872
Receiving objects: 100% (4883/4883), 242.96 MiB | 10.55 MiB/s, done.
Resolving deltas: 100% (1935/1935), done.
Cloning into '/home/abjgd/app/packages/three-vrm'...
remote: Enumerating objects: 137, done.
remote: Counting objects: 100% (137/137), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 137 (delta 42), reused 125 (delta 33), pack-reused 0
Receiving objects: 100% (137/137), 311.55 KiB | 4.05 MiB/s, done.
Resolving deltas: 100% (42/42), done.
Cloning into '/home/abjgd/app/packages/totum'...
remote: Enumerating objects: 3214, done.
remote: Counting objects: 100% (638/638), done.
remote: Compressing objects: 100% (196/196), done.
remote: Total 3214 (delta 521), reused 496 (delta 427), pack-reused 2576
Receiving objects: 100% (3214/3214), 481.68 KiB | 6.10 MiB/s, done.
Resolving deltas: 100% (2134/2134), done.
Cloning into '/home/abjgd/app/packages/wsrtc'...
remote: Enumerating objects: 758, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 758 (delta 28), reused 37 (delta 16), pack-reused 703
Receiving objects: 100% (758/758), 798.39 KiB | 7.53 MiB/s, done.
Resolving deltas: 100% (479/479), done.
Cloning into '/home/abjgd/app/packages/zjs'...
remote: Enumerating objects: 1045, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1045 (delta 1), reused 1 (delta 0), pack-reused 1041
Receiving objects: 100% (1045/1045), 168.82 KiB | 2.68 MiB/s, done.
Resolving deltas: 100% (629/629), done.
Submodule path 'packages/three': checked out 'ff70991543a05fdae9db93da4551ad72de      036f32'
Submodule path 'packages/three-vrm': checked out 'bedc92855f881e851114971f2e8f76      12fe12375d'
Submodule path 'packages/totum': checked out 'd8f87e8a203d6eed7d1d75e296ca316e4a      487d53'
Submodule path 'packages/wsrtc': checked out 'c0782accfa12cd0a9ff9203d65f9b59fde      4d2cc9'
Submodule path 'packages/zjs': checked out 'd226e1b0b258ae5710c613a6f2f0f5045530      dd1f'
abjgd@lamp-ubuntu-s-2vcpu-4gb-blr1-01:~$ # Go into the repository
abjgd@lamp-ubuntu-s-2vcpu-4gb-blr1-01:~$ cd app/
abjgd@lamp-ubuntu-s-2vcpu-4gb-blr1-01:~/app$ # Install dependencies
abjgd@lamp-ubuntu-s-2vcpu-4gb-blr1-01:~/app$ npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @pixiv/three-vrm@0.6.7
npm WARN Found: three@0.134.0
npm WARN node_modules/three
npm WARN   three@"./packages/three" from the root project
npm WARN   3 more (@react-three/fiber, troika-three-text, troika-three-utils)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer three@"^0.133.0" from @pixiv/three-vrm@0.6.7
npm WARN packages/three-vrm
npm WARN   @pixiv/three-vrm@0.6.7
npm WARN   node_modules/@pixiv/three-vrm
npm WARN
npm WARN Conflicting peer dependency: three@0.133.1
npm WARN node_modules/three
npm WARN   peer three@"^0.133.0" from @pixiv/three-vrm@0.6.7
npm WARN   packages/three-vrm
npm WARN     @pixiv/three-vrm@0.6.7
npm WARN     node_modules/@pixiv/three-vrm

added 1325 packages, and audited 1331 packages in 1m

136 packages are looking for funding
  run `npm fund` for details

26 vulnerabilities (8 moderate, 17 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 8.11.0 -> 8.12.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.12.1
npm notice Run npm install -g npm@8.12.1 to update!
npm notice
abjgd@lamp-ubuntu-s-2vcpu-4gb-blr1-01:~/app$ # Run the app
abjgd@lamp-ubuntu-s-2vcpu-4gb-blr1-01:~/app$ npm run dev

> webaverse-app@0.0.1 dev
> node index.mjs

/home/abjgd/app/node_modules/esbuild/lib/main.js:1237
        return callback(new Error(error), null);
                        ^

Error: The service was stopped
    at /home/abjgd/app/node_modules/esbuild/lib/main.js:1237:25
    at /home/abjgd/app/node_modules/esbuild/lib/main.js:629:9
    at Socket.afterClose (/home/abjgd/app/node_modules/esbuild/lib/main.js:607:7      )
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Node.js v17.9.1
abjgd@lamp-ubuntu-s-2vcpu-4gb-blr1-01:~/app$ # Navigate to the URL mentioned in       the terminal
abjgd@lamp-ubuntu-s-2vcpu-4gb-blr1-01:~/app$

**Comment by alisaad673** [comment]
Apologies for the inconvenience, I have tried on my end and the flow seems to be working working fine. There is some issue on your local. Please try these solutions:
- npm install esbuild
-Make sure you are on latest node version

**Comment by qmiiinc** [comment]
The custom host setup page no found https://docs.webaverse.com/docs/setup-custom-host Will be great if I get step by step process to setup it to work on cloud server like digital ocean with Ubuntu 20.04. thanks pls check below screenshot.

![image](https://user-images.githubusercontent.com/58512318/173543523-700bf0f0-c5f7-48b2-96bf-81195652f8ec.png)

**Comment by qmiiinc** [comment]
The custom host setup page no found https://docs.webaverse.com/docs/setup-custom-host Will be great if I get step by step process to setup it to work on cloud server like digital ocean with Ubuntu 20.04. thanks pls check below screenshot.

![image](https://user-images.githubusercontent.com/58512318/173544418-5826eee3-00cd-4a86-a78a-4e3bf829d4cc.png)

**Comment by qmiiinc** [comment]
Yes both ports are open 3000/1 
But not sure how to and why to change to local.webaverse.com
thanks.

**Comment by qmiiinc** [comment]
Thanks Rob. I did that the other issue now I am facing is the service gets stopped. What is the reason for it? Any idea? thanks
root@ubuntu-s-2vcpu-4gb-amd-blr1-01:~/app# PORT=3000 npm run dev

> webaverse-app@0.0.1 dev
> node index.mjs

Forced re-optimization of dependencies
  > Local: https://local.webaverse.com:3000/
  > World: wss://local.webaverse.com:3001/
**The service was stopped**

**Comment by rob-webaverse** [comment]
I'm not sure. You can try npm start instead of npm run dev. That will start the app running in the background with forever.

**Comment by qmiiinc** [comment]
I used npm start and the result is the same. Maybe I am not able to run this webaverse and its so difficult to understand after changing host in hosts file to point to  (https://local.webaverse.com:3000/). There should be proper documentation for quick start which is missing. thanks, I will try Vircadia now.

**Comment by zyvoi** [comment]
I got it working on Ubuntu by doing this...

1. Clone repo: git clone --recurse-submodules https://github.com/webaverse/app.git

2. Go into the repository: cd app/

3. Pull recursively: git pull --recurse-submodules 

4. Install dependencies:
              . Instead of running "npm install" run "npm install --save-dev --ignore-scripts esbuild"

5. Run the app: npm run dev

**Comment by lalalune** [comment]
@sumeru-digital we've rewritten the docs and quickstart. should be much more straightforward. Check out the README.md!

**Comment by lalalune** [comment]
> I used npm start and the result is the same. Maybe I am not able to run this webaverse and its so difficult to understand after changing host in hosts file to point to (https://local.webaverse.com:3000/). There should be proper documentation for quick start which is missing. thanks, I will try Vircadia now.

By the way, docs moved here:
https://docs.webaverse.com/docs/engineering/setup-custom-host
