### ISSUE TITLE
Can't switch avatars in z-targeting branch

### ISSUE THREAD

**Issue by Loryhoof** [webaverse/app#3123]
![unknown (7)](https://user-images.githubusercontent.com/29487929/173378998-4c81c6d9-63da-4cb9-b40f-eac070fcb40e.png)

Related lines:
https://github.com/webaverse/app/blob/b9c99b6835b742ed78ebe73526a56df65f64a502/character-controller.js#L1043

https://github.com/webaverse/totum/blob/61da3f81567f6677f4b70685d85170d63d6a37fa/type_templates/vrm.js#L112

**Comment by ultrabot2022** [comment]
@lalalune 

https://user-images.githubusercontent.com/80860637/179366795-a7c3d9f0-d67c-4e6a-b5dc-849c56b55548.mp4


I checked again, this issue is fixed meantime.
