### ISSUE TITLE
Baked Lightmaps support

### ISSUE THREAD

**Issue by UncannyAlley** [webaverse/app#3127]
Hi is it possible to implement baked lightmaps into the super duper webaverse. Pretty pretty please kind hackers.

**Comment by gonnavis** [comment]
Do you mean this type of baked lightmaps? https://threejs.org/examples/?q=lightmap#webgl_materials_lightmap
Because of we are using three.js, so it should be supported, just need to design some apis in such as `.scn` files.

**Comment by avaer** [comment]
I think a proper export of GLB might support it already. The THREE.js standard material shaders support it.

https://threejs.org/docs/#api/en/materials/MeshStandardMaterial.lightMap

**Comment by pigloo** [comment]
I've been unable to export a glb with lightmap from blender directly to weba, however it can be achieved by exporting a glb with an second set of UVs for the lightmap/aomap, as well as baking and saving the textures to external image files, you can then traverse the model in three.js and apply the lightmap/aomap to the specific material texture slots, its not the smoothest workflow though.

**Comment by UncannyAlley** [comment]
Thanks so much for the replies. Apologies only seeing them now. Yeah I have just been using vket cloud and they do a cool job of connecting the lightmaps to the models. Although they have Unity as a front end so doing it from there.(im not sure how they do it) 

Webaverse is just too damn cool. The team shld be so freakin proud!

**Comment by madjin** [comment]
I'm testing this out tonight, so far it's not that ez pz lol
https://hubs.mozilla.com/labs/ez-bake-lightmapping/

I'd much prefer is a WYSIWYG workflow like needle tools: https://twitter.com/marcel_wiessler/status/1539737926854221824
I will test such tomorrow 😄

**Comment by madjin** [comment]
I think [three-gpu-pathtracer](https://github.com/gkjohnson/three-gpu-pathtracer) stuff like what bai has been experimenting with could be potentially used for ultra EZ mode 1 click lightmap / AO / GI baking 
![image](https://user-images.githubusercontent.com/32600939/175456599-1c3505bf-37b2-4fd2-bb2f-c08eafdf9366.png)

**Comment by madjin** [comment]
![brave_WmXNrh52UR](https://user-images.githubusercontent.com/32600939/175460983-c0b6ac9c-d9ac-4095-8d1b-59359ce5e42e.jpg)
![brave_K3gNDb9Hq6](https://user-images.githubusercontent.com/32600939/175460987-b03c697d-5ad9-453c-a452-87433aafd5b8.png)

Testing an archviz sample file made with MOZ lightmap, seems like it doesn't work. Admittedly that workflow was really difficult for artists to adopt anyhow. Going to test threejs route via needletools now.

**Comment by lalalune** [comment]
Hey @madjin @UncannyAlley I did a bit of research on this

Here is a GLB with lightmap setup correctly:
[TEST_CUBES_6.zip](https://github.com/webaverse/app/files/8985988/TEST_CUBES_6.zip)

Here is file set up in blender:
![image](https://user-images.githubusercontent.com/18633264/175799526-59e4564a-b987-460a-88ae-79eb0e9c9dad.png)
There are lightmaps on this, but you cannot see them

Here is the same file in Hubs / spoke
![image](https://user-images.githubusercontent.com/18633264/175799541-c805f67e-fb07-491e-931d-1282a9dc395e.png)

I dropped this model into Webaverse and lightmaps loaded fine:
![image](https://user-images.githubusercontent.com/18633264/175799596-59bd1b0d-bf4f-4e3f-954c-53d9205fc8de.png)

Problem is probably with handling and exporting lightmaps, the MOZ_lightmap extension seems to work fine in Webaverse.

We have a Unity tool coming that helps a lot with baking and exporting btw :)

**Comment by lalalune** [comment]
@avaer @UncannyAlley @madjin solved in https://github.com/webaverse/app/pull/3170
