### ISSUE TITLE
Z-Targeting: Crash while trying to Switch Scene from street scene 

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3129]
Selecting the same scene causes the graphics to turn black and cause errors.

https://user-images.githubusercontent.com/104460803/174085263-48271aab-28bd-43e8-bc3f-cc514b7a33a1.mp4

https://user-images.githubusercontent.com/104460803/174085290-153e4b34-ccbb-4722-9e7b-a6ab44fc9587.mp4

**Comment by alisaad673** [comment]
This is actually the case with street scene, If we try to switch to any other scene from street scene, It crashes the app and throws these long list of errors.

![switching zt](https://user-images.githubusercontent.com/35926530/174105371-9687d464-6b1b-4630-897e-e0790f852a83.PNG)
![switching zt 2](https://user-images.githubusercontent.com/35926530/174105364-10fc90c8-a7d1-4a9d-9f75-0d706dcff684.PNG)

**Comment by alisaad673** [comment]
This has been due to the stats banner, since the stats banner is removed, it no longer happens.
https://github.com/webaverse/app/issues/3267
