### ISSUE TITLE
Z-targeting: Unable to change avatar

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3131]
The avatar is not equipped in Z targeting branch

https://user-images.githubusercontent.com/104460803/174105152-0e45c08b-3609-4c21-ba69-a24797d16d14.mp4

https://user-images.githubusercontent.com/104460803/174105166-1725071b-423a-408d-80f6-15d8b411cce2.mp4

**Comment by alisaad673** [comment]
It throws this error while trying to switch avatar

![image](https://user-images.githubusercontent.com/35926530/174112888-c0ea1eb1-1507-48e2-8f2d-cc1b3d26d9ac.png)
