### ISSUE TITLE
Z-targeting: Unable to equip gun/pistol/uzi

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3132]
I have equipped the gun in Z targeting branch but it still remained on the ground.

https://user-images.githubusercontent.com/104460803/174105472-290df274-11e6-45eb-9258-c37b76eb149f.mp4

**Comment by alisaad673** [comment]
Yes, The piston/gun/uzi all three are not getting equipped properly and if we try to fire, they shoot the bullet through its original spawn position. Throws these errors

![image](https://user-images.githubusercontent.com/35926530/174113985-95c5683f-912a-4219-8ab8-51f99bec6542.png)

https://user-images.githubusercontent.com/35926530/174114053-9d8fc263-33ff-4ea3-a881-5f50fb3a4c2e.mp4

**Comment by tcm390** [comment]
https://github.com/webaverse/machine-gun/pull/2
https://github.com/webaverse/uzi/pull/2
https://github.com/webaverse/pistol/pull/14

**Comment by alisaad673** [comment]
Fixed
