### ISSUE TITLE
Z-Targeting: Character Select Option is Not Visible

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3137]
In Character Menu, Character select option is not visible

https://user-images.githubusercontent.com/104460803/174291224-b9bd223e-46e7-4223-8489-fd2e1d6d1c20.mp4

**Comment by alisaad673** [comment]
You need to zoom out.

**Comment by msm0823** [comment]
I zoomed out but the issue is still there

**Comment by lalalune** [comment]
You can solve this by pressing ctrl + -

We need to make the UI more responsive generally, but that's a different issue. Closing this one.
