### ISSUE TITLE
Z-targeting: Expressions are not visible.

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3143]
Character is not showing expressions.

https://user-images.githubusercontent.com/104460803/174453245-785a12e2-b17a-4345-9e97-cc1cec838440.mp4

https://user-images.githubusercontent.com/104460803/174453254-ac7ebd6b-cc19-4a1d-ab2c-28f2f13a0f73.mp4

**Comment by lalalune** [comment]
This was working, might just need review

@msm0823 this is in master branch?

Might be fixed in z-targeting

**Comment by alisaad673** [comment]
Tried this in both master and z-targeting. Works fine.
