### ISSUE TITLE
Z-targeting: Error while loading terrain

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3154]
While we try to load the dual-countering terrain, It throws a long list of these errors and terrain doesn't loads.

![image](https://user-images.githubusercontent.com/35926530/175067304-7ccb4d03-95be-4966-a88d-157528a65931.png)

**Comment by avaer** [comment]
Thanks, it was broken by this merge: https://github.com/webaverse/app/commit/4b9b4ba2839e12b533e8373c49b1eec48432adda#diff-f7c9e958f219541b2f4b5abb3d72c43b6503896ab9986c5ed85ae02a190995c3L254

Should be fixed now.
