### ISSUE TITLE
Z-Targeting: Screen blinking on first load

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3155]
The Z-targeting branch do not load correctly and screen keeps on blinking for the first time. However, if we again refresh the gitub repository and load again, it loads correctly on second attempt.

https://user-images.githubusercontent.com/104460803/175121762-f56b2202-6a11-4d08-b3c8-5c6534c2a8b3.mp4

**Comment by alisaad673** [comment]
I wasn't able ti reproduce it.. Can you post the error you got?

**Comment by msm0823** [comment]
On first load, these are the errors. After reloading it for the second time, it starts working

![image](https://user-images.githubusercontent.com/104460803/175537079-52bd5147-9a38-4cc2-94be-af0f9e2ef956.png)


![image](https://user-images.githubusercontent.com/104460803/175537111-bd975167-572f-4c3c-8dcc-9eac62954b60.png)

**Comment by msm0823** [comment]
https://user-images.githubusercontent.com/104460803/175537421-4773103d-522a-46ff-adaa-85f607b5bb29.mp4

**Comment by lalalune** [comment]
This seems to be a local development issue, I haven't encountered it. I think if you clear your vite stuff it will probably work ok.
