### ISSUE TITLE
Z-Targeting: Helmet reamins in the scene after equipping it

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3174]
After equipping the helmet, it remains in the scene.

https://user-images.githubusercontent.com/104460803/176060634-51973227-1ded-4953-9f7a-35fd2281d22e.mp4

**Comment by alisaad673** [comment]
Related:
https://github.com/webaverse/app/issues/3092
https://github.com/webaverse/app/issues/2373
https://github.com/webaverse/app/issues/2605
https://github.com/webaverse/app/issues/2605

**Comment by aryasalehi** [comment]
this is fixed : https://github.com/webaverse/app/issues/3092
