### ISSUE TITLE
Z-Targeting: Unable to equip Avatar using "E"

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3179]
The display key should be changed from "E" to "G"

![image](https://user-images.githubusercontent.com/104460803/176474093-66d25f58-1cc4-4264-b991-35538114015b.png)

https://user-images.githubusercontent.com/104460803/176474168-c8eefa47-9644-4148-8d9d-fa66afa3b45a.mp4

**Comment by lbgrid** [comment]
https://webaverse.notion.site/metaversefile-628e2c46f49345dfa68a2eab7b89d3f5

**Comment by alisaad673** [comment]
You are confusing between avatars and npcs. This one is npc and it follows you once you hold 'E'.
