### ISSUE TITLE
Implement PhysX Trigger Shapes

### ISSUE THREAD

**Issue by lalalune** [webaverse/app#3183]
We want to make things like automatic doors and optimize water entry and other collidision-based tasks. Currently we have no triggering, and all of our queries are on one layer, so this requires inefficient for loops with multiplayer queries.

We should implement trigger shapes, which is already in PhysX and just needs bindings. I believe that this should just be a few flags to enable even, although we could keep the current API and add a trigger API so that the end developer doesn't need to worry about query flags.

https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/RigidBodyCollision.html?highlight=trigger#trigger-shapes

**Comment by avaer** [comment]
It looks like it's one flag and an event emitter.
