### ISSUE TITLE
Main App: Wearing avatar directly breaks app

### ISSUE THREAD

**Issue by lalalune** [webaverse/app#3197]
Drag and dropped VRM onto window. Did not remove scilly.

![image](https://user-images.githubusercontent.com/18633264/177639273-9d6e9eeb-3cb9-4e46-b570-53d2043f31bb.png)

**Comment by lalalune** [comment]
@ultrabot2022 is this fixed?

**Comment by ultrabot2022** [comment]
It seems the Drag and Drop function doesn't work on my side, I'll check it again.
