### ISSUE TITLE
GLB Animations being Parsed wrong

### ISSUE THREAD

**Issue by helloama** [webaverse/app#3199]
I have been running into an issue with webaverse recently and bringing my animated glb models into it, in the past it would typically pick up my animations and play them normally, however it seems to be reading animations wrong and applying them to the wrong model it self. A few examples below:
![EA9yjqz4hn](https://user-images.githubusercontent.com/91581825/177664118-55a4181f-fe71-49ec-be0c-d457e53833c3.gif)
GLB Viewer:  https://sandbox.babylonjs.com/
Loads perfect.
In Webaverse:
![image](https://user-images.githubusercontent.com/91581825/177664242-c6efc264-34d3-420a-8571-659d133703b0.png)
Mismatched.

![hXvTfQlDvq](https://user-images.githubusercontent.com/91581825/177664254-fcba6d13-b093-4bc2-9e8f-69601bc1d5fd.gif)
Borgor Train loading fine.
![wLhHSPaW66](https://user-images.githubusercontent.com/91581825/177664268-4d4e3df6-9e69-46da-9c0a-0b2ae70221c8.gif)
Webaverse is only a patty animated and small.

![BYficS8KmB](https://user-images.githubusercontent.com/91581825/177664290-0987f4e1-32bf-4445-8f18-d49e969570d6.gif)
![CNEXKATY94](https://user-images.githubusercontent.com/91581825/177664374-057aceee-66a4-4460-83c6-d9670ed50a1d.gif)

Just a few examples, I honestly can't tell if this is on my end or if webaverse is reading animation data wrong with something changed.

I have tried on the public app.webaverse.com as well as a self hosted version. 

Would love some help here!

**Comment by avaer** [comment]
TY for reporting, there's ~90% chance this is a bug on our end.

Most likely in this file where GLTF animations are played: https://github.com/webaverse/totum/blob/main/type_templates/glb.js#L56

To debug this it would be helpful to have a sample file that is exhibiting the bug.

**Comment by helloama** [comment]
> TY for reporting, there's ~90% chance this is a bug on our end.
> 
> Most likely in this file where GLTF animations are played: https://github.com/webaverse/totum/blob/main/type_templates/glb.js#L56
> 
> To debug this it would be helpful to have a sample file that is exhibiting the bug.

Hey Avaer! 

Hope you been well :3.  

The main scene that is displayed in the post above is all packaged in this repo: 

https://github.com/helloama/borgorworld

Primarily the borgor train, ferris wheel, and borgors.

**Comment by lalalune** [comment]
Fixed by https://github.com/webaverse/totum/commit/c967acc293d07f81c7891e16085e1cb5c48a32d0

**Comment by helloama** [comment]
> Fixed by [webaverse/totum@c967acc](https://github.com/webaverse/totum/commit/c967acc293d07f81c7891e16085e1cb5c48a32d0)

hugs and kisses
