### ISSUE TITLE
Character Importing from VRM has issues in both master and Z-targeting

### ISSUE THREAD

**Issue by lalalune** [webaverse/app#3202]
Bug in master:
![image](https://user-images.githubusercontent.com/18633264/177830110-c87f40f6-d3ed-4bcb-9300-e68f3a4629d7.png)

Bug in z-targeting:
![image](https://user-images.githubusercontent.com/18633264/177830135-6b4b2a96-b33a-4351-b3b6-b1eefa95ff58.png)

**Comment by alisaad673** [comment]
Related:
https://github.com/webaverse/app/issues/3131
https://github.com/webaverse/app/issues/3123

**Comment by lalalune** [comment]
@ultrabot2022 we good on this?

**Comment by ultrabot2022** [comment]
It seems that this issue has already been fixed.
