### ISSUE TITLE
Hide [ E ] and disable activate of objects that don't do anything on activate

### ISSUE THREAD

**Issue by lalalune** [webaverse/app#3209]
Right now all GLBs show the [ E ] if you look at them, even big scene ones. This is ugly and misleading to the user, so we should disable it.

![image](https://user-images.githubusercontent.com/18633264/177947179-fd55880d-af38-4f2b-9de9-72612f71c299.png)

**Comment by ultrabot2022** [comment]
This issue was fixed by adding component like {"key": "nonItem", "value": true} to the item info in the SCN file.
I'll push later, please give me feedback after then.

**Comment by lalalune** [comment]
Fixed by https://github.com/webaverse/app/pull/3345
