### ISSUE TITLE
Master: Error switching treehouse scene

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3234]
Treehouse.scn throws this error when we try to switch to any other scene

![image](https://user-images.githubusercontent.com/35926530/178750171-0fc78f15-d6eb-481c-b569-4b3d7fcc7778.png)

**Comment by msm0823** [comment]
Avatar also unable to move in treehouse scene.

**Comment by ultrabot2022** [comment]
It seems like this issue occurred when the resources aren't loaded properly, and can be fixed after adding loading screen, I think.
