### ISSUE TITLE
Master: Errors while switching mic on/off

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3235]
Switching mic on throws this error, While it gets turned on though and then we are unable to disable it.

![image](https://user-images.githubusercontent.com/35926530/178785371-67798a47-337f-4b31-9474-a04751033464.png)

trying to turn it off throws this error and doesn't gets turned off.

![image](https://user-images.githubusercontent.com/35926530/178785509-c58622d2-ea89-4905-ad7c-542d6fbce406.png)

https://user-images.githubusercontent.com/35926530/178785590-80bd041b-ffe7-4016-b825-06dbde1cdb4b.mp4

**Comment by lalalune** [comment]
Fixed with https://github.com/webaverse/app/pull/3222
