### ISSUE TITLE
Master: Vertex shader is not compiled

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3247]
Upon loading the master, the vertex shader is not compiled

![image](https://user-images.githubusercontent.com/104460803/179013124-010d9d6a-2271-460b-86c1-4f59ddedbd20.png)

**Comment by alisaad673** [comment]
Can you point out in which scene it happens? Or how to reproduce it?

**Comment by msm0823** [comment]
When we first load the game, it appears. However, after that, it does not appear on the street scene

**Comment by lalalune** [comment]
couldnt reproduce
