### ISSUE TITLE
Master: Dragon Equipment Issue

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3249]
When we equip the dragon for the second time, it creates another copy of the dragon without removing the first dragon.

https://user-images.githubusercontent.com/104460803/179015902-e88db791-e6a9-4937-9418-5cf37b17abb3.mp4

https://user-images.githubusercontent.com/104460803/179015912-1a10ae7d-ff42-4df0-ae40-ed0932e90bb4.mp4

**Comment by ultrabot2022** [comment]
Checking the project logic, when the customer presses the button to equip an item from Up street, a new item is added to the scene newly, so I think this result is correct.
