### ISSUE TITLE
Master: Equipping dragon without unequipping previous dragon causes movement issues

### ISSUE THREAD

**Issue by msm0823** [webaverse/app#3250]
If we equip another dragon without unequipping the previous one, the movement is applicable to newly equipped dragon while the avatar does not move and camera stands still.

https://user-images.githubusercontent.com/104460803/179017070-d38b4387-a3ac-41d7-acdb-a70e5534b58e.mp4

**Comment by ultrabot2022** [comment]
Do we need automatic animation to move from one equipment to another one about every vehicle?

**Comment by alisaad673** [comment]
This is fixed my #3440
