### ISSUE TITLE
Unable to hide UI anymore

### ISSUE THREAD

**Issue by madjin** [webaverse/app#3261]
Clicking Hide button and ctrl+h (previous hotkey) doesn't seem to work in latest build

**Comment by madjin** [comment]
tried on chrome win10 by clicking the hide ui button
![image](https://user-images.githubusercontent.com/32600939/179373073-9b5edc90-42bd-4570-beae-35fd5dc5609b.png)
![image](https://user-images.githubusercontent.com/32600939/179373079-001217df-12c0-4a3f-b1f6-2016882147d6.png)

**Comment by lalalune** [comment]
Fixed by https://github.com/webaverse/app/pull/3289
