### ISSUE TITLE
In Game Editor  "World Tokens" Crashes Webaverse

### ISSUE THREAD

**Issue by helloama** [webaverse/app#3269]
The in-game editor that you canby  access clicking "Z" on the keyboard seems to crash the whole world. This is using the latest build ran locally.

I did grab the update for the GLB.js in type_templates. not sure if this is causing the issue.

![eV0zud7xHN](https://user-images.githubusercontent.com/91581825/179365579-a509b1b9-2726-4009-88fb-8e7dc7c1ab55.gif)

Recreated on the default street scene as well, here are the errors:

![image](https://user-images.githubusercontent.com/91581825/179365594-0b34ba66-a1b1-41e7-a8f7-661e5fe750b1.png)
![image](https://user-images.githubusercontent.com/91581825/179365603-aa42ee23-3f2e-4f83-bcde-1a9c03da4b8c.png)

**Comment by lalalune** [comment]
Fixed by https://github.com/webaverse/app/pull/3288
