### ISSUE TITLE
Latest build seems to have messed up AI/NPCS

### ISSUE THREAD

**Issue by helloama** [webaverse/app#3285]
Hello! Hate to be annoying, I have pulled the recent build, and the animations are working correctly. However, I am running into an issue with NPCS no longer responding or animating. See in gifs below.
![dyaaMBuMts](https://user-images.githubusercontent.com/91581825/179626441-ec1c8e85-0f8c-4e4c-b3c1-ca00a03531a5.gif)

https://user-images.githubusercontent.com/91581825/179626548-c35c2353-d534-40be-9c28-a50f949b6b4f.mp4

**Comment by lalalune** [comment]
Yep, thanks for posting.

This patch fixes the animation playback:
https://github.com/webaverse/app/commit/fc1976e4488e7e8d41b9f8794d26c732a6b5da2f

**Comment by avaer** [comment]
Awesome, thanks @lalalune!
