### ISSUE TITLE
Add sound effects

### ISSUE THREAD

**Issue by avaer** [webaverse/app#331]
https://www.asoundeffect.com/sound-library/high-tech-interface-sounds/?ref=isp_rel_prd&isp_ref_pos=4

* building UI
* steps

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/103435461-98d90f00-4bc3-11eb-9da3-f496757de12b.png)

It'd be nice to have a woosh / hyperdrive sound effect when teleporting on the parcel as well
