### ISSUE TITLE
Poor quality animations code

### ISSUE THREAD

**Issue by avaer** [webaverse/app#3328]
https://github.com/webaverse/app/pull/3286/files added a lot of poor quality animation code hacks in swimming, such as:

- referencing animations by case sensitive file name instead of logical name
- inline constant hacks
- adding dead variables

This shouldn't have been merged in this state @gonnavis

Additionally, other developers have been copying this code, making surrounding code worse.

**Comment by gonnavis** [comment]
I see, sorry, I wanted to ship water related codes quickly that time.
I'll improve it with the help of patriboz.
