### ISSUE TITLE
Hardcoded ports causes CONN_REFUSED when using nginx and proxy_pass

### ISSUE THREAD

**Issue by justincolangelo** [webaverse/app#3364]
In [universe.js](https://github.com/webaverse/app/blob/master/universe.js#L34) the ports are hard coded (with current + 1). When running this with nginx and using `proxy_pass` the call to /worlds will fail. Can we get the port another way?

**Comment by lalalune** [comment]
You can set the PORT environment variable, by default it's 443.

**Comment by justincolangelo** [comment]
We discussed this on Discord and in that file it is hard coded. Just wanted to bring that discussion here in case it helps others later. It sounds like this will be fixed with other work on multiplayer things. Thanks!
