### ISSUE TITLE
Vite build failed

### ISSUE THREAD

**Issue by MoAra1** [webaverse/app#3367]
![vite](https://user-images.githubusercontent.com/106288605/180876480-8f76786b-87f6-4edb-b134-6a71d3427493.PNG)
After running vite build i get the error throwing: 

return Math.abs(value) < 1e-10 ? 0 : value;
Unable to create production build

**Comment by lalalune** [comment]
Right now we run `npm run prod` in prod.

Build progress is here: https://github.com/webaverse/app/pull/3205

Contributions welcome, especially debugging and uncommenting the freeze() function and dealing with NPC loading.

**Comment by karthikpms** [comment]
Why is this closed? This issue still seems to be present. 

Isn't #3511 reverted in #3611 ?
