### ISSUE TITLE
No character intro for any of the characters in character select panel

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3399]
Characters in character select panel had intro before but now none of the characters have it.

https://user-images.githubusercontent.com/35926530/181544166-593536a9-3c85-455a-a6c2-0327a725160d.mp4

**Comment by mavisakalyan** [comment]
I have a question about this. Can you please refresh the page and try again? As testing this myself I noticed that the intros are just running once after page refresh when the characters are just loading. Pleas confirm this so I know what to do next. @alisaad673
