### ISSUE TITLE
app crashes while we equip dragon after equipping silsword

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3400]
App is crashing if we equip silsword first and then try to equip dragon, It throws this error

![image](https://user-images.githubusercontent.com/35926530/181569093-9cda9246-ea5a-4e7c-95f9-20f7f2535dbb.png)

https://user-images.githubusercontent.com/35926530/181569136-46f176c9-3f8e-4838-9ba1-3f43438b194e.mp4

**Comment by avaer** [comment]
Fixed by https://github.com/webaverse/app/issues/3400

**Comment by alisaad673** [comment]
Reopening because of a regression in the previous fix.

**Comment by alisaad673** [comment]
fixed with: https://github.com/webaverse/app/pull/3440
