### ISSUE TITLE
Equipping sword makes the avatar run and disappear ! 

### ISSUE THREAD

**Issue by aryasalehi** [webaverse/app#3408]
https://user-images.githubusercontent.com/64514807/181755375-b2097ec1-e761-4610-9a32-b5e2c3ba1a75.mp4

**Comment by alisaad673** [comment]
This issue is happening in street scene only, Happens with wearing sword/silsword.

https://user-images.githubusercontent.com/35926530/181772266-5ccec64f-5745-4b8c-828d-62fbabd163f0.mp4

**Comment by lalalune** [comment]
fixed in master
