### ISSUE TITLE
Error while trying to switch to npc('g' key)

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3410]
App Throws this error while we try to switch to the nearest npc with g key and we are unable to switch it.

![image](https://user-images.githubusercontent.com/35926530/181764342-f04d7ca9-2d88-49d3-87cc-1f5cc589ccaa.png)

https://user-images.githubusercontent.com/35926530/181764374-41bf1690-1319-4853-a39a-b4aa4b6cceb8.mp4

**Comment by alisaad673** [comment]
This is working in master now:

https://user-images.githubusercontent.com/35926530/182201726-8d0876fa-d591-45ca-8f1f-9749bce4d591.mp4

**Comment by ultrabot2022** [comment]
This is fixed already in https://github.com/TheNexusCity/webaverse-app/pull/218
