### ISSUE TITLE
helm drop offsets are wrong and re-wearing is broken

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3411]
-Dropping off helmet has wrong offsets and it appears at far away position
-The activator "E" is still at the position where helm was dropped while helm actually is at a far off position
-Re-wearing it by pressing "E" at where it was dropped, It has weird behavior, doesn't gets worn and  a weird black things appears over in the scene.

Related: 
https://github.com/webaverse/app/issues/2605
https://github.com/webaverse/app/issues/2373

https://user-images.githubusercontent.com/35926530/181766619-e34ea6c6-b5b8-4711-9dfc-5b223bf91059.mp4

**Comment by memelotsqui** [comment]
Fixed in #3437 by @tcm390

**Comment by alisaad673** [comment]
fixed
