### ISSUE TITLE
npc appearing at avatars spawn point while the app is loading

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3413]
While the app is loading, the npc appears at the spawn-point of the default avatar till the app fully loads. Even though the defined position for npc is different.

https://user-images.githubusercontent.com/35926530/181776438-a5aa0d03-8d14-4652-b6d0-48a045dbe211.mp4

**Comment by jakezira** [comment]
The npc is loaded at origin position, and then physics moves it to it's initial position. https://github.com/webaverse/app/blob/4fffe3532a358762cf7d5b2f8d4f67427d0cf109/npc-manager.js#L175

**Comment by jakezira** [comment]
npc's mesh is keep rendering at origin while avatar creation and physics is ready.

Best solution seems to be controlling npc's rendering and physics's control time, but hard to figure out.
For now, I updated npc to be hidden till physics is ready.

**Comment by jakezira** [comment]
FYI: The problem was due to avatar is being rendered before it's ever animated
