### ISSUE TITLE
Character Blink support regressed

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3424]
Character no longer blinks in latest master.

Here is a video of character blinking from a previous build:

https://user-images.githubusercontent.com/35926530/181908179-7988baa5-58f7-4203-a27d-a260363feb4d.mp4

**Comment by memelotsqui** [comment]
Seems like latest version (scilly_drophunter_v31.6_Guilty.vrm) doesnt have blink blendshapes, I also tried with (scilly_drophunter_v31_Guilty.vrm) and no blendhspaes either, only working on (scilly_drophunter_v30.5_Guilty)

Current version:

https://user-images.githubusercontent.com/1117257/182738075-2c76138c-a5d0-4694-9a3a-4932c72e112c.mp4

version 30.5

https://user-images.githubusercontent.com/1117257/182738112-b778034b-3b4d-42cc-8a1d-39f32fcc7b07.mp4
