### ISSUE TITLE
Physicscube is texture-less for initial seconds while loading

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3439]
**Describe the bug**
While we load the app, for the initial few seconds, the vrm appears stuck in a cube that is texture-less. Though the textures appear later on.

**To Reproduce**
1. load the app
2. In the initial few seconds of load, the cube is textureless

**Expected behavior**
The cube should appear with textures during the load even

**Screenshots & Recordings**

https://user-images.githubusercontent.com/35926530/182192273-2dd18269-fc24-4c85-a681-e5b0d5515884.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome

**Comment by jakezira** [comment]
Fixed: Postpone rendering and physics till textures are loaded
- https://github.com/webaverse/physicscube/pull/3
- https://github.com/webaverse/physicscube/commit/626275c5be9349146071ba83beaa9072a2005a2c
