### ISSUE TITLE
Physicscube appearing at the spawn point of vrm for initial seconds

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3441]
**Describe the bug**
While the game is being loaded, the physicscube appears at the position (0,0,0) same as that of spawn-point of vrm. 

**To Reproduce**
1. Load the app
2. For the initial loading time, till the game is fully loaded, the cube appears at the spawn point.

**Expected behavior**
It should appear anywhere but the spawnpoint while being loaded. Though this would be solved with a loading screen

**Screenshots**
![image](https://user-images.githubusercontent.com/35926530/182200478-83572ef1-f5c4-4013-9b46-343021e8db62.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome

**Additional context**
Related: https://github.com/webaverse/app/issues/3413

**Comment by jakezira** [comment]
Fixed here: https://github.com/webaverse/physicscube/pull/2
