### ISSUE TITLE
"sit" component not working properly (character physics issue)

### ISSUE THREAD

**Issue by platote** [webaverse/app#3458]
**Bug description**
Everything freezes when using the "sit" component.  "TypeError: Cannot read properties of undefined (reading 'scene')"
Related to #3455, not restricted to planes.

**To Reproduce**

- Import the [plane](https://github.com/webaverse/plane) in a webaverse scene OR make a custom three.js object, with a "sit" component using useActivate() and try to use the vehicle
- See error

**Expected behavior**
The character should be just riding the vehicle. 

**Screenshots**
![image](https://user-images.githubusercontent.com/84842352/182619551-b67e20df-88dc-4d30-9824-8a4cfa7517d5.png)
Adding new screenshots, but same error as in #3455 while being unrelated problem

**Comment by memelotsqui** [comment]
Thank you for reporting this issue :), I will try to fix it.

**Comment by alisaad673** [comment]
Fixed
