### ISSUE TITLE
App's missing the srgbtolinear function & street-base app isn't loading

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3471]
**Describe the bug**
This error is appearing in master and in result, street-base app is not loading.

**To Reproduce**
1. Run the app in browser and open console 
2. street-base is missing

**Expected behavior**
Console should be error free

**Screenshots**
![image](https://user-images.githubusercontent.com/35926530/182843452-c335d6d8-8e72-4659-a00a-d89ded138f95.png)

**Desktop (please complete the following information):**
 - OS: Windows (wsl)
 - Browser Chrome

**Comment by jakezira** [comment]
This is due to @lalalune is merging his update.
