### ISSUE TITLE
Equipping Piano crashes the app

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3480]
**Describe the bug**
In piano.scn , while we try to equip piano, it crashes the app and throws this error

**To Reproduce**
1. Go to piano.scn
2. try to equip piano by holding 'E' key

**Expected behavior**
Piano should work as before without any error

**Screenshots**
![image](https://user-images.githubusercontent.com/35926530/182878201-d2a99159-e2e5-418a-a7d5-dea12d51785c.png)

https://user-images.githubusercontent.com/35926530/182878235-15deeda2-1b78-4a81-a485-982eea297309.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by memelotsqui** [comment]
Might be related to #3458

**Comment by alisaad673** [comment]
Fixed
