### ISSUE TITLE
VRM's physics cube not covering whole avatar

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3485]
**Describe the bug**
In the ann.vrm , the physics cube isn't fully covering the whole avatar.

**To Reproduce**
1. Go to app
2. go close to ann.vrm in street scn.
3. press the tilde grabbing key "~" the one above tab key
4. point toward vrm's center to see its cube

**Expected behavior**
VRM' physics cube should cover whole avatar so that in case of combat, its not missed and for other reasons too.

**Screenshots**
![image](https://user-images.githubusercontent.com/35926530/182938079-b14493cb-15a8-4748-ab97-13bd2c16e3c4.png)

**Comment by jakezira** [comment]
Fixed
