### ISSUE TITLE
Improvise tilde grabbing feature ( ~ key)

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3486]
**Is your feature request related to a problem? Please describe.**
The Tilde grabbing feature is quite confusing right now, like there no proper animation to and no properly defined controls on how to use the feature.

**Describe the solution you'd like**
We need to find ways to improvise it and a way for it to be self explanatory in terms of its use and ways to use

![image](https://user-images.githubusercontent.com/35926530/181908517-519aac06-ce42-4f07-a0da-1d57d7b45869.png)

**Comment by avaer** [comment]
There should be visual in-world indicators for this.

**Comment by patriboz** [comment]
> 

I don't exactly understand what you mean by "visual in-world indicators". Could you give me more details on this please?

**Comment by patriboz** [comment]
@avaer I don't exactly understand what you mean by "visual in-world indicators". Could you give me more details on this please?

**Comment by alisaad673** [comment]
visual Indicators have been added
