### ISSUE TITLE
Arrows released from bow get teleported to other scenes

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3488]
**Describe the bug**
While we use bow and release arrows from it to attack any object, the arrows are there on the object, but on switching the scene, the arrows get teleported along with the vrm to the next scene as well. 
-Same is the issue with damage meshes of swords, guns. They get teleported too.

**To Reproduce**
1. Equip bow and attack any object( release some arrows)
2. Switch scene to any other scene
3. The arrows would teleport too

**Expected behavior**
Arrows should be destroyed on switching scene. 

**Screenshots**

https://user-images.githubusercontent.com/35926530/182943264-22213115-abd3-453a-a674-cbd304f551b1.mp4

**Comment by aryasalehi** [comment]
This is fixed with this PR : https://github.com/webaverse/bow/pull/2

**Comment by avaer** [comment]
https://github.com/webaverse/app/issues/3488

**Comment by aryasalehi** [comment]
Fixed the leak : https://github.com/webaverse/bow/pull/10
