### ISSUE TITLE
Error when installing with npm

### ISSUE THREAD

**Issue by hayfeverx** [webaverse/app#3496]
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: three@undefined
npm ERR! node_modules/three
npm ERR!   three@"./packages/three" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer three@"^0.133.0" from three-vrm@0.6.7
npm ERR! packages/three-vrm

after i follow the steps in the app readme, I type npm install and get the above error ^

Any ways to fix?

**Comment by hayfeverx** [comment]
Any idea?

**Comment by lalalune** [comment]
@hayfeverx try again, this regression should be fixed
