### ISSUE TITLE
Url loading error in master

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3502]
**Describe the bug**
This Error is appearing in master

**To Reproduce**
1. Run the app
2. open console

**Expected behavior**
Console should be error free

**Screenshots**

![lineslash](https://user-images.githubusercontent.com/35926530/183090351-fb7fc1c3-97ea-4673-b101-e1757537ff3b.PNG)

![linserr](https://user-images.githubusercontent.com/35926530/183090356-b2f1a702-1e4d-4e19-bb63-831ad6091a72.PNG)

**Comment by aryasalehi** [comment]
Fixed by pushing the svg
