### ISSUE TITLE
Switching the avatar to npc gives wrong interaction on new avatar

### ISSUE THREAD

**Issue by jakezira** [webaverse/app#3504]
- Load the `street.scn`
- Switch the avatar with npc by pressing 'g'
- You can see interaction icon 'E' around your new avatar
![image](https://user-images.githubusercontent.com/14852075/183098016-ff315419-7718-4223-8a97-519339b47f9d.png)

**Comment by alisaad673** [comment]
Duplicate: https://github.com/webaverse/app/issues/3397

**Comment by jakezira** [comment]
Close due to duplicated
