### ISSUE TITLE
AI NPC Response system gives lore-ai error, and OpenAI does not save your API key

### ISSUE THREAD

**Issue by helloama** [webaverse/app#3518]
Pulled the latest build and attempted to talk to Ann on the street, using the two non-API key AI options to provide a Lore-Ai.js error.

Trying to save OpenAI API key, after hitting apply, you head back to the settings, and it will be empty, with no prompt of the API being saved. 
no response in console since API key is not being saved.

**To Reproduce**
1. pull latest git clone --recurse-submodules https://github.com/webaverse/app.git
2. load and run webaverse, head to settings, AI, AI21 or GooseAI both provide the error.
3.) openAi does not save API key.

**Expected behavior**
Response from NPC via console with prompt as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/91581825/183235785-ba9ab7e8-6bd9-4f03-9603-c47d14877ffc.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome
 - Version 103.

**Comment by jakezira** [comment]
> openAi does not save API key.
Previous implementation left the API key textbox empty on purpose. This PR maintains the latest value: https://github.com/webaverse/app/pull/3522

**Comment by jakezira** [comment]
_load and run webaverse, head to settings, AI, AI21 or GooseAI both provide the error._

@avaer 
Tried on latest, and the version of 6th May, both versions failed to call AI21 and GooseAI API from `ai.webaverse.com`. As both code base fail to call API, I wonder if the GPT service is not working.
How can we monitor the status of these services? Or are there any sample requests available to test?

**Comment by alisaad673** [comment]
Related: https://github.com/webaverse/app/issues/3343
