### ISSUE TITLE
Classroom.scn does not load VRChat HTML page

### ISSUE THREAD

**Issue by avaer** [webaverse/app#3519]
This should be going through the proxy to load the VRChat home page:

![image](https://user-images.githubusercontent.com/6926057/183239328-7621a445-db5c-4ec4-995e-63dd4460690f.png)

Instead, it errors.

```
metaversefile-api.js?t=1659763895440:435 error loading "/@proxy/https://https-vrchat-com.proxy.webaverse.com/" SyntaxError: Unexpected token ':'
```

**Comment by jakezira** [comment]
## Enable HTML page iframe
https://github.com/webaverse/app/pull/3536
https://github.com/webaverse/totum/pull/120
