### ISSUE TITLE
Landing sound effect plays when reaching peak of jump

### ISSUE THREAD

**Issue by avaer** [webaverse/app#3532]
Seems that whenever the jump animation finishes (no double jump), it will play the landing sound effect.

https://user-images.githubusercontent.com/6926057/183266184-2650e53a-f529-4337-9727-1debe468092a.mp4

**Comment by tcm390** [comment]
https://github.com/webaverse/app/pull/3402

**Comment by tcm390** [comment]
fixed in this PR
https://github.com/webaverse/app/pull/3402

**Comment by alisaad673** [comment]
Duplicate: https://github.com/webaverse/app/issues/3481

**Comment by alisaad673** [comment]
Fixed
