### ISSUE TITLE
Cannot click out of character select

### ISSUE THREAD

**Issue by avaer** [webaverse/app#3534]
The top part of the character select is no longer clickable in the MegaHup.

![image](https://user-images.githubusercontent.com/6926057/183268411-887c85b7-3c27-4330-8686-13b7fdba36b5.png)

This recently regressed.

**Comment by alisaad673** [comment]
Fixed:

https://user-images.githubusercontent.com/35926530/184382675-149f99e9-13d7-40bd-8499-bfb447916af1.mp4
