### ISSUE TITLE
Stretchy head on pistol + middle click

### ISSUE THREAD

**Issue by avaer** [webaverse/app#3537]
The pistol (available in `shadows.scn`) can cause a stretchy head glitch when right click (aim) is combined with middle click (lock on).

![image](https://user-images.githubusercontent.com/6926057/183278210-f9023e50-7b49-4070-962b-176787b20f0c.png)

**Comment by lalalune** [comment]
@intelliverse777 is working on this as a test task right now

**Comment by alisaad673** [comment]
Fixed
