### ISSUE TITLE
Sfx issue for switched npc('g' key)

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3565]
**Describe the bug**
-The switched npc doesn't have the footsteps sfx while its walking
-Walking sfx plays while its running

**To Reproduce**
1. Run the app
2. Press 'g' key
3. Walk and run

**Expected behavior**
walking sfx should play when npc is walking and running sfx should play when its running

**Screenshots**

https://user-images.githubusercontent.com/35926530/183646350-a5421f46-730b-4ba6-8bd2-87194ab5e2ba.mp4

**Comment by tcm390** [comment]
https://github.com/webaverse/app/pull/3422

The issue would solved by this PR

**Comment by tcm390** [comment]
related: https://github.com/webaverse/app/issues/3568
