### ISSUE TITLE
Npc's physics wrongly update twice per frame.

### ISSUE THREAD

**Issue by gonnavis** [webaverse/app#3568]
After using `g` key to switch player, npc's ( currently localPlayer ) physics wrongly update twice per frame.
The two call stacks are:
![image](https://user-images.githubusercontent.com/10785634/183708642-3c14e3da-cbe4-47e9-9b15-cdb1039c61e0.png)
![image](https://user-images.githubusercontent.com/10785634/183708647-4f540f55-4d24-4058-8451-3b56963287f7.png)

This will cause problem such as npc's aesthetic jump speed doubled:

https://user-images.githubusercontent.com/10785634/183709487-ee17848e-4566-40c2-b478-b6b1fb1ec0fd.mp4

**Comment by tcm390** [comment]
related: https://github.com/webaverse/app/issues/3565

**Comment by jakezira** [comment]
This also seems related: https://github.com/webaverse/app/issues/3397

**Comment by gonnavis** [comment]
Close due to duplicated https://github.com/webaverse/app/issues/3397#issuecomment-1208686160
