### ISSUE TITLE
List in API based on account contract instead of transfers

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#363]
The API currently creates a list from transfer history. This does not list accounts that have a name/avatar/address -- but do not have any GREASE or NFT ownership yet.

https://github.com/webaverse/api-backend/blob/21a96f4a2c6af78bfa0b385e23d84c8aa8318b8e/index.js#L769

**Comment by avaer** [comment]
We could do it based on whether the user has set a `name` or `avatarUrl` in the `Account` contract metadata.
