### ISSUE TITLE
Move to IPFS

### ISSUE THREAD

**Issue by avaer** [webaverse/app#367]
We were previously on IPFS but it kept crashing on us, so we are currently using S3.

However I think everyone is in agreement IPFS would be much better overall, if it were performant and inexpensive.

**Comment by avaer** [comment]
An IPFS endpoint is implemented:

```
curl https://ipfs.exokit.org/QmbtftrnvgVfgPSCHsp9iUB81ScNnFtn4HUe6EHFcFJgnW
curl https://ipfs.exokit.org/ipfs/QmbtftrnvgVfgPSCHsp9iUB81ScNnFtn4HUe6EHFcFJgnW
curl https://ipfs.exokit.org/QmbtftrnvgVfgPSCHsp9iUB81ScNnFtn4HUe6EHFcFJgnW/lol.js
```

```
echo lol | curl --data-binary @- -XPOST https://ipfs.exokit.org
```

**Comment by madjin** [comment]
closing this issue since we have been on IPFS, next step is Filecoin https://github.com/webaverse/app/issues/748
