### ISSUE TITLE
useAvatarRenderer is not function

### ISSUE THREAD

**Issue by rondoor124** [webaverse/app#3672]
**Describe the bug**
When we pull recent master, we can't find the `useAvatarRenderer` function on `metaversefile-api.js` that `totum/type_templates/vrm.js` is using.

**To Reproduce**
1. Pull current master branch
2. Run `git pull --recurse-submodules`
3. See error

**Expected behavior**
We should have `useAvatarRenderer` somewhere of the app

**Screenshots**
![image](https://user-images.githubusercontent.com/92342281/187300666-60cb533d-d042-45a6-ad36-4aa4733d35b6.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zenkale** [comment]
Also another point to be noted is that it doesn't appears on the deployed version of master (dev.webaverse.com) for some reason.

**Comment by avaer** [comment]
This looks like it's coming from a `totum` version from the labs.

Did `webaverse/app:master` accidentally get a labs version of `totum:master`? Totum currently cannot be updated in this repo, so any such changes need to be reverted.

**Comment by avaer** [comment]
I moved the `totum` version we need for labs to the `labs` branch, so feel free to revert the `totum:main`.

**Comment by avaer** [comment]
> Also another point to be noted is that it doesn't appears on the deployed version of master (dev.webaverse.com) for some reason.

I am assuming the deployment failed and there is no ops person watching it.

**Comment by jakezira** [comment]
- The totum submodule bound with latest `master` apps doesn't have `useAvatarRenderer()` call. https://github.com/webaverse/totum/tree/293d7eedebff2ae58d28bfad910bf72f7a964b07
- You shouldn't try totum `main` version unless app project is updated from labs.

**Comment by avaer** [comment]
Ok cool, seems it's a non-issue then. Closing per @jakezira's investigation. Thanks!

**Comment by avaer** [comment]
If it's still an issue let's set the `webaverse/app` `packages/totum` ref back to the working one.
