### ISSUE TITLE
FE: 404 page design

### ISSUE THREAD

**Issue by avaer** [webaverse/app#387]
https://webaverse.com/lol

Looks like there is no 404 page design yet.

<img width="1201" alt="Screen Shot 2020-12-25 at 6 18 44 PM" src="https://user-images.githubusercontent.com/6926057/103143079-aa12af00-46dd-11eb-8af0-59fdad2d9f59.png">

**Comment by chrislatorres** [comment]
![404pag](https://user-images.githubusercontent.com/29695350/104196563-8c398f80-53e9-11eb-8a59-3b2ae926bc99.PNG)
