### ISSUE TITLE
Invalid token is accepted in login page

### ISSUE THREAD

**Issue by avaer** [webaverse/app#390]
Go to https://webaverse.com/settings
Paste `https://webaverse.com/settings` as your key
Click `LOGIN WITH KEY`
It will seem to log in to something, even though the mnemonic was not valid

It should error/reject this in a validation step. Here is a validation function we can use: https://github.com/webaverse/app/blob/94279d423f06ae2d5bbcf5238ff31dafed16c1bc/ethereum.js#L764

**Comment by chrislatorres** [comment]
Fixed.
