### ISSUE TITLE
Update docs to note we use IPFS

### ISSUE THREAD

**Issue by avaer** [webaverse/app#398]

**Comment by madjin** [comment]
Noted in a number of obvious places like overview (image), items page, and FAQ: https://github.com/madjin/docs/commit/4d34e4cd4520c9541214232f9dc311c07676a6ac

![image](https://user-images.githubusercontent.com/32600939/122651796-363fe500-d109-11eb-87c2-7846aaf24fd3.png)
![image](https://user-images.githubusercontent.com/32600939/122651811-4657c480-d109-11eb-87be-41f225ea282b.png)
![image](https://user-images.githubusercontent.com/32600939/122651819-4eafff80-d109-11eb-9e40-d7e04d72af93.png)
