### ISSUE TITLE
Crouch support

### ISSUE THREAD

**Issue by avaer** [webaverse/app#399]
Being able to crouch is a simple but powerful virtual production technique.

**Comment by madjin** [comment]
I see there's now crouch support, awesome! Possible to tweak the walk speed to be slower when crouched?

**Comment by avaer** [comment]
Absolutely.

**Comment by avaer** [comment]
Should be fixed with https://github.com/webaverse/app/commit/cf7b7310d671fcefb37ad13a97eea99ca55c823b
