### ISSUE TITLE
Bug - invalid callStack ID occasionally. 

### ISSUE THREAD

**Issue by ChrisEddy** [webaverse/app#4]
Might be related to multi-peer. Seems to happen with 2+ peers only.

`edit.js` line 2453:

![vcbfgnrfwtghg](https://user-images.githubusercontent.com/27584221/92324923-0e104b00-effb-11ea-9e18-675b0222d7af.PNG)

**Comment by avaer** [comment]
This is probably not related to multi-peer, it's coming from WebAssembly.

Are there any better repro steps?

**Comment by ChrisEddy** [comment]
Starting 2 tabs, walking around a bit, then backing out and switching tabs, then come back to tab and I get this error.

**Comment by avaer** [comment]
I think this should be fixed. If you haven't seen this particular crash lately, we can close it.

**Comment by avaer** [comment]
Haven't seen this in a while.
