### ISSUE TITLE
FE: setting page/header profile picture is not correct

### ISSUE THREAD

**Issue by avaer** [webaverse/app#422]
https://webaverse.com/settings

<img width="1292" alt="Capture4e1" src="https://user-images.githubusercontent.com/6926057/103274380-86768f80-498f-11eb-92a7-2c262d1dd56c.PNG">

**Comment by chrislatorres** [comment]
It looks like that is an outdated/cached site there because there isn't the cards UI.. I wonder if this has been fixed by now
