### ISSUE TITLE
Docs: document webaverse.link

### ISSUE THREAD

**Issue by avaer** [webaverse/app#437]
At least we should document its existence, though it is self-explanatory once you go there.

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/122660858-bb032100-d152-11eb-9740-878bc4deae13.png)

added into the FAQ section, will be quick to find when search is implemented. Shipping with V2 of docs. https://github.com/madjin/docs/commit/acaf6f339ea29e3383a7cc64678589223c7db977
