### ISSUE TITLE
Not able to find VRM thumb from VRoid Studio

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#440]
> avatar #139 is not loading, not able to find any thumb in the VRM file

https://github.com/webaverse/app/blob/e3d13d98e23b3994484d43c93abe21c70103ba0f/avatars/avatars.js#L721

**Comment by avaer** [comment]
[I fixed that](https://github.com/webaverse/app/commit/890bfa26001b42652145d4c1c3b93aba20294532), but that avatar still fails to preview correctly.

Looking into the preview issue...

**Comment by chrislatorres** [comment]
Should be fixed now, the preview was from loading locally 

![](https://cdn.discordapp.com/attachments/684167488963215364/793686370311864330/Screen_Shot_2020-12-29_at_10.45.02_PM.png)
