### ISSUE TITLE
Discord bot gif backdrop color

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#442]
We currently use a white background for gif previews (https://github.com/webaverse/app/blob/master/screenshot.html#L294), we could use the Discord background to make it look like the items are moving / living "inside" of discord

Discord uses the hex color #36393f for their background.

![discordprev](https://user-images.githubusercontent.com/29695350/103329082-cc2f6880-4a20-11eb-885d-6fe23d30f4e3.PNG)

**Comment by chrislatorres** [comment]
actually, in this case, the bg is different when your @ named

**Comment by avaer** [comment]
What about a grad?
