### ISSUE TITLE
update matrix world on bones for avatars

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#454]
> I am guessing this is because we don't update matrix world on bones and so the attachments subchilds do track
> when we animate we do not updateMatrixWorld

![](https://cdn.discordapp.com/attachments/758975549540007957/793751081066430514/unknown.png)

avatar is `QmcfcmxgPbYbFqFWKCbEpJiUWEXdAw6994wY25fm8WqBbw`

**Comment by avaer** [comment]
Should be fixed.
