### ISSUE TITLE
FE: Add search, sort, and filter

### ISSUE THREAD

**Issue by softwarebycl** [webaverse/app#459]

**Comment by chrislatorres** [comment]
started https://github.com/webaverse/webaverse.com/commit/007deb7f86f093f0678e2dcf2ae8b3cbf351aae4

**Comment by chrislatorres** [comment]
good inspiration https://www.nbatopshot.com/search?orderBy=GAME_DATE_DESC

**Comment by chrislatorres** [comment]
> Just a feature request but while exploring NFTs on the website if we can change preview modes like how in Windows explorer there's thumbnail / detailed list it would make the experience nicer. People can filter by date modified, size, file type, card or raw image previews. Will make experience feel like using the Ethereum world computer Metaverse OS.

**Comment by madjin** [comment]
Added in 
![image](https://user-images.githubusercontent.com/32600939/118403953-e3bd6580-b63e-11eb-929b-fa1537b83c3d.png)
