### ISSUE TITLE
FE: Activity feed

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#460]

**Comment by chrislatorres** [comment]
This can be constructed on the backend api with `getPastEvents` calls

**Comment by chrislatorres** [comment]
got basic version here: https://github.com/webaverse/webaverse.com/compare/9883dca88dd0%5E...72f3d80b02bf

Need to do more backend work, but that will solve:
- https://github.com/webaverse/app/issues/460
- https://github.com/webaverse/app/issues/659

we could subscribe to events (https://web3js.readthedocs.io/en/v1.2.11/web3-eth-subscribe.html) and add them to db to be able to pull from cache instead of having everyone pinging the geth nodes for the same data. Then it can be a normal "web 2.0" api to query.

But also that could go wrong if a server goes down or subscription doesn't work for whatever reason. So we can have a script that gets all of the logs and caches any that do not already exist in the cache. 

then that allows us to make the FE experience much more familiar, as you make transactions, you can get a toast notification that links you to the transaction you just made.. rather than just a loading indicator and hoping it worked (https://github.com/webaverse/app/issues/659)

![webascan3](https://user-images.githubusercontent.com/29695350/106169509-10fc0b80-6155-11eb-9544-2d52dfdd20ac.PNG)

**Comment by avaer** [comment]
As long as servers aren't crashing from it I think web3-direct pagination is fine.

**Comment by chrislatorres** [comment]
added version for FT https://webaverse.com/activity, need to also support for NFTs

**Comment by chrislatorres** [comment]
FT, NFT, LAND should all be supported on activity page and tx detail page https://github.com/webaverse/webaverse.com/compare/c15429b6e2a1...e29a0fe0a810
