### ISSUE TITLE
FE: Allow for showing Discord name on profile

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#461]

**Comment by chrislatorres** [comment]
we have `.discordtoken` in the db for the ids, and then lookup the id with the Discord client like: `Client.fetchUser("123456789012345678");`

I don't know if it completely makes sense to do, it would require a way to keep those names refreshed

**Comment by avaer** [comment]
The bot could fetch those names.

What make most sense to me is... if someone does `.play` or `.key`, we check if they have a name on that account and if not, we set it to the discord name. If there was already a name, do nothing.
