### ISSUE TITLE
APP: scroll wheel to push/pull items

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#471]
Currently you have to learn new keybindings to push and pull objects where using scroll wheel may be more intuitive

**Comment by madjin** [comment]
For reference, JanusWeb has made great use of mousewheel for edit mode and has the following hotkeys:

1234 - change multiplier
mousewheel - move object up and down
shift + mousewheel - move object left and right
alt + mousehweel - move object forward and backwards

test: https://web.janusxr.org/ (hit edit, drag n drop a primitive, right click to activate)

**Comment by madjin** [comment]
Scroll wheel is now moving camera angle while holding an object :\

**Comment by madjin** [comment]
to test: grab object by looking at its bounding box (usually near feet) then press E, then scroll
