### ISSUE TITLE
DISCORDBOT + FE: add .play command

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#476]
This can use the existing `.login` infrastructure and add a query parameter that specifies for the redirect to go to the app instead of the website

**Comment by chrislatorres** [comment]
this is now added from https://github.com/webaverse/ethereum-bot/commit/1f9772d3ac4a925cc90012410b3048bf04a2595d and https://github.com/webaverse/webaverse.com/commit/4eae9b02a47c9d94f6b2f3bef0c36b64b7541918#diff-fafdc9965c46d2390b15f793e6bb5c12f1f6f01509366adb0de4a12ab3639b61R14


need to update this on the Discord bot server

**Comment by avaer** [comment]
Should be updated.
