### ISSUE TITLE
Physics alignment issues with .wbn

### ISSUE THREAD

**Issue by madjin** [webaverse/app#485]
Processed a large 3D model (Internet Archive) as a .wbn with physics, after spawning it in-world I had several issues:

- soon as it spawns I get stuck inside, can't push / pull
- hard to place it where I want it to be, can't fly to get overhead view while grabbing
- strange collision errors afterwords, including invisible walls

Best guess: physics are not aligned with the world position yet.

The video is pinned in `#testing` channel on Discord

**Comment by avaer** [comment]
Physics have been redone a few times since this was filed.

Closing unless there is a good repro case (which could be a new issue).
