### ISSUE TITLE
Loading into parcel falls through floor

### ISSUE THREAD

**Issue by madjin** [webaverse/app#487]
1. When loading into another world, the user will fall through the floor before the map loads
![image](https://user-images.githubusercontent.com/32600939/103473531-82ab8a00-4d4e-11eb-8dba-e4fa0ef9eba7.png)
1. Accidentally hookshotting the floor will cause a person to fall through the ground

**Comment by avaer** [comment]
For 1) I think we do need to wait for the load. That feature exists in the overwold but not for parcels yet.

For 2, the hookshot is not released or supported. We'll fix this before releasing it to buyers though.

**Comment by avaer** [comment]
I'll break these into two separate issues.
