### ISSUE TITLE
nftid in output is mismatch when unpacking

### ISSUE THREAD

**Issue by madjin** [webaverse/app#502]
![2021-01-06-11:53:03](https://user-images.githubusercontent.com/32600939/103813969-c71c7b80-5015-11eb-998c-b7af4e5dcee6.jpg)

**Comment by chrislatorres** [comment]
fixed https://github.com/webaverse/ethereum-bot/commit/f1f3a680c5a2fe4561cdc71041e702ae6a52c8a2
