### ISSUE TITLE
FE: clicking on account page requires two backs to get back

### ISSUE THREAD

**Issue by avaer** [webaverse/app#503]
- Start at https://webaverse.com/land/1
- Click the account selector
<img width="754" alt="Capture4e8" src="https://user-images.githubusercontent.com/6926057/103834484-88a4b200-5051-11eb-80d7-f69f04ec7b21.PNG">
- Hit back two times to get back to https://webaverse.com/land/1; it should be one click

**Comment by chrislatorres** [comment]
fixed
