### ISSUE TITLE
land-main api endpoint not listing correctly

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#510]
The "main" endpoint for land is not currently listing anything, even when there are tokens on mainnet: http://land-main.webaverse.com/1-10

- This is because all of the tokens are inaccurately listing a totalSupply of 0: https://github.com/webaverse/api-backend/blob/master/index.js#L1283

- They are listing a totalSupply of 0 because it is calling `tokenByIdFull` https://github.com/webaverse/api-backend/blob/ca55bdf1532b41d5b30ba2e99a99d6976198c976/index.js#L1282

- `tokenByIdFull` gets totalSupply by looking up ` hashToTotalSupply[hash]` https://github.com/webaverse/contracts/blob/acb7b74073ecc29827feab61b320c23c49118101/ethereum/WebaverseERC721.sol#L317

- the proxy calls `mintTokenId` https://github.com/webaverse/contracts/blob/acb7b74073ecc29827feab61b320c23c49118101/ethereum/WebaverseERC721Proxy.sol#L52

- `mintTokenId` calls `_mint` https://github.com/webaverse/contracts/blob/acb7b74073ecc29827feab61b320c23c49118101/ethereum/WebaverseERC721.sol#L171 

- when this is minted, ` hashToTotalSupply[hash]` is not updated.

**Comment by avaer** [comment]
Can this be closed?

**Comment by chrislatorres** [comment]
yeah, fixed now
