### ISSUE TITLE
FE: add map above LAND cards

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#521]
- a real image map of the street
- mouseover info with owner, name of LAND, if for sale/sale price
- click goes to LAND card detail

**Comment by avaer** [comment]
I think the start of the map would be to add map snapshot functionality to `build.html`. LMK if that is needed.

**Comment by chrislatorres** [comment]
Will need to look more into the best way to get it in...

The most common library for js maps is leaflet https://leafletjs.com/

The map texture is a tile layer https://leafletjs.com/reference-1.7.1.html#tilelayer


 In this TileLayer, you give the URL for the to-be-fetched images to leaflet with a template like this:

`http://{s}.somedomain.com/{z}/{x}/{y}.png`

When you are at the specified zoom, x and y level, Leaflet will automatically fetch the tiles on the URL you gave.

Tiles by default have a 256x256px size (can be changed in the TileLayer options)

**Comment by avaer** [comment]
An initial map renderer is up at https://app.webaverse.com/map.html

It is tiled/lodded, but it is generated at runtime. Instead, we should generate these tiles on the preview server and serve them with something like leaflet.js.

**Comment by avaer** [comment]
Note that because of https://github.com/webaverse/app/issues/532, it might not always render the full world since we don't wait for everything to load, only 5s. User apps will need `waitUntil` support to signal when they finish loading.

**Comment by chrislatorres** [comment]
added initial leaflet map on `add-map` branch of webaverse.com repo just using a manual screenshot of the map - https://github.com/webaverse/webaverse.com/commit/6b4718570a34a363643274f062db8ffb1285c7f2


![streetmap1](https://user-images.githubusercontent.com/29695350/104217762-67e9ad00-5401-11eb-8325-91ba6629b86b.gif)

**Comment by chrislatorres** [comment]
added iframe to https://map.webaverse.com

![mapif](https://user-images.githubusercontent.com/29695350/104635178-2a865900-5667-11eb-8215-03ed346111f7.PNG)
