### ISSUE TITLE
FE: styling bugs due to em usage

### ISSUE THREAD

**Issue by avaer** [webaverse/app#529]
<img width="360" alt="Screen Shot 2021-01-10 at 5 38 18 PM" src="https://user-images.githubusercontent.com/6926057/104138746-2828b400-5374-11eb-8fb5-fb1108337a35.png">

I suspect there are more of these cases where `em` was used in the CSS and `px` is used elsewhere, causing render problems in some case.

MacOS

**Comment by chrislatorres** [comment]
fixed
