### ISSUE TITLE
FE: clicking into categories does not show that category

### ISSUE THREAD

**Issue by avaer** [webaverse/app#537]
I feel like clicking this button should only show avatars: 
<img width="1711" alt="Capture4e9" src="https://user-images.githubusercontent.com/6926057/104362615-064d3f80-54e2-11eb-996c-a6f2cdb8859c.PNG">

On the assets page there could be categories on the left: 
<img width="1119" alt="Capture4e9" src="https://user-images.githubusercontent.com/6926057/104362771-372d7480-54e2-11eb-9c8f-f5fe6c08ebcf.PNG">

**Comment by chrislatorres** [comment]
Similar to https://github.com/webaverse/app/issues/459

**Comment by avaer** [comment]
Closing in favor of #459
