### ISSUE TITLE
FE: clicking View All corrupts history

### ISSUE THREAD

**Issue by avaer** [webaverse/app#538]
- Go to https://webaverse.com
- Click a "View All"
- Back once does nothing
- Back twice takes you out of webaverse

This seems like a bug that's happened before, so we might want to look at the underlying link infrastructure and if this is a tech design problem.

**Comment by chrislatorres** [comment]
You might be clicking it too fast, before the page loads completely

**Comment by avaer** [comment]
Cannot repro anymore.
