### ISSUE TITLE
.inventory says "parcels"

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#544]
![inventoryaprcels](https://user-images.githubusercontent.com/29695350/104467031-7956c480-557b-11eb-9705-907b593a9a8e.PNG)

**Comment by chrislatorres** [comment]
https://github.com/webaverse/ethereum-bot/blob/59a18c2240b1da519d5f2e84ffdabdc095a23441/index.js#L2178

**Comment by chrislatorres** [comment]
updated, needs deploy 

https://github.com/webaverse/ethereum-bot/commit/ea147c43b6c460ec43968b47154a74da87bfb10f

**Comment by avaer** [comment]
Fixed after redeploy.
