### ISSUE TITLE
App: third party NFTs

### ISSUE THREAD

**Issue by avaer** [webaverse/app#547]
We should support displaying the OpenSea suite of NFTs, pulling from their contracts to get the metadata for loading files.

**Comment by avaer** [comment]
To auto-detect NFTs from OpenSea we would need to know the user's address on mainnet, so we would need some sort of account -> mainnet address binding feature.

**Comment by madjin** [comment]
Perhaps this might help in the case of importing cryptoavatars https://github.com/polygonalmind/CryptoAvatars-Interaction-example
