### ISSUE TITLE
FE: show owner on asset page

### ISSUE THREAD

**Issue by avaer** [webaverse/app#548]
> jaredmonkey
> It'd be cool, for on an item page for there to be navigation to see who owns an item.
> It was quite cool as a creator to mint something, have someone else buy it. 
> I'd like to share a link to someone else about this item, and have it be clear someone else owns it now and I created and sold it.

**Comment by chrislatorres** [comment]
added
![ownedby](https://user-images.githubusercontent.com/29695350/104633009-27d63480-5664-11eb-9e42-c34a8abadfbe.PNG)

but more improvements later:
> it could be a lot more prominent to invoke the feeling that yeah you own it
