### ISSUE TITLE
FE: spinner is broken

### ISSUE THREAD

**Issue by avaer** [webaverse/app#549]
I think there is something wrong with the CSS.

<img width="1920" alt="Capture4e9" src="https://user-images.githubusercontent.com/6926057/104626146-86e77980-5663-11eb-9a4c-8a082a22dcd0.PNG">

**Comment by avaer** [comment]
Windows 10, Chrome.

**Comment by chrislatorres** [comment]
fixed https://github.com/webaverse/webaverse.com/commit/1f721386e8f5ee1208db4485fb0d4a80b2e4b5f5
