### ISSUE TITLE
FE: should Map be a tab?

### ISSUE THREAD

**Issue by avaer** [webaverse/app#551]
<img width="1905" alt="Capture4e9" src="https://user-images.githubusercontent.com/6926057/104634555-c798c000-566e-11eb-95cb-dfca586a3fe8.PNG">

I know the plan is to make Land asset inpects have a minimap above. But should we also link to the general map?

**Comment by avaer** [comment]
Related: https://github.com/webaverse/app/issues/521

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/commit/39c351e1663b815d5a1500a092bd7f51acae5e14
