### ISSUE TITLE
FE: loading bars/spinners to increase UX smoothness

### ISSUE THREAD

**Issue by avaer** [webaverse/app#553]
Right now forward/back navigation feels unresponsive due to the load lag.

We should show some indication that the load is happening for a better feel.

**Comment by avaer** [comment]
In same cases we have a spinner but not for forward/back.

This might be something general we want in the design, not per page.

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/commit/e5cd9fcd8f24b2f6d0fe39fe7bb2bcdf3105ac87
