### ISSUE TITLE
land.webaverse.com list endpoint does not show all parcels

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#557]
http://land.webaverse.com/1-100

shows 1, 2, and 6

but you can see the parcel data on their individual endpoint http://land.webaverse.com/5

**Comment by avaer** [comment]
Confirmed.

**Comment by avaer** [comment]
Should be fixed now. We weren't treating LAND as LAND and it was trying to compute unique NFT hash buckets in the ASSET code path.
