### ISSUE TITLE
Docs need to be organized around call to action

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#565]
The creators section should be created around a few call to actions:

* artists creating neighborhoods on the street
* parcel owners deploying to parcels
* general NFT creators, what file formats are supported
* wbn specific NFT guides/apis

**Comment by madjin** [comment]
there's a call to action for participating as a season artist currently on the main overview page
the creator section has many guides, not much on creating and deploying parcels (changed strategies)
