### ISSUE TITLE
FE: no indication LAND token is on mainnet

### ISSUE THREAD

**Issue by avaer** [webaverse/app#572]
After transferring land to main net, it is not clear to the user that their token is already on the main net and it worked.

This is what is seen after the token is supposedly sent to main net, which suggests it did not work:

<img width="505" alt="Capture4e8" src="https://user-images.githubusercontent.com/6926057/104798416-9ca88c00-5794-11eb-9f01-70da2cb1c1c5.PNG">

**Comment by chrislatorres** [comment]
there was already a "transfer **from** mainnet" button once it was on mainnet, but I also added a "view on opensea" button to make it clearer

![onmainnetland](https://user-images.githubusercontent.com/29695350/104815776-3c3d3d00-57dc-11eb-869e-71e0634bef94.PNG)
