### ISSUE TITLE
FE: cannot move to mainnet

### ISSUE THREAD

**Issue by avaer** [webaverse/app#573]
Currently I couldn't get this to work from https://webaverse.com/land/1

It seems to just refresh the page, and the token has not been deposited. Are the contract addresses being pulled correctly? (they were updated)

**Comment by avaer** [comment]
Related: https://github.com/webaverse/app/issues/572

**Comment by chrislatorres** [comment]
should work now https://testnets.opensea.io/assets/0x2ff8240fc458d131b304f1369e8f4903cdab9f2c/4
