### ISSUE TITLE
FE: pull address.js and abi.js automatically

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#574]
Right now there are manually updated, will need to find a way to make it work as these ways do not work right away for FE:

```js
import addresses from 'https://contracts.webaverse.com/ethereum/address.js';
import abis from 'https://contracts.webaverse.com/ethereum/abi.js';
```

```js
  const addresses = await fetch('https://contracts.webaverse.com/ethereum/address.js').then(res => res.text()).then(s => JSON.parse(s.replace(/^\s*export\s*default\s*/, '')).sidechain);
  const abis = await fetch('https://contracts.webaverse.com/ethereum/abi.js').then(res => res.text()).then(s => JSON.parse(s.replace(/^\s*export\s*default\s*/, '')));
```

**Comment by avaer** [comment]
Yeah ideally it does not require a deploy. Everything else pulls it dynamically.

**Comment by chrislatorres** [comment]
The reason 1 doesn't work is because it isn't imported as a script tag as a module to use ES6 url imports

2 doesn't work because there exports in blockchain.js, can't do a top level async in that case

**Comment by avaer** [comment]
It could be es6 imports based.

**Comment by chrislatorres** [comment]
Hmm, going to look into making es6 import work, this would be the easiest solution if we can make it work:

```js
import addresses from 'https://contracts.webaverse.com/ethereum/address.js';
import abis from 'https://contracts.webaverse.com/ethereum/abi.js';
```

**Comment by chrislatorres** [comment]
fixed https://github.com/webaverse/webaverse.com/compare/a2cbb6ddbf95...f1ad9172167e

**Comment by ExplosivePro** [comment]
You currently have an issue related to frustum culling issue?
