### ISSUE TITLE
APP: query string entry to multiplayer rooms

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#577]
![world4042](https://user-images.githubusercontent.com/29695350/104818732-05245700-57ef-11eb-8a55-7d18e3972bea.PNG)
![world404](https://user-images.githubusercontent.com/29695350/104818734-06ee1a80-57ef-11eb-993b-a6174e2cdc07.PNG)

**Comment by chrislatorres** [comment]
hmm when not logged into an account:

a room: https://app.webaverse.com/?r=room-2
refers to https://app.webaverse.com/undefined

**Comment by chrislatorres** [comment]
loading in via query string for rooms does not seem to work, but loading in through the room switcher does seem to work, although there are dangling avatars

![romm3](https://user-images.githubusercontent.com/29695350/104819233-c0e68600-57f1-11eb-9194-02d6bb8740c6.PNG)

**Comment by chrislatorres** [comment]
that `r` for rooms is not being read yet in `bootstrapFromUrl` https://github.com/webaverse/app/blob/master/app.js#L59

**Comment by avaer** [comment]
Should be fixed.
