### ISSUE TITLE
Pedestal link broken

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#580]
from https://github.com/webaverse/app/commit/77c9ceecf3421b127fce469d70c4bd16b6969fed#diff-d0245bcf79685208a493bfa60848f4112c35e0f2e5cc8c89e5bfaf1853154583R487

repro: https://app.webaverse.com/?t=472

**Comment by avaer** [comment]
https://github.com/webaverse/app/commit/182accc1f38c0c2721eb9d48b98901774044f0bf
