### ISSUE TITLE
DOCS: document `load` event for xrpks

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#582]
> the nfts signal their readiness via promise

**Comment by avaer** [comment]
Usage: https://github.com/webaverse/stacks/blob/ff94886adc03d633c85b86f151a7f276d32c78cb/index.js#L1029
Runtime engine implementation: https://github.com/webaverse/app/blob/a67348fc823947fb6b05b3cb879e26392e85c488/runtime.js#L554
