### ISSUE TITLE
FE: add NFT collaborators

### ISSUE THREAD

**Issue by avaer** [webaverse/app#592]
The same thing as https://github.com/webaverse/app/issues/590, except for hash-based metadata collaborators on ASSET NFTs on the frontend.

https://github.com/webaverse/contracts/blob/99b56bde896d98aaa8d63e077678dc486133a857/ethereum/WebaverseERC721.sol#L210

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/compare/7aed11b89f44...be266fbf1696

needs https://github.com/webaverse/app/issues/598 to be functional as expected
