### ISSUE TITLE
FE: LAND previews no rarity colors

### ISSUE THREAD

**Issue by avaer** [webaverse/app#594]
<img width="1900" alt="Capture4e9" src="https://user-images.githubusercontent.com/6926057/104845239-4fb2db80-58a2-11eb-8568-c35f98f7c63d.PNG">

The token has rarity in the API: https://land.webaverse.com/1 
There is a `r=rarity` flag that you can pass to the previewer backend: https://land-preview.exokit.org/32/-8/-24?e=[[-10,0,-26],[-6,4,-22]]&r=epic

It just needs to be patched together on https://webaverse.com/land

**Comment by chrislatorres** [comment]
added, will need to update app constants for rarity https://github.com/webaverse/webaverse.com/compare/53e71a9d30d4...ab24561f3519
![landrarit](https://user-images.githubusercontent.com/29695350/104849723-e1294a00-58b0-11eb-9a73-a675ae7fea61.PNG)
