### ISSUE TITLE
FE: more visit land options

### ISSUE THREAD

**Issue by avaer** [webaverse/app#595]
If feels like there are three levels of visiting land.

1) Visit on street
2) Open hologram
3) Enter parcel

It might need some new engine support but we can handle all of these cases with the proper parameters passed to the `app`.

**Comment by avaer** [comment]
<img width="436" alt="Capture4e9" src="https://user-images.githubusercontent.com/6926057/104845353-f7300e00-58a2-11eb-907c-bf98bb3b0e7f.PNG">

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/compare/ab24561f3519...e274bc54d9f0
