### ISSUE TITLE
addSingleCollaborator does not check if owner

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#597]
https://github.com/webaverse/contracts/blob/99b56bde896d98aaa8d63e077678dc486133a857/ethereum/WebaverseERC721.sol#L246

where setSingleMetadata lets you access if you're an owner _or_ collaborator https://github.com/webaverse/contracts/blob/99b56bde896d98aaa8d63e077678dc486133a857/ethereum/WebaverseERC721.sol#L378

**Comment by avaer** [comment]
Might be fixed with https://github.com/webaverse/contracts/commit/5e0910e8225cead24596456c545e9d96bbcfd333.

However, that needs a contract redeploy.
