### ISSUE TITLE
can addCollaborator but not removeCollaborator

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#598]
https://github.com/webaverse/contracts/blob/99b56bde896d98aaa8d63e077678dc486133a857/ethereum/WebaverseERC721.sol#L217

addCollaborator works, but removeCollaborator returns 
> execution reverted: you are not a collaborator

They both check for `require(isCollaborator(hash, msg.sender), "you are not a collaborator");`

**Comment by avaer** [comment]
Should be fixed now.
