### ISSUE TITLE
FE: options lists are getting unruly

### ISSUE THREAD

**Issue by avaer** [webaverse/app#599]
![image](https://user-images.githubusercontent.com/6926057/104860881-54f04480-58fb-11eb-9671-0ebf2f0fe62d.png)

There are too many options packed in here now, and it doesn't pass the squint test.

As a user dropping into this page, I have no idea what is going on, and some of the options feel scary, like deletion. I instinctively don't want to touch it.

We should separate out these options into categories, use iconography, and use simpler terms, like no mention of Webaverse or other new vocabulary.

**Comment by avaer** [comment]
Some structural inspiration.

![image](https://user-images.githubusercontent.com/6926057/104861456-ee205a80-58fd-11eb-803d-c22d37efd122.png)

**Comment by avaer** [comment]
I think the bot suffers from this too.

**Comment by chrislatorres** [comment]
fixed https://github.com/webaverse/webaverse.com/compare/6062cba7baec...ae5c81383ab5
