### ISSUE TITLE
APP: avatar turns to one direction suddenly

### ISSUE THREAD

**Issue by softwarebycl** [webaverse/app#609]
If you afk / exit pointer lock, the avatars will suddenly face one direction after a period of time

┆Issue is synchronized with this [Jira Task](https://webaverse.atlassian.net/browse/EN-1592) by [Unito](https://www.unito.io)

**Comment by avaer** [comment]
This is because the avatar's velocity rounds to zero and so their direction resets to forward.

It's a bug though.,
