### ISSUE TITLE
FE: allow transferring FT from mainnet

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#616]
https://github.com/webaverse/contracts/blob/99b56bde896d98aaa8d63e077678dc486133a857/ethereum/WebaverseERC20Proxy.sol#L38

**Comment by avaer** [comment]
I _think_ signing should already be supported on the backend: https://github.com/webaverse/api-backend/blob/9c97d6c5c468fb8194abaa772b3577361b62ea4a/routes/sign.js#L107

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/compare/b8549e6465c3...91fdda8f27f5
