### ISSUE TITLE
Docs: point XRPK to https://utils.webaverse.com

### ISSUE THREAD

**Issue by avaer** [webaverse/app#617]
We can build xrpk from directory at https://utils.webaverse.com now, so there is no need for the npm flow.

The only requirement is that the user places a compatible asset file somewhere in the directory. `manifest.json` is supported but if no `manifest.json` exists we will automatically generate it.

**Comment by madjin** [comment]
Updated xrpk pages with relevant information, will get bundled into the V2 release of the docs: https://github.com/webaverse/app/issues/1308
