### ISSUE TITLE
Utils: add bake option when generating XRPK

### ISSUE THREAD

**Issue by avaer** [webaverse/app#618]
We can generate the bake for GLTF/VRM cases when an option is flagged during XRPK build from folder.

This could supersede the "bake" function in the utils since the main reason you'd bake is to put it in an xrpk.

**Comment by avaer** [comment]
At some point we could move the entire bake flow into the mint pipeline.

**Comment by chrislatorres** [comment]
Should this be integrated into the FE / mint process?

**Comment by avaer** [comment]
Yes I think so, for two different cases: "give me physics with this model" and "mint my code".

In order to be useful however, there should first be a preview/test room before the user commits to the mint, teasing what you would get if you hit the "mint for $1" button. But more importantly, the user would be able to intuitively see what they are getting, how it looks and works, and if there are any problems.

Unless we have mint preview support first, I think doing baking as part of the mint process would add even more mysterious failures as the user puts in data and what they minted is some mystery bake of that. Better to see it live and spot problems before any mint.

I suspect we can load blob urls in the runtime in the iframe to load local wbns for preview.

**Comment by avaer** [comment]
Scratch the test part; the test room exists and can be used for this exact purpose.

However, I think we need to clean up the design for it.

**Comment by chrislatorres** [comment]
added "mint my code", need to add "give me physics with this model"

https://github.com/webaverse/webaverse.com/compare/91fdda8f27f5...40da1474d9a8

**Comment by chrislatorres** [comment]
added both now https://github.com/webaverse/webaverse.com/compare/40da1474d9a8...7161f7987264
