### ISSUE TITLE
APP: inspect NFTs

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#623]
Be able to inspect similar to ` physics view/toggle

* name
* description
* NFT owner
* NFT minter
* num of triangles
* num of materials
* file size
* link to asset card

**Comment by madjin** [comment]
The NFT card UI covers atleast half the bases, the other bits of data that'd be useful while inspecting is the tri / material / filesize count so people can assess the quality of objects in worlds and give feedback and imagine use-cases of them based on their performance.
![image](https://user-images.githubusercontent.com/32600939/104962308-07241c80-598d-11eb-9d44-3898ede6c075.png)
Spoke outputs similar useful information right before you export the project to Hubs (which has a nice rating system also). Perhaps this can be displayed as another page on the card?

**Comment by avaer** [comment]
The bake server code knows how to fetch these stats. It makes some sense
that the fe uses the preview server to get stats, while the app computes
the stats in real-time since it is loading the assets anyway.

**Comment by avaer** [comment]
Could include provenance too.

**Comment by madjin** [comment]
Would VRM conditions of use be considered related to this?

**Comment by avaer** [comment]
Possibly, that is a good thing to expose.
