### ISSUE TITLE
Support for reflection/environment maps

### ISSUE THREAD

**Issue by karunakaruna** [webaverse/app#625]
Support for reflection maps defined either globally (all reflective materials reflect skysphere) - or reflections set per object/area. Defining by obect/area would allow interior spaces to have separate reflection maps for different lighting conditions. Environment map interacts with normalmap.

Seen here: [https://stack-59625510.glitch.me/ ]
Also here: [https://gltf-viewer.donmccurdy.com/]

A-frame example:
`<a-plane id="waterplane" rotation="-90 0 0" position="-200 -4 0" width="200" height="200" segmentsheight="1" segmentswidth="1" color="#7BC8A4" material="shader:standard;sphericalEnvMap:sky.png;metalness:.95;normalMap:#waves" scale="" visible="" geometry=""></a-plane>`

**Comment by avaer** [comment]
Looking for a way to declare the override case in Blender.

**Comment by avaer** [comment]
https://threejs.org/docs/#api/en/extras/PMREMGenerator

**Comment by avaer** [comment]
We could either choose an HDRI to use as the env map, generat on load from origina, generate per-object, or generate offline on the preview server.

HDRIs are available here: https://hdrihaven.com/hdris/

To render the cube map we can use https://threejs.org/docs/#api/en/cameras/CubeCamera.
