### ISSUE TITLE
BOT: .send message does not say FLUX

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#626]
![100](https://user-images.githubusercontent.com/29695350/104971133-77de2f80-59b3-11eb-9a1e-1075a1fbb27c.PNG)

**Comment by chrislatorres** [comment]
needs deploy https://github.com/webaverse/ethereum-bot/commit/7137aa7e1f7fd20c6af18ccb9db337de96d78832

**Comment by avaer** [comment]
Deployed.
