### ISSUE TITLE
Lights import very bright

### ISSUE THREAD

**Issue by karunakaruna** [webaverse/app#627]
Lights imported into webaverse appear 10-1000x brighter than defined.
Blend and .glbs: https://www.dropbox.com/sh/fnr627huonijwi0/AADdoTfgcUQ9b68PyseaIvOta?dl=0
Webaverse: https://webaverse.com/assets/500

### 1000w lights:
Blender:
![blender!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-48-18](https://user-images.githubusercontent.com/20630604/104971760-9983ea80-59a4-11eb-907b-1357ccb486ad.png)

![blender!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-37-43](https://user-images.githubusercontent.com/20630604/104971599-1c587580-59a4-11eb-8f2b-a0d2fe6fb02c.png)
![blender!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-37-58](https://user-images.githubusercontent.com/20630604/104971604-1ebacf80-59a4-11eb-8dac-677908328042.png)

Preview in don's gltf viewer: 
![brave!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-39-14](https://user-images.githubusercontent.com/20630604/104971626-2d08eb80-59a4-11eb-9dc8-b8c78fa9b657.png)
Preview in bablyon.js:
![brave!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-40-38](https://user-images.githubusercontent.com/20630604/104971633-35612680-59a4-11eb-8791-57fff276e36c.png)
Webaverse: 
![brave!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-43-27](https://user-images.githubusercontent.com/20630604/104971640-3abe7100-59a4-11eb-81a8-5bddb3c87c5a.png)

### 100w Lights
![blender!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-48-43](https://user-images.githubusercontent.com/20630604/104971777-a7d20680-59a4-11eb-895d-ad824495f172.png)
Don:
![brave!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-49-24](https://user-images.githubusercontent.com/20630604/104971899-0c8d6100-59a5-11eb-8d9c-1550b073ea9d.png)
Babylon:
![brave!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-49-58](https://user-images.githubusercontent.com/20630604/104971900-0eefbb00-59a5-11eb-8799-0fa2f05f28e8.png)
Webaverse:
![brave!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-50-41](https://user-images.githubusercontent.com/20630604/104971906-13b46f00-59a5-11eb-9f0f-2457d279b7ee.png)

### 10w
Blender:
![blender!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-53-26](https://user-images.githubusercontent.com/20630604/104971999-59713780-59a5-11eb-88b3-b008431d8749.png)
Don:
![brave!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-54-03](https://user-images.githubusercontent.com/20630604/104972022-6aba4400-59a5-11eb-9a05-f76944a561ad.png)
Babylon:
![brave!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-54-32](https://user-images.githubusercontent.com/20630604/104972050-8291c800-59a5-11eb-9109-489304bc881a.png)
Webaverse:
![brave!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-55-56](https://user-images.githubusercontent.com/20630604/104972159-c5ec3680-59a5-11eb-8ae2-09560877acc9.png)

### 1w:
Blender: Black
Don: 
![brave!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-56-40](https://user-images.githubusercontent.com/20630604/104972182-d3092580-59a5-11eb-87e6-d194ffef4829.png)
Webaverse:
![brave!UNITO-UNDERSCORE!2021-01-18!UNITO-UNDERSCORE!15-58-10](https://user-images.githubusercontent.com/20630604/104972242-02b82d80-59a6-11eb-9c5b-249ffdaef1cb.png)

**Comment by avaer** [comment]
This is probably because we add extra lights to the scene, to ensure a default avatar render. There might be ways around this by layering scene draw calls per-object.

**Comment by karunakaruna** [comment]
Perhaps, though I wouldn't expect the 1000/100w and 1w versions to be so different in webaverse if it were just a reasonable-intensity scene light being added on top. Though you know best!  

100W
![](https://user-images.githubusercontent.com/20630604/104971906-13b46f00-59a5-11eb-9f0f-2457d279b7ee.png)

1W
![](https://user-images.githubusercontent.com/20630604/104972242-02b82d80-59a6-11eb-9c5b-249ffdaef1cb.png)

The intensity of the color also seems to suggest different intensity levels/falloff.
10W
![image](https://user-images.githubusercontent.com/20630604/105098292-b41a9a00-5a5e-11eb-8312-82d44c946fe3.png)
1W
![image](https://user-images.githubusercontent.com/20630604/105098309-ba107b00-5a5e-11eb-94ac-c1abfd951f06.png)
