### ISSUE TITLE
APP: text chat overflow is hidden / cut off

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#631]

**Comment by avaer** [comment]
Should be solved because we are now deleting extra chat messages.

**Comment by chrislatorres** [comment]
![textwrap](https://user-images.githubusercontent.com/29695350/104981595-884fd380-59ce-11eb-97ae-8aad969d1413.PNG)
 
The text does not wrap / gets cut off if it is too long

**Comment by avaer** [comment]
Good catch.

**Comment by avaer** [comment]
<img width="372" alt="Screen Shot 2021-01-18 at 10 24 34 PM" src="https://user-images.githubusercontent.com/6926057/104984033-fa7ae500-59db-11eb-8a16-f67526330076.png">

I fixed the long message overflows. A very large message could still completely blow the limit but I think most real-world cases should be handled.

Please re-open if it can still be repro'd.
