### ISSUE TITLE
Support .glb animation

### ISSUE THREAD

**Issue by karunakaruna** [webaverse/app#635]
**Currently: minted .glb files with animation do not play back automatically.** 
Same .glb animation plays in https://sandbox.babylonjs.com/ and https://gltf-viewer.donmccurdy.com/

Test .glb: https://www.dropbox.com/sh/onypljfmtpgvbyi/AABxu6uJFBUBcbQ8Wiru5ACYa?dl=0

**Questions:**
What is the default behaviour? Do animations autoloop unless stated otherwise.
How is animation playback defined within the xrpk?
How is animation playback behaviour managed by artists?
Provide standard animation use-cases? Play/Stop on click etc

To me it makes sense that .glbs with animation would auto-play and loop all animation within the file. This would be satisfying for beginners and a lot of life can be given to the world through simple loop animations. Unlikely there is a general use-case in which animation would be present within the .glb but the user would not like it to play.

Possibly related: https://github.com/webaverse/app/issues/210

**Comment by avaer** [comment]
> What is the default behaviour? Do animations autoloop unless stated otherwise.
They should yes, we should implement it that way.
> How is animation playback defined within the xrpk?
We'll add an `autoplay` that makes it configurable.
> How is animation playback behaviour managed by artists?
Via XRPK, though we should provide tooling for managing this.
> Provide standard animation use-cases? Play/Stop on click etc
That seems a separate UI issue but this should be doable from within the world in "edit mode".

**Comment by karunakaruna** [comment]
Related: 
Support .glb bone animation:
Test file: https://www.dropbox.com/sh/hty7gnvct9utsmv/AABXt_oNvfey6VRaWZd7U910a?dl=0
