### ISSUE TITLE
FE: show top flux holders

### ISSUE THREAD

**Issue by avaer** [webaverse/app#636]
It's a question I had, would be cool if the FE had a leaderboard or some sort of distribution graph.

**Comment by avaer** [comment]
It would have to be different for the 4 chains. That would be hard to keep non-confusing.

**Comment by chrislatorres** [comment]
The only one that's important is mainnet+mainnetsidechain in this case. The rinkeby one is not very relevant who has the top.

Also people may prefer to have their holdings "private" (can't really be private on the blockchain), or at least not be publicly announced in this way

**Comment by avaer** [comment]
Hm yeah. Also there are third party tools that do this anyway.

Closing for now.
