### ISSUE TITLE
FE: Mint flow back feature

### ISSUE THREAD

**Issue by avaer** [webaverse/app#638]
The mint flow at https://webaverse.com/mint is great, but a common use case is:

- Upload asset
- Test it out, it's not what I want
- Back to upload new asset

Currently there is no flow for doing that and the back button doesn't work.

We should have both a "Try again with a different asset" link, as well as back button support.

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/compare/fcadc5ff178b...5edef71f846c
