### ISSUE TITLE
App: support multi-glb

### ISSUE THREAD

**Issue by avaer** [webaverse/app#648]
Multiple GLB files (or disparate types of files) referenced from a `.scn`.

The idea is that some would have colliders and some wouldn't.

**Comment by karunakaruna** [comment]
Tried .scn using the unmodified [street](https://github.com/webaverse/street) example without luck.
https://webaverse.com/assets/520
![explorer_2021-01-20_14-44-04](https://user-images.githubusercontent.com/20630604/105250257-4b025780-5b2e-11eb-9985-4ffc22a50cef.png)
![sublime_text_2021-01-20_14-43-50](https://user-images.githubusercontent.com/20630604/105250265-4d64b180-5b2e-11eb-9124-1b5691ec2766.png)
![brave_2021-01-20_14-45-27](https://user-images.githubusercontent.com/20630604/105250324-68cfbc80-5b2e-11eb-958b-6d7059669ff1.png)

**Comment by avaer** [comment]
This is probably a bug on our end, perhaps because there is no `./` prefix on the filename.

What you have looks right, we just need to fix it.

**Comment by avaer** [comment]
There is an example scene here that should work: https://github.com/webaverse/example-scene
