### ISSUE TITLE
Brave is blocking previews while IPFS daemon is running

### ISSUE THREAD

**Issue by madjin** [webaverse/app#652]
While running an IPFS daemon I noticed the assets weren't loading for this preview: https://webaverse.com/preview/447

It was because Brave was blocking them

![2021-01-20-06:57:34](https://user-images.githubusercontent.com/32600939/105193730-aa8c4300-5aed-11eb-8fdf-6984448829f6.jpg)

Everything loads fine, even on Brave, when there is no daemon process in the background. I wonder if Brave's full ipfs:// support can be part of a solution?

**Comment by avaer** [comment]
We could use their IPFS, but this seems like a misdetection on their end. Might have to contact the Brave team about ways around this blocking.

**Comment by avaer** [comment]
@madjin Can you please file this as an issue with Brave, including your setup, so they can tell us how best to get around this block?

https://community.brave.com/

**Comment by avaer** [comment]
@madjin When it's posted in Brave forums, can we add a link to track it here?

**Comment by madjin** [comment]
fixed
