### ISSUE TITLE
Feature: Twitter bot

### ISSUE THREAD

**Issue by avaer** [webaverse/app#653]
Same as the Discord bot except Twitter.

**Comment by avaer** [comment]
This looks like a good backend: https://github.com/FeedHive/twitter-api-client
Here is the API: https://github.com/FeedHive/twitter-api-client/blob/master/REFERENCES.md

Looks like the two methods needed are these:
- https://github.com/FeedHive/twitter-api-client/blob/master/REFERENCES.md#twitterclienttweetsstatusesupdateparameters
- https://github.com/FeedHive/twitter-api-client/blob/master/REFERENCES.md#twitterclienttweetssearchparameters

Technically it could all go in the Discord bot codebase. We can search for #webatweet and run the regular bot's code.

I have the Twitter credentials for out application ready, with:
- API key
- API secret key
- Access token
- Access token secret

Let me know if it's needed.

**Comment by avaer** [comment]
https://github.com/webaverse/ethereum-bot/pull/10

**Comment by avaer** [comment]
We also have https://twitter.com/webatweet, but I don't know if that is a good name choice. It's just needed for the above PR.

**Comment by madjin** [comment]
ready, just needs api keys and better branding
