### ISSUE TITLE
FE: transfer to mainet dialog box is confusing

### ISSUE THREAD

**Issue by avaer** [webaverse/app#657]
Even when in rinkeby the dialog says we are transferring to "mainnet" which cannot be possibly literal.

Can it say it is transferring to `rinkeby`?

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/compare/b24b093c0a60...3aed5b8e80da and https://github.com/webaverse/webaverse.com/commit/d899201d8afedf1cc724a5bb4534b9d2ffe2c1be
