### ISSUE TITLE
FE: transfers should show transaction addrs + links

### ISSUE THREAD

**Issue by avaer** [webaverse/app#659]
As a crypto native person I am expecting a familiar crypto expereince, centered around transaction numbers and etherscan links.

In that mindset though, right now the FE is a little unsettling -- it is a click and pray and doesn't provide cryptonative feedback.

It would be assuring for this persona to have transaction links in toasts or something. Also, perhaps a transaction log page.

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/compare/b40dda6a55a9...07216fbb8958
