### ISSUE TITLE
FE: "Accounts" is a confusing tab

### ISSUE THREAD

**Issue by avaer** [webaverse/app#660]
- Creators
- Users
- Collectors
- People
- Versers (my favorite since it is most descriptive)

Then again Uniswap uses Accounts.

Putting the issue up for debate/closure.

**Comment by chrislatorres** [comment]
I think NBA Top Shot is a good case study for naming. They've created a really successful NFT platform, but if you go to their site , there isn't really any use of "crypto" terms.

https://www.nbatopshot.com/

**Comment by avaer** [comment]
"Members" was suggested by Jared.

**Comment by chrislatorres** [comment]
Accounts initially came from how OpenSea labels routes, but I will update the navbar to "Members" as it is easy enough. We can also update the routes/links if it makes sense to.

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/commit/58dbfdf6e9fb04aea07eef461f299881e0fd0435
