### ISSUE TITLE
AWS: Backups

### ISSUE THREAD

**Issue by avaer** [webaverse/app#671]
We should have a backup schedule + continuity in place for S3, DynamoDB, IPFS (our own node on EC2), and Geth (EC2).

**Comment by avaer** [comment]
https://www.tarsnap.com/
https://rsync.net/

**Comment by avaer** [comment]
The latest word was using rsync.net

**Comment by soulofmischief** [comment]
https://github.com/webaverse/backups

Requires:
https://github.com/webaverse/ethereum-backend/pull/4
https://github.com/webaverse/ethereum-backend/pull/3

**Comment by soulofmischief** [comment]
@avaer now that IPFS and geth are in place, do you still want S3 and DDB or can I mark this closed?

**Comment by soulofmischief** [comment]
35-day AWS backups enabled for `users` table.

**Comment by avaer** [comment]
This is ok, but I think we should have it in perpetuity and daily.

This is actually not a huge table so I don't think the costs would be large.
