### ISSUE TITLE
FE: invalid discord code hangs

### ISSUE THREAD

**Issue by avaer** [webaverse/app#673]
https://webaverse.com/login?id=284377201233887233&code=228182&play=true

This should at least show an error message.

**Comment by avaer** [comment]
```
login-f35b5c58cf81ffe04d73.js:1 POST https://login.exokit.org/?discordcode=228182&discordid=284377201233887233 403 (Forbidden)
```

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/commit/b24b093c0a60304ac65fa32f5ac3506e26d250cb
