### ISSUE TITLE
FE: never reload page

### ISSUE THREAD

**Issue by avaer** [webaverse/app#675]
We've had several cases where the FE errors on some blockchain thing and then refreshes, silently ignoring the error.

This is not acceptable in production in any scenario, since it prevents debugging and reproduction. We should never need to refresh the page on the FE. The UI state should instead be updated to be the new state.

Can we get rid of all cases of FE reload?

**Comment by chrislatorres** [comment]
fixed https://github.com/webaverse/webaverse.com/compare/fdf3f4d2253b...b7949b10bab6
