### ISSUE TITLE
APP: sketchfab assets require scaling down to 0.1 original size

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#679]
This is a common thing for sketchfab assets

**Comment by avaer** [comment]
It is most likely that we are not absorbing the scene matrix. Could you post an affected asset?

**Comment by chrislatorres** [comment]
https://ipfs.exokit.org/QmSJSizgEhTKoUPqaJWT4VA7ektFaksYpLee9DMsSaamxa/item.glb

**Comment by avaer** [comment]
This looks like the correct behavior, and the file is just huge.

For the price of loading jank on all models to compute the bounds, we can forbid city sized models by default and apply scale.

**Comment by avaer** [comment]
Note that with this change, things like the homespace container are forbidden by default and will scale down.

**Comment by avaer** [comment]
The way I ended up doing it is:

- `dynamic` objects (pickupable by the user) are the only ones that are autoscaled by default to 4m (fortnite rules)
- `autoScale` parameter allows the authro to disable auto scale even on dynamic objects

**Comment by avaer** [comment]
Done.
