### ISSUE TITLE
FE: add editor/scene support

### ISSUE THREAD

**Issue by avaer** [webaverse/app#682]
We should be able to create scenes from the FE, perhaps in the try room.

`.scn` is a [supported JSON format for NFTs in the runtime](https://github.com/webaverse/app/blob/dd946b4109a519016c096d7e5bc233c2ffb4daa5/runtime.js#L849).

**Comment by avaer** [comment]
I'm thinking a flat scene graph editor to generate the `.scn` xrpks.

**Comment by chrislatorres** [comment]
added https://editaverse.com/projects/new -- though this has a lot of room for improvement, needs to be more integrated into webaverse... like ability to place NFTs you own, etc.
