### ISSUE TITLE
FE: land page show deployed content hash

### ISSUE THREAD

**Issue by avaer** [webaverse/app#684]
We could use an an easily accessibly place for the content has for parcels to be displayed.

**Comment by chrislatorres** [comment]
![deployedcontentCapture](https://user-images.githubusercontent.com/29695350/105597358-90ef3380-5d59-11eb-9b22-3f9eb1bab274.PNG)

added https://github.com/webaverse/webaverse.com/compare/a740fe9f5aa3...691fbb310c0a
