### ISSUE TITLE
FE: "Open hologram" button is not an anchor

### ISSUE THREAD

**Issue by avaer** [webaverse/app#685]
<img width="955" alt="Screen Shot 2021-01-23 at 6 00 56 AM" src="https://user-images.githubusercontent.com/6926057/105576382-62189380-5d40-11eb-9bf3-d0aec32f1125.png">

How UX considerations, we should make this an anchor and openable in a new tab like the other anchors on that page.

**Comment by chrislatorres** [comment]
fixed https://github.com/webaverse/webaverse.com/commit/a740fe9f5aa39bc1e9e05327d21332cb98594b3f
