### ISSUE TITLE
Style / Cleanup the avatar upload button.

### ISSUE THREAD

**Issue by ChrisEddy** [webaverse/app#69]

**Comment by ChrisEddy** [comment]
button is gross looking and thrown in for a demo, needs a real skinning with CSS.

**Comment by avaer** [comment]
Avatars are part of inventory for future, so this should probably go away entirely.

Instead we need clean CSS for popping up the inventory in desktop mode. This could just be taken from the existing HTML rendering that happens in VR mode (`vr-ui.js`).

**Comment by avaer** [comment]
Will be done as part of the new UI cleanup.
