### ISSUE TITLE
App: consider Hubs flows (Blender exporter)

### ISSUE THREAD

**Issue by avaer** [webaverse/app#692]
https://github.com/MozillaReality/hubs-blender-exporter/releases

**Comment by madjin** [comment]
Webaverse uses Blender like how VRChat uses Unity. Here are some ideas for improving the pipeline:

- name thing for LODs
- environment map export
- lightmap previewing
- use custom blender data for colliders

What about custom shaders such as adding water into a scene?

> It would be trivial to add a "SHADERTYPE" node and have like unlit, water, emissive, normal, or just parse any model named <whatever>_WATER.
