### ISSUE TITLE
Docs: Mozilla Hubs component support 

### ISSUE THREAD

**Issue by avaer** [webaverse/app#695]
We support https://github.com/MozillaReality/hubs-blender-exporter#using-lightmaps, animations, and the uv animation Hubs component.

This should be documented/linked in the docs.

**Comment by avaer** [comment]
Related: https://github.com/webaverse/app/issues/627

**Comment by madjin** [comment]
added here: https://docs.webaverse.com/docs/webaverse/worlds#blender
will add a before/after screenshot when upgrading to v2 https://github.com/webaverse/app/issues/1308
