### ISSUE TITLE
FE: mobile clicking hits Twitter instead of actions

### ISSUE THREAD

**Issue by avaer** [webaverse/app#698]
![image](https://user-images.githubusercontent.com/6926057/105616459-09c7ad00-5da5-11eb-8eda-a523842bda45.png)

**Comment by chrislatorres** [comment]
this might be safari/iOS specific, cannot repro on android+brave/chrome

**Comment by avaer** [comment]
Yeah I can't repro in emulation in Chrome. But it repros in a real iPhone.

**Comment by chrislatorres** [comment]
maybe fixed by this https://github.com/webaverse/webaverse.com/commit/6fa23f991ffabea71dcb16e632501c2fd889b47a ?

If you clear cache/refresh does this still occur?

**Comment by softwarebycl** [comment]
Closing outdated issue.
