### ISSUE TITLE
App: mountables cannot mount in preview

### ISSUE THREAD

**Issue by avaer** [webaverse/app#715]
Clicking does not mount: https://webaverse.com/preview/172

I don't know if this NFT is bad, it needs experimentation.

**Comment by chrislatorres** [comment]
These were made as xrpks with `xrpk build .` from the github repos. They also did not work in app.webaverse.com spawned from loadout or inventory tab

**Comment by avaer** [comment]
Thanks, in that case, I think `xrpk` might need to be updated to whitelist some fields.

**Comment by avaer** [comment]
Fixed with https://github.com/webaverse/xrpackage-cli/commit/dce39e673cf7911e5b09fe65012e6b5a59c1f98d.

https://webaverse.com/preview/216

You will need to update to `xrpk@0.0.80` before creating WBNs for this to work.
