### ISSUE TITLE
Docs: pets/wearables/sittables

### ISSUE THREAD

**Issue by avaer** [webaverse/app#718]
I'm not sure what the terminology for these three should be but we need documentation for them.

# Pets
https://github.com/avaer/dragon-pet/blob/master/manifest.json
https://github.com/avaer/dragon-fly/blob/master/manifest.json

# Wearables
https://github.com/avaer/cat-in-hat/blob/master/manifest.json
https://github.com/avaer/sword/blob/master/manifest.json

# Mounts
https://github.com/avaer/dragon-mount/blob/master/manifest.json

**Comment by madjin** [comment]
Docs pages have been created for each:

https://docs.webaverse.com/docs/create/pets
https://docs.webaverse.com/docs/create/wearables
https://docs.webaverse.com/docs/create/mounts
