### ISSUE TITLE
Preact UI

### ISSUE THREAD

**Issue by avaer** [webaverse/app#72]
- Add Preact
- Integrate menus for tools as a 2D render on the page
- System for stringifying preact and rendering it with [exokit-render](https://github.com/exokitxr/exokit-render) and `vr-ui.js`
- System for tracking anchor callbacks for 3D renders so VR clicks work
- Copy 3D menus to 2D

Later:
- Split 2D and 3D menu systems to optimize for the respective form factor

**Comment by ChrisEddy** [comment]
This is a pre bug issue. I'ma keep this but do smaller tickets to split up the work a bit.

**Comment by avaer** [comment]
Well in progress.
