### ISSUE TITLE
APP: multiplayer pet duplicates

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#730]
not sure on exact repro, this happened when I joined a parcel that already had someone in it with a pet following them.

![multiplayerpets](https://user-images.githubusercontent.com/29695350/106314630-9c49cf80-622f-11eb-8ce2-62be236d4cb6.PNG)

**Comment by avaer** [comment]
Probably the pet is not being detected as a dupe when sending status.

**Comment by avaer** [comment]
Fixed.
