### ISSUE TITLE
FE: progress bar for upload/minting

### ISSUE THREAD

**Issue by avaer** [webaverse/app#743]
I had a 5 minute upload and thought the page was broken during mint.

With a progress bar, we can also add HYPE with "Reticulating splines" type messages: https://modthesims.info/archive/index.php?t-331011.html

**Comment by chrislatorres** [comment]
Nice, I like the hype messages

**Comment by chrislatorres** [comment]
added initial version, need to adjust design https://github.com/webaverse/webaverse.com/compare/dec17ed28601...20214831d3da

>  a little too candycane, and not enough digital on that bar

![load2](https://user-images.githubusercontent.com/29695350/106559888-b3b4e100-64eb-11eb-8720-437641146403.PNG)

**Comment by chrislatorres** [comment]
fixed https://github.com/webaverse/webaverse.com/commit/24ac71d3f99d6bcf84a7dd58477673c449f60ab2
