### ISSUE TITLE
FE: 2D art issues

### ISSUE THREAD

**Issue by avaer** [webaverse/app#744]
- cards crop the images

**Comment by chrislatorres** [comment]
this is because of the css 

`object-fit: cover;`

Would need to rearrange the card size overall to adapt to the aspect ratio of the image. 

The cards would look less like rectangle cards and more like square cards or there would be white space

**Comment by chrislatorres** [comment]
changed object-fit to contain -- this fixes this, but the tradeoff is now the card images will have whitespace instead

https://github.com/webaverse/webaverse.com/commit/824f455489467b7005f19dc0b3f84230bb6b408e
