### ISSUE TITLE
IPFS: find filecoin service

### ISSUE THREAD

**Issue by avaer** [webaverse/app#748]
We have some filecoin to use. If it gives us IPFS hosting it could be worth it to move.

I like Pinata but it might not be ready.

https://docs.filecoin.io/build/

**Comment by madjin** [comment]
https://blog.textile.io/announcing-managed-powergate-instances-enterprise-filecoin-and-ipfs/
https://docs.textile.io/buckets/

**Comment by madjin** [comment]
Opensea does Filecoin now for freezing metadata. https://filecoin.io/blog/posts/opensea-decentralizes-and-persists-nft-storage-with-ipfs-and-filecoin/
