### ISSUE TITLE
APP: scn coords do not map to blender coords

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#749]
![coords (2)](https://user-images.githubusercontent.com/29695350/106399385-e4a6f000-63dd-11eb-8755-e600f824fc32.PNG)

**Comment by avaer** [comment]
This sounds like a GLTF exporter issue. There is a "Y UP" flag that needs to be checked in the exporter.

**Comment by avaer** [comment]
<img width="1920" alt="Capture4e10" src="https://user-images.githubusercontent.com/6926057/106400139-ba0f6400-63ea-11eb-90a9-b418a4272891.PNG">

**Comment by avaer** [comment]
Also manual: https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/210

**Comment by karunakaruna** [comment]
In my case Y up has been checked on blender export, but coordinates of a point do not match .scn file: 
![image](https://user-images.githubusercontent.com/20630604/106400678-b5d84c00-63d4-11eb-97a3-8bee3ea793a5.png)

![image](https://user-images.githubusercontent.com/20630604/106400694-d30d1a80-63d4-11eb-9a33-c10b62328ef0.png)
Same point in .scn is: 
![image](https://user-images.githubusercontent.com/20630604/106400705-e4eebd80-63d4-11eb-8c02-15463bcccc92.png)
