### ISSUE TITLE
New 2d preact inventory UI.

### ISSUE THREAD

**Issue by ChristopherTrimboli** [webaverse/app#75]
![Capture.PNG](https://user-images.githubusercontent.com/27584221/94164172-92f1c600-fe3d-11ea-92d0-99c97ac9f63b.PNG)

![20200924060824885.png](https://user-images.githubusercontent.com/27584221/94164191-971de380-fe3d-11ea-9515-2b50bdfe2019.png)

![capture2.PNG](https://user-images.githubusercontent.com/27584221/94164221-9c7b2e00-fe3d-11ea-8c6f-0856a987caae.PNG)

**Comment by avaer** [comment]
Working on it.
