### ISSUE TITLE
Twitter bot: deploy

### ISSUE THREAD

**Issue by avaer** [webaverse/app#753]
The bot is merged now: https://github.com/webaverse/ethereum-bot/pull/11

We just need to key + deploy + test + monitor it.

**Comment by avaer** [comment]
Is this considered deployed? @shawticus @chrislatorres

**Comment by chrislatorres** [comment]
Yes, it is deployed to https://twitter.com/cryptotestbot1

we're awaiting approval from Twitter for a developer account for @Webaverse to switch over to that official account

**Comment by avaer** [comment]
Thanks! 👏
