### ISSUE TITLE
.wbn collision mesh off in mint preview

### ISSUE THREAD

**Issue by karunakaruna** [webaverse/app#755]
.wbn with a .bin collision mesh generated from webaverse.com/build registers collisiions two meters off (-y in blender) when in mint preview. Is fine when minted and deployed to parcel.

https://user-images.githubusercontent.com/20630604/106535321-dd014d00-64aa-11eb-92c9-cd1f65328149.mp4

using temple.wbn
https://www.dropbox.com/sh/qidrc6opidsjolm/AABuMUC8eORYleqLVFSeheiya?dl=0

**Comment by avaer** [comment]
Is the mint preview offsetting anything?

**Comment by avaer** [comment]
https://github.com/webaverse/app/blob/54692554777f7e40d49d5e2db8c0822e9e53e4e7/world.js#L494

**Comment by avaer** [comment]
I checked, it should be fixed now.
