### ISSUE TITLE
App: update three-vrm to v0.6.0

### ISSUE THREAD

**Issue by avaer** [webaverse/app#757]
https://twitter.com/FMS_Cat/status/1356499779413442561?s=20

**Comment by madjin** [comment]
three-vrm.js got deleted in May, not being used anymore I assume? https://github.com/webaverse/app/commit/9bfe6a5de95f29390bdca4ebe6947073a5a5f767

**Comment by avaer** [comment]
I think it is still used, it provides hair at least.

**Comment by avaer** [comment]
But this issue is no longer important.
