### ISSUE TITLE
Bots: separate documentation

### ISSUE THREAD

**Issue by avaer** [webaverse/app#758]
Jin:
> i think we should have a separate page for the discord bot on the website
> some ppl wanna way to use it to enhance their community with brand factorytools to monetize when currently they just have a patreon. atm its selling them on the virtual world stuff with it which is like a bonus aspect

Shaw:
> separate docs for twitter bot too, since commands are a little different

**Comment by chrislatorres** [comment]
added seperate doc for twitter bot https://github.com/webaverse/docs/commit/6529a5a725d4209718c1762cc2586f6741e3b368

other issue broken out to #768
