### ISSUE TITLE
FE: animation select during mint

### ISSUE THREAD

**Issue by avaer** [webaverse/app#759]
https://user-images.githubusercontent.com/6926057/106677633-14ddc280-6587-11eb-8c76-d58c02ce5b98.mp4

We currently have prompts to fill in animations during mint.

We should instead:
- detect the animations in the model, with a regex, and select defaults for these animation slots
- provide UI to change the animations to a different one
- allow previewing the animations that are selected for the pet
- have the next button continue with the selected animations to complete the mint

**Comment by chrislatorres** [comment]
Added a gltfloader on the pets page, automatically detects the animations and lets user pick which one is the walk/idle animation https://github.com/webaverse/webaverse.com/commit/84d1d65ee8be91647b5d5a9ea50ef2a0113b8067
