### ISSUE TITLE
FE: only allow upload of files supported

### ISSUE THREAD

**Issue by madjin** [webaverse/app#764]
It's sometimes confusing for people if they try uploading files that aren't yet supported like FBX / GLTF. Only allow uploading of files supported and have helpful error message for people that try uploading anything else.

**Comment by madjin** [comment]
Apparently this GLTF gets an error trying to delete: https://webaverse.com/assets/175

**Comment by chrislatorres** [comment]
fixed https://github.com/webaverse/webaverse.com/commit/4ed67d4969d04f36214fee4497356c253e0c47da
