### ISSUE TITLE
FE: Different view modes for assets

### ISSUE THREAD

**Issue by madjin** [webaverse/app#767]
Just a feature request but while exploring NFTs on the website if we can change preview modes like how in Windows explorer there's thumbnail / detailed list it would make the experience nicer. People can filter by date modified, size, file type, card or raw image previews. Will make experience feel like using the Ethereum world computer Metaverse OS.

**Comment by chrislatorres** [comment]
Yeah that makes sense, similar to #459

**Comment by chrislatorres** [comment]
Merging into #459
