### ISSUE TITLE
Bot: Landing page for the bot

### ISSUE THREAD

**Issue by madjin** [webaverse/app#768]
Noticed while checking out bots on https://top.gg that after you invite some of the bots into your server a landing page pops up with useful information.

![image](https://user-images.githubusercontent.com/32600939/106804097-f6350580-6632-11eb-9835-6fa93e688553.png)

Currently there isn't much information about the NFT bot outside of Discord.

**Comment by chrislatorres** [comment]
this can be passed into the `redirect_uri` in the discord bot invite url https://discord.com/developers/docs/topics/oauth2#authorization-code-grant-authorization-url-example

**Comment by chrislatorres** [comment]
Similar to #758

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/compare/17be53ab062d...12720d2b7d3a

going to get review from @madjin

**Comment by chrislatorres** [comment]
done https://github.com/webaverse/webaverse.com/commit/cebeb8162769f5e26ca048ad8d3409e521b005d5
