### ISSUE TITLE
APP: multiplayer text reverse for 1 person

### ISSUE THREAD

**Issue by softwarexyz** [webaverse/app#771]
This happened after entering a parcel from a realm, but after a minute or two it corrected back to normal

![backwardstexxt](https://user-images.githubusercontent.com/29695350/106830708-3658b000-6654-11eb-9a75-cbd7d204f027.PNG)

**Comment by avaer** [comment]
Must be done weird Unicode rtl code points...

**Comment by avaer** [comment]
We could filter it.

**Comment by avaer** [comment]
Then again, I think we want to keep rtl mode for actual rtl languages.

I'd need to know if there is something weird about the browser setup (any extensions) or failing that someone needs to print the unicode that is coming in.
