### ISSUE TITLE
App: Microphone can be active without T highlighted

### ISSUE THREAD

**Issue by karunakaruna** [webaverse/app#775]
I'm not sure the events leading up to this, but was told my mic was on even though the T was off. Toggling T got it under control again. Not feeling confident my mic is _actually_ off  is quite nerve-racking!

**Comment by avaer** [comment]
This will have a stack trace in console usually. Can you paste that?

**Comment by karunakaruna** [comment]
I believe I was typing and placing NFTs at the time. 
Closed out of the window a while ago unfortunately!

**Comment by avaer** [comment]
Cool, if you see it again, pasting the stack would help.

**Comment by avaer** [comment]
> Any way to recover from a previous session?
No, sadly.
