### ISSUE TITLE
Camera item drops FPS to <5

### ISSUE THREAD

**Issue by karunakaruna** [webaverse/app#776]
![image](https://user-images.githubusercontent.com/20630604/106874781-d5989a00-668a-11eb-8527-923fc043c49d.png)
Should probably be removed for now. Came into Room-1 to find it super laggy, had to hunt down the source. If present in a room new users might assume app is poor performance.

**Comment by avaer** [comment]
It is because of the gamma. I can fix that.

I'm against removing features because of a bug though.

**Comment by avaer** [comment]
Should be fixed.

**Comment by avaer** [comment]
https://github.com/avaer/camera/commit/f47647b3ecb7147238079ba31782b301b924d1b8
