### ISSUE TITLE
Bot: Better collection algo for inventory

### ISSUE THREAD

**Issue by madjin** [webaverse/app#777]
When you mint a large quantity of a NFT it will quickly fill up your inventory and open lots of pages, like below:

![2021-02-04-10:11:40](https://user-images.githubusercontent.com/32600939/106913086-7f425000-66b8-11eb-932c-260792c6457b.jpg)

Perhaps NFTs that have many editions can be expressed as a range inside the inventory, similar to how the output is when minting.

**Comment by avaer** [comment]
@hamzatrq What is the current method used for multi-mints?
