### ISSUE TITLE
GH action to deploy production to S3. 

### ISSUE THREAD

**Issue by ChristopherTrimboli** [webaverse/app#78]
We relying on GitHub pages. We need to be a public repo for this. 

Not a big fan of only being public because we need GH pages. We don't need GH pages. 

Can build the app in GH actions and push to S3 using GitHub secrets and like 15 lines of code. 

Throw a cert on S3 bucket. Maybe a distribution. Shouldn't be too bad.

**Comment by avaer** [comment]
We can use GH pages on a private repo if we pay. I don't think we should use S3.

**Comment by ChrisEddy** [comment]
Oh I didn't know. Ok. Well prob should do that for post-beta then.
