### ISSUE TITLE
Get webaverse.com onto Oculus Browser new tab page

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#787]
For when we are promoting WebXR support, this could be a good source of users

This used to be the link to the submission form -- https://go.fb.com/WebXR-SignUp.html it looks like there isn't a public link for this, but we can contact the team.

the submission link: https://oculusweb.facebookinc.com/submit

**Comment by avaer** [comment]
I'm pretty sure the path for that is through an Oculus contact.
