### ISSUE TITLE
Fe: delete is confusing

### ISSUE THREAD

**Issue by avaer** [webaverse/app#789]
Since it does not actually delete.

**Comment by chrislatorres** [comment]
Changed "delete" to "burn" https://github.com/webaverse/webaverse.com/commit/86ef7e129744ee2469ca874094cb47590c60f288

**Comment by avaer** [comment]
Will users be able to re-mint the item after deletion?

That is the main issue.

**Comment by chrislatorres** [comment]
Since #765 users can re-mint an item after deletion/burning.

**Comment by avaer** [comment]
Ok thanks for the clarification 👍.
