### ISSUE TITLE
Bot: Mint tweets

### ISSUE THREAD

**Issue by madjin** [webaverse/app#793]
The twitter bot would have the ability to mint images people tweet but it could also have the ability to mint the tweet itself. This has potential for viral marketing. There's several examples of this existing in the wild such as:

* https://twitter.com/tokenizedtweets
  * https://twitter.com/TweetsNft
* https://v.cent.co/
* https://eternal.report/

Each has a slightly different approach to minting. For example, a twitter user can mention tokenizedtweets in a reply and include a wallet address / ENS domain / .crypto domain to transfer the archived tweet to the wallet. Valuables by Cent work by allowing people to bid on tweets while letting the creator of a tweet decide if they would like to mint it on the blockchain, making it a 1of1 autographed version.

One presentation format that might be interesting to explore is rendering a tweet as a [3D model](https://twitter.com/chapter_2021/status/1356643896470589440). This could be a fun way to share tweets inside of a 3D world.

![2021-02-06-01:22:03](https://user-images.githubusercontent.com/32600939/107110935-bde32200-6800-11eb-83f2-e888e8c62e3a.jpg)

One could imagine a whole virtual trinkets store selling tokenized tweets like this. For this unique service, one could perhaps charge a fee of $5 for minting and rendering such tokens.

**Comment by madjin** [comment]
Along with this feature there should a gallery where you can explore the minted NFTs for sale or have recently sold.

**Comment by avaer** [comment]
This is a cool idea, but it seems less a core feature and more a new type of NFT to support.
