### ISSUE TITLE
Misc: URN namespace

### ISSUE THREAD

**Issue by avaer** [webaverse/app#794]
This is a promising idea: https://github.com/common-metaverse/urn-namespaces

We should figure out our URN and submit a PR: https://github.com/common-metaverse/urn-namespaces#adding-a-namespace

**Comment by avaer** [comment]
@madjin Is this something we want to partake in right now? It is more a matter of strategy/collab timing.

**Comment by madjin** [comment]
I could send some of my wearables from Cryptovoxels and Decentraland to a wallet, associate it with my Webaverse account, and we could use those to test with. First, I think we need metadata inspect mode: https://github.com/webaverse/app/issues/623

Once these ingredients are in place, we can prototype and post about it.

**Comment by avaer** [comment]
Ok makes sense, so you see it more of an issue for implementing existing NFTs.

I was thinking that we should register Webaverse NFTs into this registry and kick off that process.
