### ISSUE TITLE
Fe: design bugs on iPad

### ISSUE THREAD

**Issue by avaer** [webaverse/app#796]
https://cdn.discordapp.com/attachments/737801646364557394/807464063550095370/IMG_0367.jpg
https://cdn.discordapp.com/attachments/737801646364557394/807464063931514980/image-1.png

**Comment by chrislatorres** [comment]
first pic same as #698 -- second one looks like the canvas did not resize to innerwidth/height? https://github.com/webaverse/app/blob/512537f9582eee6805092dc709da02fe2c1f92bc/app-object.js#L19

**Comment by avaer** [comment]
@ChristopherTrimboli let us know if this is fixed on a real iPad. If so we can close it.

**Comment by chrislatorres** [comment]
What's happening here is the footer is overflowing

the quickest solution is
`overflow: hidden;`

but since we could support mobile (#712) down the road, the right solution would be using media queries to adjust UI for tablets/phones

![footeroverflow](https://user-images.githubusercontent.com/29695350/107444493-4ebb4580-6b00-11eb-9311-645a66bd8b6a.PNG)

**Comment by avaer** [comment]
Why can't the footer just be properly flowed?

**Comment by ChristopherTrimboli** [comment]
I can repro in devtools: 
![xcvbxcvbxcvb](https://user-images.githubusercontent.com/27584221/107461277-89c47580-6b0e-11eb-8b76-28b91b1558a9.PNG)

**Comment by ChristopherTrimboli** [comment]
footer seems fixed 👍🏻

**Comment by ChristopherTrimboli** [comment]
![zxvzxcvzxcv](https://user-images.githubusercontent.com/27584221/107461719-76fe7080-6b0f-11eb-96f7-acb60a69576a.PNG)
some text overflowing in the cards, I can repro in devtools and real ipad

**Comment by chrislatorres** [comment]
could not repro the FE ipad one
![ipad1](https://user-images.githubusercontent.com/29695350/107557939-d310d580-6b9f-11eb-9b11-0032fef6dc21.PNG)

created PR for the overflow one https://github.com/webaverse/app/pull/821
![ipad2](https://user-images.githubusercontent.com/29695350/107557971-de640100-6b9f-11eb-951a-45cb09eaa272.PNG)
