### ISSUE TITLE
Fe: mainnet sidechain duality

### ISSUE THREAD

**Issue by avaer** [webaverse/app#799]
- Should be able to connect metamask and write the signature to the account.
- Inventory should dually be pulled from mainnet and be marked specially.

**Comment by avaer** [comment]
Can be implemented first on `rinkeby` and `rinkebysidechain`.

**Comment by chrislatorres** [comment]
added

FE: https://github.com/webaverse/webaverse.com/pull/27
BE: https://github.com/webaverse/api-backend/pull/53

**Comment by chrislatorres** [comment]
everything is moved over to duality now
