### ISSUE TITLE
App: fullpage menu

### ISSUE THREAD

**Issue by avaer** [webaverse/app#807]
![image](https://user-images.githubusercontent.com/6926057/107331785-55ef3e80-6a81-11eb-848f-9b5ef6a06454.png)

becomes something closer to

![image](https://cdn.discordapp.com/attachments/808651898973454346/808862438169509888/fnspawntab.png)

**Comment by avaer** [comment]
Should support drag and drop. The main things you want to do in this menu are:

- Spawn
- Equip
- Add to Hotbar

**Comment by avaer** [comment]
I wouldn't copy the UI directly, but I think that lighthearted gradient feel would work well. Something that feels like a game UI.

**Comment by avaer** [comment]
@ChristopherTrimboli this would be a good thing to work on.

**Comment by avaer** [comment]
This could blend with the inventory dragger in the `I` menu. That one is not currently pulling live data but it could.

**Comment by ChristopherTrimboli** [comment]
![unknown](https://user-images.githubusercontent.com/27584221/107595956-1df41280-6bcb-11eb-9f6c-61438538d4c2.png)

**Comment by ChristopherTrimboli** [comment]
![mockup](https://user-images.githubusercontent.com/27584221/107600067-7b8e5c00-6bd7-11eb-9289-fdf8ca93efe4.png)

**Comment by avaer** [comment]
Folding this into https://github.com/webaverse/app/issues/857
