### ISSUE TITLE
App: minify build pass

### ISSUE THREAD

**Issue by avaer** [webaverse/app#811]
We should find a way to do a build process via Github Actions to ship our code minified.

It could be whatever packing solution, but note that our code is pure HTML5/ES6 import and we should keep it working like that on the dev env. I.e. no WDS.

The build process should merely bundle and minify `app.js` and change the `index.html` entry point or something. Source maps for production should work.

Note that some things technically would be hard to minify, like our geometry manager, which is a non-ES6 PhysX WASM loader script. I would leave that part unminified for now.

**Comment by avaer** [comment]
@ChristopherTrimboli Another good familiarization issue.

**Comment by avaer** [comment]
Non-module load of `geometry.js`: https://github.com/webaverse/app/blob/b4526144c72de502efed4c706f2c20803f2fba80/index.html#L525

**Comment by avaer** [comment]
Loading `app.js` via ES6 (this is what we would build and replace). https://github.com/webaverse/app/blob/b4526144c72de502efed4c706f2c20803f2fba80/index.html#L527

**Comment by avaer** [comment]
@ChristopherTrimboli Can you PR anything you had here and link it up to the issue?

**Comment by ChristopherTrimboli** [comment]
some progress in this PR here: https://github.com/webaverse/app/pull/837 
I'm stuck on the dynamic imports in runtime.js: https://github.com/webaverse/app/blob/master/runtime.js#L806
