### ISSUE TITLE
Docs: jobs page split

### ISSUE THREAD

**Issue by avaer** [webaverse/app#814]

**Comment by avaer** [comment]
## 3D engineer
- THREE.js, WebGL, JavaScript, WASM
- Strong browser knowledge
- Deep understanding of graphics pipelines
- Art skills not required
## Blockchain engineer
- Ethereum, solidity, sidechains, debugging EVM
## Infrastructure engineer
- Node.js, AWS, Cloudflare, IPFS, bots, WebSockets, WebRTC, devops

## Shader artist
- Write, debug, optimize GLSL
- Port shaders from other languages and platforms
## Avatar artist
- Design, modeling, rigging, optimization of avatars
- Commissions from users
## World artist
- Design, modeling, texturing, optimization of digital spaces
- Conceptualize original work, as well as designing to spec
## Artist
- Texturing, decals, animations
- Frontend design

## Tester
- Ongoing testing to file detailed bug reports
- Interface with the community

**Comment by chrislatorres** [comment]
added https://github.com/webaverse/webaverse.com/compare/7fdaf877fcc4...c2df4dd6a890

**Comment by avaer** [comment]
https://webaverse.com/hiring
