### ISSUE TITLE
Docs: artist-friendly NFT guides

### ISSUE THREAD

**Issue by avaer** [webaverse/app#816]
We should do a better job visually defining what NFTs are and how they work, in the docs. It is only briefly mentioned here: https://docs.webaverse.com/docs/webaverse/nfts

This could use more examples or a single detailed walkthrough of a specific case of an NFT, or similar.

A good inspiration might be how A-Frame explains the ECS: https://aframe.io/docs/1.2.0/introduction/entity-component-system.html

I think we should just expand on what's there.

**Comment by avaer** [comment]
> agreed, being immediately usable by artists as a live experience of their art, with also being able to voxel yourself an exhibit environment is huge and is something that I've seen a few artists go through hell to create themselves up until this point

**Comment by chrislatorres** [comment]
added more visuals here, made an issue to do a full passover the docs #848 

https://github.com/webaverse/docs/compare/6529a5a725d4...cda24cb90311
