### ISSUE TITLE
Nameplates cutting off text.

### ISSUE THREAD

**Issue by ChristopherTrimboli** [webaverse/app#819]
![zzzzz](https://user-images.githubusercontent.com/27584221/107467047-014bd200-6b1a-11eb-9b68-021294b28661.PNG)

**Comment by avaer** [comment]
https://github.com/webaverse/app/blob/afadb3accc6c94cebfb51749d2e738f26a16d025/rig.js#L166

**Comment by avaer** [comment]
Either the text is sliced, there is some wrapping in troika, or it is a rendering issue. Needs more investigation.

**Comment by avaer** [comment]
We use this for the actual text rendering: https://github.com/webaverse/app/blob/master/troika-three-utils.esm.js
