### ISSUE TITLE
Email / key login not working.

### ISSUE THREAD

**Issue by ChristopherTrimboli** [webaverse/app#820]
Repro:
`.key` the discord bot and try using Mnemonic to login.

If we no longer support Mnemonic logins we should remove the feature from bot + frontend.

![cvbxcvbxcbv](https://user-images.githubusercontent.com/27584221/107467714-7b308b00-6b1b-11eb-853c-383da28b1a5a.PNG)
![qqqweqwe](https://user-images.githubusercontent.com/27584221/107467718-7cfa4e80-6b1b-11eb-9647-a44ac53b50f0.PNG)

**Comment by avaer** [comment]
Hm this is a good question.

I think we should continue to support it since it should be low overhead. This would be a bug.

**Comment by avaer** [comment]
This might help: https://github.com/webaverse/app/commit/d7aefa917bb97204101b12cb82f33cc31a77e67a
