### ISSUE TITLE
Fe: Maximize 3D view window

### ISSUE THREAD

**Issue by madjin** [webaverse/app#822]
Wanted to get a closer look at an object but there was no way to make the preview bigger. Would be helpful to maximize that window.

![brave_2BoitrBtJH](https://user-images.githubusercontent.com/32600939/107558541-c4222700-6b8f-11eb-8917-0f4ca540845a.png)

This issue might be tangentially related for different thumbnail views: https://github.com/webaverse/app/issues/459#issuecomment-772792056

**Comment by avaer** [comment]
That render is not high quality. If you really wanted to see, the try mode is probably best.

Would a low res large image be good enough?

**Comment by madjin** [comment]
Fixed
![image](https://user-images.githubusercontent.com/32600939/118405052-a1e2ee00-b643-11eb-9ff8-2bf0d0179533.png)
