### ISSUE TITLE
Fe: getting metamasked by default

### ISSUE THREAD

**Issue by avaer** [webaverse/app#830]
I got hit with a metamask login when navigating to https://webaverse.com/assets/392. I don't think this is a good user experience. The user should click `Connect` first somewhere in a prominent place.

**Comment by chrislatorres** [comment]
Yeah, noticed this too. Will fix

**Comment by chrislatorres** [comment]
fixed https://github.com/webaverse/webaverse.com/commit/740b40ce7ffbec57879b9c05c246175b2a165ed0
