### ISSUE TITLE
App: default avatars experience

### ISSUE THREAD

**Issue by avaer** [webaverse/app#832]
We need the default experience to guide the user with setting up an avatar. Either as a single default that is not the debugger triangles, or a selection of defaults.

Longer term, we could also do an avatar remix contest to create some well-themed defaults.

**Comment by chrislatorres** [comment]
Related issues: #294, #238, #171, #37

**Comment by avaer** [comment]
Closing in favor of https://github.com/webaverse/app/issues/840
