### ISSUE TITLE
App: Artifacts from parcel return to street

### ISSUE THREAD

**Issue by madjin** [webaverse/app#838]
Visited this parcel: https://app.webaverse.com/?u=https%3A%2F%2Fwebaverse.github.io%2Fparcels%2Fparcel.scn&r=5-avaer-stacks-s1

Then press back on my browser and the grey object followed me back onto the street.

![image](https://user-images.githubusercontent.com/32600939/107728823-2167c680-6cbd-11eb-88e5-ae5ece34643c.png)

**Comment by avaer** [comment]
I could be the world load race condition.

**Comment by karunakaruna** [comment]
That's the undeletable instance test object .glb from my parcel re: #817

**Comment by avaer** [comment]
Oh makes sense.
