### ISSUE TITLE
App: Default public avatars

### ISSUE THREAD

**Issue by madjin** [webaverse/app#840]
I predict that one of the most common questions we'll have during the new user experience is how to change your avatar. Right now users start out with a skeleton and there's no clear path to modifying it.

There should be a roster of public avatars that users can pick from. This selection can be part of the inventory UI you access from pressing `i`, the hamburger menu in-game, or settings on FE.

There's a pool of avatar candidates we can populate this roster with such as the open source ones from Polygonal Mind and some from Vroid Hub (will need to pay attention to rights and optimization). We can also run a competition using Orion to generate new candidates and promote avatar artists.

**Comment by avaer** [comment]
Related: #294, #238, #171, #37

**Comment by avaer** [comment]
I am leaving this as the tracking issue for good initial avatars experience, since the other issues are similar.
