### ISSUE TITLE
ALL: Change token to SILK

### ISSUE THREAD

**Issue by madjin** [webaverse/app#841]
- avoids name collisions
- invite only access to bot
  - web of trust
- **ancient** silk road trade paths
  - value flows between platforms (cities)

**Comment by avaer** [comment]
I have no opinion on this, but if we do it we will need to update:
- bot
- docs
- whitepaper

**Comment by avaer** [comment]
For the blockchain part, we will need to redeploy all contracts essentially.

**Comment by chrislatorres** [comment]
website updated https://github.com/webaverse/webaverse.com/compare/3ef968ae9606...eec0eed59e07

**Comment by chrislatorres** [comment]
website updated https://github.com/webaverse/webaverse.com/compare/3ef968ae9606...eec0eed59e07
discord channel updated
docs updated https://github.com/webaverse/docs/commit/104720086560150b79b29d77e1cafaf1f73d3f9e
whitepaper updated https://github.com/webaverse/whitepaper/commit/43eda3583125a5fe747b12e3d25dfe4defaad3ab
bot updated https://github.com/webaverse/ethereum-bot/commit/38f28e3a94c4f72ba7818e2e896787450d6f99a3

last is the contract redeploy, closing this one, and we can track that at #854
