### ISSUE TITLE
Fe: hero text copywriting

### ISSUE THREAD

**Issue by avaer** [webaverse/app#843]
> An open virtual world built with existing communities.

The sample size is small but we've heard this expressed as a confusing wording -- what are the communities?

**Comment by softwarebycl** [comment]
Now the hero text is "An Internet Scale Cinematic Universe" -- this + the hero image are worth testing to see what new users initial impressions are.

**Comment by avaer** [comment]
https://www.youtube.com/watch?v=S2xHZPH5Sng
