### ISSUE TITLE
APP: cannot delete drag & dropped .glb items under scene tab

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#846]
This seems to only be drag & dropped `.glb` items specifically. They are not delete-able by pressing X like NFTs or other drag&drop file types like a png.

From: https://app.webaverse.com/?u=https%3A%2F%2Fwebaverse.github.io%2Fparcels%2Fparcel.scn&r=7-avaer-stacks-s1

**Comment by karunakaruna** [comment]
related to #817

**Comment by avaer** [comment]
Holograms on the street should have nothing to do with colliders.

**Comment by avaer** [comment]
Note that any sort of crash should be considered the root issue and you should not continue to look for other issues once you get a stack trace.

For example, whenever loading a bloated model like that one, the world is considered broken until a refresh without such a model.

**Comment by avaer** [comment]
The scene tab will also be going away.
