### ISSUE TITLE
App: wbn collision offset until refreshed

### ISSUE THREAD

**Issue by softwarexyz** [webaverse/app#847]
When this was first spawned in a Street multiplayer room, the colliders were offset a bit. After refreshing, it was working as expected.

https://webaverse.com/assets/207 / https://ipfs.exokit.org/QmX1HzXVyj2Tt3TrggFTU7wE4q8Ah4d2Bvia3GZ2YuD1Eh/Avatar%20King.wbn

**Comment by avaer** [comment]
Is this easy to reproduce?
