### ISSUE TITLE
App: ready player me compatibility

### ISSUE THREAD

**Issue by avaer** [webaverse/app#852]
A lot of people like personalized RPM avatars. Looking at the structure, they are close to VRM already.

**Comment by madjin** [comment]
Already possible by converting from GLB -> FBX -> VRM, official support is on the way. Leave this open?

![brave_AzkWRfbRmX](https://user-images.githubusercontent.com/32600939/121789818-430f8680-cba7-11eb-8d95-bd9ac52df8d8.png)


![image](https://user-images.githubusercontent.com/32600939/121789815-3b4fe200-cba7-11eb-83fd-1ddcc5419a03.png)
