### ISSUE TITLE
App: camera view busted pre-load

### ISSUE THREAD

**Issue by avaer** [webaverse/app#860]
Try scrolling out while it loads.

https://webaverse.com/preview/426

**Comment by madjin** [comment]
what is this, a preview for ants?
![image](https://user-images.githubusercontent.com/32600939/118408947-fd1ddc00-b655-11eb-8cee-b979608c6ead.png)

**Comment by avaer** [comment]
> what is this, a preview for ants?

Lol

**Comment by avaer** [comment]
I actually don't think that preview page should be used anymore. I deleted it so now it will be 404.

The replacement page that works is https://webaverse.com/assets/426

I didn't find any references to the old page in the bot, which would be the main place this would be referenced. If we missed something, we can update the href when we see it.
