### ISSUE TITLE
Editaverse: Failed to fetch

### ISSUE THREAD

**Issue by madjin** [webaverse/app#861]
Tried importing a legacy spoke scene into editaverse and got a big error log complaining about network errors

![image](https://user-images.githubusercontent.com/32600939/107869099-5439c800-6e3f-11eb-812a-6fa20a853ce9.png)

https://cdn.discordapp.com/attachments/696210985035235358/810376568794775552/arcade-room-1.0.spoke

**Comment by avaer** [comment]
Is this still an issue?

**Comment by madjin** [comment]
closing since editaverse is not online and not currently maintained
