### ISSUE TITLE
Mint button on webaverse.com does not mint

### ISSUE THREAD

**Issue by karunakaruna** [webaverse/app#883]
Two .glbs tested - upload/preview correctly but clicking 'Mint for 10 silk" does nothing. Brave 1.20

![image](https://user-images.githubusercontent.com/20630604/107988773-90774080-6f85-11eb-8a85-205459d97cc7.png)
![image](https://user-images.githubusercontent.com/20630604/107988783-9705b800-6f85-11eb-92c8-44ca88285085.png)

**Comment by avaer** [comment]
Trying to fix it with this: https://github.com/webaverse/webaverse.com/pull/30
