### ISSUE TITLE
Mint button after voxel.editaverse does not mint, throws error:

### ISSUE THREAD

**Issue by karunakaruna** [webaverse/app#884]
![image](https://user-images.githubusercontent.com/20630604/107989231-b51fe800-6f86-11eb-982d-18dabb2200bd.png)
Brave 1.20

This may be related to the chain switch last night - apologies if you know about it already!

**Comment by avaer** [comment]
It could be a port issue?

**Comment by avaer** [comment]
@karunakaruna Please re-open if it is not fixed.
