### ISSUE TITLE
App: make HTML preview work on opensea

### ISSUE THREAD

**Issue by avaer** [webaverse/app#888]
https://opensea.io/assets/0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7/307

I don't know how this is implemented yet; probably `animation_url` or similar.

**Comment by chrislatorres** [comment]
Some reverse engineering -- 

Looking at the `tokenMetadataURI` <https://etherscan.io/address/0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7#readContract>

points to: <https://cloudflare-ipfs.com/ipfs/QmS23rGm5yLW9c4gAWKtn9na4n3k2YWjT2LzDKiUWdmrZs>

`{"description":":musical_note::sun_with_face::musical_note: internet pirate radio.","mimeType":"text/html","name":"zora.fm v1","version":"zora-20210101"}`

and the `tokenURI` points to: https://cloudflare-ipfs.com/ipfs/QmUTMQLgvE2o2ZooR1gGsYjznE4rsYTKRLSwDo5wwHhjBW

So it looks like... they use `tokenMetadataURI` for the metadata to show on OpenSea, and the `tokenURI` points to the html file that is iframed on OpenSea

**Comment by avaer** [comment]
Perfect, thanks for the investigation.

Does this mean we would need to be on IPFS?

**Comment by chrislatorres** [comment]
There isn't any documentation on `tokenMetadataURI` -- searched the OpenSea Discord, twitter, docs, google

I don't think IPFS is what matters, it's that:

- `tokenMetadataURI` has the metadata JSON
- `tokenURI` points to the html file that will be iframed

in this contact (<https://etherscan.io/address/0xabefbc9fd2f806065b4f3c237d4b59d9a97bcac7#writeContract>) they have both a `updateTokenMetadataURI` and `updateTokenURI` -- I can deploy the same contract and see if it is reproducable

a few weeks ago Dan from OS:
> It's just a hardcoded iframe for now.  But I have a feeling that the community cares deeply about this and will call for it as a feature.

> Initially, we'll probably just dynamically add an iframe.  Eventually, we might end up supporting scripts as a metadata type

https://twitter.com/dan_OpenSea/status/1352763071660494852

**Comment by avaer** [comment]
Related: https://github.com/webaverse/app/issues/889

**Comment by avaer** [comment]
https://twitter.com/pxlqart/status/1382679722056953862
