### ISSUE TITLE
Bot: Inspect command

### ISSUE THREAD

**Issue by madjin** [webaverse/app#890]
Way to check provenance of NFTs from Discord

.inspect [nftid]

who minted it, when, and who owns it

**Comment by madjin** [comment]
also:
- edition number
- file type (jpg, png, vrm, etc)
- file size (305kb, 24MB, etc)
- resolution (eg: 1000x1000 px)
- who are the collaborators of the NFT?
- does it have unlockable content?

**Comment by avaer** [comment]
Done.
