### ISSUE TITLE
App: local development experience

### ISSUE THREAD

**Issue by avaer** [webaverse/app#892]
Something with local files, versus the current XRPK upload.

Related: https://github.com/webaverse/app/issues/858, https://github.com/webaverse/app/issues/795

**Comment by avaer** [comment]
For now, the easiest thing to do is to clone `app` and set the local scn constant to a local scn file instead:

https://github.com/webaverse/app/blob/bdd826d01eb92f4c8ae1ba86997ebe9b56a1232a/constants.js#L27

**Comment by avaer** [comment]
☝️ This can be a local path, like `./test.scn`.

**Comment by madjin** [comment]
Created a page in the docs on the current local development experience:
https://docs.webaverse.com/docs/create/scenes
