### ISSUE TITLE
App: Avatar frozen in realms

### ISSUE THREAD

**Issue by madjin** [webaverse/app#901]
If you go to any realm such as `.realm 1` and try to move you'll be stuck in place.

![image](https://user-images.githubusercontent.com/32600939/108276944-6d879080-712d-11eb-8334-014a5097a95c.png)

**Comment by avaer** [comment]
Is this fixed now?

**Comment by avaer** [comment]
Was this fixed by another bug?

**Comment by madjin** [comment]
Tested and this issue has been fixed :+1:

**Comment by avaer** [comment]
Phew, ty for checking.

**Comment by madjin** [comment]
This bug has returned

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/114284804-78212080-9a20-11eb-92bc-c7d01d57defa.png)
