### ISSUE TITLE
500 Internal Error (universe.js)

### ISSUE THREAD

**Issue by soulofmischief** [webaverse/app#903]
```
universe.js:139 GET https://rinkebysidechain-land.webaverse.com/1-100 500 (Internal Server Error)
getParcels @ universe.js:139
(anonymous) @ 58571433-b050-4470-80da-2ebc543b4763:12
(anonymous) @ 58571433-b050-4470-80da-2ebc543b4763:104
```

**Comment by chrislatorres** [comment]
This looks like it may be cached? But it's because of the constant, we can hardcode it as mainnet now, since rinkeby is not used https://github.com/webaverse/app/blob/master/constants.js#L14 

Similar to #902

**Comment by chrislatorres** [comment]
Looks like this was fixed after updating to latest version
