### ISSUE TITLE
APP:  procgen error - TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#904]
![Screenshot 2021-02-17 at 9 36 23 PM](https://user-images.githubusercontent.com/29695350/108301806-5b771380-7168-11eb-86c6-88439f21224a.png)

This is in the multiplayer switcher room:
https://app.webaverse.com/?u=https%3A%2F%2Fwebaverse.github.io%2Fparty%2Fparty.scn

**Comment by avaer** [comment]
I can look.

**Comment by avaer** [comment]
It was a missing runtime.js contentId argument passthrough.
