### ISSUE TITLE
App: solid color rendering issues

### ISSUE THREAD

**Issue by madjin** [webaverse/app#913]
All of these solid colors have rendering issues

![image](https://user-images.githubusercontent.com/32600939/108569060-1b2aa900-72c0-11eb-9ace-f22c70991157.png)

Test here: https://webaverse.com/preview/76

![image](https://user-images.githubusercontent.com/32600939/108568913-cbe47880-72bf-11eb-918b-9770f0776c8f.png)

did not happen at 256fes room: https://webaverse.com/preview/59

Perhaps its because the atlas is smaller, so the black grain could be floating point errors? Or it could be a clamping issue?

**Comment by karunakaruna** [comment]
It's normal maps on areas with 0 UV space. Reprojection fixes.

**Comment by avaer** [comment]
Does that mean this is resolved?

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/108887718-9c43b200-75d8-11eb-83ca-a0738cf11baa.png)

fixed
