### ISSUE TITLE
Fe: NFT burns after cancelling

### ISSUE THREAD

**Issue by madjin** [webaverse/app#921]
- User selects NFT from their inventory
- Hits transfer to mainnet
- Sees the crazy gas fees, cancels
- NFT no longer in their inventory

**Comment by avaer** [comment]
Need to hook in the inter-chain stuck notifications/cleanup.

**Comment by madjin** [comment]
This issue also prevents me from minting the same NFT, which a user would likely attempt to do after not seeing the NFT no longer in their inventory on the discord/web interface.

**Comment by soulofmischief** [comment]
Here is a block mentioning stuck assets and running a main net transaction, is this the right block of code? investigating...

https://github.com/webaverse/webaverse.com/blob/8aae10c64d5da309fab5767de7dc37d14820d4c3/functions/AssetFunctions.js#L174

**Comment by avaer** [comment]
https://github.com/webaverse/webaverse.com/blob/c3f8462ab49dbefa1615511daf73ba5a69d9d2cc/functions/AssetFunctions.js#L91
