### ISSUE TITLE
App: Rotate head with camera movement

### ISSUE THREAD

**Issue by madjin** [webaverse/app#924]
Currently there is no way to 'nod' to other users. Having head rotation movement will add powerful virtual production techniques for desktop users, similar to how crouching does.

**Comment by avaer** [comment]
Right click is currently an aim button. If you have a weapon out the head will follow.

I think we need to make the head track without a weapon as well.

Would that be convenient enough?

**Comment by madjin** [comment]
Holding right click while looking around might be okay, the use-case is very similar to aim where head movement signals more of where the user is focused / adds more communication. Could maybe get used to it like how people nod in Hubs with click n drag.
