### ISSUE TITLE
Cache generated image previews

### ISSUE THREAD

**Issue by soulofmischief** [webaverse/app#934]
Image requests for previews are not cached by the browser.

This might just need a simple content header in express, or a rework of the image preview backend, or failing both of those a client-side caching mechanism.

**Comment by avaer** [comment]
Etag would probably work here.

But the image preview cache is probably not the biggest performance problem at the moment.

**Comment by soulofmischief** [comment]
Related: https://github.com/webaverse/app/issues/962
