### ISSUE TITLE
App: Builder hotkeys

### ISSUE THREAD

**Issue by madjin** [webaverse/app#940]
The sidebar needs to be updated, says x is delete and c is pull 

x creates floor
c creates ramp
z creates wall

Also, can't delete anything and users can place floor tiles in same position.

![image](https://user-images.githubusercontent.com/32600939/109740517-3d55de00-7b80-11eb-9855-c4485d5df937.png)

**Comment by avaer** [comment]
> Also, can't delete anything and users can place floor tiles in same position.

Sounds like a different issue.

**Comment by madjin** [comment]
Filed separately https://github.com/webaverse/app/issues/942
