### ISSUE TITLE
App: Bones affect avatar visibility

### ISSUE THREAD

**Issue by madjin** [webaverse/app#943]
Currently in the code we just match bones which is not optimal; when theres a missing bone or wrongly named the avatar will throw a fit and cease to be properly visible when equipped. Apparently this is an issue for Webaverse but not other VRM apps we tested.

Here is how bones are properly named in the heirarchy for reference:

![image](https://user-images.githubusercontent.com/32600939/109861107-ca964280-7c13-11eb-9b95-f8d011a895fa.png)

Side note: VRM importer for Blender has a supposed 'preset VRM armature' which might be worth looking into.

**Comment by avaer** [comment]
The code is around here: https://github.com/webaverse/app/blob/cf7b7310d671fcefb37ad13a97eea99ca55c823b/avatars/avatars.js#L854
