### ISSUE TITLE
App: Avatars freeze the window

### ISSUE THREAD

**Issue by madjin** [webaverse/app#948]
Steps to reproduce:

* Change into the cool fridge avatar here: https://app.webaverse.com/?r=room-2

![image](https://user-images.githubusercontent.com/32600939/110246008-ad66ba00-7f1a-11eb-9573-b4a0e2420d08.png)

Highlighted in red is the error after changing into the avatar

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/110246672-64fccb80-7f1d-11eb-85bc-437e959ea621.png)

Tried to ride this, started to change my avatar instead, froze the window. It's also in realm 2

**Comment by avaer** [comment]
Apparently there is a video file being loaded?

**Comment by avaer** [comment]
Also, what is the VRM?

**Comment by madjin** [comment]
In realm 2 next to the other avatars is "Cool Fridge" VRM which caused the freezing issue.
