### ISSUE TITLE
Street: myst/dothack environments

### ISSUE THREAD

**Issue by avaer** [webaverse/app#949]
https://sketchfab.com/3d-models/r1-dun-loireag-b6a6d6f740134384bad0a3e9f835ac68
https://sketchfab.com/3d-models/carmina-gadelica-67493deef9684472a8f6cdc897c67ab2

Need a thematically consistent home space neighborhood that resembles Myst.

**Comment by madjin** [comment]
Citadel / Green Hill were made
![Citadel_CM_2 1](https://user-images.githubusercontent.com/32600939/117614890-f8799500-b136-11eb-9c28-6cfb0872a478.jpg)
