### ISSUE TITLE
Bug - Drag n drop fails,  Cannot read property 'payload' of undefined

### ISSUE THREAD

**Issue by ChrisEddy** [webaverse/app#95]
drag a file onto the canvas

caught (in promise) TypeError: Cannot read property payload of undefined
    at EventTarget.uploadFile (login.js:501)
    at async EventTarget.inventory.uploadFile (inventory.js:12)
    at async HTMLDocument.<anonymous> (inventory.js:48)
uploadFile @ login.js:501
async function (async)
(anonymous) @ inventory.js:48

login.js line 501:
` const id = parseInt(response2.transaction.events[0].payload.value.fields.find(field => field.name === 'id').value.value, 10);
`

**Comment by avaer** [comment]
My guess is that the upload failed to mint.

Can you log the `response`?

**Comment by avaer** [comment]
Is this still an issue? No response for 2 days.

**Comment by avaer** [comment]
@ChrisEddy No response to this issue for a week, so closing.

I couldn't reproduce.
