### ISSUE TITLE
Lightmaps for Atoll

### ISSUE THREAD

**Issue by lalalune** [webaverse/app#960]
We need baked lightmaps for atoll. This is also a test task for a freelancer.

**Comment by avaer** [comment]
Can the Hubs solution be used?

**Comment by madjin** [comment]
Indeed the [Hubs blender plugin](https://github.com/MozillaReality/hubs-blender-exporter) works for exporting lightmaps. Here's a look at the shader editor for reference after baking the lightmap as a separate UV:

![blender_yPSxrfp43N](https://user-images.githubusercontent.com/32600939/111078557-779e7400-84cc-11eb-98af-4a289cdabf69.png)

If the shadows are too soft, one can import the lightmap into image processing editor like GIMP and make the shadows darker using curves:

![shadows_lightmap](https://user-images.githubusercontent.com/32600939/111078616-bdf3d300-84cc-11eb-9c36-3ab82bf0a3ca.jpg)

Here are a couple side by side looks between VRChat (left) and Webaverse (right):

![sbs_atoll1](https://user-images.githubusercontent.com/32600939/111078630-cfd57600-84cc-11eb-8197-cbfb09d8d4d8.jpg)

![sbs_atoll2](https://user-images.githubusercontent.com/32600939/111078694-2c389580-84cd-11eb-8a12-3cf6a9ec944a.jpg)

Final checklist:

- [ ] fix normal map (didn't export with gltf)
- [ ] add `generateMipMaps: true`
- [ ] add ocean shader for the water
- [ ] add env map
- [ ] add skybox (we have the file)
- [ ] add audio (getting soon)

Do you think it needs any tone mapping or will env map suffice?

**Comment by avaer** [comment]
> Do you think it needs any tone mapping or will env map suffice?

Hard to say without trying it. Tone mapping is possible to do, but I don't know how it's specified in the source files.

**Comment by madjin** [comment]
One thing to note, you'll only know the lightmaps are working when you import it into Spoke or Webaverse since the blender viewport does not display it correctly

![image](https://user-images.githubusercontent.com/32600939/111079016-7cfcbe00-84ce-11eb-9fbc-0d5a7b24edf3.png)

**Comment by madjin** [comment]
Potential shaders for the ocean:

- https://threejs.org/examples/webgl_shaders_ocean.html
- https://github.com/jbouny/ocean

Goal is to have a good import process not to write new shaders. Will write a separate issue on thoughts around blender pipeline.

**Comment by madjin** [comment]
Last thing to figure out for this issue is how to add the normal maps with the final GLTF.
