### ISSUE TITLE
Fe: Like NFTs

### ISSUE THREAD

**Issue by madjin** [webaverse/app#961]
Add metadata field for adding likes to NFTs

**Comment by charisra** [comment]
Trying to [log in](https://webaverse.com/login), in production results into a screen with spinner that never goes away. The user  can't log in.

**Comment by madjin** [comment]
Update
![image](https://user-images.githubusercontent.com/32600939/117614681-a9cbfb00-b136-11eb-93a0-c68e9393ef77.png)
