### ISSUE TITLE
Backend: Logs overflowing / crashing servers

### ISSUE THREAD

**Issue by shawticus** [webaverse/app#970]
Logs are overflowing on ethereum backend and crashing servers, stderr in particular. This will also eventually happen to the api-backend probably, since it's logging similarly. Keep logs under a max limit or work with an external logging service / S3 action.

**Comment by avaer** [comment]
I think trimming the logs makes the most sense.

**Comment by avaer** [comment]
I think the logs are fine, we just need to make sure we aren't running out of disk space.

This issue is fixed but here is the follow up: https://github.com/webaverse/app/issues/972
