### ISSUE TITLE
App: Certain VRM avatar won't equip

### ISSUE THREAD

**Issue by madjin** [webaverse/app#974]
The avatar is called `Averina_Avatar.vrm`

![image](https://user-images.githubusercontent.com/32600939/111706689-eeef4300-87ff-11eb-97cf-859cd5d566be.png)

> Uncaught (in promise) TypeError: Cannot read property 'parent' of null
    at new Avatar (avatars.js:900)
    at RigManager.setAvatar (rig.js:233)
    at async RigManager.setLocalAvatarUrl (rig.js:203)

**Comment by avaer** [comment]
Can't find the left ankle: https://github.com/webaverse/app/blob/cf7b7310d671fcefb37ad13a97eea99ca55c823b/avatars/avatars.js#L900

**Comment by avaer** [comment]
It's fixed in my branch.

![Capture](https://user-images.githubusercontent.com/6926057/111723040-5970a500-8839-11eb-84fc-2b16ff6b2024.JPG)

**Comment by avaer** [comment]
However I think the eyes are not sufficiently googly on this avatar.

They are rotation in place which only looks correct from the camera direction normal. From all other angles it's clear the eye is not an eyeball.

This can be confirmed in blender.

If we use this head I think the eyes would need to be fixed.

**Comment by madjin** [comment]
These avatars won't equip at all (from chemical's shop)

![image](https://user-images.githubusercontent.com/32600939/111728358-19aebb00-8843-11eb-8e30-0d02fe7af1f4.png)

![brave_u6zrAd8Oz1](https://user-images.githubusercontent.com/32600939/111728407-33500280-8843-11eb-86a2-298ce84957eb.png)

Same errors, avatar won't change.

![brave_7spPA7fwdx](https://user-images.githubusercontent.com/32600939/111728393-2a5f3100-8843-11eb-99c3-c1ed2df377fd.png)

**Comment by avaer** [comment]
Thanks, I fixed the chemical ones.
