### ISSUE TITLE
App: VRM wide arms and one eye blinking

### ISSUE THREAD

**Issue by madjin** [webaverse/app#975]
VRMs that have this issue (found in booth folder in gdrive)

`kasamoto_kanji.vrm`
`gokouya_neiko.vrm`

![image](https://user-images.githubusercontent.com/32600939/111714742-b2840d00-8828-11eb-9673-e77d074e0dc9.png)

Here's a pic from inside Blender

![image](https://user-images.githubusercontent.com/32600939/111718181-db5bd080-882f-11eb-9c7b-86bd54904f49.png)

Console doesn't give us much information:

![image](https://user-images.githubusercontent.com/32600939/111714688-954f3e80-8828-11eb-9e0a-4340a800a42a.png)

**Comment by avaer** [comment]
The eye blink is fixed in my branch, since I now look up visemes correctly in the VRM metadata.

The arms needs to be debugged.

**Comment by avaer** [comment]
I fixed the arms. The problem was that the avatars had an extra forearm bone.

**Comment by madjin** [comment]
fixed
