### ISSUE TITLE
Avatar: Egg doggo visemes

### ISSUE THREAD

**Issue by avaer** [webaverse/app#976]
https://booth.pm/en/items/2777434

Related: #965

**Comment by plankatron** [comment]
current idea is to add new geometry / textures to allow for viseme control.

**Comment by plankatron** [comment]
like this : 
![doggo1](https://user-images.githubusercontent.com/5592454/112024320-75f73080-8b0a-11eb-9932-5930f677eac8.jpg)

**Comment by plankatron** [comment]
ok , one more .. surprised + sorrow 
![sursorrow](https://user-images.githubusercontent.com/5592454/112026725-e010d500-8b0c-11eb-8d1c-a2ed624209d2.jpg)

**Comment by plankatron** [comment]
visemes added ,
