### ISSUE TITLE
App: update OpenSea asset page links

### ISSUE THREAD

**Issue by avaer** [webaverse/app#982]
One suggestion: https://opensea.io/assets/asset -> https://opensea.io/webaverse/item

This can probably be done by asking the OpenSea team.

**Comment by madjin** [comment]
I don't think opensea allows urls like `https://opensea.io/webaverse`
I've only seen `opensea.io/accounts/` or `opensea.io/assets/` or `opensea.io/collection/`

**Comment by madjin** [comment]
`items` seems to be taken
- https://opensea.io/collection/items
- https://opensea.io/assets/items
- https://opensea.io/accounts/items

**Comment by madjin** [comment]
![image](https://user-images.githubusercontent.com/32600939/112220513-bb942600-8bfc-11eb-8e28-276272f7d2c7.png)

Related to updating asset pages, the previews have wrong aspect ratios for images. Would be better if it was scaled and can click to expand like so:

![image](https://user-images.githubusercontent.com/32600939/112220722-f5fdc300-8bfc-11eb-990b-4b2037f72bdc.png)

![image](https://user-images.githubusercontent.com/32600939/112220749-fc8c3a80-8bfc-11eb-9ec6-6b1733fc47f7.png)
