### ISSUE TITLE
Bot: Adding comments to NFTs

### ISSUE THREAD

**Issue by madjin** [webaverse/app#985]
The help menu for minting says this:
`.mint [count]? (upload comment) - mint NFTs from file upload`

Upon `.mint` I'm unable to add a comment to a NFT, tested with and without parenthesis.

The other method for adding comments only recognizes the first word, would be better if in quotes or parenthesis.

![image](https://user-images.githubusercontent.com/32600939/112220109-41fc3800-8bfc-11eb-970a-ca5c03672f81.png)

**Comment by avaer** [comment]
Probably best to wrap it in some quotes.

**Comment by avaer** [comment]
Fixed. You do not need quotes, it will just take everything after that in the `.set`.

**Comment by avaer** [comment]
I still need to fix the `.mint` case though.

**Comment by avaer** [comment]
Updated `.mint` help text and documented the `.gets`/`.sets` commands.
