### ISSUE TITLE
Fe: read unlockable from mainnet

### ISSUE THREAD

**Issue by madjin** [webaverse/app#990]
After moving a sidechain NFT to mainnet, it's no longer in the user's inventory, so we can't `.gets` the unlockable content.

**Comment by avaer** [comment]
One solution to this is to have a URL that exchanges a metamask signature for the unlockables you have in your wallet.

**Comment by avaer** [comment]
Almost done, this is getting ready at https://app.webaverse.com/unlock.html

**Comment by avaer** [comment]
This should be done.
