### ISSUE TITLE
Fe: add RNG and stats to cards

### ISSUE THREAD

**Issue by avaer** [webaverse/app#995]
NFTs have stats generated for each token, and this will likely feature in the trailer.

The stats are generated here: https://github.com/webaverse/app/blob/21980a006f658e679ae193945dc49a72fa50f114/procgen.js

This issue is to add stats display to the frontend cards view, in a manner similar to Yugioh or Pokemon.

**Comment by madjin** [comment]
Going through old issues, I would say this is done and you did an incredibly amazing job with it. Every NFT mint is a chance to get an awesome card is so cool. Beautiful work!

![cardsstats](https://user-images.githubusercontent.com/32600939/122678611-8d02f880-d1b5-11eb-947b-2270f2945cd7.png)

![DMrddTS](https://user-images.githubusercontent.com/32600939/122678640-a60ba980-d1b5-11eb-9893-6db0e3f86aec.png)
