### ISSUE TITLE
Fe: support new shader NFTs

### ISSUE THREAD

**Issue by avaer** [webaverse/app#996]
The PR [here](https://github.com/webaverse/app/pull/993) adds shader NFT types to the Webaverse NFT repertoire.

We'll need to be able to mint these NFTs on the frontend, as we do with other token types.

Basically we would need to detect the three new `gl**` file types: https://github.com/webaverse/app/blob/0c24f5ecc55d012bd7638c3a5199293997edb86f/runtime.js#L1651

And then make sure that loads correctly via the iframe technique.

A crazy bonus would be some text editor to actually live-change the shaders in the NFT as you are making it, but that's not needed right now.

**Comment by madjin** [comment]
https://webaverse.com/assets/692

![](https://gyazo.com/da31192d865287a61933baf3c4f11411.gif)

I was able to mint this on the new frontend: https://github.com/hicetnunc2000/hicetnunc/tree/main/templates/html-glslcanvas-template
