### ISSUE TITLE
Fe: Document NFT types

### ISSUE THREAD

**Issue by avaer** [webaverse/app#997]
We need proper documentation for how to mint each NFT type. The frontend is currently very opaque about it.

**Comment by madjin** [comment]
Starting this soon, I will need a sample models for each type:

- walking pet
- flying pet
- mount
- vehicle
- hoverboard
- wearable
- weapons

**Comment by avaer** [comment]
- walking pet: https://github.com/avaer/dragon-pet
- flying pet: https://github.com/avaer/dragon-fly
- mount: https://github.com/avaer/dragon-mount
- vehicle: https://github.com/avaer/hovercraft
- hoverboard: https://github.com/avaer/hoverboard
- wearable: https://github.com/avaer/sword
- weapons: https://github.com/avaer/pickaxe, https://github.com/avaer/rifle

**Comment by madjin** [comment]
so far done:
- pets
- mounts
- hoverboards

**Comment by madjin** [comment]
Update on it. The information on these pages isn't complete, need to know what the best way is to mint things. Would it be through a URL on https://webaverse.com/mint ?

https://docs.webaverse.com/docs/create/sword
https://docs.webaverse.com/docs/create/pickaxe
https://docs.webaverse.com/docs/create/guns
https://docs.webaverse.com/docs/create/pets
https://docs.webaverse.com/docs/create/mounts
https://docs.webaverse.com/docs/create/hoverboards
