### ISSUE TITLE
Bot: .set name includes "name"

### ISSUE THREAD

**Issue by madjin** [webaverse/app#998]
![image](https://user-images.githubusercontent.com/32600939/112367450-4b46dc80-8cb0-11eb-8eaa-ccd0ce15a8d0.png)

Noticed it included "name" in the new name, so I tried without "name" (`.set 12 Whiskers`) and it doesn't return anything.

**Comment by avaer** [comment]
Oh whoops

**Comment by avaer** [comment]
Fixed? If it is please close.
